### ISSUE TITLE
PHAST - orange bar pinning

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1011]
If the page is long enough (charge materials) the top bar still goes away if you scroll beyond the bottom of the results

**Comment by rmroot** [comment]
Orange bar pins as desired when the screenshot stuff on the top is removed

**Comment by rmroot** [comment]
Going to be tied with scrolling connects #1129

**Comment by rmroot** [comment]
This is somewhat covered, it won't be perfect until the screenshot banner is gone. Please comment and move back if different functionality is desired

**Comment by koay9f** [comment]
looks good to me.  will try on a bigger computer later (on a laptop now)
