### ISSUE TITLE
Homogenize top bar

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1013]
Top bar for the pump/furnace assessments should have similar links:

____ Setup, Assessment, Diagram, Report, Sankey, Calculators

**Comment by koay9f** [comment]
Could the Sankey available from the top bar have a drop down to choose baseline or one of the modifications?

**Comment by rmroot** [comment]
Branch issue-1013 has this started for @DmitryHoward

PHAST Calcs are in just need to implement sankey in PSAT

**Comment by koay9f** [comment]
Good but:
Could the Sankey available from the top bar have a drop down to choose baseline or one of the modifications?
