### ISSUE TITLE
Roll up reports

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1023]
If no modifications, roll up should default to using baseline.

Not sure furnaces are being added in the top bar.

Attached are two furnaces that should be about the same, except one is fuel and the other ET

[exportData.txt](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1552134/exportData.txt)

**Comment by rmroot** [comment]
Need to add functionality for selecting baseline in rollups
