### ISSUE TITLE
Decimal Places

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1030]
Should try to reduce the number of decimal places displayed by app.

For example:
Values from databases - should be have max 4 decimal places

All values after unit conversion?? - should they be rounded? each time?  that could introduce a lot of rounding errors...

**Comment by rmroot** [comment]
4 - wait till after 12/18

**Comment by gaccawi** [comment]
Please round to 4 decimal places.
