### ISSUE TITLE
Autoupdate - Spinner

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1040]
Trying to autoupdate my app.  I click "Download Now" and nothing happens.  Modal stays up.

If click the info button, then close the release notes, the autoupdate modal is there again.  I click "Download Now", it works

**Comment by koay9f** [comment]
It has taken over 5 minutes to try and download/install.  Canceled and did a manual update

**Comment by gaccawi** [comment]
Can you uninstall then reinstall and older version from GitHub, then see if the autoupdate works.

**Comment by gaccawi** [comment]
Also, it appears the "spinner" is gone. Tom reported this on Windows.

**Comment by koay9f** [comment]
installed 0.2.2 and 0.2.3 and both could autoupdate to 0.2.4 just fine. 

"Spinner" is still an issue

**Comment by koay9f** [comment]
Can't verify until this is on github and I can do an auto update...
