### ISSUE TITLE
Furnace Calculator Settings

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1049]
Add settings logic to furnace calculators now that they are in assessments

**Comment by rmroot** [comment]
connects #1006

**Comment by koay9f** [comment]
Is there a way for me to test this?  The build I just got doesn't have Calculators in PHAST yet, so maybe next draft build?

**Comment by rmroot** [comment]
Yes. Once we get #1013 done and in you can test this. Until then leave in Needs Verification
