### ISSUE TITLE
Unit Conversions - K to F temperatures

### ISSUE THREAD

**Issue by pshires** [ORNL-AMO/AMO-Tools-Desktop#1055]
The Kelvin to Fahrenheit conversion doesn't work properly

**Comment by koay9f** [comment]
For some reason when converting from F to K it is using this equation
K = (5/9)*F + 133.97

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/34731793-5f75f606-f531-11e7-8e83-69e68c483369.png)

For testing

**Comment by gaccawi** [comment]
Issue original source library.
