### ISSUE TITLE
PHAST - operating costs small calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1058]
make calculator to help user calculate weighted average of fuel costs if using more than one fuel

modal -
fuel A     Fraction _____      Cost ____
fuel B     Fraction _____     Cost_____

Result = sum (fraction * cost)

Kristina - Do I need to make a mock up ?

**Comment by koay9f** [comment]
For electricity and steam 
instead of "Fuel A" it would be "Electricity Source A" or "Steam Source B"

**Comment by nbintertech** [comment]
A branch already exists for this, let me know when you start

**Comment by koay9f** [comment]
Needs some left margin
Math is not correct
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c6feee1a-b8e8-4132-80ea-b4da2190da57)
math should be:
sum(percent used x cost)/sum(percent used)
