### ISSUE TITLE
PHAST - Change numbers that come from DB

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1061]
In Charge Materials, Fixtures, Atmo

If change one of the numbers that is populated by a database lookup, can they be highlighted in some way?  maybe green box (since yellow and blue are used)?  Also colored in the input report
connects #1062

**Comment by rmroot** [comment]
Removing from 0.2.6-beta. Larger then expected, need to consider units

**Comment by rmroot** [comment]
completed, need clarification on "Specific Heat Vapor" vs "Specific Heat Gas" in Gas Charge Materials

**Comment by koay9f** [comment]
I'm guessing because of rounding,  this is sometimes showing a false positive.
If set the material --> Change Units
some of the values get highlighted.  
If you change the material in the dropdown and then put it back, the highlighting goes away.
Is the initial highlighting due to rounding?  Can we add approximates (Preston does something like approx for the unit tests)? (edited)

If it doesn't seem like an easy fix, let me know, and I'll make a new issue and put it in the backlog
