### ISSUE TITLE
PHAST - Change numbers from DB - help

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1062]
Add something to help text saying you can change these, but if you change the material drop down then then will return to the previous values.  if adjusting for more than one assessment, may want to consider "Add new ..."

Need to figure out wording and make a list of all fields it needs to go in

**Comment by gaccawi** [comment]
connects #1061

**Comment by koay9f** [comment]
FOR CHARGE MATERIALS & FIXTURES & ATMOSPHERE
This value comes from the PHAST Materials Database.  Its value can be changed here, however, it will not be saved.  
If you change the dropdown menu value, then this number will change to reflect the value in the database.
If you will be using the same adjustments to a value for multiple assessments, you may want to consider adding it as a new material by clicking "Add New ... "

FOR FUELS
This value comes from the PHAST Fuels Database.  Its value can be changed here, however, it will not be saved.  
If you change the dropdown menu value, then this number will change to reflect the value in the database.
If you will be using the same adjustments to a value for multiple assessments, you may want to consider adding it as a new fuel by clicking "Add New Fuel "

FOR WALL SURFACES
This value comes from the PHAST Surfaces Database.  Its value can be changed here, however, it will not be saved.  
If you change the dropdown menu value, then this number will change to reflect the value in the database.
If you will be using the same adjustments to a value for multiple assessments, you may want to consider adding it as a new surface by clicking "Add New Surface "

**Comment by koay9f** [comment]
CHARGE MATERIALS
SOLIDS
Ave. Specific heat of the solid material
Latent heat of fusion
Specific heat of liquid...
Melting Point
LIQUIDS
Ave. Specific heat of the liquid
Latent heat of vaporization
Specific heat of Vapor...
Vaporizing Temperature
GAS
Specific Heat of Gas

FIXTURES
Specific Heat

**Comment by koay9f** [comment]
Sorry, reading the text, found a small thing to be changed:

"... however, it will not be saved in the database."

AND
"... then this number will change to reflect the value stored in the database."
