### ISSUE TITLE
PHAST - flue gas new fuel

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1074]
In the new fuel modal (where the users enter composition data; for either gas or solid/liquid):
The results for Heating Value have the units of Btu/SCF (kJ/Nm3).  These should be Btu/lb (kJ/kg).

We need to add another result (JUST FOR GAS FUELS) that is also labeled Heating Value, but with the units Btu/SCF  (the C++ & bindings should be coming soon, probably named something like HeatingValueVolume)

See suite issue 165 for more info

**Comment by pshires** [comment]
completed, however this requires a tools-suite release. May wait until we have fully implemented premium efficiency motors for PSAT (which will also require a new release)

**Comment by koay9f** [comment]
good for gas, solid/liquid has new issue devoted to unit change
