### ISSUE TITLE
PHAST - metered white screen

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1095]
When on metered energy, if select a solid/liquid fuel and then pick a fuel ( any of the last 3), the screen goes white and the app locks.

possibly relating to issue #1075

**Comment by koay9f** [comment]
also happens in the pre-assessment calculator

**Comment by pshires** [comment]
confirmed to be broken at or before (most likely before) https://github.com/ORNL-AMO/AMO-Tools-Desktop/commit/9aeaf22b957e7c3e88b468bd28067e5f6ddc1b25

**Comment by pshires** [comment]
confirmed to be broken in the github release 0.2.4 beta
