### ISSUE TITLE
PHAST - Input + Cooling

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1106]
The field "Name of Cooling Medium" in the Input data is showing the name of the loss instead of what was entered in the calculator

**Comment by rmroot** [comment]
I think 1032 covers this

**Comment by koay9f** [comment]
Still in the my build as of 01/17

**Comment by koay9f** [comment]
The name of the cooling medium within Cooling losses in the report (Input Data)
