### ISSUE TITLE
PHAST - Operating Conditions Input Data

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1116]
Add operating hours and operating conditions to the input data tables in phast

**Comment by koay9f** [comment]
Operating Hours has been added.  

Operating Conditions is in the printed report (under "Summary of Energy Sources Used"), but it is not in the "View Report" area.

**Comment by rmroot** [comment]
![operating-conditions.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e7849f318397a081eef240ab53f49d3d4f287d3a46ef696097ec22ba416f43554d4ba5150d0d15fead802cf7e06e228a5c0eea876c5a27943b03b0aac04ee155e57dd205d0f4ae805ec1e13724e28a864f391c051d8df95437b2d4.PNG)

**Comment by rmroot** [comment]
Are you saying you want them moved to input data?

**Comment by koay9f** [comment]
No sorry.  I was just saying where they are . 

Though, Operating Conditions should be in the "View Report", which it looks like you did.  so I think that's all that needs to happen for this issue.

**Comment by rmroot** [comment]
this is done as of v0.2.6-beta closing
