### ISSUE TITLE
PHAST- Add a new material -Liquid- Unit

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1118]
The unit of Latent Heat of Vaporization should be changed to Btu/lb-F . Check unit conversion as well

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/34795506-92da1aa0-f620-11e7-877e-362986fcf6e5.png)

Latent Heat of Vaporization is not converting correctly.
I entered "32" for each field in imperial.  Latent Heat ... should = 133.977...

**Comment by koay9f** [comment]
Opps.  okay, so the conversion is now correct (and it should be 32 Btu/lb, 74.432 kJ/kg), but the unit label is not.
It should be 
Btu/lb and kJ/kg

Again, JUST THE LABEL is wrong.  My fault.

**Comment by AshaShibu** [comment]
It is now using the conversion for Btu/lb-F to kJ/kgC. It needs to be the conversion for Btu/lb to kJ/kg
The label is right but the conversion is now wrong
