### ISSUE TITLE
Scrolling up/down

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1129]
Users have expressed desire to have something ON SCREEN to help them scroll up & down, such as in PHAST, when you add 6+ wall losses or charge materials

Thoughts on how to do this such that it looks nice?

**Comment by RoundDev** [comment]
Example scroll temples Bootstrap 
https://mdbootstrap.com/javascript/smooth-scroll/

**Comment by gaccawi** [comment]
Can the baseline and modification scroll together, but the help/results panel stay independent?

**Comment by koay9f** [comment]
Not showing up in Assessment.  Should be sure to be in Charge Materials and Wall losses.
[lots of losses.txt](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1683297/lots.of.losses.txt)
