### ISSUE TITLE
PHAST - Gas Leakage Allow negative furnace draft pressure

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1133]
"Furnace Draft Pressure" should allow negative values

sorry if this contradicts something I said earlier

No minimum

**Comment by pshires** [comment]
this might be impossible unless we rework the current math for gas leakage, it's trying to take a square root of a negative number if we allow this

**Comment by koay9f** [comment]
Code has sqrt (furnace draft pressure).  so can we handle cold air leaking into the furnace?

**Comment by koay9f** [comment]
Nevermind - should not allow negative

**Comment by koay9f** [comment]
Edit Help text to remove negative pressure text:

Savings Suggestions, replace third bullet:
Avoid excessive positive pressure or presence of openings to reduce or eliminate hot gas leaks from the furnace

Furnace Draft Pressure Help Text:
Remove last Sentence ("Cold Air leaks...")
