### ISSUE TITLE
Compressed Air-System Capacity

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1148]
![capture-8](https://user-images.githubusercontent.com/31292133/34898564-bd26d210-f7c1-11e7-86d6-15defe079183.PNG)

**Comment by AshaShibu** [comment]
![capture-9](https://user-images.githubusercontent.com/31292133/34898576-d061a80a-f7c1-11e7-8cbf-af33d53fa947.PNG)

**Comment by pshires** [comment]
there is a tools suite method for this, and for all other compressed air methods
