### ISSUE TITLE
Compressed Air -Flow Factor

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1151]
![capture12](https://user-images.githubusercontent.com/31292133/34898621-22049abe-f7c2-11e7-8b39-5188fb92a922.PNG)

**Comment by rmroot** [comment]
see #1201

**Comment by pshires** [comment]
tools suite bindings exist for this

**Comment by AshaShibu** [comment]
Need to refine the flow of the calculation. It's better to keep it as it is and once all calculators are finished, will figure out the order
