### ISSUE TITLE
Table Layouts for PHAST Rollups

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1161]
Clean up layouts of tables

**Comment by rmroot** [comment]
![image (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e1999b2487c3e1dea0fd0fe64de29b234324676b5ee17e2981e62abe107f58580e18fe13585f41fbaf882ef5e43a62964e49bc8f3900299f7744eeaa880dbe09b0218e4e83b7be8f44c1ea3c22e599c2.png)

**Comment by rmroot** [comment]
use colspan on columns

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/36049847-423373ea-0db2-11e8-94a7-c51645b5c4e3.png)

first 4 columns should be grouped into 2 sets (Energy Intensity and Annual Cost) of two (baseline / modification).  See picture in Mark's comment above (units should also be centered above column name)

**Comment by koay9f** [comment]
Energy Intensity, Annual Cost, cost savings, and their units need to be centered over the two columns.
