### ISSUE TITLE
PHAST - Operating Costs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1180]
Defaults and in general the fields for costs should have two decimal places
$8.00

**Comment by gaccawi** [comment]
This would be on the screens and reports. Verify if in reports already.

**Comment by koay9f** [comment]
find a price that has 2 decimal places

**Comment by koay9f** [comment]
Natural Gas - change default price to $3.99/MMBTU
Steam - change default price to $4.69/MMBTU
Electricity - ... $0.066/kWh
