### ISSUE TITLE
PHAST Warnings

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1183]
If warning occurs in PHAST, could the "Loss Total" also highlight in some way?  Just as another way for the user to be aware of a problem

**Comment by pshires** [comment]
are we sure that we want this? Imo any user input error is nearly impossible to miss if there is an error message displayed on the form

**Comment by koay9f** [comment]
Sachin agrees, but maybe just make text red or something?
Add warning:

Warning: one or more of your inputs are out of the valid range and therefore results are not  valid.
