### ISSUE TITLE
PHAST - Electrotech Design & Metered

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1189]
For Electro technologies (all kinds)

For both the pre-assessment calculator AND assessments
Design Energy Use and Metered Energy Use must include the fields from fuel (do not need to duplicate Aux. Equipment fields)

Watch units (kW vs Btu or kJ)

**Comment by rmroot** [comment]
![metered-fuel.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e5918e269086adc2efaa46a81fbcd6395428792c07b7692ac7b671bb4779005d0b47ab100e0d16fcf98c2cf0b73923d85a19f1c32f0e2a92624cf5f2d75dad0ba821824584b3bd834cc7e93527e28387472c53.PNG)

**Comment by rmroot** [comment]
![metered-electricity.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e5918e269086adc2ecb346a749e29d2a4f336a6b48e13b628ae92dbc56395b4d5a47f8140a0e46a8f08e7af0e46e708a590cbbd0680c26c02f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e6828f483f16011f8afb5927ed.PNG)

**Comment by rmroot** [comment]
We want all of those field from fuel in electricity?

**Comment by rmroot** [comment]
How does this effect calculations?

**Comment by koay9f** [comment]
Yup.  (yuck I know)

So the electricity part would be as is.

The fuel should have its normal calculations done.  Converted to kWh (or whatever unit the electricity stuff is in) and then added to the electricity values.

Stupid hybrid furnaces...
let me know if I just made things more confusing

**Comment by rmroot** [comment]
Temporary putting in completed, assessment portion is done, waiting for feedback from Sachin before implementing Pre Assessment

**Comment by koay9f** [comment]
Metered Energy still has the x 10^6 problem in the fuel results.

**Comment by koay9f** [comment]
Now design is having problems
![image](https://user-images.githubusercontent.com/25389736/37368772-92568c38-26dd-11e8-9c7f-c34b4a90e1c2.png)

**Comment by rmroot** [comment]
1) That would be 1.1 MMBtu -> 322.3 and I have fixed that
2) There is a problem with steam
![steam-designed.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46fb809f228fcead8afab644aa58f4d665043761260ea62864c7b96aea1b7f040d0e4cf8485f0e12aeab892ba3b16a718f0f59ebc3714d36976345f3e5db55ea43a82a994e8cbcbd8f4ec1e83924e78f8d483d1b1755.PNG)

Steam is calculated in Btu or kJ. Is that desired? If so all I have to do is change the unit label in the results for steam, I have taken care of the conversion for the Pre Assessment already. 

The other option would be to change the unit label on the input to MMBtu or GJ (like fuel)

**Comment by koay9f** [comment]
the "total heat for steam" should be in btu/lb or kJ/kg.   The Fuel Energy Used should be in the assessment's "Energy Units" (MMBTU; GJ...)
