### ISSUE TITLE
PHAST - Rollup - Units

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1203]
Choose units "By Assessment'

**Comment by koay9f** [comment]
Allow user to choose a "common" unit and then a unit for each type of fuel:

![image](https://user-images.githubusercontent.com/25389736/37294782-f7d645d6-25ec-11e8-93fc-b106481019b1.png)
![image](https://user-images.githubusercontent.com/25389736/37294828-12db0434-25ed-11e8-9fad-461b7225fb75.png)
