### ISSUE TITLE
Icons - All calculators

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1213]
I drew the sketches below and if anyone has better suggestions do pitch in. Tom wants these icons to be placed on the left side of calculator name.

![img_5662](https://user-images.githubusercontent.com/31292133/35294019-813b82de-0043-11e8-9f0c-90a1c73cc1d7.jpg)
![img_5663](https://user-images.githubusercontent.com/31292133/35294026-85550ffc-0043-11e8-9c39-f509ca3e2778.jpg)

**Comment by pshires** [comment]
my main concern with this is how can we make the icons be big enough to be understandable, visually?

**Comment by koay9f** [comment]
This is for the screens where the calculators are listed, so if the pictures are given about 1/4 to 1/3 of the screen (excluding the side bar), then that should probably give them quite a bit of size

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/35575617-d27df156-05aa-11e8-88bf-f6c36cc960b7.png)

![image](https://user-images.githubusercontent.com/25389736/35575650-f49dee12-05aa-11e8-90d0-89d5367152a4.png)
