### ISSUE TITLE
Add Fan interfaces

### ISSUE THREAD

**Issue by pshires** [ORNL-AMO/AMO-Tools-Desktop#1215]
Add Fan input object(s) interfaces to typescript to make calling the tools-suite methods easier and less error prone

**Comment by pshires** [comment]
for now this is a size 2, but there may be other issues that come about after this one that may be a good reason for more issues to be created or the size to go up. There will almost surely need to be some rethinking of input sending / splitting-up of the tools-suite methods in order to get what the UI needs relatively efficiently.

**Comment by rmroot** [comment]
added into seperate branch, not ready to merge develop yet
