### ISSUE TITLE
Ubuntu Drop-Down Menus Broken

### ISSUE THREAD

**Issue by Mlwhitmer** [ORNL-AMO/AMO-Tools-Desktop#1221]
This issue seems to be Ubuntu specific. All drop-down menus in Desktop are completely black.

**Comment by Mlwhitmer** [comment]
![menuProblem.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6a40a3b6d90e001285d13f/125516c66e82c728ace21e0d46e5919436b291a68de5ba4ee611b2843b492d762a10e17132d0ba2cba407a530b5649fd170a0d44fcfc8e7da7b36f228c4e17ff933c0120996048e6edc00db513bb27814e80b7ba8344c8ea3f23ef83895d73.png)

**Comment by pshires** [comment]
Could be specific to ORNL's installation of Ubuntu. I tested with 16.04 (same version as Mlwhitmer) in a VM, and the dropdown menus worked for me. I think this was confirmed to be a non-issue for newer versions of electron

**Comment by pshires** [comment]
Closing for now, could not reproduce on a fresh install of ubuntu
