### ISSUE TITLE
PSAT Modifications Notes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1228]
Add notes for PSAT Modifications.

Where should these go in the report?

**Comment by rmroot** [comment]
PSAT Modifcation notes currently exist. Not sure if they are in report.

**Comment by koay9f** [comment]
They don't seem to be in the report yet.    Maybe add to the bottom of the results, kind of like how PHAST is

**Comment by koay9f** [comment]
was fixed at some point.  it is in the print report
