### ISSUE TITLE
PHAST - Flue Gas Loss

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1245]
Where is Flue Gas Losses in the results coming from?
It does not match "System Losses" on the Flue Gas tab
Net Heat = sum (all other losses)
System Losses = (Net heat / AH%) - Net Heat

**Comment by pshires** [comment]
sitting on branch https://github.com/ORNL-AMO/AMO-Tools-Desktop/tree/phast-issues

**Comment by koay9f** [comment]
So right now, the System losses displayed on the flue gas page are calculated from gross heat, which includes Exothermic Heat.  

It is CORRECT in the results.

Can the calculation from the results panel be put in the page?

If that can't happen, then maybe the better way to calculate System losses would be
System Losses = (Net Heat / Available Heat (0.XX) ) - Net Heat

And also display Net Heat...
Reminder Net Heat = Sum (Charge, Fixtures, Wall, Cooling, Atmo, Opening, Leakage, Surface and Other Losses)  
Exothermic Heat & Flue Gas losses are NOT included

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/35691759-58613f92-0747-11e8-819b-5ee72be34a84.png)

**Comment by koay9f** [comment]
Also, change the name of "System Losses" on the flue gas page to "Flue Gas Losses"
