### ISSUE TITLE
PHAST Report Graphs Printing 2 - B&W

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1311]
For b&w printing, it was suggested that we use patterns if we cannot manage leader lines.  The most important losses are:
Flue Gas Losses
Charge Materials
Opening Losses
Wall Losses

The others can be less distinctive

**Comment by DmitryHoward** [comment]
Patterns can be utilized, but this will require refactoring pie chart creation code.

**Comment by koay9f** [comment]
Leader lines are better than patterns.
