### ISSUE TITLE
PHAST report Pie charts

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1322]
numbers in pie do not match those in hover or legend

![image](https://user-images.githubusercontent.com/25389736/36441685-5526fe62-1641-11e8-80fe-3c43d95d23dc.png)

**Comment by DmitryHoward** [comment]
This issue seems to be originating from GasChargeMaterialFormComponent and suiteDbService.selectGasLoadChargeMaterial before it reaches the graphing stage.

**Comment by DmitryHoward** [comment]
Handled with pie chart refactor
