### ISSUE TITLE
DB Value checks after conversion

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1356]
Converting PHAST assessments rounds all values to 3 decimal places. Checking if values are different from DB rounds to 4 decimal places and indicates different when they really are not

**Comment by koay9f** [comment]
would bumping up unit conversion rounding to 4 decimal places help?

**Comment by koay9f** [comment]
Still seeing some conversion issues, but I don't think we should bump up to 5 decimal places....
