### ISSUE TITLE
PHAST Modify Conditions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1378]
So automaticlly making a "Explore Opportunities" modification is being a problem.

If a user clicks on Assessment before Flue Gas has been completed, then it generates a modification, however, my baseline is not actually complete, so the whole thing gets kind of screwy.  I have to go through and delete the 

Could we bring back the warning popup for this?  

also, it is annoying to be making a nice tidy report and have to go in and delete the "Explore Opportunities" modification.

**Comment by rmroot** [comment]
Going to also add to PSAT

**Comment by koay9f** [comment]
When click on the orange/red "Explore Opportunities" button on the new landing page, it does not give the popup about locking the baseline.
