### ISSUE TITLE
PHAST Roll up Report - extra pre-assessment

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1408]
![image](https://user-images.githubusercontent.com/25389736/37367228-3175914c-26d9-11e8-95fd-ae2b9659fdc0.png)

**Comment by koay9f** [comment]
also duplicated in report

**Comment by koay9f** [comment]
Cannot reproduce.  Guessing that I generated a blank pre-assessment that is hiding somewhere and it is pulling up both.

**Comment by koay9f** [comment]
Still happening.  Attaching file to see if it comes over

**Comment by DmitryHoward** [comment]
Could not reproduce. Did not happen even with the extras import.

**Comment by koay9f** [comment]
Still happening
It happens when I generate a report using a specific folder, but not when I select the items individually in the folder
So I think there is a hidden empty pre-assessment somewhere in that folder, probably generated when the pre-assessments were having problems saving.
