### ISSUE TITLE
PHAST - Pre-assessment - add table

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1409]
In which ever way makes it easier to also add to reports...

Add a "Total" table that has the calculated energy used (from each furnace)

Show in both sidebar & reports

Furnace Name ....Type ... Category...  MMBtu*
Furnace 1            Fuel      Metered        12

* based on report units

**Comment by koay9f** [comment]
Instead of table : 
in the form, add total line for each furnace

**Comment by rmroot** [comment]
Oops
