### ISSUE TITLE
PHAST Report Tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1410]
Exe Summary
Bold the lines: percent savings, energy savings, cost savings, simple payback

Result Data
like Input data, any loss that is different from baseline have bold/colored

Result Graph (pies)
is it possible to hide any loss that = 0? or better yet, any loss that wasn't used in that type of furnace (slag shouldn't show up for a fuel furnace)

Result Graphs (bar)
getting kind of squished and using two lines for some words
![image](https://user-images.githubusercontent.com/25389736/37367826-dee8f0d4-26da-11e8-97a7-09948bc7c572.png)

Sankey
Gross heat is in the wrong spot
Charge Materials should be singular (Material)
it is overlapping the teal boundary thing

![image](https://user-images.githubusercontent.com/25389736/37367789-c3a45386-26da-11e8-9560-75e9ab3c9622.png)

**Comment by DmitryHoward** [comment]
Sankey tweaks have been made, but the tweaks to the bar chart can be included in an overall refactoring of charts for black and white print compatibility.

**Comment by DmitryHoward** [comment]
Bar chart fixes should be made into a separate issue.

**Comment by koay9f** [comment]
Gross heat is still to far below where it should be
![image](https://user-images.githubusercontent.com/25389736/37719677-e968ded0-2cfb-11e8-9f26-1cf10d8bf064.png)
