### ISSUE TITLE
MEASUR

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#1411]
New name for the AMO-Tools-Desktop

**Comment by koay9f** [comment]
Start adding to homepage
At this time, do not change repository name or similar.  just cosmetic changes

**Comment by koay9f** [comment]
Page layout
![image](https://user-images.githubusercontent.com/25389736/37983371-4a40eea4-31c1-11e8-8179-65bdbee4e86c.png)

Logo (just little logo)
![image](https://user-images.githubusercontent.com/25389736/37983395-5ba930e8-31c1-11e8-9333-79908741f00c.png)

Logo (with all text as logo)
![image](https://user-images.githubusercontent.com/25389736/37983414-65803f26-31c1-11e8-8780-9e4d26ba2ed7.png)

**Comment by koay9f** [comment]
https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/1467
