### ISSUE TITLE
PHAST - pre-assessments

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1422]
Could the pre-assessments be treated a bit more like assessments?
able to export and have a check box to include them in the final report?

Does the facilities info export?

**Comment by koay9f** [comment]
Be able to move and export pre-assessments
Have them have a full card
Be able to add them to the report using the checkbox (like assessments)

**Comment by rmroot** [comment]
Started branch `issue-1422` going to get the energy costs graph implemented first so that we can use the energy cost values in the card view. Also going to add the table to pre assessments first, values will be similar to what we want to display in card view.

**Comment by rmroot** [comment]
Creating separate issue for exporting/deleting Pre Assessments.
