### ISSUE TITLE
Print Settings

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1428]
Add print settings in general settings

**Comment by Aeledbetter** [comment]
What kind of print settings?

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/8500a0c3-a6a3-4708-8317-8c721825c708/download](https://app.zenhub.com/files/80439269/8500a0c3-a6a3-4708-8317-8c721825c708/download)

Basically, the options for the print rollup are settings we can set in the global settings, but they don't have application in all modules (no "losses summary" for treasure hunt). But something like "Result Details" being checked off means that, by default, any module + roll up where you can print "Result Details" has that checked off

The ppt also has a few other updates we could do with printing.  let me know if any of them are too out of bounds and I can make another issue
