### ISSUE TITLE
Unit change- RT General Method

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1451]
Change the units of Air demand from ft2 to ft3 (cubic feet)

**Comment by koay9f** [comment]
Are there metric units for Compressed air calculators?  will this effect conversions?

**Comment by rmroot** [comment]
Compressed air is not setup for metric and even the imperial units may be wrong. I've attached a excel sheet with our current units in imperial. Need the corresponding unit in Metric. Alternatively we could add unit settings for Compressed Air if we preferred that over metric/imperial.
[compressed-air-units.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb0ea554e2d93c482e673a46ef696097ec22ba416f43554d4ba5150d0d15fead802cf7e06e228a5c0eea876c5a27943b03b0aac04ee155e57dd205d0f4ae805ec1ef3724e2888a4c361700108cfa5530b2d4.xlsx)

**Comment by rmroot** [comment]
Created second issue for compressed air units
