### ISSUE TITLE
Delete Pre Assessment

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1452]
Add functionality for exporting and deleting pre assessments from folders. Explore cleaning up process for exporting and deleting

**Comment by rmroot** [comment]
Import/Export needs to be refactored. Currently not working properly and not written very well.

**Comment by koay9f** [comment]
Not sure it exported.  It did not show up in the list of exported assessments (though it might not). and it did not import (I imported into a new folder)

[testpre.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46fc9189379291accda5fd53b652fa912a5265296b51fa2f7587e27abb1b2c00090d1cac415d5812fdfcda79a0a42062c80d55b98e30063e937f03a6aa8318b500bf22894f82bfbf8b48c1e93a37aa.txt)
