### ISSUE TITLE
Minor Changes in apperance

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1532]
Auto close.  Add "copy" to V menu
Long names can move the V menus
Badges are hyperlinks to specific calculator
In general when close - go to operations by default
Change blue for badges (to match link color)
MEASUR should be the green color that the shadow used to be

**Comment by rmroot** [comment]
didnt change blue, will update in 1535

**Comment by koay9f** [comment]
problem with the dropdown cutting off
