### ISSUE TITLE
Compressed Air-Icons

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1543]
![icons](https://user-images.githubusercontent.com/31292133/38505354-f62d168e-3be4-11e8-8387-3281b895de86.jpg)

**Comment by gaccawi** [comment]
![1-leaklossestimator](https://user-images.githubusercontent.com/8973004/38950909-f1c0d6c6-4314-11e8-9941-172a7c5912ad.png)
![2-valveflowfactor](https://user-images.githubusercontent.com/8973004/38950910-f1ccb626-4314-11e8-82da-74521959599b.png)
![3-pneumaticarc](https://user-images.githubusercontent.com/8973004/38950911-f1da5e2a-4314-11e8-81ac-1b906e416421.png)
![4-recievestank](https://user-images.githubusercontent.com/8973004/38950912-f1eb243a-4314-11e8-9524-19180d83aa7e.png)
![5-pipesizing](https://user-images.githubusercontent.com/8973004/38950913-f1f60c9c-4314-11e8-9aef-749415d978ca.png)
![6-velocityinpiping](https://user-images.githubusercontent.com/8973004/38950914-f20143f0-4314-11e8-994f-45104480f17b.png)
![7-systemcapacity](https://user-images.githubusercontent.com/8973004/38950915-f211745a-4314-11e8-8362-cc1b70141cb7.png)
![8-operationcost](https://user-images.githubusercontent.com/8973004/38950916-f21c9f60-4314-11e8-884c-d720fb750485.png)
