### ISSUE TITLE
Rename - Premium Efficient

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#1599]
Under pump/motor setup (PSAT), and Motor - Efficiency Class should say "Premium Efficient".

It's missing the "efficient" in the dropdown and in the help text

**Comment by rmroot** [comment]
PSAT Service needs to be updated to handle this change for calculations

**Comment by koay9f** [comment]
This was fixed, but as of right now, in develop, it is gone again.
