### ISSUE TITLE
Add OS conditions node-gyp binding file

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#16]
Alter node-gyp to pull in packaged library from Git releases per platform

**Comment by gaccawi** [comment]
Before this can be done, work is needed in the suite

1. Need to alter build in the suite to include the sqlite (or run python to generate then include).
2. Need to package for all target platforms.
3. Create release on GitHub (target URL for pulling)

**Comment by mbadams5** [comment]
The work in the suite is done with the following PR, ORNL-AMO/AMO-Tools-Suite#12

**Comment by gaccawi** [comment]
Completed.
