### ISSUE TITLE
Motor Performance Calculator

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#160]

**Comment by gaccawi** [comment]
![image](https://cloud.githubusercontent.com/assets/8973004/24714875/bfde99c8-19f7-11e7-97dc-71cc54a610d3.png)

**Comment by rmroot** [comment]
Mock up done. Hasn't been implemented

**Comment by rmroot** [comment]
![motor-performance-psat-electron](https://cloud.githubusercontent.com/assets/10789740/24873407/4bf71a92-1de6-11e7-9bf4-606a08b709d4.PNG)


From old PSAT Electron
