### ISSUE TITLE
Create new Load Estimation - Field Measurement Method Calculator

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#1608]
Create calculator to take in field measurement data (voltage, current, power factor) to calculate load, power & voltage/current imbalance

**Comment by AshaShibu** [comment]
[Load Measurement.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1944731/Load.Measurement.docx)

**Comment by AshaShibu** [comment]
![phase voltage and current](https://user-images.githubusercontent.com/31292133/40503040-c0d9a31e-5f5a-11e8-9022-afe17096426e.PNG)
@rmroot  Please include this figure as well
