### ISSUE TITLE
Specific Speed calculator

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#161]

**Comment by gaccawi** [comment]
![image](https://cloud.githubusercontent.com/assets/8973004/24714915/de0b5a08-19f7-11e7-8148-c41e63c18e41.png)

**Comment by rmroot** [comment]
Mock up done. Hasn't been implemented

**Comment by rmroot** [comment]
![specific-speed-psat-electron](https://cloud.githubusercontent.com/assets/10789740/24873391/40dc4f60-1de6-11e7-813b-58c107cc6896.PNG)

From old PSAT Electron

**Comment by rmroot** [comment]
Need to use log function for calculations
