### ISSUE TITLE
Motor Drive Comparison Calculator

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#1611]
Develop calculator to compare various drive types (direct drive, v-belt, notched v-belt, cogged belt, hydraulic, magnetic)

**Comment by AshaShibu** [comment]
[Motor Drive.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1944729/Motor.Drive.docx)

**Comment by koay9f** [comment]
Change order of results
V Belt Drive
Notched V Belt Drive
Synchronous Belt Drive

Double check the numbers.  
In increasing size:
Synch < Notched < V Belt
I think you swiched Synch and Notched.  Synch should be divided by 0.98; Notched divided by 0.95

Change Annual Energy Cost to ($k/yr).  Divide by 1000, no decimal places.
Change Annual Energy Use to (MWh/yr). Divide by 1000, no decimal places.
(note, MWh not MW)

Unit on Electricity cost should be $/kWh (cap W, with h)

Change label "Graph" to "Results"
OR

Bar Chart :D + table
(Left to right: V, Notched; Synch)
