### ISSUE TITLE
Develop Power Factor Correction Calculator for General

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#1612]
Develop calculator for power factor correction

**Comment by AshaShibu** [comment]
[Power Factor.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2031942/Power.Factor.docx)

Calculator to be included in the general section

**Comment by koay9f** [comment]
Capacitance Required calcuation is not correct.
To clarify the equation is:

H = D * tan (arccos B - arccos C)

where arccos is the arccosine or inverse cosine or whatever you want to call it.  not 1/cosine

For the default values, the answer should be 32.004

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/40561321-bcc611ba-602a-11e8-8cb0-6872ff4ba33b.png)


If the inputs are 500, 0.75, 0.9 then the Capacitance should be 165.6659
