### ISSUE TITLE
Achievable Pump Efficiency calculator

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#162]

**Comment by gaccawi** [comment]
![image](https://cloud.githubusercontent.com/assets/8973004/24714952/fbc41ca6-19f7-11e7-8cbf-74dcd37bb80f.png)

**Comment by rmroot** [comment]
Mock up done. Hasn't been implemented

**Comment by rmroot** [comment]
![achievable-pump-efficiency-psat-electron](https://cloud.githubusercontent.com/assets/10789740/24873358/1e2fbcd6-1de6-11e7-9e7a-b690d91e22ac.PNG)

From old PSAT Electron
