### ISSUE TITLE
NEMA Energy efficiency calculator

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#163]

**Comment by gaccawi** [comment]
![image](https://cloud.githubusercontent.com/assets/8973004/24714977/07f0d442-19f8-11e7-8954-2e3329930183.png)

**Comment by rmroot** [comment]
Mock up done. Hasn't been implemented

**Comment by rmroot** [comment]
![nema-psat-electron](https://cloud.githubusercontent.com/assets/10789740/24873378/348a61ac-1de6-11e7-924a-6c83b3c4e9b9.PNG)

From old PSAT Electron
