### ISSUE TITLE
Make Facility Info more obvious

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1654]
1 - Add link on home under "create assessment" that is "Create Facility Assessment".  Modal asks you to name folder and clicking create takes you to the folder in the dashboard.  with facility info open?

2 - Add link on Assessment Settings (PHAST and PSAT) that takes you to the assessment's folder (with facility info open?)

**Comment by rmroot** [comment]
If facility info is primarily used for reports, should we fill it out there?

**Comment by koay9f** [comment]
Add folder choice to the New Assessment Modal
Allow user to add and name new folders here also
