### ISSUE TITLE
Pre-Assessment in roll up

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1696]
make sure that the equipment you have in the "Energy Use" in the roll up is in the same order/colors as in the pre-assessment in the roll up, but I have no idea how to handle that...

**Comment by nbintertech** [comment]
May be able to create a filter service to call from pre-assessment-table.component and rollup-energy-use-table components. Setting aside until higher priority

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c6917966-bf86-446b-9f13-5842d099a4a4)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9d215e20-cac2-4b30-a43a-6cc66a634dd1)
Sent Rachel an export via slack.
