### ISSUE TITLE
Pre-Assessmnet Help Text

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1699]
Need general intro/description for pumps Metered and Design, the furnace descriptions are too heavy on furnace verbage to make agnostic, I think a second set of help would be easiest.

Missing 3 help fields for Metered Fuel:
"Type of Fuel"
"Metered Fuel Energy"
"Calculate using flow rate"

**Comment by koay9f** [comment]
Metered:
Enter data about the energy use of process equipment based on meter data. This helps the user prioritize which equipment to focus assessment efforts on. This method calculates total energy used by the equipment by multiplying meter energy data by the measurement period (hours).

Designed Energy Help
Enter data about the design of process equipment. This helps the user prioritize which equipment to focus assessment efforts on. This method calculates total energy used by the equipment by multiplying total rated capacity of the equipment with annual operating hours, percentage rated capacity used and duty cycle.

Type of fuel:  Choose between Gas or Solid/Liquid Fuels
