### ISSUE TITLE
Calculator Saving

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1714]
Brainstorm ways to allow users to "save" calculator calculations

Print Screen 
Generate csvs

Requires #2616

**Comment by koay9f** [comment]
generate table  with inputs and results.  
put in inputs --> hit "Add To Table"

be able to export as csv

**Comment by koay9f** [comment]
Figure out where it fits into the folders

**Comment by koay9f** [comment]
Kristina:  which calcs need functionality

**Comment by koay9f** [comment]
Lighting calc is a good place to start

**Comment by rmroot** [comment]
Just Saving lighting calculator

**Comment by rmroot** [comment]
Created treasure hunt assessment and added initial functionality for saving Lighting Calculator. Can be found in `treasure-hunt` branch
