### ISSUE TITLE
Fans - Hook up AMCA Modal

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1717]

**Comment by koay9f** [comment]
[FSAT Turn Operating points calculator into.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2036479/FSAT.Turn.Operating.points.calculator.into.docx)

**Comment by koay9f** [comment]
Revised
[Uploading FSAT.Turn.Operating.points.calculator.into.docx...]

**Comment by koay9f** [comment]
Revised Again
[FSAT.Turn.Operating.points.calculator.into.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46cea7bb17ccb7bc9de7f16cb458e2953d4f29746714ac227e91f066bc4377021a031fe81e1a411da2bdd639baa47c32d5065ebe957f5566c33445f9ead31deb08bd71dd1dd7b6bc8f4b96e93876b58d9d532c5c5446dda0006ceacc09da52e44ae64754a1113161e0743f7e44951b753e26.docx)
