### ISSUE TITLE
FSAT - Diagram

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1727]
Need diagram for fans

**Comment by gaccawi** [comment]
![Fan Diagram_v1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46ce959463a68aa888fbbe4e9b4ba1d665043761260ea62864c7b96aea1b7f040d0e4cf8485f0e12aeab892ba3b16a718f0f59ebc3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc2e83422e3838649391a1755.png)
