### ISSUE TITLE
FSAT - Add Calculators

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1729]
Setup fan calculators in assessment

**Comment by rmroot** [comment]
Can setup and add AMCA 203 but may want additional calculators first?

**Comment by koay9f** [comment]
Any motor calculators that are in PSAT can be added

**Comment by koay9f** [comment]
System Curve:
Head --> Pressure, change units
Flow, change units
calculation should be okay

Achievable FAN Efficiency
Flow, change units
FAN type, use fan list.  for calculations use OptimalFanEfficiency.h I guess

Motor Perf. is good
NEMA Efficiency is good
Cut Specific Speed

FAN curve
Head --> Pressure, change units
Flow, change units
calculation should be okay
