### ISSUE TITLE
Fans - Additional Units

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1736]

**Comment by koay9f** [comment]
Figure out what units are for metric

**Comment by koay9f** [comment]
Fluid
![image](https://user-images.githubusercontent.com/25389736/40940136-d740636e-6814-11e8-9d99-8f92e556f8ba.png)

Fan - No units
Motor - already good


Field Data
![image](https://user-images.githubusercontent.com/25389736/40940128-cfab83c2-6814-11e8-86df-6a0598903948.png)


Anything that was missed:
![image](https://user-images.githubusercontent.com/25389736/40940163-ee03defa-6814-11e8-816c-15ec3a5d16af.png)

**Comment by koay9f** [comment]
In Metric, Flow Measurement needs a default (m3/hr)
