### ISSUE TITLE
Fsat - Field Data validation

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1737]
Need validation for flow rate and motor power. 

PSAT flow rate validation uses pump style.

**Comment by rmroot** [comment]
[New.FSAT.Help.Text.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46c6918d6da4b088bba79746a84dbea02c5e33316546b3397f8fe62bab0021435a561af913095d10f5fed87df4e43c708f5b5decd43e0d72d42103eee9dc4be05ce36ade0d97bcae8b44cae93827e08d864b371c031b80fb4f78.docx)

I think this document has the ranges for validation

**Comment by koay9f** [comment]
^ yes that should have everything

**Comment by koay9f** [comment]
Validation for Gas Density works when being calculated, but not when direct user input
