### ISSUE TITLE
Motor Drive Icon

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#1800]
Need icon for motor drive calculator

**Comment by AshaShibu** [comment]
![drive](https://user-images.githubusercontent.com/31292133/40503826-5d2b7c72-5f5d-11e8-867d-6ae4ec2825a7.PNG)

**Comment by AshaShibu** [comment]
![download](https://user-images.githubusercontent.com/31292133/40511370-7703c9be-5f6d-11e8-9125-1d247e4082c1.jpg)

**Comment by rmroot** [comment]
Is it possible to get icon without a white background?

**Comment by AshaShibu** [comment]
![img_8444](https://user-images.githubusercontent.com/31292133/40732633-afd27540-6401-11e8-8b5c-29a715357578.jpg)

**Comment by brappop** [comment]
![drive.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b16cbd52262de001287e149/125516c66e82c728ace21e0d46ec86933587c1e5cdf9ad4cae58f3806b1c65267000a62971d7e771e8437d030d5f4ea9460e5e41afab8f39baa47e21d40854b088270a36d43703adbf881eba03b224824f82bfb58e4cc7fa70.png)

icon without white background
@rmroot
