### ISSUE TITLE
PSAT Sankey identical

### ISSUE THREAD

**Issue by serob20** [ORNL-AMO/AMO-Tools-Desktop#1806]
Sankey diagrams for modification is the same as baseline for report and sankey- not in explore opportunities

**Comment by serob20** [comment]
![Explore Opps Sankey.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46cd8c8a2f8d91accfc6af53b71dc395274d226a6b48e13b628ae92dbc56395b4d5a47f8140a0e46a8f08e7af0e46e708a590cbbd0680c26c02f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e5838e4c3d1a071a8ffb5d27ed.png)
![Report Sankey.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46da918a2c9097e9bce8b148a144b2d86b56357c2301a03f32dfa17de6467e030e5d1aa546090916aef9892ea1e03d75d90e0dffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98844c1eb3e21e48d8b473f0c48.png)

**Comment by serob20** [comment]
Top picture is from the Explore Opportunities Sankey tab, those are correct. The bottom picture shows what the Sankeys looks like in the report tab and the Sankey tab, the modified Sankey should not be the same as the baseline Sankey

**Comment by koay9f** [comment]
ummmm... I assume this is related...

![image](https://user-images.githubusercontent.com/25389736/41358797-2350a366-6ef7-11e8-8e02-e7150b060ca7.png)
It is like this in Report and Sankey, not in explore opps.

[test_sankey.txt](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2098647/test_sankey.txt)

**Comment by koay9f** [comment]
Just made a new one, just in case.  It is screw in Sankey for both baseline and modification.
