### ISSUE TITLE
Adding new assessments to a new folder

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1817]
Will not automatically add new assessments to a folder created in the new assessments modal.

It creates the assessments and it creates the folder, but the assessments are put on the "All Assessments folder".  Could it be made that, if you create a new folder, it automatically is chosen for that assessment?

**Comment by rmroot** [comment]
I believe this is how the current application is set up.

**Comment by koay9f** [comment]
The new folder is selected, but the new assessment goes into the "All Assessments folder".
If it helps, I'm getting an error "Form submission canceled :1 because the form is not connected"
