### ISSUE TITLE
Power factor Correction- Icon and Help Text

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#1821]
[Power Factor Help +Icons.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2048588/Power.Factor.Help.Icons.docx)

**Change the unit of Current demand from A to kW**

**Comment by AshaShibu** [comment]
[Power Factor Help +Icons.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2048586/Power.Factor.Help.Icons.docx)

**Comment by rmroot** [comment]
a branch has been started with the help text `issue-1821`

**Comment by vanced** [comment]
I have more to add to this issue.
[Power.Factor.Help.Icons.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46d89b8d2690cd8f8eeaab4cb613d8912556695a2a0bad3832c9a138ad4d71040c1b5ca6535d5610a9abd829f2bf3b21dc0e59edd1685822c73842febe9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3c16021c8af65d36a99148da15.docx)
