### ISSUE TITLE
PHAST graph labels incorrect

### ISSUE THREAD

**Issue by serob20** [ORNL-AMO/AMO-Tools-Desktop#1845]
The labels don't add up to 100%

**Comment by serob20** [comment]
![PHAST graph error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46d8bcbb10b6c3ae9de8af4be458e2862654653f6b14b1247a80e03cfd183954560b1bfe105a0b4dfba8df79f4b63c758d0a0ae8823f5966da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3f2de688874c3d1e011f88ed10.png)

**Comment by koay9f** [comment]
Still seems to be a problem (on develop)
