### ISSUE TITLE
PHAST energy intensity error

### ISSUE THREAD

**Issue by serob20** [ORNL-AMO/AMO-Tools-Desktop#1866]
Energy intensity shows in the report but not in results- also off by a factor of 10⁻⁶, should be 1,424.5 in picture

**Comment by serob20** [comment]
![PHAST energy intensity 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46d8bcbb10b6c3ac81ecad44bd1df99a3d4329602010ba6b21c7af6aaf50740b0a0c0abe4b4a5a4da8acdb7aa4e23577db0a59bfd16d5a73903c14ffea840da313f871d51bdaebe5c01982fa3737e68c854e3b1c0d1b80f75432a59e4bcf4abb.png)
![PHASt energy intensity 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46d8bcbb1096c3ac81ecad44bd1df99a3d4329602010ba6b22c7af6aaf50740b0a0c0abe4b4a5a4da8acdb7aa4e23577db0a59bfd16d5a73903c14ffea840da313f871d51bdaebe5c01982fa3737e68c854e3b1c0d1b80f7543da2984ece4abb.png)

**Comment by rmroot** [comment]
All of that is being overhauled

**Comment by koay9f** [comment]
connects #1794
