### ISSUE TITLE
Upgrade to EAF algorithm

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1872]
What we want...

User enters "Electricity Input" in the "Energy Input" page.
This is used to calculate "Exhaust Gas Loss" (instead of calculator)
Exhaust Gas Loss = Energy Input Total - sum (all losses)

IF user enters an Exhaust Gas Loss, then modify "Other Losses"
"Other Losses" = "Other Losses form total" + Energy Input Total - sum (all losses)

On Exhaust Gas page, before the user clicks "Add Loss" show message
`This can be automatically estimated from your total energy input or estimated from data relating to your exhaust gas`

On Energy Input page.  Change help text for * page * to...
`The data entered on this page is used to estimate the total energy input into the system.  If data regarding the system's exhaust gas is not known, this is also used to estimate exhaust gas losses after all other losses are estimated.`

In case it isn't already, Energy Input is a required calculator. 

ORIGINAL - IGNORE THIS ------

* Remove page for exhaust gas (users will rarely know this data very well, data collection is very expensive)

* Actually use input for electrical energy

Know energy inputs (electrical input + chemical inputs)

Know MOST losses (except exhaust)

Exhaust losses = sum(inputs) - sum(charge + other losses)

**Comment by koay9f** [comment]
make exhaust gas loss a stand alone calculator

**Comment by rmroot** [comment]
BRANCH issue-1872

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/13480642-c1e2-4236-b982-7fe7a59094f0)
slacking you the test file
