### ISSUE TITLE
more unit checks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1878]
Anytime you have F,  Fahrenheit, or C, Celsius
it should be °F or °C

**Comment by brappop** [comment]
°C : &#8451
°F : &#8457

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/41258423-151426c4-6d9e-11e8-8831-6cf0bea653e6.png)

![image](https://user-images.githubusercontent.com/25389736/41258467-362e8e44-6d9e-11e8-8c56-f14ecb3ea3fa.png)


also check Imperial

**Comment by rmroot** [comment]
Second image will be taken care of in 1738
