### ISSUE TITLE
Auxiliary Power - Heat Use

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#188]
This loss appears for Induction Heating and Melting, Electrical Resistance, Electrical Infrared, and Vacuum Furnace (*NOT* for Electric Arc Furnace)

![image](https://cloud.githubusercontent.com/assets/8973004/25197488/41b81102-2512-11e7-8433-7cf305b00e19.png)

**Comment by pshires** [comment]
https://github.com/ORNL-AMO/AMO-Tools-Suite/tree/addAuxiliaryPowerLoss

the bindings and calculation are both implemented now
