### ISSUE TITLE
Tidy Fan units

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1892]
minor issues with fan unit labels

Fans Field Data in H2O  (space between in and H, capital O)
![image](https://user-images.githubusercontent.com/25389736/41295226-097a5c18-6e28-11e8-8f95-58a315a3e088.png)

**Comment by koay9f** [comment]
check flow and density units to make sure the 3's are superscript

**Comment by brappop** [comment]
2 in h2o to be subscript

**Comment by koay9f** [comment]
also in calculate inlet pressure and in calculate outlet pressure
