### ISSUE TITLE
Order of calculators differs between sidebar and "All Calculators" tab

### ISSUE THREAD

**Issue by brappop** [ORNL-AMO/AMO-Tools-Desktop#1926]
Sidebar:
Motors
Pumps
Fans
Process Heating*
Steam
Compressed Air
General

All Calculators:
Pumps
Motors
Process Heating Equipment*
Fans
Compressed Air
Steam
General

*bonus: sidebar has "Process Heating" while all calculators has "Process Heating Equipment"

**Comment by koay9f** [comment]
I think merging `fans` into `develop` may have lost this
