### ISSUE TITLE
Create Dynamic Power Factor Triangle

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#1947]

**Comment by vanced** [comment]
[Dynamic triangle for Power Factor Calculator.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cc8d94228f8aaacffdad4aa553f7982c06217c3b4493246780f16899437815001d5edf10040c01a0a8cd74e4a42062ca1e54b7843e1b66cc2f14a5ecd74dee03ee298c1ed3e4ee8a4cc5ef6b24e2d8dd492c02175ad8a1096afdc0019d1ae441f34f55ae123361ef7235784f9d16712963756b.docx)

**Comment by vanced** [comment]
Dynamic triangle should change according to output of Power Factor Calculator.

**Comment by gaccawi** [comment]
Connects 1612

**Comment by koay9f** [comment]
I have a excel for this, but it has macros, b/c of Chris :D

message Kristina for file
XLSM_PFcalculatorUpgrades.xlsm 
Tab 1 "PF Triangle Calculator"

Inputs & Results:
Apparent Power (kVA)
Real Power (kW)
Reactive Power (kVAr)
Phase Angle (degrees)
Power Factor (fraction)

Inputs - 2 of those, 9 options (see excel)
Results - the remaining 3

<img width="531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fe82e412e445ac62905e6f430d36bbe08526e3d/image.png" alt="image.png" />


Graph - 
3 lines from 2 points each
Line 1:  x: (0, Real Power), y: (0, 0)
Line 2: x: (0, Real Power), y: (0, Reactive Power)
Line 3: x: (Real Power, Real Power), y: (0, Reactive Power)

<img width="511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02c4d58769cdc13c9c03648781a89e579b0951fe/image.png" alt="image.png" />
