### ISSUE TITLE
PSAT "Report Graphs" calculation error

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#1964]
I'm fairly certain there is a calculation bug in the PSAT Report Graphs; I believe the "modification" item on the bar chart is incorrect - it should be lower.  It may be tied to changing the head and/or flowrate.  Screenshots attached

![image](https://user-images.githubusercontent.com/16322443/41794583-cfd109f4-762d-11e8-83fd-d8c51339430f.png)
![image](https://user-images.githubusercontent.com/16322443/41794596-dad7ea0c-762d-11e8-8cdf-9774da2d7f12.png)

**Comment by koay9f** [comment]
was able to recreate.

for some reason, it is saying the pump losses are 54.04, when they should be 5.62 according to the Sankey (which looks correct).  

This is the case for the two where head and flow were changed...
the values should be
Opportunities Modification (1)
motor: 2.47kw, 7.9%, pump: 5.62 kW, 18%; useful: 23.1 kW; 74%
Opportunities Modification
motor: 2.37 kW, 9.9%; pump: 4.23 kW, 17.7%; useful: 17.4 kW, 72.8%


attached the assessment

[issue_1964.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46e187893687bcf8d6bfeb01e81fe086264c22703d46f96925dce72dbd43290556581ffa130a5f44f9fedf2aa3e56e76984019af80330b2b9b645bf9fa9015ad00b22a8a4a86b6bd8a4bc0ed3b22e58f9d02.txt)

**Comment by koay9f** [comment]
did not use explore opps to make modifications.
