### ISSUE TITLE
Need consistent looking graphic for motor drive calculator

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#1967]

**Comment by serob20** [comment]
![MotorDrive1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46c59b8e2c90a7bb86ffba12e611b2843b492d762a10e17132d0ba2cba407a530b5649fd170a0d44fcfc8e7da7b36f228c4e17ff933c0120996048e6edc00db513bb28814e80b5bd8d4ac3eb3520e388895d73.png)
