### ISSUE TITLE
PSAT report graphs hover - and axis units

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#1988]
the units for the PSAT (and probably FSAT) bar chart hover should be kW not hp

**Comment by DmitryHoward** [comment]
Could not replicate. Units in the bar charts updated with unit changes in system settings.

**Comment by koay9f** [comment]
The units of the graph axis and hover should always be kW.  I don't know why the units for motor power change w/ system settings, but they are not supposed to

![image](https://user-images.githubusercontent.com/25389736/42381456-20d388e6-80ff-11e8-98b5-ae20720d8721.png)
