### ISSUE TITLE
FSAT Operating Points Help

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2002]
Use the AMCA 203 Document from Flowcare

**Comment by vanced** [comment]
[Operating Points Calculator Help Text.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46c7849f318397a081eeff73ab54fe803a0604722507b6277191ec3aff6a7e0d1f4f2af9091c4d58eeb9cb74fce36f34985619e8d8390a26973f45a5bfd349ed53ba208e48d3b7b9d91ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e14455a0103e63ef7e366e0a.docx)

Needs review by Kristina and Sarah

**Comment by koay9f** [comment]
New version.  use this.  Need to check some things with Tom/Daryl, but should be good to get started with
[operating points.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46e7849f318397a081eeff53ab54fe803a046b313916ac217586f76ae5002e580b0a1cfd430c5643adafdb79a6b63977dc5d0ebe836b4d68d47f40f2ecdd42e64bef62994597b7b4804dc5eb3c26e38c8a4e3f1e0d1a9bb2.docx)

**Comment by koay9f** [comment]
revision of text (no revision to defaults/ranges)
[operating points help.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46e7849f318397a081eeff53ab54fe803a062f762514e1673295f127b54778154d555ca9480c0a16adfbdd22a1e76a22d85c0be8d63b5e71956f17bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8c4e3a1c0d1f8dfb5f35a28b06.docx)

**Comment by koay9f** [comment]
New version. changes to help text only.  not defaults or ranges
[operating points help.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2190291/operating.points.help.docx)

**Comment by koay9f** [comment]
Revised.  Only text and figure changes.  No changes to ranges or defaults.
[operating points help.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46e7849f318397a081eeff53ab54fe803a062f762514e1673295f127b54778154d555ca9480c0a16adfbdd22a1e76a22d85c0be8d63b5e71956f17bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8c4e3a1d05198ffe5e31a78b06.docx)

**Comment by rmroot** [comment]
Opened PR with field by field setup, help content still need to be added. 

Ranges are applied to forms but messaging needs to be added for errors.

**Comment by koay9f** [comment]
Specific field edits:
Gas Dew Point (Est. Base Gas Density)
The temperature where air is cooled enough to become saturated with water vapor. For atmospheric air, this can be found via weather reports. Otherwise, it’s a result of the gases composition and pressure.

Missing help text
Specific Heat Gas (Est. Base Gas Density)
The amount of heat required to raise the temperature of the gas one degree for each unit of mass. For air this is 0.24 Btu/lb °F, for flue gases, this ranges between 0.248 and 0.320 Btu/lb °F, depending on temperature and composition.

VFD Efficiency
If fan is equipped with a VFD, input the VFD efficiency (%)


General Text for Plane 2:
Plane 2 is the fan outlet flange. If there is an evase, Plane 2 can be located either upstream or downstream of Plane 5.
