### ISSUE TITLE
FSAT - Explore Opps Sankey

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2020]

**Comment by koay9f** [comment]
Values are screwy
For the example fan
![image](https://user-images.githubusercontent.com/25389736/42386728-4a50e54c-810e-11e8-829f-04d77fc03e73.png)

**Comment by koay9f** [comment]
Baseline:
Energy input = 450 kW
Motor = 19.06 kW
Drive = 17.23 kW
Pump = 151.42 kW
Useful Output = 262.29 kW

Modification:
EI = 354.4 kW
M = 15.33 kW
D = 13.57 kW
Pump = 120.44 kW
UO = 205.06 kW
![20180709_093841.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46bac4cb7bd2d4f9d6d6ef1af705a4c56b0a65633b0ba92e7391a172fd1722050a0d1fae15515815aaabdb2ba6b33b268b5958bfd77f4366846c4ff8e7df46f554f832815d84b1b68b49c3e93c21e48c8e4b3717010ac4.jpg)

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/42454143-b6497c8c-835c-11e8-8934-eb3dbf2bd1bc.png)
