### ISSUE TITLE
Add Fan Calculators and Motor Calculators to All Calculators

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#2046]
Add fan calculators and Replace Motors calculators to All calculators list. Currently if you click on Operating Points calculator from all calculators it it sends you to the Fans calculators not the Operating Points Calculator like the others.

**Comment by koay9f** [comment]
split the last part of this into its own issue (clicking on Fans from fan calculators)

**Comment by koay9f** [comment]
This issue should just cover:
adding fan calcs to all calculators
fixing the operating points calculator link

**Comment by koay9f** [comment]
also add the new motors calculators
