### ISSUE TITLE
Release notes for v0.2.29-beta

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2071]

**Comment by koay9f** [comment]
[Release Notes v0.2.9.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46da9196268390accfc7b057a14eb0827908753d7046ef696097ec22ba416f43554d4ba5150d0d15fead802cf7e06e228a5c0eea876c5a27943b03b0aac04ee155e57dd205d0f4ae805ec1e03724e2888e463a17061e88fa5a3cb2d4.txt)
