### ISSUE TITLE
System Capacity Calculator

### ISSUE THREAD

**Issue by serob20** [ORNL-AMO/AMO-Tools-Desktop#2128]
Units should be cubic feet for total pipe volume, total receiver volume, and total capacity of compressed air system

**Comment by serob20** [comment]
![System Capacity Units.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46db8d8937878ee9ace8af42a754e48d6973297a3d17e1673295f127b54778154d555ca9480c0a16adfbdd22a1e76a22d85c0be8d63b5e71956f17bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8c4d3e1c071981ff5b3da58b06.png)

**Comment by serob20** [comment]
![Picture2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc497d0bfb6000116ed267/125516c66e82c728ace21e0d46d89d99379791acddabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901dbf0bbb25884d86bebc8b49c7e83824f5c6.png)

**Comment by serob20** [comment]
"Pipe Size (ft)" should be changed to "Pipe Diameter (in.)" 
Add "Pipe Length" as title above input fields
Button for ability to add a different pipe diameter underneath existing pipe diameters ( picture says "Add pipe size", but should say "add pipe diameter"

**Comment by rmroot** [comment]
Adding additional pipe sizes would have no effect on calculations with updates to the tools suite.

I changed the "Pipe Diameter (in.)", was I supposed to change the units from ft->in on the inputs too?

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/43721181-212e6cb0-9960-11e8-974b-5a691ed80cb0.png)

top unit still needs to be ft^3

the units for pipe length (the inputs) are good

for the "add length" idea, could we do the math in the UI (see below) and then add that total to the total given by the C++?

input diameter (inches)
input length (feet)

individual pipe volume (ft3) = (pipe diameter / 24) ^2 * pi  * length
additional pipe volume = additional system volume = SUM(all individual pipe volumes)

Total pipe volume = value from C++ + additional pipe volume
Total system volume = value from C++ + additional system volume

**Comment by rmroot** [comment]
I'm making a second issue for adding additional pipe lengths
