### ISSUE TITLE
Boiler Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2134]
https://www4.eere.energy.gov/manufacturing/tech_deployment/amo_steam_tool/equipBoiler

**Comment by vanced** [comment]
Help:
`Input steam properties, flow rate, and general boiler operational characteristics to determine the amount of fuel energy required to produce steam at the specified properties.`

Description:
`Determines the amount of fuel energy required to produce steam with specified properties at a given flow rate using general boiler operational characteristics.`

**Comment by koay9f** [comment]
Looks great.  Add above description pls.
