### ISSUE TITLE
Heat Loss Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2135]
https://www4.eere.energy.gov/manufacturing/tech_deployment/amo_steam_tool/equipHeatloss

**Comment by rmroot** [comment]
Form, Results, Conversions are all done.

Still need: 
Help
Validation Boundaries

**Comment by vanced** [comment]
Help:
`Input inlet steam conditions and % heat loss to determine energy (heat) loss and outlet steam properties.`

Description:
`Calculates the energy (heat) loss and outlet steam properties given inlet steam conditions and a % heat loss.`

**Comment by koay9f** [comment]
Inlet Entropy value had inlet enthalpy's value
Outlet enthalpy's value had inlet enthaply's value
Outlet enthalpy (once ^ was fixed) needs to be 1000 x (making issue)

check unit conversions in imperial

apply top help and description text
