### ISSUE TITLE
Flash Tank Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2136]
https://www4.eere.energy.gov/manufacturing/tech_deployment/amo_steam_tool/equipFlashtank

**Comment by vanced** [comment]
Help:
`Input inlet conditions to determine mass flows and properties of resulting outlet gas and/or liquid.`

Description: 
`Determines the mass flows and properties of any resulting outlet gas and/or liquid for given inlet conditions.`

**Comment by koay9f** [comment]
Description & help needed

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/43324785-00d51bec-9183-11e8-83d7-593ae1525652.png)
