### ISSUE TITLE
Header Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2138]
https://www4.eere.energy.gov/manufacturing/tech_deployment/amo_steam_tool/equipHeader

**Comment by vanced** [comment]
Help:
`Input header pressure and inlet conditions to determine the combined steam properties.`

Description:
`Calculates the combined steam properties of multiple steam inlets.`

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/43432497-2c5c907c-9441-11e8-9e6d-0bf05028cfb4.png)
nothing in phase slot
all inlets seem to be just repeating combined header
![image](https://user-images.githubusercontent.com/25389736/43432524-5197dc2a-9441-11e8-9037-5064eaf0fd04.png)

**Comment by koay9f** [comment]
Energy flow has an extra x 1,000,000.

**Comment by koay9f** [comment]
^^ my fault, it looks like it was off by x 1000.  (so now it is off by 1/1000)
![image](https://user-images.githubusercontent.com/25389736/43720075-748b9642-995d-11e8-8386-09c913e6313e.png)
