### ISSUE TITLE
Save calculators

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2142]
some calculators need to be able to be saved

Fans Operating points

**Comment by rmroot** [comment]
In addition, do we want to persist data throughout the time the app is open? Meaning, when the user navigates away from the calculator and comes back it is in the same state?

**Comment by rmroot** [comment]
Do you mean save within an assessment?

**Comment by koay9f** [comment]
Persist would be a great start.

Need to brainstorm maybe, but I think more like save like an assessment, or more accurately a pre-assessment

**Comment by rmroot** [comment]
Created second issue for persist #2258, will continue to explore how we want to save like pre assessment.

**Comment by koay9f** [comment]
Which calculators should be saved?  Can they be saved with the assessment?

Do we want some to be saved more like pre-assessment (fan analysis)?
