### ISSUE TITLE
Stand alone flue gas calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2156]
In Steam Calculators
Called "Stack Loss Calculator"

Uses flue gas calculator from PHAST

Results are 
Stack Loss = 100% - Available Heat%

the others are not necessary

**Comment by koay9f** [comment]
If we could "hide" `Fuel Temperature` and just set it to be equal to `Combustion Air Temperature`

Change `Combustion Air Temperature`'s label to `Ambient Air Temperature`

**Comment by vanced** [comment]
Help:
`Input fuel type and flue gas and combustion characteristics to determine the amount of heat lost in the boiler stack gas.`

Description:
`Determines the amount of heat lost in the boiler stack gas based on fuel type, flue gas characteristics, and combustion specifications.`

**Comment by koay9f** [comment]
Also put a result line for Stack Loss on the left panel (we will eventually be putting a different graph there)
Give the result 3 sig figs

Change `Flue Gas Temperature` to `Stack Gas Temperature`

Need defaults for solid/liquid (Kristina)
