### ISSUE TITLE
Auto Scale Fan Curve Calculator Graph

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#2208]
The y-axis doesn't seem to scale.  We entered a max pressure of 0.6 in H2O and it kept a max scale of 100

**Comment by koay9f** [comment]
Still not scaling right.  Here is an example curve 
![image](https://user-images.githubusercontent.com/25389736/44731456-3cc0c600-aab1-11e8-944c-54c2db6d4637.png)

the x-axis is okay, but the y is still not scaling

it looks like the green line is doing something weird right at the y-axis, so it could be the axis scaling is behaving fine but there is something wrong with the line generation?

I tried putting the equation in and the y-axis line disappeared, but still didn't scale correctly

**Comment by DmitryHoward** [comment]
connects #2213
