### ISSUE TITLE
PHAST and PSAT Report Rollups

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2218]
Empty rollups show in print when there are no psat or phast assessments

**Comment by koay9f** [comment]
I am assuming that this is for if you make a Fans rollup.  I just did these two assessments (just deleted my data and made them fresh).  

and this was my roll up.  


If this is not the same issue tell me and I will make a new one

**Comment by DmitryHoward** [comment]
Printed reports has not been created at all for fans, so this will need to be a separate, much larger issue.
