### ISSUE TITLE
Steam Icons

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2266]
Add icons to application after getting back from graphics

**Comment by gaccawi** [comment]
![1-Boiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46b9d9b82c8b8fac9dabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb70bbb25884b81b2b8824ac3ec3c26f5c6.png)
![2-Heat Loss.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46bad9b2268397e9a3e6ac50e611b2843b492d762a10e17132d0ba2cba407a530b5649fd170a0d44fcfc8e7da7b36f228c4e17ff933c0120996048e6edc00db513bb28814e80b5b88e48c4e03b26e4838c5d73.png)
![3-Flash Tank.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46bbd9bc2f8390a1cfddbe4daf1fbcd6395428792c07b7692ac7b671bb4779005d0b47ab100e0d16fcf98c2cf0b73923d85a19f1c32f0e2a92624cf5f2d75dad0ba821824584b3bf8e48c4ec3523e4888c4e2c53.png)
![4-PRV.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46bcd9aa11b4c1e5cdf9ad4cae58f3806b1c65267000a62971d7e771e8437d030d5f4ea9460e5e41afab8f39baa47e21d40854b088270a36d43703adbf881eba02be248f4b8db0bf8e4cc4fa70.png)
![5+Header.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46bddfb2268387ac9dabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb70bbb25884b81b2b8824ac3eb392cf5c6.png)

![6-Deaerator[1].png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46bed9be268386bb8efdb0519f0ccdd665043761260ea62864c7b96aea1b7f040d0e4cf8485f0e12aeab892ba3b16a718f0f59ebc3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc4ec3921ef8d8c4c3c1f1755.png)
![7-Steam Turbine.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46bfd9a9378782a4cfddaa51a654fe916b0a65633b0ba92e7391a172fd1722050a0d1fae15515815aaabdb2ba6b33b268b5958bfd77f4366846c4ff8e7df46f554f832815d84bfb68b49c3ec3921e383894c3d1c050ac4.png)
