### ISSUE TITLE
When auto-update fails, don't just hang

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#2267]

**Comment by koay9f** [comment]
to test: try to update without internet connection when we do next release

**Comment by rmroot** [comment]
Re-worked update flow.

Now using "Toast" in upper right hand corner. 

Release notes for new update can be viewed via link/modal.

2 steps to update:
1: Download
2: Quit and Install (will install on quit after download)

Can test auto updater in without release...
To do so, change version number in package.json to a previous version.
in "main.js" comment/remove if(!isDev()) statement at line 48.

Then you should be able to build and test locally.

**Comment by koay9f** [comment]
Yay it works!!!
