### ISSUE TITLE
Add print button to quick report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2274]

**Comment by rmroot** [comment]
In the folder summary dashboard you can view a quick report that pops up as a modal. Add printing functionality.

**Comment by nbintertech** [comment]
We should consider not doing this. It will create a situation where the user sees a print dialog inside of a modal inside of a modal. The amount of work and dev time to get around this issue would be significant and would probably end in us just re-routing them to the actual report.

Can we close?
