### ISSUE TITLE
Fan Curve Calculator Error

### ISSUE THREAD

**Issue by Harrison-Kesling** [ORNL-AMO/AMO-Tools-Desktop#2285]
When using the fan curve calculator, modifying the speed or diameter to a value lower than the baseline results in the modified fan curve being higher than the baseline and vice versa. Reducing speed or diameter should result in a fan curve that is lower on the graph than the baseline condition.

![measur tool error clear](https://user-images.githubusercontent.com/42644676/44531030-c80b1780-a6bd-11e8-8bdd-a2ba7f804f44.JPG)

**Comment by koay9f** [comment]
pump-curve-graph.component.tx

getModifiedData
line 320
`let ratio = baseline / modified;`
should be
`let ratio = modified / baseline;`
