### ISSUE TITLE
Compressed Air Metric

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2292]
Compressed air is not setup for metric and even the imperial units may be wrong. I've attached a excel sheet with our current units in imperial. Need the corresponding unit in Metric. Alternatively we could add unit settings for Compressed Air if we preferred that over metric/imperial.

**Comment by rmroot** [comment]
[compressed-air-units.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb0ea554e2d93c482e673a46ef696097ec22ba416f43554d4ba5150d0d15fead802cf7e06e228a5c0eea876c5a27943b03b0aac04ee155e57dd205d0f4ae805ec1e03724e2888a4c371e051881f65432b2d4.xlsx)

**Comment by koay9f** [comment]
Metric units added

[compressed air units.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb03a554e2d43c482e673a46ef696097ec22ba416f43554d4ba5150d0d15fead802cf7e06e228a5c0eea876c5a27943b03b0aac04ee155e57dd205d0f4ae805ec1ef3724e2888a4c37190c1a89fe5c3db2d4.xlsx)


I added a column for "category", if we wanted to do individual unit settings, however there are a few problems with this
1 - a lot of categories
2 - some (like volume) use both gal & ft3 for imperial, not sure how to approach this

Putting in another issue for incorrect units (highlighted in yellow)

**Comment by koay9f** [comment]
In leak loss estimator
if put in 1000 hr/yr;  60 s to fill bad and a bag of either 12 in by 12 in or 30.53 cm by 30.53 cm

in imperial, got 0.70 ft3 / min (this is correct), but in metric, I got 0.36 m3/min when I should get 0.022.  I'm guessing there is a hard coded conversion in the C++.  the C++ is expecting the dimension inputs to be in inches.

**Comment by koay9f** [comment]
pneumatic valve is also incorrect.
50 psi; 0 psi (no flow rate) = 344.738 kPa; 0 kPa
flow rate results should be
34.38 sfm = 0.974 Nm3/min

**Comment by koay9f** [comment]
pneumatic air requirement is good

**Comment by koay9f** [comment]
Not correct
receiver tank - general

**Comment by koay9f** [comment]
Operating Costs.  costs should be same for 1000 hp or 745.7 kW

**Comment by koay9f** [comment]
System Capacity:
For now.  undo the changing label for the list of pipe  diameters.  there is no way to fix that right now.  It will just have to stay in inches. (made an issue for what to do about it.

Something weird is going on w/ the receiver tank volume.  if you put 100 gal (and no pipe lengths) you should get 13.37 ft3 for both reciever and system volume.  but receiver tank is showing 113.37 ft3

If put in 100 m3 for receiver tank you get 100.05 m3 and .38 m3 for reciever and system volume??

The custom piping works fine in metric

**Comment by koay9f** [comment]
Pipe sizing
35317 ft3/min = 1000 m3/min
50 psi = 344.738 kPa
20 ft/s = 6.096 m/s
14.7 = 101.35 kPa
__________________
962.83 in2 = 6211.8 cm2
35.13 in = 89.23 cm
