### ISSUE TITLE
Copy to clipboard Results Tables

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2298]
* Like the graph-clicking tables

* Calculator results (e.g., Motor Replace/Rewind)
* Assessment results

**Comment by rmroot** [comment]
Copy to clipboard

**Comment by DmitryHoward** [comment]
This depends on #2659 completing first.

**Comment by DmitryHoward** [comment]
Motor calculator replace-rewind is complete with style updates and new export component that can be used for all future result tables.
