### ISSUE TITLE
Help Text - Compressed Air- System Capacity

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2308]
Revamp the help text for Compressed Air- System Capacity

Add field-by-field.
All pipe lengths will be the same text.
Need some guidance for custom pipe size
need more guidance for the receiver capacities

**Comment by vanced** [comment]
[Compressed Air System Capacity Help Text.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cb9b97339086ba9cecbb038554e2d41a5f34672c09e3087195e22bb6566241270a12ec513c0a0cb8eb9539e6f4632adf0f4fffdb7f5a7d926843fdbad616b850ec72d94f85b3bbdc4dc5bb6f23f5979d0d6f405147d4a61760e28b41da59fe41e04851ad103f64ef723e744e970c38.docx)

**Comment by vanced** [comment]
Change the label `Enter the Receiver Capacities` to say `Receiver Tanks`

**Comment by vanced** [comment]
Change the top label `Compressed Air - System Capacity` to just say `System Capacity`

**Comment by vanced** [comment]
Change the calculator name from `System - Capacity` to `System Capacity` (delete the hyphen) on the side bar and in the calculator menu
