### ISSUE TITLE
Gauge Pressures in assessments

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2309]
Which assessments are expecting gauge pressures vs. absolute pressures?

**Comment by koay9f** [comment]
PSAT - 
Head: doesn't matter it is in feet

FSAT - 
Barometric pressure - absolute
all other pressures in gauge 

PHAST -
Leakage - Furnace Draft Pressure - Gauge

Calculators -
Pump
Head - all gauge pressure
Process Heating
Flow/Energy Use - orifice pressure - gauge
Compressed air
Any that are labeled "Atmospheric Pressure" - absolute
All others - Gauge

**Comment by koay9f** [comment]
adding more gauge units in another issue

**Comment by koay9f** [comment]
Given that the overwhelming majority of pressures are gauge, it may be better to change the "default" to gauge and make atmospheric the "alternative"

1 - change the unit converter so that the units with anchor shifts are the absolute pressures (+ xxxx instead of - xxxx, but it would be the same xxxx)
3 - make sure the handful of atmospheric pressures are by default absolute (see above list) and what goes into the C++ for steam is absolute (default shown in the UI will be gauge)
4 - ignore all other pressures and assume they are gauge

**Comment by rmroot** [comment]
Is the conversion for `kPa gauge -> bar gauge` the same as `kPa absolute -> bar absolute` ?

**Comment by rmroot** [comment]
May want to update help text for Barometric Pressure in FSAT

**Comment by rmroot** [comment]
Need to handle MPaa of 0 in steam calculators.
