### ISSUE TITLE
Add CO2 Emissions to Savings Results

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#2332]
Possibly set up similar to simple payback calculation.  Possibly include an option to include in the system settings.  May need to allow for emission values that can be modified.

**Comment by nbintertech** [comment]
Broken into other issues. I will do first implementation and update other issues for Josh and Rachel

**Comment by nbintertech** [comment]
closing - tracked in epic 5104
