### ISSUE TITLE
Create CO2 savings (energy to CO2) conversion calculator

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#2333]
Calculator to help convert from energy to CO2 (covering scope 1 and 2)

**Comment by koay9f** [comment]
Bad Mockup:
![image](https://user-images.githubusercontent.com/25389736/46632721-963cfb80-cb19-11e8-813e-8f3b68b76d2a.png)

Lookup table
[Updated Emission Factors.xlsx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2457840/Updated.Emission.Factors.xlsx)
