### ISSUE TITLE
SSMT Explore Opportunities

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2350]

**Comment by rmroot** [comment]
![explore-ops-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ed8c8a2f8d91acc2e6af50e90cb2d86b56357c2301a03f32dfa17de6467e030e5d1aa546090916aef9892ea1e03d75d90e0dffcd7f1d2598694ef1e1c84afd13b0328a478fb7b9894bc1e13426e3838c4c360c48.png)
![explore-ops-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ed8c8a2f8d91acc2e6af50e90fb2d86b56357c2301a03f32dfa17de6467e030e5d1aa546090916aef9892ea1e03d75d90e0dffcd7f1d2598694ef1e1c84afd13b0328a478fb7b9894bc1e13426e3838c4c360c48.png)
![explore-ops-3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ed8c8a2f8d91acc2e6af50e90eb2d86b56357c2301a03f32dfa17de6467e030e5d1aa546090916aef9892ea1e03d75d90e0dffcd7f1d2598694ef1e1c84afd13b0328a478fb7b9894bc1e13426e3838c4c360c48.png)
![explore-ops-4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ed8c8a2f8d91acc2e6af50e909b2d86b56357c2301a03f32dfa17de6467e030e5d1aa546090916aef9892ea1e03d75d90e0dffcd7f1d2598694ef1e1c84afd13b0328a468fb7b9894bc1e13426e3838c4b3e0c48.png)

**Comment by rmroot** [comment]
Per Mock Up UI

**Comment by koay9f** [comment]
When click `Adjust Steam Demand/Usage`,  `Adjust Heat Loss Percentages`, `Adjust Condensate Handling` (Condensate Recovery Rate),  there are check boxes for Low & High P, but not medium

**Comment by koay9f** [comment]
I think this is fixed by issue 2407
