### ISSUE TITLE
SSMT Diagram

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2352]

**Comment by rmroot** [comment]
![diagram-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ec9d9b249082a4c2b8fd0fe64de29b234324676b5ee17e2981e62abe107f58580e18fe13585f41fbaf882ef5e43a62964e49bc8f3900299f7744eeaa880dbe08b0218e4c82b7b5834ec4ef3f2ce399c2.png)
![diagram-2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ec9d9b249082a4c2bbfd0fe64de29b234324676b5ee17e2981e62abe107f58580e18fe13585f41fbaf882ef5e43a62964e49bc8f3900299f7744eeaa880dbe08b0218e4c82b7b5834ec4ef3f2ce699c2.PNG)

**Comment by rmroot** [comment]
Not sure how all this works but is in Mock UI powerpoint so just leaving these here for now

**Comment by koay9f** [comment]
There are files in the php code for building this if that would help

**Comment by rmroot** [comment]
Initial steam diagram has been added, creating smaller issues for remaining work.
