### ISSUE TITLE
SSMT Report

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2354]
What tabs do we need for report?
Energy Used?
Executive Summary? Will we have designed/metered/aux equipment?
Result Data
Sankey/Diagram
Input Summary
Facility Info

**Comment by koay9f** [comment]
[report mockup.pptx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/2704124/report.mockup.pptx)

**Comment by rmroot** [comment]
Have broken this issue down into multiple smaller issues. Closing this one
