### ISSUE TITLE
SSMT Header

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2366]
Setup Header tab/form

**Comment by rmroot** [comment]
![header-1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e0919b278791e4deabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb70bbb25884884bfb58c4ac0ec3525f5c6.PNG)

**Comment by rmroot** [comment]
Between 1-5 headers

**Comment by koay9f** [comment]
Go on and limit the input to 3 headers
Fix the "Desuperheat into next highest header" to specifically into medium and low pressures
Change Names to High; Medium; Low (instead of Highest...)

**Comment by koay9f** [comment]
If Desuperheat = yes then need a field for temperature

**Comment by koay9f** [comment]
^ Last comment not taken care of.  Desuperheat temperature needs an input field
