### ISSUE TITLE
Include Lighting Calculator

### ISSUE THREAD

**Issue by wenningtj** [ORNL-AMO/AMO-Tools-Desktop#2373]
Develop basic lighting replacement calculator - can pull from Treasure Hunt Toolkit calculator sheet

**Comment by koay9f** [comment]
Inputs:
Hours / day
Days / month
Months / year
Watts  / lamp
lamps / fixture
Number of fixtures

Calculate: 
Operating hours per year =  (hr/d * d/m * m/y) = hr / yr
Electricity Use = Watts/lamp * lamp/fix * # fixtures * 1 kW/ 1000 W * hr/yr= kWh/yr

Have inputs for "Baseline" and "Scenario"
Calculate Op Hrs & electricity use for both
Savings = Baseline - Modification

Optional Inputs:
lumens / lamp
Optional Calculation
Total Lighting in Workplace = lumens / lamp * lamp / fixture * # fixtures = lumens

**Comment by koay9f** [comment]
Allow multiple sets of inputs for both baseline and scenario (to model a building having more than one type of lighting).  
Maybe "+ Add Fixture" ?

use same operating hours?
