### ISSUE TITLE
PSAT / FSAT reports notes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2383]
Where should the notes be shown in the report?
Result Data? at the bottom like PHAST?

**Comment by koay9f** [comment]
Add notes to the report like in PHAST

**Comment by nbintertech** [comment]
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/60aa8bcc-7437-404b-a810-eecc854d3d21)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/6c5a73c0-612d-488a-8cff-e807dcba59da)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/b4c4bf0d-52d2-4e82-a25d-508e2dedf32a)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/92e173a1-0c78-40ec-af42-2156e3b9c275)
