### ISSUE TITLE
SSMT Help Text

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2406]
Need field by field help text for ssmt assesment

**Comment by koay9f** [comment]
Probably a lot can be re-used from the calculators.  need to ID the ones that are not in calculators 
Approach Temperature
...

**Comment by koay9f** [comment]
[SSMT modeler field by field help text.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46dba7b717c28ea68becb346b61df69d2c4a23332b1de32d7980ef2cff4a7e0d1f4f0af9091c4d58eeb9cb74fce36f34985619e8d8390a26973f45a5bfd349ed53ba208e48d3b7b9d91ec6fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f348e94a53ac163363ee72326e0a.docx)

**Comment by koay9f** [comment]
[SSMT modeler field by field help text.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46dba7b717c28ea68becb346b61df69d2c4a23332b1de32d7980ef2cff4a7e0d1f4f0af9091c4d58eeb9cb74fce36f34985619e8d8390a26973f45a5bfd349ed53ba208e48d3b7b9d91ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e84d54a7163261e275316e0a.docx)

**Comment by vanced** [comment]
Along with Operations page, on the Turbine page logic and text need to be added for the Fixed Power and Fixed Flow help text

**Comment by koay9f** [comment]
Turbine page - Max flow has Max Power's help text

**Comment by koay9f** [comment]
^ same thing, but needed for  HP-MP and MP-LP (it is fixed for HP-LP)
