### ISSUE TITLE
Default text for features that aren't implemented.

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#241]
For feature that aren't yet implemented, can we have text to indicate such. Centered in the area, or otherwise styled to look okay.

This feature is not yet available.

**Comment by rmroot** [comment]
Needed for:
- All Calculators Component
- Fans Calculators component
- Furnaces Calculators component
- Steam Calculators component
- Motors Calculators component
- PHAST Aux Equipment
- PHAST Design Energy Use
- PHAST Metered Energy Use
- PHAST flue gas losses

Should add verbage to PHAST setup that tool is still under construction

Some verbage should also be added to sankey
