### ISSUE TITLE
Treasure Hunt Assessment

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2414]
Button on savings related calculator that saves it to a special folder within a facility folder (button causes pop up that lets user set the destination facility folder)

Within that folder, user can generate a special roll up report with whatever saved calculators they are interested in.

There should also be something either in the folder or in the big roll up that lets users choose which of the calculators will be included in the big rollup report

Requires #1714

**Comment by rmroot** [comment]
Just lighting first.

**Comment by koay9f** [comment]
Is this still needed?  We basically replaced this idea with the TH Assessment, right?
