### ISSUE TITLE
FSAT warnings

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2480]
* There should be no warning for Outlet Pressure being less than zero

* Check the warning for Barometric Pressure.  It is triggering when it shouldn't.  What is the warning right now? Should probably just delete it... (changing the units for `Pressure Measurement` seem to be effecting in.  It should be governed by `Barometric Pressure Measurement`.

**Comment by rmroot** [comment]
duplicate #2248
