### ISSUE TITLE
Add cost savings to various calculators

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2501]
* Add field for "Electricity Cost" (or fuel cost)
* have it default to value in General Settings (if applicable)
* Cost savings = $/kW * kW/yr
* result = $/yr

Calculators:
* Lighting
* Compressed Air - Leak Calculator ($/scf would be input) (How would users calculate this?)

requires #2500

**Comment by rmroot** [comment]
I don't know how this is different from 2500?

**Comment by koay9f** [comment]
2500 was adding the field.  This is adding the results
