### ISSUE TITLE
FSAT Explore Opps Overhaul

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2510]

**Comment by koay9f** [comment]
see #2509

Requires ORNL-AMO/AMO-Tools-Suite#292

**Comment by koay9f** [comment]
Requires ORNL-AMO/AMO-Tools-Suite#292

see #2509

**Comment by rmroot** [comment]
Do we want size margin in explore opportunities for fan?

**Comment by rmroot** [comment]
Does FSAT have the VFD option for explore opportunities?
