### ISSUE TITLE
PSAT/FSAT Explore Opps

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2512]
Put in links to sub calculators in explore opps 
PSAT
* Head Tool
* Estimate Full Load Amps

FSAT
* Estimate Inlet Pressure
* Estimate Outlet Pressure
* Estimate Full Load Amps

**Comment by rmroot** [comment]
Don't need "Estimate Full Load Amps" for pump, remove FLA from input list and calculating automatically.
