### ISSUE TITLE
FSAT Input Data in Report

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2513]
Units?
Fan and Drive Efficiency classes are showing ENUM Values
Fan Specified / Fan Efficiency are wrong I think

&mdash; values instead of leaving blank

**Comment by koay9f** [comment]
The  fan specified/ fan efficiency will probably be take care of with issues #2511, #2510, and ORNL-AMO/AMO-Tools-Suite#292

I'm seeing the  ENUM values for drive and MOTOR efficiency class and `Load estimated method`. and the motor efficiency should be blank unless the class = specified

We also don't need to show a lot of the fields in Base Base Density unless the input type matches (`static pressure`, `dry bulb temp`, `relative humidity`, `dew point`, `wet bulb temp`, `specific heat`) (and what is `Condition Location`?).

Also do not need `Pressure Calc Result Type` under Field data
