### ISSUE TITLE
Update PSAT Results Tables

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2579]
Add additional psat results to results tables.

from suite issue 290

**Comment by koay9f** [comment]
Load Factor 
Think this needs a x100%

![image](https://user-images.githubusercontent.com/25389736/49602350-3c5c8480-f956-11e8-82ed-f2db5ea7a468.png)

Also, why is there two zeros?

**Comment by koay9f** [comment]
looks like still needs a x 100 before display
