### ISSUE TITLE
Finish SSMT Algorithm

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2609]
Finish SSMT algorithm and algorithm document.

**Comment by rmroot** [comment]
1/4/19:
Need to finish iterator
Vented steam from low pressure header
Need to identify and calculate missing pieces of information
       Ex: Header energy loss, Process usage

**Comment by rmroot** [comment]
Heat Exchanger

**Comment by rmroot** [comment]
Condensate flash tank negative gas mass flow

**Comment by rmroot** [comment]
Creating additional issues for:
Vented Low Pressure Steam
Condensate Flash Tank needs requires
Heat Exchanger

**Comment by koay9f** [comment]
Looks great!!!
