### ISSUE TITLE
SSMT Report Graphs

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2621]

**Comment by rmroot** [comment]
![process-use.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46f88695208790bac2fcac46e611b2843b492d762a10e17132d0ba2cba407a530b5649fd170a0d44fcfc8e7da7b36f228c4e17ff933c0120996048e6edc00db513bb29814e80b2ba8c4dc4ef3426e78a8f5d73.PNG)
![turbine-generation.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46fc8188218b8dacc2eeba4da14ff180204929316546b3397f8fe62bab0021435a561af913095d10f5fed87df4e43c708f5b5decd43e0d72d42103eee9dc4be05ce36ade0d97bcae8b45cae93821e18d8e4b391707118ff84f78.PNG)
![energy-losses.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46ed9a9f31859ae483e6ac50a14eb2d86b56357c2301a03f32dfa17de6467e030e5d1aa546090916aef9892ea1e03d75d90e0dffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98e4ac6e93922ee8c8b4a3b0c48.PNG)

**Comment by koay9f** [comment]
The generation pie - shouldn't be using the "generator efficiency" value;  should be using "power Out". For labels can you do actual value +unit AND % of pie?  or is that too much for quickly done this week?  if so, then just pick the one you can get done first and make an issue for the other.

**Comment by koay9f** [comment]
Also, only 2 decimals pls

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/53596653-33064100-3b6e-11e9-9bcb-76e61d0059cd.png)


![image](https://user-images.githubusercontent.com/25389736/53596668-3994b880-3b6e-11e9-9d82-64a5a34ed977.png)

**Comment by koay9f** [comment]
* waterfall needs units
* some waterfall values are off - see above (these fixes should also make it so all the pieces equal the total)
*  unit labels for process usage pie chart should be mass flow units (klb/hr; tonne/hr; kg/hr)
* can the pies be a little smaller so they are side-by-side.

**Comment by DmitryHoward** [comment]
Ignoring pie sizing for side-by-side.

**Comment by koay9f** [comment]
Make sure all three venting losses are included in "other" (Low Pressure Vented Steam Loss, Condensate Flash Tank Loss, Deaerator Vent loss)
