### ISSUE TITLE
SSMT Diagram- Collapse help

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2632]
On smaller screens, collapse help/results panel and add modals for clicked equipment

**Comment by koay9f** [comment]
This is still needed
Normal screen size
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ec93f953-199a-40ea-beb0-89bff166e096)
Small screen
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ce3d08a8-815e-478b-81c0-6d2e697da804)

when you click on an equipment the side bar changes, but if the side bar is hidden (b/c tiny screen) a modal would be nice
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4b0d3bbd-5a6e-4d9f-8d56-c14a9f5ef3ef)
