### ISSUE TITLE
SSMT Diagram - Errors and warnings

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2634]
Add errors and warnings to diagram.

Need to identify what errors and warnings are needed

**Comment by koay9f** [comment]
WIP list of known errors that need to appear:
If any of the steam lines  (HP, MP, LP) have a quality < 1 ; error = "Saturated"
If any of the turbines have an outlet quality <1; error = "Steam Condensing in Turbine"

**Comment by vanced** [comment]
SSMT / library / Steam / Model / Constructor.php

Beginning on line 428

**Comment by vanced** [comment]
Steam/Equipment/Turbine.php 
Line 179
"Inlet Steam contains condensate"
"Steam condensing in turbine"
"Outlet steam pressure higher than inlet"
"Steam Flow Negative"

**Comment by vanced** [comment]
Steam/Equipment/Boilers.php
Line 183

If  Outlet steam quality < 1
"Outlet steam contains condensate"

If fuel energy < 0
"Boiler using negative energy"

If mass flow feedwater < 0
"Steam Flow Negative"

**Comment by vanced** [comment]
Steam/Equipment/Deaerator.php
Line 138

If  ???? (don't understand the warning)
"Not Enough Energy to Operate Correctly"

If mass flow < 0
"Negative Steam Flow"

If mass flow == 0 
"No Mass Flow"

If ????
"Steam and Water Specific Enthalpy Equal"

If ????
"Water Specific Enthalpy Greater Than Steam"

If ????
"Steam Specific Enthalpy too Low for Feedwater Requirements"

**Comment by vanced** [comment]
Steam/Equipment/FlashTank.php
Line 105

If saturated gas mass flow == 0 && saturated liquid mass flow <> 0 (Don't understand the <>)
"No Steam Flashing"

If inlet steam phase == 'Gas'
"Inlet is Super Heated Steam"

**Comment by vanced** [comment]
Steam/Equipment/PRV.php
Line 94-96

Need conditions for generating these warnings:

"Outlet specific enthalpy associated with set desuperheating temperature is less than the cooling fluid specific enthalpy. Desuperheating canceled."

"Outlet specific enthalpy associated with set desuperheating temperature is greater than the inlet specific enthalpy. Desuperheating canceled."

"Outlet specific enthalpy associated with set desuperheating temperature is less than specific enthalpy for saturated steam. Desuperheating canceled."

**Comment by rmroot** [comment]
[steam-warnings.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46fb809f228fcebe8efbb14aaa5ae3d665043761260ea62864c7b96aea1b7f040d0e4cf8485f0e12aeab892ba3b16a718f0f59ebc3714d36976345f3e5db55ea43a82a994e82bcbd8f49c5ec3e20ef8d88493f1e1755.docx)

doc created with notes/conditions for warnings added to diagram

need update to #344 before adding PRV errors

**Comment by koay9f** [comment]
* Don't need warning on deareator for saturated stream
