### ISSUE TITLE
Add assessment buttons don't work while viewing "All assessments"

### ISSUE THREAD

**Issue by Aeledbetter** [ORNL-AMO/AMO-Tools-Desktop#2652]
When add assessment is clicked on while viewing  "All Assessments", the dialog box doesn't appear. After leaving All assessments and going to any other tab, the dialog box appears.

**Comment by koay9f** [comment]
Branch?

**Comment by Aeledbetter** [comment]
Nevermind, looks like resetting the data fixed both bugs
