### ISSUE TITLE
Hover over equipment they get big

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2680]
When you hover over a piece of equipment, have it get a bit bigger.  make sure everything still lines up

**Comment by koay9f** [comment]
everything is great. 
Is there something that can be done about the boiler not lining up tot eh pipes anymore?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4939eaab-4653-44b2-a991-445d19c58c01)

everything else looks good.  if it would take too much time (you get to define too much) then go ahead and just close the issue.

**Comment by DePauwJosh** [comment]
Was determined that this would require re-designing the diagram
