### ISSUE TITLE
User reported bug - system curve fluid power

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#2692]
Hello,

Thank you for de MEASUR it is a powerfull tool. I identify some bugs in system curve calculator, sometimes the system curve don’t update and the always the fluid power don’t be right.   

Thank You

Best Regards

Miguel Silva

**Comment by gaccawi** [comment]
![image004.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46e1999b2487d3f9dbabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb70bbb258f4782b1bf8f4ac4ea3921f5c6.jpg)
![image003.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dfa9ce3b7c3c0011288d6d/125516c66e82c728ace21e0d46e1999b2487d3f9dcabf301b44fff9e2c4533317346f6727480e129ed4622560e091cfe41585a43aaf88c78f4b02e6c981e5ab38532022d8c6853beb2901eb70bbb258f4782b1bf8f4ac4ea3c2df5c6.jpg)

**Comment by koay9f** [comment]
I'm not having any problems getting it to update right now, although I may have encountered it before.  

The problem with the fluid power is that the calculators do not seem to have unit conversions hooked up.  
Bare minimum: we need unit conversions hooked up for System Curve (b/c the calc's required that values go into the C++ with certain units) (in Pump System Curve, Fan System Curve,  Pump Curve & Fan Curve).  

Check that the head tool has units hooked up (I think it does)
Specific Speed and Pump Efficiency Curve probably needs them.

Pump/Fan Curve probably shouldn't outside of the parts that are actually system curve.

Like the head tool, I hope that Fan Analysis has them...

**Comment by koay9f** [comment]
Just check pump system curve.  Looks like imperial calculates right but it is not doing so for custom units (as set in Pump settings).
