### ISSUE TITLE
Electricity Reduction TH Calculator

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#2703]

**Comment by vanced** [comment]
[Electricity TH help and math.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cd989f209691a08ce0ab5ae469d8d421432b636905ad2f3088e23cb70037431f1d11f6140b1b56f6eb8c22f2e36e21880802ea803b0d26c63d14abee831aec53bc32975dc7e7e2de139db17770a599855d3f190f198cfb553ca59e4dcd51f04ae15f18.docx)

**Comment by koay9f** [comment]
UI Mockup to come soon

**Comment by koay9f** [comment]
weeks/year
days/week
shifts/day
hours/shift
--> hours/year
