### ISSUE TITLE
SSMT Diagram - Help Text

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2707]

**Comment by vanced** [comment]
[SSMT Diagram Help Text.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46dba7b717c2a7a08eeead42a91dd891255667472c1cb7693cc7f33ab0487e021b4d44be44510b11aea88b7fafb16d26d80e0bedd46a0975c36e43aaaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4a3f1a03108ef95437a29a5985.docx)
