### ISSUE TITLE
Where to put the treasure hunt calcs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2712]
Some can go in existing folders:
Air Leak --> Compressed Air
CA reduce system P --> Compressed Air
CA - Treasure Hunt --> Compressed Air
Electricity - Treasure Hunt --> Motors?
Electricity - Lighting -->  Lighting
Insulation --> Process Heating or Steam?
NG - Treasure Hunt -->  PH or Steam?
Steam - Treasure Hunt -->  Steam
Water/WW - Treasure Hunt --> ??

Or could turn Lighting into a treasure hunt folder...
Air Leak --> Compressed Air
CA reduce system P --> Compressed Air
CA - Treasure Hunt --> Treasure Hunt 
Electricity - Treasure Hunt --> Treasure Hunt 
Electricity - Lighting -->  Treasure Hunt 
Insulation --> Process Heating or Steam?
NG - Treasure Hunt -->  Treasure Hunt 
Steam - Treasure Hunt -->  Treasure Hunt 
Water/WW - Treasure Hunt --> Treasure Hunt 

some would still be better off in other folders (air leaks, reduce system P, insulation, replace/rewind, replace motors) and they could get a little treasure hunt additional icon...?

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/52139997-9a88a980-261f-11e9-84a2-57881997e60b.png)

**Comment by rmroot** [comment]
I think having the treasure hunt assessment makes this issue unnecessary
