### ISSUE TITLE
Potential System Curve Bug

### ISSUE THREAD

**Issue by DmitryHoward** [ORNL-AMO/AMO-Tools-Desktop#2726]
As of right now, values stored in a saved stand alone system curve calculator are persisted even after changing settings to utilize different units. For example, if 2000 gpm is set for the Flow Rate of Point 1 in system curve, then the user goes to change their units so that pump flow rate is now done with m^3/h, the next time they go to system curve, the Flow Rate for Point 1 will still be 2000 m^3/h which =/= 2000 gpm. This does not affect calculators saved to individual assessments. Is this something we would want to fix? Are there significant use cases justifying a fix?

**Comment by koay9f** [comment]
I'm going to leave this open, but put it in the backlog and remove the bug tag.  I think for now it is fine, but we may want to fix it globally, at some point.
