### ISSUE TITLE
SSMT - Result Panels

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2738]

**Comment by rmroot** [comment]
Functionality for results panel has been added. Need what results we actually want to display.. currently displaying this:
![Screen Shot 2019-02-07 at 12.39.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216454f46b7191a379ed0c2858415d4fbc21254d58eeb9cb74fce36f34985619e8d8390a26973f45a5bfd349ed53ba208e48d3b7b9d91ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe84853a0143e6be175366e0a.png)

**Comment by koay9f** [comment]
Maybe get rid of the Unit Costs for now?
Everything else is pretty good and I can't think of anything to add

**Comment by rmroot** [comment]
![image (17).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46e1999b2487c3e1debef601e81fe086264c22703d46f96925dce72dbd43290556581ffa130a5f44f9fedf2aa3e56e76984019af80330b2b9b645bf9fa9015ad00bc2a8a4a81bfb58b4fc8ec3426e48e9d02.png)
