### ISSUE TITLE
Calculators Units are gone - PHAST Custom Units

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2747]
I started this thinking it was just in the PH calcs, but it is everywhere.  Pulled develop at about 3:45ish 2/8/2019

Units are missing.  Also check results
![image](https://user-images.githubusercontent.com/25389736/52505839-c923f880-2bba-11e9-96c2-ecb324040be6.png)
![image](https://user-images.githubusercontent.com/25389736/52505917-f8d30080-2bba-11e9-855b-c91cf11f17f1.png)
![image](https://user-images.githubusercontent.com/25389736/52505945-0b4d3a00-2bbb-11e9-95a9-0247d52ed0cd.png)
![image](https://user-images.githubusercontent.com/25389736/52505975-228c2780-2bbb-11e9-8d12-4fabc6bf3163.png)

**Comment by koay9f** [comment]
Some calcs are fine. seems to be temp, length, energy.

in compressed air, pressure and flows seems to be okay

**Comment by rmroot** [comment]
Somehow your units for this PHAST got set to custom and not metric/imperial

**Comment by koay9f** [comment]
Well, my pump units are set at custom...  we shall have to think about this

**Comment by koay9f** [comment]
Need to either make custom list for PHAST units or come up with a work around so PHAST still has units if General = Custom

**Comment by rmroot** [comment]
Duplicate for #2748 ?
