### ISSUE TITLE
SSMT - Small fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2775]
Wait until at least 2/20 to start this.  I will try to add more to this issue rather than making new issues

* Report Losses Table has "Medium to Low Turnine Efficiency Loss" instead of "Medium to Low Turbine Efficiency Loss"

* Report Losses Table:under: *Condensate* change "Condensate Loss" to "Condensate Heat Loss"

* Report Losses Table: change "Process Losses" to "Non-recovered Process Condensate"

**Comment by koay9f** [comment]
Hover table in diagram - can it move when user scrolls.  Small screen (my laptop) becomes problematic, I lose the table

**Comment by koay9f** [comment]
Entropy should have 3 decimals (sorry)

**Comment by rmroot** [comment]
Make seperate issue for hover table

**Comment by rmroot** [comment]
Cold outlet arrow for heat exchanger has wrong values in the hover table

**Comment by rmroot** [comment]
"tonne" => "t"

**Comment by koay9f** [comment]
** Medium to low turbine Efficiency loss is now missing from the table **

other name changes look good
entropy looks good
heat exchanger looks good
tonne --> t looks good

**Comment by koay9f** [comment]
turbine had no steam flowing though it.  it is fine.
