### ISSUE TITLE
Modify All - dynamic badges

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2799]
![image](https://user-images.githubusercontent.com/25389736/53364220-56ca4c80-390c-11e9-862a-45b1413a7552.png)
No difference in the form, but the circle is still blue...
Mod was originally made in Novice View.  did have a change, then removed it...

**Comment by rmroot** [comment]
Verify still an issue after 2796 is merged in

**Comment by koay9f** [comment]
Was good until I made a change in headers (turned blue) then removed the change (stayed blue)
