### ISSUE TITLE
Water TH Calculator

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#2821]

**Comment by vanced** [comment]
![Water TH Figure.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46df958e2690c39da7a9994aa348e2916b0a65633b0ba92e7391a172fd1722050a0d1fae15515815aaabdb2ba6b33b268b5958bfd77f4366846c4ff8e7df46f554f832815d84beb68b49c5e93923e18b8b4e3917020ac4.png)
[Water TH help and math Final.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46df958e2690c39da7a9b746a84db0952742677e2810ab6b568ced29b30037431f1d11f6140b1b56f6eb8c22f2e36e21880802ea803b0d26c63d14abee831aec53bc32975dc7e7e2de139db17770a599855d3f160f198cfa5c31a69f4bcc50ff4fe45f18.docx)

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/733766c2-1962-4634-9497-d6f570c3b5f3/download](https://app.zenhub.com/files/80439269/733766c2-1962-4634-9497-d6f570c3b5f3/download)

**Comment by koay9f** [comment]
Add dropdown to identify if the calculator is for water or wastewater

**Comment by rmroot** [comment]
Will need local suite (develop) installation

**Comment by koay9f** [comment]
Added this to integration as well

Add new equipment adds new op hours block not new equipment block
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6d407fd0-9473-4c9c-997c-547c596d6337)

**Comment by DmitryHoward** [comment]
Could not reproduce the problem. Seems to work just fine on my end.

**Comment by DmitryHoward** [comment]
Works correctly only with local install of the suite. Need to make a local build in order to test.
