### ISSUE TITLE
Compressed Air Reduction TH Calculator

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#2822]

**Comment by vanced** [comment]
[Compressed Air TH help and math Final.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cb9b97339086ba9cecbb038554e2d41d6e677b2c08b36b718be768b2436f094f2917f210044d58eeb9cb74fce36f34985619e8d8390a26973f45a5bfd349ed53ba208e48d3b7b9d91ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee04953a2103e6ae37e346e0a.docx)
![Compressed Air Reduction TH Figure.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cb9b97339086ba9cecbb038554e2d41b4323662a10aa247ec5d700ff6472061a1d1bbe5d4a1f06a3a3dc78e2a436628f555fb8833c5d20cf3a40faead01fbf04bd768a4ad6e4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd59f24de74e5ca2113062f43b.png)

**Comment by koay9f** [comment]
weeks/year
days/week
shifts/day
hours/shift
--> hours/year

**Comment by koay9f** [comment]
UI Update.  New field "Utility Type" will determine if the electricity section shows up, utility cost units, and what utility the opp sheet will be

![image](https://user-images.githubusercontent.com/25389736/57151091-1240ae80-6d9e-11e9-90f7-7dd29958a4b1.png)

**Comment by koay9f** [comment]
For orifice method, have the "Nozzle Flow Rate" result shown before "Number of Nozzle" input

**Comment by koay9f** [comment]
**Left side: Inputs**
*Utility Type Dropdown*
* Change "None" to "Compressed Air"
* Should be locked for whole calculator.  (only choose once)

*Need cost fields.  either...*
1 - one that's name changes and what is multiplies to changes (if utility = compressed air, then it is compressed air cost and annual cost = unit cost * consumption; if utility = electricity, then it is electricity cost and annual cost = unit cost * energy use)
2 - two where one hides if not in use, and they are multiplied by the correct consumption (if utility = compressed air, then compressed air cost shows and annual cost = CA cost * consumption; if utility = electricity, then electricity cost shows and annual cost = CA cost * energy use)

Show final Air flow result in the left side in card, above break for electricity (example: Flow Meter result = meter reading x # units) for all but offsheet method

Keep number of units (and the final air flow result) above electricity section

Bag flow method: dimensions of bag should be in inches or cm (not ft...)

Tried to enter data in metric.  No results.
Orifice / Pressure - no unit label for Supply Pressure in metric(if not in document, use barg)

**Right side results:**
Can we hide energy use and energy savings if utility type =/= electricity

*Flow Method*
no flow rate showing (0 scfm)
Consumption: looks like it needs a /1000 to go from SCF to kSCF
Energy Use: Looks correct, so be careful when changing consumption
Energy Cost: looks good

*Bag Method, Orifice*
flow rate shows 
Consumption: looks like it needs a /1000 to go from SCF to kSCF

*Offsheet *
Is good

*If utility type == Electricity*
The default compressor type == Reciprocating and it is showing a specific Power of 0.21 kW/SCFM.  this is not correct.  If you "wiggle" it, it becomes the correct number, so the table is correct, just displaying the wrong number initially

**Comment by rmroot** [comment]
Didn't catch this earlier but..

You are using [disabled] tag in the html for the Utility Type. For reactive forms we want to disable form using their controls. So in this case we would have form.controls.utilityType.disable() when necessary. 

You can also disable the controls when creating the form if that is the only time it will change.

**Comment by koay9f** [comment]
Orifice / Pressure method still doesn't have labels for 'supply pressure' (psig for imperial and barg for metric)
Orifice / Pressure method needs a unit conversion for the `nozzle flow rate` result
