### ISSUE TITLE
Compressed Air Reduce Pressure TH Calculator

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#2823]

**Comment by vanced** [comment]
![Compressed Air Reduce Pressure TH Figure.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cb9b97339086ba9cecbb038554e2d41b4323662a01e31b6280f03baa507e413b275eda180f1a06a9eb9539e6f4632adf0f4fffdb7f5a7d926843fdbad616b850ec72d94f85b3bbdc4dc5bb6f23f5979d0d6f405147d4a61760e28b41da59fe41e04850a5173065e27e30744f940c38.png)
[CA Reduce Pressure TH help and math Final.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b18368716b0dc00135e3482/125516c66e82c728ace21e0d46cbb5da118787bc8cecff73b658e3873c5422331d2ce3237589f368be4c7f41020e0af4512e061aada59b37b4f67e2fd00958a9c3674d71cf6944fee9804bb606eb76d91d85b6b98d1ac1ed6e77e199935d7c4f5b4cd6a2047ff5db59c24af743eb4c50a1123265e073347846921b6761.docx)

**Comment by koay9f** [comment]
weeks/year
days/week
shifts/day
hours/shift
--> hours/year

**Comment by koay9f** [comment]
FYI: the oppSheet for this will ALWAYS be electricity

**Comment by koay9f** [comment]
again, just op hours not the break down
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9ddd64d2-e9e0-49e8-8448-bdb20d5311d5)
