### ISSUE TITLE
Steam Help Text Changes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2827]
* change "the model" to "your system" (Boiler - Is.. Flashed? and Boiler - Preheat... and Header - Flash Condensate Into Header) {also fix verbs as appropriate}
* Boiler- Steam Temperature: "... saturation temperature of the highest pressure header."
* Header- Heat Loss: Estimate of Heat lost in header piping before use in turbines and process
* Header- Desuperheat ... : Select YES if your system uses feedwater to desuperheat steam in pressure reducing values
* Turbine - Isentropic Efficiency - HOW TO DETERMINE?
*

*

**Comment by Aeledbetter** [comment]
Just need to know what goes under Turbine - Isentropic Efficiency, everything else is done.

**Comment by koay9f** [comment]
Add to the end of existing help text for... 

Boiler Combustion Efficiency - The "Stack Loss" calculator can be used to help determine your boilers efficiency.

Isentropic Efficiency - This can be found in your manufacturer specifications.  Single wheel turbines may be as low as 20% and larger, more complex turbines 65% or higher.

Turbine Type	Exhaust Type	Average (%)
Single Stage	Back Pressure	53
Single Stage	Condensing	57
Multi-Stage <10 MW	Back Pressure	60
Multi-Stage <10 MW	Condensing	67
Multi-Stage > 10 MW	Back Pressure	75
Multi-Stage > 10 MW	Condensing	80

source: https://www.elliott-turbo.com/TurbineCalculator

Replace this help text 
Generator Efficiency - The ratio of net power generated to total fuel input to the cycle (the conversion efficiency to electricity).  This can be found in your manufacturer specifications.  Typically around 95%.
