### ISSUE TITLE
Diagram visual tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2829]
Whatever we can work in...

Higher Priority
* Flash Tank's label is off center 
* if not done already, change "tonne" to "t"

Brainstorming/Low priority
* move blowdown flash tank up a bit?
* move red pipe a little further away from boiler?
* Really big numbers end up with two lines.  Reduce font? increase box size?
* can it be dynamically sized a bit?  if wider screen res, stretch out horizontally a bit?
* maybe have the condensate flash tank's grey output pipe go right?

**Comment by rmroot** [comment]
The brainstorming/low priority are all fairly high effort. I'll try to get to them but are most likely v2 updates.
