### ISSUE TITLE
SSMT Print Report Tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2869]
Need to go over report and iron some things out
d
* Input Data - Turbines "Operation Value 1" and 2 can we get those to show what was used (mass flow or power generation)

* waterfall with mods looks weird.  maybe two waterfalls on one page per mod?

**Comment by rmroot** [comment]
Operation Value 1/2: How do you want it labeled if baseline is Mass Flow and modification is Power Generation?

**Comment by koay9f** [comment]
Bother.

A- If all would be same (both Flow, flow range or balance header OR both power, power range or balance header) --> Mass flow or Power Generation (as applicable)
B - come up with something better than `Operation Value`  maybe just Flow/Power
