### ISSUE TITLE
SSMT 2.0 Diagram visual tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2871]
Brainstorming/Low priority

* move blowdown flash tank up a bit?
* move red pipe a little further away from boiler?
* Really big numbers end up with two lines. 
* Reduce font? increase box size?
can it be dynamically sized a bit? if wider screen res, stretch out horizontally a bit?
* maybe have the condensate flash tank's grey output pipe go right?

**Comment by rmroot** [comment]
Verify first two bullets haven't already been done..

**Comment by koay9f** [comment]
As of 5/20/2019 - 
red pipe still needs to be moved down a bit, but that is now its own separate issue, though that issue (and the one regarding two lines looks like it resolves itself if you wiggle the zoom in and out, so maybe just something to handle the first render?)

blowdown flash looks okay

*Condensate flash pipe should still "exit" to the right*

**Comment by nbintertech** [comment]
Please investigate if there is anything more to do here
