### ISSUE TITLE
PHAST - Default Explore opps help text

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2887]
No default explore opportunities help text is showing up in phast.

I don't believe there is any in yet.

**Comment by koay9f** [comment]
Use the same as Pumps
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/00dd54ab-99b6-4c68-914b-e7178df866f0)

**Comment by koay9f** [comment]
Also "Notes" are missing.

Neither are missing for `Modify all Conditions`
