### ISSUE TITLE
Default 3 Header-Metric Annual savings is -$01

### ISSUE THREAD

**Issue by Aeledbetter** [ORNL-AMO/AMO-Tools-Desktop#2894]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34ea820a0bbc0011c49a92/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2f7587e27abb1b2c00090d1cac415d5812fdfcda79a0a42062c80d55b98e30063e937f03a6aa8317b500bf25894982b3bc8e4ac2eb3f37aa.PNG)

**Comment by koay9f** [comment]
I'm not seeing this.
