### ISSUE TITLE
Export embedded calcs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2910]
When exporting an assessment, have the calculator files go with it (pump/fan/system curves, fan analysis, see if others are important...)

**Comment by rmroot** [comment]
This should be happening.. going to tag as bug.

**Comment by rmroot** [comment]
Analysis of calculators:
Found some bugs, Pump/Fan Curves aren't working properly. Some other calcs are not working properly. 

[https://app.zenhub.com/files/80439269/7d688e36-afde-4e06-92d9-ecfc2ec2630a/download](https://app.zenhub.com/files/80439269/7d688e36-afde-4e06-92d9-ecfc2ec2630a/download)

**Comment by rmroot** [comment]
Fixed all calculators except Pump/Fan curves.
