### ISSUE TITLE
Fans - density unit

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2913]
Don't think "standard" cubic feet is proper.  it may just be lb/ft3

**Comment by koay9f** [comment]
In  Fans: Air density unit should be lb/ft3

**Comment by rmroot** [comment]
Currently the unit converter just has `lb/scf`, do we want to just change the display for this to `lb/ft3` or do we need to add an additional unit for `lb/ft3`?

**Comment by koay9f** [comment]
just change it to lb/ft3, do not need an additional unit
