### ISSUE TITLE
System Curve field help text

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2928]
Field by field help text for System curve
[system curve help.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/3108803/system.curve.help.docx)

**Comment by rmroot** [comment]
I believe this help text doc is from an older version of the system curve.. 

It only has field by field for Pumps and not Fans.

**Comment by koay9f** [comment]
Text for fans

Compressibility Factor
The compressibility factor is the measure of how non-ideal the gas is. For most gases this is usually around 1.

System Loss Exponent
The system loss exponent, or system friction loss exponent, is that to which the flow rate is raised in developing friction loss estimates.  The Darcy-Weisbach equation, indicates a value of 2.  Experiment with values between 1.8 and 2.0 to see how the system curve changes.

For the pressures.  use the text for `Head` but change `Head` to `Pressure`
Flow should be good
