### ISSUE TITLE
Turn replace/rewind into TH

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2936]
BL:
Op Hours, Motor Size, Load, Electricity Cost

Mod:
Rewound Motor & New Motor.
Show both then have button/dropdown to choose for larger analysis.

Math:
BL Energy use: 
`0.746 * inputs.motorSize * (inputs.load / 100) * inputs.operatingHours * (100 / (inputs.currentEfficiency ))`

Mod Energy use:
chosenEfficiency = either `inputs.rewindEfficiencyLoss` or `inputs.newEfficiency`
`0.746 * inputs.motorSize * (inputs.load / 100) * inputs.operatingHours * (100 / (chosenEfficiency ))`

Costs = energy use * inputs.electricityCost
Savings = BL - Mod

Results - have both existing table (so users can easily choose between replace and rewind) and table to compare "chosen" to BL (which is what gets sent to the TH rollup)

**Comment by rmroot** [comment]
Combine "Replace Existing" and "Replace Rewind" into one calculator
