### ISSUE TITLE
Fan Analysis Needs Work

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2937]
Notes from Tom:

Input Plane Data
* Have the "Add Differential Pressure Readings" not be a separate page, just put the table below "Input Velocity Pressure Traverse Data"
* Name the ^ section "Pitot Tube Traverse Readings"
* Show result for Pv3 (label = "Calculated Velocity Pressure")
* any ways to make that data entry easier?
-             - copy/paste from Excel?
-              - buttons to "duplicate across row" or column
* Make it so don't have to finish "Fan Shaft Power" to get some results.  Make it like how do we do it in Fan Assessment for "Calculate Pressures and Flow Rate", can get "Plane Data Table" as soon as plane 5 data entry is complete.
* Next button for moving between planes
* BIG ASK - when on a plane, have something highlighting the diagram showing where you are.  Would this require pictures for each plane?  Could we color code the planes on the pic and have the navigation buttons match?

Fan Shaft Power
* BUG: Estimate Full Load Amps doesn't Work
* remove the `(Hi)` from `Motor Input Power (Hi)` (both the result and the entry field)
![image](https://user-images.githubusercontent.com/25389736/56676897-4543bd80-668d-11e9-97a6-d806d62d4d85.png)

Overall
* Navigation is difficult - Instead of having to "Return to Setup" could we also have "Next"
* Move Reset Data to the left side
* BUG: Results do not show up.  I think this is a problem with "Establish Base Gas Density".  It will work if you toggle "Method to Establish Gas Density"
Errors:
![image](https://user-images.githubusercontent.com/25389736/56676677-d7979180-668c-11e9-807d-ad1af8566d32.png)

**Comment by koay9f** [comment]
Re: Navigation - in addition to "next" maybe have similar layout to assessments w/ 1, 2, 3, 4, Results, in a top bar?

No results for Basic Fan Info, Establish Gas Density
Once `Make it so don't have to finish "Fan Shaft Power" to get some results` goes through, Input Plane Data should have results

Have Next for navigation in `Input Plane Data`

**Comment by koay9f** [comment]
The overall change in navigation is much better.  A few things missing/updated from original issue text.


[3] Plane Data
* Instead of "Name the ^ section "Pitot Tube Traverse Readings"" maybe change name [3] Plane Data to [3] Traverse Data    (its a lot shorter)
* And the header at the top, change from "INPUT PLANE DATA" to "Pitot Tube Traverse Readings"
* Change label for "Pv3" to "Traverse Velocity Pressure"
* ^ make this bold and put it and the result below it (Points Satisfying...) at the bottom, below the input table.
* Anything better  for the `Input Pitot Tube Differential Pressure Readings` Data entry?

[4] Fan Shaft Power
* BUG: Estimate Full Load Amps doesn't Work
* remove the `(Hi)` from `Motor Input Power (Hi)` (both the result and the entry field)

Overall
* Bring back reset button.  It should probably reset whole calculator.  There will also be a generate example button
* I couldn't test the bug relating to Gas Density, just watch for it and test it again when bring into develop
* Maybe remove the results tab for Fan Basics & Gas Density.  Since the Diagram now has the Plane Data Table (which I really like), maybe remove results tab from Plane Data as well... 

Note when testing: There will be zeros in the Plane 3 results velocity & total pressure columns unless you are running a local suite build.  I have checked it locally (2019-07-02), and they do work now.

**Comment by koay9f** [comment]
2019 - 07 -22 review
Generally looks better

Still want an easier way to enter data into traverse table :/  if this proves to be too difficult, can move it to a separate backlog issue

On traverse planes (3a, 3b, 3c?), fields/results relating to the traverse data (Traverse Velocity Pressure, tube type, coefficient, number of holes & insertion points, size of the table) do not update when you edit data in any of the related fields.

Estimate Full load amps not working (field turns green, but no number appears)
Full load amps should probably have the same validation it does in psat/fsat

Highlighting when on [i] shows wrong "plane" (highlights the last plane that was open)

Gas density bug *seems* to be fixed

Unless start from "generate example" calculator does not generate results starting at plane data

Slacked a simpler example

**Comment by rmroot** [comment]
Created seperate issues for incorporating updates into Fan assessment and improving traverse table data entry
