### ISSUE TITLE
TH calculator visual tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2948]
* make the difference between BL & Mod more clear - one be kind of grey-ish
* if multiple "equipment", put in "hover" boxes or something else to make them match up better
* if multiple..., be able to edit name {electricity, NG & lighting}
* if multiple ..., more space between each one

TEXT
NG - Flow Meter Method "Flow Rate" --> Fuel Flow Rate (both field label and in help text)
Both - "Units" --> "# of Units"
Both - "Units" help text --> make sure "units" is plural

DECIMAL POINTS
Electricity - Power (kW) --> 1 decimal point
Electricity - Energy (kWh) --> 0 decimal points
NG - waiting for feedback, maybe 2 for now

**Comment by DmitryHoward** [comment]
added more space between each;
added hovering card effect for each equipment;
fixed "Units" in help text;

**Comment by koay9f** [comment]
I think it looks GREAT!

FIELD TITLE for "Units" needs to be changed to "# of Units"
Electricity Power decimal places looks good.
Electricity Energy decimal places should be zero (left and right sides)

NG - Flow Meter Method "Flow Rate" --> Fuel Flow Rate (both field label and in help text)
