### ISSUE TITLE
Operating Hours

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2949]
Through out the tool, in various places (PSAT, FSAT, TH), we have a single line for operating hours.  
Can we make a modal like the head tool to calculate this?

For some (compressed air) could we include
seconds / minute
minutes / hour

**Comment by koay9f** [comment]
* put this everywhere there is an operating hours / year
* get rid of shifts/ day, hours/shift and just do hours/day

**Comment by rmroot** [comment]
## Needed in:
### Motors:
[] Replace and Rewind
### Furnaces
[] 02 Enrichment
[] Flow and energy used
### Compressed Air
[] System Capacity
[] Leak loss estimator - bag method
### Lighting
[] Lighting Replacement
### General
[] Combined Heat and Power
[] Electricity Reduction
[] Natural gas reduction
[] Compressed air reduction
[] Water reduction
### Assessments
[] PSAT - Field data
[] FSAT - Field data
[] SSMT - Operations
[] PHAST - Operations
[] THunt - In own tab, may want to move??
