### ISSUE TITLE
Find Treasure Error

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2950]
If go directly to Find Treasure without clicking on "Operating Hours" will just get a grey screen instead of the calculator list
Error pops up wanting "hoursPerYear"

Grey out "Find Treasure" and "Treasure Chest" ?

Next buttons in Facility Basics will help, but not prevent.

**Comment by rmroot** [comment]
Verify this may be fixed with navigation buttons for setup added
