### ISSUE TITLE
TH - Electricity Reduction Incorporation

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2952]
Incorporate Electricity Reduction into TH assessment

**Comment by koay9f** [comment]
A few weird things

* the gauge in the Treasure Chest LIST says "Fuel Cost Savings", should be "Electricity Cost Savings " for these

* This gauge's math is also REALLY wrong (way too high % savings)

* when using "Name Plate Data" Method, I think the tool is automatically unit converting the `Rated Motor Power` field or something b/c it keeps changing every time it recalcs the savings  (other methods seem to be fine)

looks like it is properly showing "Electricity Savings" on the side gauge
