### ISSUE TITLE
TH - Comp Air Reduction Incorportation

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2954]
Incorporate Comp Air Reduction into TH.

**Comment by rmroot** [comment]
requires #2822

**Comment by koay9f** [comment]
FYI: there is a field in the calc (Utility Type) that determines if the Opp Sheet is  "Compressed Air" or "Electricity"

**Comment by koay9f** [comment]
Icon
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/36254811-a21c-4f9f-8847-67242c0f3c1c)

**Comment by koay9f** [comment]
In table gauge for CA reduction (if `utility type` = electricity) should be Electricity Cost Savings (on the right, it is already part of electricity, which is good)

**Comment by koay9f** [comment]
CA in report:
looks like it works when it is an electricity savings, but not if it is a compressed air savings.

The CA opportunity is not in 
Executive Summary>Cost Summary
Executive Summary>Detailed Summary
There are no "utility savings" (it does have the cost savings) in Opportunity Summary 
I can't tell if it is reflected in the graphs...

**Comment by rmroot** [comment]
I believe this is a suite issue. Investigating...
