### ISSUE TITLE
TH - Steam calculator incorporation

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2956]
Incorporate steam TH calculator into TH assessment

**Comment by rmroot** [comment]
requires #2820

**Comment by koay9f** [comment]
FYI: there is a field "Fuel Type" that determines if the OppSheet for this calculator uses "Natural Gas", "Other Fuel" or "Steam"

**Comment by koay9f** [comment]
Icon
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0856264c-0e95-4e2f-937a-92b1d7b4fc72)
