### ISSUE TITLE
Google translate demo build

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#2966]
Create demo build with google translate hooked up. Should include treasure hunt.

**Comment by koay9f** [comment]
* make sure it has a special version number
* add note in feedback section or SOMEWHERE that says it is the international version and if you have questions, please specify that

**Comment by rmroot** [comment]
Initial branch created and hooked up: `th-google-translate`

**Comment by koay9f** [comment]
Make a windows build of v0.4.0-beta with special version number and the "international" note.
Send to Tom
