### ISSUE TITLE
Standalone Opp Sheet + Multiple Utilities

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2981]
When a standalone opportunity has multiple utilities with it

For Treasure Hunt Sorting:
put under all categories and, if possible make a notation in the number
Electricity (5*)

For Gauge graph in table:
can we fit multiple tiny ones in there?  At least if the two are Electricity and NG?

For Big Results gauge:
cost is cost
For small results gauges:
kind of treat like multiple opportunities, electriicty savings goes under electricity, ng under ng...

Report Exe table:
Like the smaller result gauges, separate out the savings and put in the correct lines

Report Opportunity Summary
Utility = "Other"
no "energy Savings"

**Comment by rmroot** [comment]
Treasure Chest "Other Fuel" should be "Other Utility" and include anything that is not Electricity or NG (compressed air, water, etc.)

**Comment by rmroot** [comment]
Created #3002 for multiple gauges in treasure chest

**Comment by koay9f** [comment]
In Opportunity Summary for the mixed opportunities
Have multiple rows for the opportunity
