### ISSUE TITLE
TH Small tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2982]
Where you have "Energy Savings" in the report or "Energy Type" and "Energy Use" in the opps sheet, have "Utility Savings", "Utility Type" and "Utility Use"

Treasure Chest "Other Fuel" should be "Other Utility" and include anything that is not Electricity or NG (compressed air, water, etc.)

"Energy Usage and Cost" --> add for steam, compressed air, water, wastewater, (and any I missed)

FYI: "Other Fuel" will be used for steam (will need fuel type dropdown added to calc) and stand alone opportunity sheets

**Comment by koay9f** [comment]
Default Units of Measure = Imperial

**Comment by rmroot** [comment]
Treasure Chest "Other Fuel" should be "Other Utility" and include anything that is not Electricity or NG (compressed air, water, etc.)  -- Added to issue 2981 (label was updated but math was not)
