### ISSUE TITLE
TH- Comp Air Leak Survey

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#2983]
Where is the Comp Air Leak Calc?

**Comment by koay9f** [comment]
Goal - Name a leak, figure out how much air loss (and electricity wasted). save it to a table so you can look at all your leaks at once.  have check box for which ones are going to be fixed (i.e. - included in results).  

The question is, how do we handle the user input for calculating the leak loss without having a huge clunky table, or something that looks like the leak loss -bag method calc we already have...

2 potential UI looks:

1 - utilizing a modal for the calculation of flow rate & energy use
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bfdf3fe0-0cb3-49e2-b7e1-68ae50a71250)
Don't like this one as much.  seems a bit clunky

2 - more like how the steam properties calculator works
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6141204f-6d4e-4b46-b015-d5eaa8984e51)
Enter the data for a leak at the top (fields depend on measurement method), and once "Add Leak to Table" is clicked the results go into the table below for easy viewing.

Both have the problem of "will we be able to retrieve the leak data later?"  Is there some way that it can be saved, but "hidden" and have another button that brings it back to the top (for method B)?

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/308ed0e7-658e-475c-b400-5fffac104845/download](https://app.zenhub.com/files/80439269/308ed0e7-658e-475c-b400-5fffac104845/download)
