### ISSUE TITLE
TH - Add report to rollup

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3002]

**Comment by rmroot** [comment]
Making a size 13, then will break down into different issue as I go. 

Report Graphs, Summary, etc..

**Comment by koay9f** [comment]
For next release:
Add TH reports to list
- "default" page being the Opportunity Summary
- Opportunities in Rows, only the ones selected in the Treasure Chest Screen
- Add "column" that is an automatically selected checkbox for inclusion in the roll up
Add a card "Coming Soon"
- could you go on and sum up all the "cost savings" (no annual cost or any energy) (extra not necessary for completing the issue, just tell me if you do it so I know to look for it)

**Comment by rmroot** [comment]
Included Thunt reports in rollup.

Selecting opportunities and calculations based on selections for summary card at top added.

Adding new card for report rollup graphs.
