### ISSUE TITLE
TH - Dashboard card

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3003]
Finish dashboard card with results and actions for treasure hunt assessments

**Comment by koay9f** [comment]
Info for the card:
Baseline Data:
Annual Utility Costs
Opportunity Data:
Number of Opportunities (only selected)
Cost Savings (only selected)

**Comment by koay9f** [comment]
Do you think it would be too much (in the card) if we added
BL
Electricity Consumption
Natural Gas Consumption
Opps:
Electricity Savings
Natural Gas Savings
??  
If you think that would be too crowded, then ignore this.

**Comment by rmroot** [comment]
Added individual utility summaries, can be removed easily.
