### ISSUE TITLE
TH - Icons needed

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3004]
Need icons for treasure hunt assessment

Need icons for new calculators

Need icons for treasure chests

**Comment by koay9f** [comment]
Electricity Calculator
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b6bded35-ae6d-41e5-a749-255fed603509)

Natural Gas Calculator
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d0355d4d-988c-442c-843b-53bce3824b1d)

**Comment by koay9f** [comment]
Treasure Hunt
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/306a192f-98dc-4d0f-b362-cae3e8a29f48)

**Comment by koay9f** [comment]
Compressed Air Reduction
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/71666e70-fd61-418e-b912-2ab343705f87)

Steam
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a3336bae-3838-46bb-a5b4-809d620113b3)

I'll put these also with their respective issues

**Comment by rmroot** [comment]
Treasure hunt, compressed air, ng reduction and electricity reduction icons added. Waiting on additional icons before PR

**Comment by koay9f** [comment]
Lighting
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bcab7d30-d26b-4d76-b55d-faa32ced3642)

Opp Sheet ... coming soon

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d0cefce1-907b-4d23-82a6-8b42b7373d40)

**Comment by rmroot** [comment]
Need to add icons in for Motor Drive and Replace existing
