### ISSUE TITLE
TH Tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3005]
Overall Tom seems to really like it.

*Bug type tweaks*
If unit system = imperial, water & waste water annual consumption unit is L/yr.  should be kgal/yr

*Enhancement type tweaks*
Executive Summary
Move Cost Summary table to left
next to it, make a graph like this
![image](https://user-images.githubusercontent.com/25389736/57540537-efbd1100-731a-11e9-88f7-11066229cbbe.png)

Keep order and names of utility constant through out assessment
Electricity
Natural Gas
Other Fuel
Water
Wastewater
Steam
Compressed Air

*Quick Fix tweaks*
Change Name of "Motor Drive" to "Upgrade Motor Drive"

Add to Energy Usage and Cost's help text
"...   Compressed air and steam fields are only to be used if the facility receives compressed air or steam as a utility.  If they are generated at the facility, then they should be considered part of other utilities (electricity or fuel)."

**Comment by koay9f** [comment]
The unit costs for CA & Steam should be $/SCF (imperial; $/m3 metric) and $/MMBTU (imperial; $/GJ metric)

**Comment by DmitryHoward** [comment]
The reordering of the unit cost for all the different utilities is outside of the scope of this issue. They utilities are split between two components, one of which is used widely for every assessment type and one that is treasure hunt specific. The refactor to fix this will need its own issue.

**Comment by rmroot** [comment]
The graph component is not setup to handle "Mixed" summaries. 

These are opportunities with more then one utility.

**Comment by koay9f** [comment]
X-axis label for compressed air can get cut off
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/706cbe48-a3fa-4cab-b892-dfd7c0f79713)

Change Name of "Motor Drive" calculator to "Upgrade Motor Drive"

The unit costs for CA & Steam should be $/SCF (imperial; $/m3 metric) and EDIT: $/klb (imperial; $/tonne metric)

**Comment by koay9f** [comment]
For CA annual costs - metric & imperial are switched and the 3 in m3 should be superscript
