### ISSUE TITLE
Tweaks to Efficiency Improvement Calc for TH

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3007]
This was originally: Further Tweaks to O2 Enrichment for use in TH.  Would be simpler to start with "Efficiency Improvement Calculator".  Skip to lower comment...

Note: just for moving it to treasure hunt.  should stay the same for the standalone

1 - hid O2 in combustion air and set the mod value to 21

2 - rename columns to Baseline & Modification

3 - Title: Reduce O2 in flue gas

4 - there will need to be help text and description tweaks that I will add later

**Comment by koay9f** [comment]
Might be better to do this from the Efficiency Improvement Calculator...

**Comment by koay9f** [comment]
For change and original - extra space between O and 2

**Comment by koay9f** [comment]
1 - make look like a TH calculator (baseline & mod)
1a - think about the results / bottom area with Energy Input.  should be able to improve looks
2 - Add Operating Hours and Fuel Costs

Would NOT need separate calc's for standalone and TH.
Would NOT really need help and other tweaks

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3972812a-1199-48c2-9350-0adf580acf32)

**Comment by nbintertech** [comment]
We need to:
- Add operating hours and fuel cost fields
- Re style/layout form side so it mimicks our other calculator baseline panel vs mod panel setup
- Add a third panel called 'results' to the graph/help panel side as shown in the above screen
- Clean up styling on the form side results (in bold)

**Comment by rhernandez-intertech** [comment]
Efficiency Improvement calculator shall henceforth be hidden.

**Comment by koay9f** [comment]
Missed one :D
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3ca0949d-ddc7-4385-84cb-3c546412a203)
