### ISSUE TITLE
Cursor misbehavior

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#3010]
When I try to change the default $0.08/kWh cost, the decimal point is not recognized, and the cost is interpreted as $6,264/kWn (instead of $0.06424/kWh)

![image.png](https://images.zenhubusercontent.com/5c9d17975648dd20c601ea17/0731f0b0-8faa-40cc-89e2-f0308df98218)

[https://app.zenhub.com/files/80439269/6b9fe87d-284d-4d25-b88c-ad728277218f/download](https://app.zenhub.com/files/80439269/6b9fe87d-284d-4d25-b88c-ad728277218f/download)

**Comment by rmroot** [comment]
This calculator no longer exists in `treasure-hunt` branch. Now just have one "Replace vs Rewind" calculator.
