### ISSUE TITLE
MEASUR Web Version

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#3026]
Epic for tracking the MEASUR web version issues.

**Comment by koay9f** [comment]
Should suite issue #257 go with this as well?

**Comment by gaccawi** [comment]
[https://app.zenhub.com/files/80439269/72284383-c3a8-4953-9d40-cb5f8c445a41/download](https://app.zenhub.com/files/80439269/72284383-c3a8-4953-9d40-cb5f8c445a41/download)

**Comment by nbintertech** [comment]
Wrap up #6174 and #4425 as part of this
