### ISSUE TITLE
Reduction Calculator Descriptions

### ISSUE THREAD

**Issue by DmitryHoward** [ORNL-AMO/AMO-Tools-Desktop#3027]
Need calculator descriptions for Electricity Reduction and Natural Gas Reduction calculators. 

Electricity Reduction Description Text:
"This calculator is used to quantify the energy savings associated with reducing electricity usage."

Natural Gas Reduction Description Text:
"This calculator is used to quantify the energy savings associated with reducing natural gas usage."

These descriptions need to appear below the calculator title.

![image.png](https://images.zenhubusercontent.com/5cd5c3ad0c0a027b2619a365/4ae13372-5344-45dd-ad93-cfedbc47812d)

Both calculators have placeholders that need to be replaced with the appropriate text.

**Comment by koay9f** [comment]
Also needs to be put in the Treasure Hunt "Find Treasure" page

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/09c8b0f6-abc1-4556-a541-1df65cc9c5cd)
