### ISSUE TITLE
Compressed Air Reduction Help Text

### ISSUE THREAD

**Issue by DmitryHoward** [ORNL-AMO/AMO-Tools-Desktop#3041]
Add help text for compressed air reduction calculator.

**Comment by koay9f** [comment]
For the help text that always appears in the calculator, the list (turning off compressed air..., reducing compressed air..., eliminating inappropriate..., using engineered nozzles...) should be bulleted.  Don't think it needs lines between each...

Add field specific help text for "Utility Type"
"Choose how compressed air is delivered to your facility.  Choosing "Compressed Air" means it enters your facility as compressed air; choosing "electricity" means it is compressed on site."
