### ISSUE TITLE
Reordering and Refactoring of Utility Cost Settings

### ISSUE THREAD

**Issue by DmitryHoward** [ORNL-AMO/AMO-Tools-Desktop#3048]
UTILITY LIST:
Electricity
Natural Gas
Other Fuel
Water
Wastewater
Steam
Compressed Air

Need to consolidate location of these inputs and establish ordering for various assessment types. Currently, treasure-hunt-specific utilities are in their own component while the rest are in a global settings component. Need to address ordering standard after receiving input from Tom.

**Comment by koay9f** [comment]
For the TREASURE HUNT Steam should be something like `Steam (as Utility)` and its units in $/klb and $/tonne.

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8211d735-327a-4e73-b59e-5fdf0ec46a63)
