### ISSUE TITLE
SSMT unit conversions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3060]
After next suite build, remove the x1000 from turbine results.massflow unit conversions

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/23d00f6e-9a67-4d0a-8422-7fdcc8770db3)

**Comment by rmroot** [comment]
Energy flow out of header /1000 right now as well

**Comment by rmroot** [comment]
converted input and output conversions for steam calcs for energy values to use "kJ".

in branch issue-3060, will need updated suite to be correct
