### ISSUE TITLE
Wastewater calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3067]
Bio-Tiger model for Wastewater Optimization
https://energyefficiency.ornl.gov/wp-content/uploads/2019/05/Bio-Tiger-Model-Model-and-User-Manual.zip 

Need PW to ID all equations etc.
Need to mockup UI

**Comment by koay9f** [comment]
Here is the excel calculator and user manual:
[https://app.zenhub.com/files/80439269/be2ee4a2-2e9f-4e67-89e2-588633ed2294/download](https://app.zenhub.com/files/80439269/be2ee4a2-2e9f-4e67-89e2-588633ed2294/download)

**Comment by rmroot** [comment]
Using issue for initial setup for calculator. Forms and baseline results calculating.. Creating new issues for the rest of the work
