### ISSUE TITLE
Head tool in PSAT modifcation screen

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#309]
Opening head tool in psat modification context has backdrop in front of content. Locks user out. Z-index issue

**Comment by jonhadden** [comment]
Hey Mark, this isn't a z-index issue but where the HTML is placed for the backdrop and modal. They need to be within the same container, but it looks like the backdrop is at the body/root level and the modal is nested inside app-root and app-core.

**Comment by jonhadden** [comment]
<img width="624" alt="screen shot 2017-06-01 at 10 26 05 am" src="https://cloud.githubusercontent.com/assets/1999028/26687217/d56e247c-46b4-11e7-9b66-2e60d493a20e.png">

**Comment by jonhadden** [comment]
Anyway we can move the backdrop into the same level of hierarchy as the .modal?

**Comment by rmroot** [comment]
`.modal-open {
    z-index: initial !important;
}`

applying `modal-open` to the `div` with `modification` class when modal opens fixes the issue
