### ISSUE TITLE
Motor Calculators Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3111]

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/57d53a12-0e54-40bf-b5d4-ebffe731d950/download](https://app.zenhub.com/files/80439269/57d53a12-0e54-40bf-b5d4-ebffe731d950/download)

**Comment by koay9f** [comment]
Percent Load Estimation's defaults need to be redone to be an example with "Field Measurement Method"

**Comment by vanced** [comment]
![image.png](https://images.zenhubusercontent.com/5cd4770cf8cffa5a19122cef/6c5b60c5-3c17-493e-99ba-c34fd9d7c884)

Defaults to replace the "Percent Load Estimation" calculator

**Comment by shubhamkokul** [comment]
Stuck with Percentage load Estimator

**Comment by vanced** [comment]
'Line Frequency' should be 60 HZ in the imperial NEMA Energy Efficiency Calculator and imperial Motor Performance Calculator examples.

**Comment by vanced** [comment]
![image.png](https://images.zenhubusercontent.com/5cd4770cf8cffa5a19122cef/e7eb88c9-737e-4c66-89b5-6ec88816cfa4)

Metric example for NEMA Energy Efficiency Calculator

**Comment by vanced** [comment]
![image.png](https://images.zenhubusercontent.com/5cd4770cf8cffa5a19122cef/709fd038-c2f4-4703-adb1-65d0cc31df4b)

Metric example for Motor Performance Calculator

**Comment by vanced** [comment]
Motor Drive Calculator has a drop down box that isn't converting from hp to kw

**Comment by shubhamkokul** [comment]
> Motor Drive Calculator has a drop down box that isn't converting from hp to kw

Drop down box should change in Generate Example button? or in General

**Comment by koay9f** [comment]
Replace and Rewind does not change when switch to metric. `Motor Size` unit `hp` label should switch to `kW` and there will need to be a conversion to the suite.  the value can stay the same.  

I think the results will all stay the same.

**Comment by koay9f** [comment]
I'm dumb.  Replace/Rewind, for metric, the motor size should be set to 100 for the example.  (I forgot we were doing that, I'm sorry)
