### ISSUE TITLE
Process Heating Calc Default

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3112]

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/166902b2-cb51-45a4-94a5-69aaf1877204/download](https://app.zenhub.com/files/80439269/166902b2-cb51-45a4-94a5-69aaf1877204/download)

**Comment by koay9f** [comment]
Change to what is in the ppt file:
For O2 enrichment calc
Combustion with Air - Combustion air preheat temperature = 80
Combustion with O2 Enriched Air- Combustion air preheat temperature = 400

**Comment by DmitryHoward** [comment]
in branch 3130

**Comment by koay9f** [comment]
O2 enrichment has wrong numbers in default & example for the two `Combustion air preheat temperature` s
With air should be 80
With O2 enriched air should be 400

**Comment by koay9f** [comment]
`Calculate Equivalent Fuel Heat` is not calculating - I think it was before
