### ISSUE TITLE
Pumps Calc Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3113]

**Comment by koay9f** [comment]
I have good values for pump/system curves

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/6339a757-cdcb-480d-ad8e-006cb0625d98/download](https://app.zenhub.com/files/80439269/6339a757-cdcb-480d-ad8e-006cb0625d98/download)

**Comment by vanced** [comment]
Head Tool does not give the specified default values. It gives an example for 'Suction Tank Elevation' instead of 'Suction Gauge Elevation'
