### ISSUE TITLE
Fans Calc Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3114]

**Comment by koay9f** [comment]
I have good numbers for the Fan Analysis tool and Fan/system curves

**Comment by vanced** [comment]
![image.png](https://images.zenhubusercontent.com/5cd4770cf8cffa5a19122cef/3b676d0f-75b4-4586-a249-e28a434f8e3d)

Create 'Generate Data' button. 

Clicking 'Generate Data' button should give the results shown.

Clicking 'Reset Data' button should clear all fields

Initialized data should be the results shown

**Comment by DmitryHoward** [comment]
In branch 3130

**Comment by koay9f** [comment]
Fan Achievable Efficiency - Fields not converting (conversion to suite is fine)
