### ISSUE TITLE
Steam Calculator Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3116]

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/5924677f-01a2-4529-b05c-3061ce9c288e/download](https://app.zenhub.com/files/80439269/5924677f-01a2-4529-b05c-3061ce9c288e/download)

**Comment by shubhamkokul** [comment]
Need Help with Flash Tank
PRV
Steam turbine
Result are not getting updated

**Comment by vanced** [comment]
* No button on the Stack Loss Calculator
* Wrong inputs for the Steam Turbine Calculator when 'Outlet Properties' is selected

**Comment by koay9f** [comment]
Stack Loss - fields are not converting (conversion to suite is fine)
