### ISSUE TITLE
CA Calc Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3117]

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/b6966e2f-9df4-4b92-a161-6eedc7d1be3c/download](https://app.zenhub.com/files/80439269/b6966e2f-9df4-4b92-a161-6eedc7d1be3c/download)

**Comment by vanced** [comment]
Good to go

**Comment by koay9f** [comment]
Receiver Tank Sizing > Dedicated Storage - change length of demand to 1 min
Receiver Tank Sizing > Bridging... - `Distance to Compressor Room` should be 1000 ft --> 304.8 m check conversion
Receiver Tank Sizing > Bridging... - `Air Demand` not converting, should be 600 scfm --> 16.99 Nm3/min
Velocity in piping - fields do not convert.  conversion to suite is good.  results are good (fields in metric should be 50.97, 689.48, 101.35)
