### ISSUE TITLE
Lighting & General Calc Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3118]

**Comment by vanced** [comment]
[https://app.zenhub.com/files/80439269/6cc01409-bb51-4fcb-9c60-c715bf08b4aa/download](https://app.zenhub.com/files/80439269/6cc01409-bb51-4fcb-9c60-c715bf08b4aa/download)

[https://app.zenhub.com/files/80439269/cb4188e7-c0db-4ec5-af9b-1dbb407c8314/download](https://app.zenhub.com/files/80439269/cb4188e7-c0db-4ec5-af9b-1dbb407c8314/download)

Unit Converter and Cash Flow Diagram are okay as is.

**Comment by shubhamkokul** [comment]
Need Clarification for Percent Load Estimator

**Comment by DmitryHoward** [comment]
Example for Pre Assessment calculator is non-exhaustive for all forms in the calculator.

**Comment by DmitryHoward** [comment]
In branch 3130

** Pre Assessment calculator, Compressed Air Pressure Reduction, Water Reduction do not have sufficient data to create examples.

**Comment by koay9f** [comment]
Combined Heat and power --> all fields with MMBTU need conversion to GJ and conversion for the suite.  No changes to the results

CO2 --> all fields with MMBtu need conversion to GJ and conversion for the suite.  No changes to the results

**Comment by koay9f** [comment]
New Calculators:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ade5edef-3012-44fb-9d6c-86bb2b35635b)

Steam: use current default for Measurement method = Mass flow of air; Measured.  have modified be measurement method = off sheet, such that you get about 5% savings.

Water

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/17e1f335-3559-4b63-abfe-cb0477adf9e0)

**Comment by koay9f** [comment]
The imperial value for modification `water consumption` is wrong.

1 - the label should be changed to gal/yr
2 - the example value should be 14000000 gal/yr (not 14979.6?)

All the MATH is correct (conversions, into the suite, etc.).  just wrong label and wrong default value
Metric looks correct (I assume converting from gal --> m3)
