### ISSUE TITLE
Increase significant digits in CO2 Savings Calculator Results

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#3122]
![image.png](https://images.zenhubusercontent.com/5cd4770cf8cffa5a19122cef/d7bdc168-1ef5-4ce4-a722-38307002806e)

Add another significant digit to 'Baseline' and Modification' results.

**Comment by koay9f** [comment]
Add one decimal point to the "output rate"-s

**Comment by koay9f** [comment]
Sorry - should also be the ones under "Baseline Summary" and "Modification Summary".  I don't know why David only highlighted the "Totals"
