### ISSUE TITLE
Percent Load Estimation Calculation 

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3145]
Average current & voltage calculations do not work.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c591ee89-a0ee-47fc-b124-8557a59c5e8d)

In screen cap 
Amps = { 205, 202, 198} --> ave current = 201.7 A
Volts = {461, 459, 458} --> ave volts = 459.3 V

Input Power = Ave Amps * Ave Volts * sqrt(3) * PF (in decimal) = power in Watts
Input Power = 201.7A * 459.3V * sqrt(3) * (0.85)  = 136489 W = 136.5 kW 

Percent Load = (ave current / rated current) * (ave volt / rated volt)
Percent Load = (201.7A/225A) * (459.3V/460V) = 89.5%

I think the calcs for input power (except for the unit conversion) and percent load are correct (when plugging in the results for average current and voltage) but should be checked.

**Comment by koay9f** [comment]
** looks like power factor is already a decimal, so don't need the /100 in `PF/100` it would just be `PF`

**Comment by rmroot** [comment]
Had a couple wires crossed. Fixed the issue here.

Do we want to make it a percent for power factor? Do we want to add a range of 0-1 if keeping it a decimal?

**Comment by koay9f** [comment]
Looks great.  Throwing this back for the power factor question.  Lets go on and make the user input be a percent, so have it convert from `98` --> `0.98` for calculations, add a % label.  Range: 0% - 100%
