### ISSUE TITLE
SSMT Calc - Header Result labels

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3154]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a0cd80c2-88db-4eeb-bad1-3a7daba25d42)

The headers for the results need to be shifted.
Ex: Inlet 1 should be the first column (the data in the column is correct, the label is wrong)

**Comment by rmroot** [comment]
I believe this has been fixed.

**Comment by koay9f** [comment]
Nope
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/dc208234-ffaf-40b3-a4e6-a1c504988908)
