### ISSUE TITLE
Pump Calculator Quick Fixes

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#3159]
PUMP HEAD CALCULATOR
* Fix subscripts throughout. Everything in parentheses should be a subscript besides Pipe Diameter (ID).  (Pg, Pd, Zs, Ks, Zd, Kd)
* Remove extra space between letter and subscript in the diagram label. K s, K d, P d
* Name of the calculator should be 'Pump Head Tool' throughout. (Change the sidebar, calculator title, general help text title, and in the calculator list.

SYSTEM CURVE CALCULATOR
* 'Order' label should be next to its field. Under Pump Curve Data > By Data
* Title of the calculator should be 'Pump System Curve' in the sidebar, title of calculator, and in calculator list

SPECIFIC SPEED CALCULATOR
* Change general help text from 'For each pump type there is an optimal specific speed based on size, flow rate, and specific speed' to say 'For each pump type there is an optimal specific speed based on pump speed, flow rate, and head.'
* Change title of the calculator from 'Specific Speed Calculator' to 'Specific Speed'

PUMP ACHIEVABLE EFFICIENCY CALCULATOR
* 'Results' Tab should say 'Graph' instead
* Name of the calculator should be 'Pump Achievable Efficiency' throughout. (Change the sidebar, title of calculator, title of general help, and calculator list.)

PUMP CURVE CALCULATOR
* 'Order' label should be next to its field. Under Pump Curve Data > By Data
* Change title of the calculator from 'Pump Curve Calculator' to 'Pump Curve'

**Comment by koay9f** [comment]
I think that's everything but I'm going to let David close it.

**Comment by vanced** [comment]
PUMP SYSTEM CURVE
* Title should be changed from 'System Curve Calculator' to 'Pump System Curve'
* When I click anywhere under 'Pump Curve Data' I can no longer click back under 'System Curve Data' to see that help text. Might be related to another issue

PUMP ACHIEVABLE EFFICIENCY
* Change title of help from 'Pump Achievable Efficiency Calculator Help' to 'Pump Achievable Efficiency Help'

PUMP CURVE
* Title should be changed from 'Pump System Curve Calculator' to 'Pump Curve'
* Can't click into the help text under System Curve Data
