### ISSUE TITLE
Fan Calculator Quick Fixes

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#3160]
FAN ANALYSIS
* Extra space between letters and subscripts throughout in 
    * Basic Fan Info (P b, N c, P c, P bc)
    * Establish Gas Density (p 0)
    * Input Plane Data (T dx, P bx, P sx, C p)
    * Fan Shaft Power (H i)
* Create help text for 'Outlet fan static pressure measurements (Plane 5) taken Upstream or Downstream of Fan Outlet (Plane 2)'
* Title for 'Establish Gas Density' says 'Establish Base Gas Density' when clicked. Should say 'Establish Gas Density'

SYSTEM CURVE CALCULATOR
* 'Order' label should be next to its field. Under Fan Curve Data > By Data
* Pressure help text is repeated if you click on one of the pressure inputs under Fan Curve Data > By Data
* Title of calculator throughout should be 'Fan System Curve' (Title of calculator, sidebar, and calculator list)

FAN CURVE CALCULATOR
* 'Order' label should be next to its field. Under Fan Curve Data > By Data
* Pressure help text is repeated if you click on one of the pressure inputs under Fan Curve Data > By Data
* Change title of calculator from 'Fan Curve Calculator' to 'Fan Curve'

ACHIEVABLE EFFICIENCY CALCULATOR
* 'Graph' tab should be labeled 'Results' instead
* Capitalization errors in inlet and outlet pressure help text
* Calculator should be named 'Fan Achievable Efficiency' throughout

**Comment by koay9f** [comment]
In case this isn't said in another issue.  Fan Analysis's name should be changed to Fan Traverse Analysis.
