### ISSUE TITLE
General Calculator Quick Fixes

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#3166]
LIGHTING REPLACEMENT
* Need to ask Tom what he wants to put for units of 'Watts per lamp', 'Lumens per lamp', 'Lamps per fixture', 'Number of fixtures' if any.
* 'Electricity Cost' field by field help text: 'Per unit cost of electricity in ($/kWh).'

PREASSESSMENT/ SCREENING CALCULATOR
* Bold 'Total Electricity Consumption (Process Equipment)', 'Total Fuel Consumption', 'Total Steam Consumption (Process Equipment)' to make clear that it is a header and not a label
*  General Help text: 'Enter metered or designed energy data for multiple systems to compare their energy consumption.' NEED BETTER HELP TEXT
* Change every instance of 'Pre-Assessment / Screening Calculator' to 'Pre-Assessment Screening'. (Calculator list, sidebar, title of calculator)

UNIT CONVERTER
* Under Area, the scroll bar has units with extra ';' at the end. For example, 'Square Inches (in2);', 'Square Kilometers (km2);', 'Square Miles (mi2);', square millimeters, and square yards.

COMBINED HEAT AND POWER
* Change title on calculator page from 'Heat and Power Calculator' to 'Combined Heat and Power'

CASH FLOW DIAGRAM
* Change every instance of 'Cash Flow Diagram' or 'Cash Flow Calculator' to 'Cash Flow'. In the title of the calculator page, sidebar label, and calculator list
*  Capitalization errors in Lifetime, Installation Cost, Annual Operation Cost, and Annual Fuel Cost help text
* Unit for 'Lifetime' is 'yrs'

POWER FACTOR CORRECTION CALCULATOR
*  Add to the end of 'Existing Power Factor' and 'Proposed Power Factor' help text: 'Input this number as a decimal.'
* Change the title of general description from 'Calculator Description' to 'Power Factor Correction'
* Change the title of the calculator from 'Power Factor Correction Calculator' to 'Power Factor Correction'

CO2 SAVINGS CALCULATOR
* Change calculator title from 'CO2 SAVINGS CALCULATOR' to 'CO2 SAVINGS'
* Total Emission Output Rate unit label doesn't fit on one line

Compressed Air Reduction Calculator
* Help text for Electricity Cost : "Cost of electricity per kilowatt hour."
* Help text for Compressed Air Cost: "Per unit cost of compressed air in (UNIT)." Replace unit with the actual unit used. Look at Natural Gas Reduction Fuel Cost for example.

**Comment by koay9f** [comment]
Lighting units:  Watts/lamp (W/lamp) and lumens per lamp (lm/lamp)
Dont need to add lumens to the converted, just make a label.
Other fields dont need units
