### ISSUE TITLE
Motor Drive 'Motor Power' drop down box

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#3171]
'Motor Power' field in the Motor Drive Calculator should be input instead of a dropdown so that it can convert from hp to kW.

**Comment by rmroot** [comment]
Does this mean we want to allow either hp or kW as a unit for this input?

Are there min/max or any other constraints on the input?

**Comment by koay9f** [comment]
Yes please. Depending on the unit system in settings
min = 0 
max = none

should be like other motor power fields in PSAT, FSAT and other motor calcs
