### ISSUE TITLE
Pump Types dropdown broken

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3188]
Cannot get the last pump types, even when using the arrow keys

psatConstants.ts has
`export const pumpTypesConstant: Array<{ value: number, display: string }> = [
    {
        value: 0,
        display: 'End Suction Slurry'
    },
    {
        value: 1,
        display: 'End Suction Sewage'
    },
    {
        value: 2,
        display: 'End Suction Stock'
    },
    {
        value: 3,
        display: 'End Suction Submersible Sewage'
    },
    {
        value: 4,
        display: 'API Double Suction'
    },
    {
        value: 5,
        display: 'Multistage Boiler Feed'
    },
    {
        value: 6,
        display: 'End Suction ANSI/API'
    },
    {
        value: 7,
        display: 'Axial Flow'
    },
    {
        value: 8,
        display: 'Double Suction'
    },
    {
        value: 9,
        display: 'Vertical Turbine'
    },
    {
        value: 10,
        display: 'Large End Suction'
    },
    {
        value: 11,
        display: 'Specified Optimal Efficiency'
    }`
but cannot choose anything past double suction

**Comment by rmroot** [comment]
Is this within a pump assessment or a specific calculator? Both?

*I was not able to replicate within pump example
