### ISSUE TITLE
Inconsistencies between Efficiency Improvement Calculator and O2 Enrichment calculator

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#3198]
User reported differences via email:

Consider the basic problem below:
Natural Gas Furnace
Current Flue Gas Oxygen = New Flue Gas Oxygen = 4%
Current Flue Gas Temp = New Flue Gas Temp = 500 F
Current Combustion Air = 80 F
New Combustion Air = 300 F

The Fuel Savings (%) calculated by the "Efficiency Improvement Calculator" does not match with the Fuel Savings calculated by the "Oxygen Enrichment Calculator".

The latter is closer to PHAST's calculations.  Can you look into why the two calculators give different answers?

**Comment by koay9f** [comment]
Parentheses are in the wrong places
In EfficiencyImprovement.cpp
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/20a2b577-604e-4e99-a369-5cb870d1a3d6)

line 45 should be
`    this->currentAirCorrection_ = -(-1.07891327 + currentAirSpecificHeat * (this->currentFlueGasTemp_)) * (currentExcessAir/100);`

line 52 should be
`    this->newAirCorrection_ = -(-1.07891327 + newAirSpecificHeat * (this->newFlueGasTemp_)) * (newExcessAir/100);`

line 59 should be
`    this->currentCombustionAirCorrection_ = (-1.078913827 + currentAirSpecificHeat * (this->currentCombustionAirTemp_)) * (1 + (currentExcessAir/100));`

line 66 should be
`    this->newCombustionAirCorrection_ = (-1.078913827 + newAirSpecificHeat * (this->newCombustionAirTemp_)) * (1 + (newExcessAir/100));`
