### ISSUE TITLE
Boiler Blowdown Modal

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3212]
Modal (or something) for boiler calc & steam assessment.

Link for calculating Blowdown rate:

Two user inputs: `Blowdown Conductivity` and `Feedwater Conductivity`
`Blowdown Rate = (FW Conductivity/BD conductivity) * 100%`

Result of the calculation goes into Blowdown Rate Field.

**Comment by rmroot** [comment]
Add Calculator to steam calcs

**Comment by vanced** [comment]
The SI unit of conductivity is Siemens per meter or (S/m). In industry it is usually given as micro Siemens/centimeter.

**Comment by rmroot** [comment]
Added issue for creating full calculator. Currently just added modal calculation
