### ISSUE TITLE
Add Calculator for Blowdown Rate

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3234]
Modal added for calculating blowdown rate. Need to add a full calculator.

Blowdown Rate = (Blowdown Conductivity / Feedwater Conductivity) *100

Units: The SI unit of conductivity is Siemens per meter or (S/m). In industry it is usually given as micro Siemens per centimeter (μS/cm). (per david)

Will need help text and ranges(?).

**Comment by koay9f** [comment]
User input: Steam Flow 
User input: Steam Temp
User input: Steam Pressure

Calculate Enthalpy Steam (Steam Properties Enthalpy, T = Steam Temp, P = Steam Pressure)
Calculate Enthalpy Blowdown (Saturated Properties Enthalpy Liquid, T = Steam Temp)

**Comment by koay9f** [comment]
Math and help text
[https://app.zenhub.com/files/80439269/135ccb1c-c124-4018-a259-87e86bfccfab/download](https://app.zenhub.com/files/80439269/135ccb1c-c124-4018-a259-87e86bfccfab/download)

**Comment by koay9f** [comment]
Steam Flow - 1000 klb/hr
Steam Temp - 500 F
Feedwater Cond - 400
Blowdown Cond - 5500
Makeup Water - 50
Fuel Cost - 4.99
Water - 0.025
Op Hrs 8760

**Comment by koay9f** [comment]
Notes from call:

* make it so can calculate blowdown rate even with zeros/blanks in (non-"conductivity") fields
* Add results
  - `Blowdown rate [lb/hr]` = `Blowdown rate (%)` * Steam Flow / (1 -  `Blowdown rate (%)` )
  - ` Feedwater rate [lb/hr]` = Steam Flow / (1 -  `Blowdown rate (%)` )
* Group and rearrange
 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2b48abcc-2780-4c52-99fb-9972f9a72d20)

**Comment by koay9f** [comment]
Does not seem to be calculating dynamically

Results tweaks
- Blowdown rate (klb */hr* )
- Feedwater rate  (klb */hr* )
- Blowdown % - 2 decimal places
- Blowdown (klb/hr) - 2 decimal places
- All other results - no decimal places
