### ISSUE TITLE
User reports unexpected results with %FLA at 0% shaft load

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#3251]
User reports:

On two recent occasions MEASUR gave a value of %FLA at 0% shaft load that was about double the value given on the technical data sheet for the motor. The Motor Performance Calculator should have a field to stipulate this and force the charting algorithm to be duly constrained.
 cid:image001.jpg@01D5569E.94908B60

**Comment by gaccawi** [comment]
![image001](https://user-images.githubusercontent.com/8973004/63302805-15f43480-c2ac-11e9-85eb-458ec74fc236.jpg)

**Comment by rmroot** [comment]
Possibly start graph at 1% motor shaft load.

Check database for where numbers start.

**Comment by koay9f** [comment]
The value for Current at 0% load is calculated based on MotorMaster curves.  I'm not sure what would be accomplished by manually setting the current at zero load.  At best it would shift up all the values and I'm not sure that they would be valid.  Need to talk to Daryl about this.
