### ISSUE TITLE
Fans Inlet/Outlet Pressure Validation

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3254]
I noticed that Fan Achievable Efficiency calculation doesn't work when:

Inlet Pressure > Outlet Pressure

This is the calculation in the suite..

![optimalFanEfficiencyCalc.PNG](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/eb2a0c60-3a07-4d9c-b06c-1ef04ce780b5)

Do we want to add validation to ensure Inlet < Outlet for this calculator? Do we want to add the same validation to FSAT Field Data?

**Comment by rmroot** [comment]
Add validation confirmed

**Comment by koay9f** [comment]
I can't tell that this is in Fan Achieveable Efficiency or FSAT.
Better validation though:
Inlet pressure must be < 0
Outlet pressure must be > 0

**Comment by rmroot** [comment]
Added to both FSAT and Fan Achievable Efficiency

Using: 
Inlet pressure must be < 0
Outlet pressure must be > 0
