### ISSUE TITLE
TH - Icon Updates

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3280]
Need the following icons updated with circles and lighting/shading added.

![compressed-air-pressure-reduction-icon.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/e7ce4766-df42-488b-9429-9db94e9165d7)

![steam-reduction-icon.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/926222ec-95cf-4c98-93e3-e0f5d5611781)

**Comment by rmroot** [comment]
Potentially may want to add icons for "Replace Existing Motor" and "Upgrade Motor Drive"

Both are using the square backgrounds that don't match with the other TH icons.

![motor-drive.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/435c884f-1b0a-4381-9ba6-7fe034ed7dfa)

![replace-rewind.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/fa0a467d-28b8-471c-8726-7c5e8325ba03)

If we could stick em in a circle of some sort that would be great.

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/088ba4c1-6397-4a8b-9faf-e1b240d4cb80)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/291e2386-c8f7-4dd7-ac13-0f3843445c04)

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f696f952-2547-40d9-b131-a5588a802c43)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a6c06c52-21dc-4add-9926-25dd0b877d8b)
