### ISSUE TITLE
Steam Graphs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3284]
Sometimes the top of the T-S diagram is cut off

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a091dee4-172a-4f19-8249-5470cb485bae)

And the P-H didn't even show up.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a3e4fa5a-9ae5-4632-9536-320d7e67201e)

**Comment by koay9f** [comment]
Trying to recreate in develop and I'm not getting any graphs at all...

**Comment by rmroot** [comment]
I can fix no graphs bug. Comes from package updates.

**Comment by rmroot** [comment]
Created #3291 for the graph not showing up bug

**Comment by rmroot** [comment]
Fixed native element bugs. There is still a bug with P-H diagrams that is related to d3.

**Comment by koay9f** [comment]
T-S Diagram
Still cutting off top of graph when T is low. 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/42fdafce-e1e7-4d5b-a6fb-6e41b9d3bb86)
Why are we resizing the axis?  Maybe just make it so that the y-axis max is always 800F (700K) or higher and only extends up if T > 750F (~650K) (IDK what units you are using for your settings...).  

Also, graph has F units on y axis when T setting is K or R (i.e., not "metric"). (looks like the numbers and dot position were correct, just the label is wrong)

PH diagram is good
