### ISSUE TITLE
Subscripts in Pump Head Calculator

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#331]
Edit the picture and the text so that lowercase letters are subscripts. Will clarify that the lowercase letters are not variables but describe the uppercase letters.

**Comment by gaccawi** [comment]
Kristina, can you take a look at this one? We can integrate a new image if you can specify for us which ones exactly should change.

**Comment by koay9f** [comment]
Who made the image?  If someone has an editable version still, I can fix it or they can (just make the second letter in each label subscripts)

Old:
![image](https://user-images.githubusercontent.com/25389736/29635357-cd7faa2c-881a-11e7-90d9-914755ae3ee1.png)
With Subscripts:
![image](https://user-images.githubusercontent.com/25389736/29635363-d53e5bd2-881a-11e7-950c-788e669e7943.png)
(Don't use this in the tool, just a quick example)

The other picture would look similar

**Comment by koay9f** [comment]
There are pic in the drop box that have the subscripts,.  Were these rejected or might they be better to use?

Suction tank elevation
![Flow_chart_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46ce989534bd80a18efbab7cf61fbcd6395428792c07b7692ac7b671bb4779005d0b47ab100e0d16fcf98c2cf0b73923d85a19f1c32f0e2a92624cf5f2d75dad0ba822894584b3bd8a4ac6e03526e08b89472c53.png)

Suction Gauge Elevation
![Flow_chart_1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46ce989534bd80a18efbab7cf51fbcd6395428792c07b7692ac7b671bb4779005d0b47ab100e0d16fcf98c2cf0b73923d85a19f1c32f0e2a92624cf5f2d75dad0ba821834584b3bd8a4ac6e03521e5888f4c2c53.png)
