### ISSUE TITLE
TH Tracking

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3321]
Best: Make something like this file (the chart kind of stinks in excel)
* Second "Opportunity Sheet"? "Implementation Sheet"
* Implementation Report - basically the "Project Tracking Sheet" - with same inputs

Good Enough: Pull info from Opportunities summary into "Master Sheet"
Minimum Effort:  create csv file that can be copied into "Master Sheet"

[https://app.zenhub.com/files/80439269/1abce0e3-f9dc-4b11-b5f7-bf951dcee729/download](https://app.zenhub.com/files/80439269/1abce0e3-f9dc-4b11-b5f7-bf951dcee729/download)

**Comment by koay9f** [comment]
I would think we could export ALL the info in the Opp Sheet into a "Opportunities List" then have another sheet kind of like the implementation sheet, ready for users to fill out or not.

**Comment by koay9f** [comment]
IGNORE ABOVE

Opportunity Summary -
Add "Copy Table" button
When copy table get pretty much everything in the opportunity sheet (including new field in #3901)
See first worksheet in attached

Getting fancy - 
 Project Tracker[https://app.zenhub.com/files/80439269/24e95f0b-56ca-4148-a277-653da03555a6/download](https://app.zenhub.com/files/80439269/24e95f0b-56ca-4148-a277-653da03555a6/download)
mostly same data as opp summary, but a few columns with headers but no data
see second worksheet in attached

**Comment by nbintertech** [comment]
A user should be able to click a 'copy table' button on the opportunity summary, which will export a 2 sheet excel file. The first sheet is a copy of the table (all opp summary data). The second sheet is the same opp summary table data with added blank columns and renamed columns - see comment above.

**Comment by koay9f** [comment]
_Big To Do_
Bring back old copy table button
Put this in a "Export Project Tracker" Button

**Comment by koay9f** [comment]
_Big Big Reach_
[https://app.zenhub.com/files/80439269/07f3c1c7-9999-4477-a90e-a177fcd9a3bb/download](https://app.zenhub.com/files/80439269/07f3c1c7-9999-4477-a90e-a177fcd9a3bb/download)
[https://app.zenhub.com/files/80439269/cda5da97-5645-4962-a778-43ad212bd8b0/download](https://app.zenhub.com/files/80439269/cda5da97-5645-4962-a778-43ad212bd8b0/download)
[https://app.zenhub.com/files/80439269/a952da13-d8ee-45f0-99bf-675d19d9aa06/download](https://app.zenhub.com/files/80439269/a952da13-d8ee-45f0-99bf-675d19d9aa06/download)
