### ISSUE TITLE
pump curve equation text overlapping

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3341]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4816ba13-62d3-4262-b3e7-3f4f8d7e681e)

Ideas to help: 
coefficients all in scientific notation with only 2 decimal places (also for system curve coefficient)
smaller text?
"Head" --> "H"
"Pressure" --> "P" (for fans)
"Flow" --> "Q"
"Pump Curve Regression" --> "Baseline"
"Modified Regression" --> "Modification"
"System Curve Regression" --> "System Curve"

**Comment by rmroot** [comment]
Somewhat working on this in existing issue for pump/fan curve #3149
