### ISSUE TITLE
Add new unit - Thermal Conductivity

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3449]
Imperial Anchor = "BTU per hr-feet-Rankin (BTU/hr-ft-R)"

Metric Anchor = "Watt per meter-Kelvin (W/m-K)"

conversion from imperial to metric
1 BTU/hr-ft-R = (1055.056*3.2804*1.8/3600) W/mK

**Comment by DmitryHoward** [comment]
1 BTU/hr-ft-R = (1055.056 * 3.2804 * 1.8 / 3600)
