### ISSUE TITLE
Load Factor Revision

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3459]
Change field name of Load Factor to "Percent Loaded" and replace the help text with what is below

Locations (may be missing some)
Pumps-Results
Fans - Results
Motor Drive Comparison (actually called `Average Motor Load` here)
Replace vs. Rewind (actually called `Load` here)
Electricity Reduction - "Measurement Method" = Name Plate Data

Help Text
Also called load factor, this is the ratio between actual load and rated load.  Often motors are installed larger (more horsepower) than required by the driven load to compensate for time degradation and variations in the demand.   The Percent Load is best determined by measurement of the current and voltage, percent loaded can then be calculated (the Percent Load Estimation Calculator can help).

If a measurement is not possible, then it can be estimated using the following rule-of-thumb.  If the motor is part of OEM equipment then 100% is probably correct, if the motor was installed as part of a system and loading is not known 75% or 80% Is a conservative estimate.

Maximum efficiency is usually near 75% of rated load. Overloaded motors can overheat and lose efficiency. Underloaded motors, those loaded below 50% of rated load, are inefficient and exhibit low power factor.

**Comment by cranfillkd** [comment]
- ~~Pumps-Results~~
- ~~Fans - Results~~
- ~~Motor Drive Comparison (actually called Average Motor Load here)~~
- ~~Replace vs. Rewind (actually called Load here)~~
- ~~Electricity Reduction - "Measurement Method" = Name Plate Data~~
- ~~Help Text~~
