### ISSUE TITLE
TH Report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3461]
In the Opportunity Summary, the very edge of Simple Payback can get cut off.  
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1efb6264-ad3c-4456-bcab-638f41c176d8)

This one's not bad, but I was sent a worse one

**Comment by rmroot** [comment]
Potentially landscape view
