### ISSUE TITLE
TH quick fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3471]
For the steam & CA calcs - change defaults for "Utility type" = Natural Gas (instead of steam) and "Utility type" = Electricity (instead of compressed air)

Energy Usage & Costs - all utility groups should look more like Electricity ("Annual Consumption" & "Annual Costs")

"Custom Opportunity Savings" - dropdown for utility type should include "Other".  Just lump it with the other we already have in reports (so Other will = "other" and combined utilities).  I think this would have to be inputted as cost savings (no per unit) and so there would also be a new utility that was "other" with no unit costs or utility value, just annual cost

Report Charts - can we have comma separators (I think this is already an issue somewhere, but just in case)

Is this possible?  Is it a day's work?  
For compressed air related opportunities, if compressed air is not selected as a utility, do not show compressed air in the utility dropdown menu. 
If it isn't possible or is too much work ignore it, but leave me a note for when I verify

**Comment by koay9f** [comment]
Ignore the "other" part.  will make new issue

**Comment by rmroot** [comment]
Creating another issue for updating dropdowns in calculators to just show used utilities.
