### ISSUE TITLE
Natural Gas Reduction - Flow meter method calc bug

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3472]
NaturalGasReduction.cpp
Line 19

`tmpEnergyUse = tmpTotalFlow * naturalGasReductionInput.getOperatingHours() * 1.03;`
should be
`tmpEnergyUse = tmpTotalFlow * naturalGasReductionInput.getOperatingHours() * 1.03 * 1000;`

**Comment by DmitryHoward** [comment]
This is a Suite issue, not desktop.

**Comment by koay9f** [comment]
I'm an idiot.  Should be `... / 1000` not multiplied.

Test:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c597afc5-7dc8-4dbd-82ec-96196da32a18)
