### ISSUE TITLE
Translation won't calculate

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3479]
If viewing MEASUR translated by google, it does not perform calculations (current work around: change back to English, "wiggle" a field, then change back)

May be everywhere.  For sure the calculators, pumps doesn't seem to be working either (can't use estimate FLA, the rest works after navigating away to another tab then returning).  PH works (if do the navigation trick).  Steam seems to work. (Assuming Fans is the same as pumps)

Graphs seem to update

**Comment by nbintertech** [comment]
@rhernandez-intertech Can you comment any info you have on this and/or collaborate with Kai for him to take a look?

Also big NOTE: since this issue was made we no longer do google translate in the desktop (deprecated) so it will have to be looked at in the web version
