### ISSUE TITLE
LogTool: Import/Parse Data 

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3495]
Enhance importing and parsing of data to handle all file types and create the correct objects.

**Comment by rmroot** [comment]
Make sure all date types are supported, including dates with seconds and without

**Comment by cranfillkd** [comment]
12 Hour Combinations

- hh
- hh:mm
- hh:mm:ss
- hh a
- hh:mm a
- hh:mm:ss a
- hh A
- hh:mm A
- hh:mm:ss A

24 Hour Combinations

- HH
- HH:mm
- HH:mm:ss
- kk
- kk:mm
- kk:mm:ss
