### ISSUE TITLE
LogTool: Support Data files without Dates

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3500]

**Comment by koay9f** [comment]
Tool allowed me to bypass not having a date but Data Visualization wouldn't show anything

use file AMO Tools/AirMaster/Sample Data/bigdata2.csv in dropbox

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/97be39dd-39d4-42b2-b45f-3ea3f8f4596f)
