### ISSUE TITLE
Desktop crashes if click "Calculate Head"

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#355]
Desktop crashes (window darkens and user cannot click on anything) if user tries to use the "Calculate Head" function when at the "Modify Conditions" Stage.

In the window you can see the Pump Head Calculator, but cannot interact with the window beyond minimizing and closing.

**Comment by rmroot** [comment]
Thank you, this issues has been fixed and will be apart of the next release in the coming days.
