### ISSUE TITLE
Remove old acronyms  

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3559]
I think this is mostly an issue with PHAST - in Report - Energy Used, System Setup - Design Energy Use & System Setup - Metered Energy

Except when referring to the older software (the home page and the about page), the old acronyms should not be used

Old name          New name
PSAT                  PA
PHAST               PHA
FSAT                  FA
SSMT                SA

**Comment by rmroot** [comment]
Updated PHAST:
- designed energy help
- designed energy results
- Lossses help: "PHAST Materials Database" -> "Process Heating Materials Database"
- Energy input help
- Metered energy help
- Metered energy results
- PHAST report energy used

Updated PSAT/FSAT:
- PSAT Report graphs
- Report Rollup
- Tutorials disable modal
- Print options menu

**Comment by koay9f** [comment]
Leftover ones:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ba8a15b0-9736-4794-9964-4b16a1b7f24c)

Only other ones:
The tutorials themselves
Pump System Assessment Tool = Pump Assessment Module
Process Heating... = Process Heating Assessment Module
Fan
Steam

Can't think of anywhere else
