### ISSUE TITLE
Report Rollup Sidebar Bug

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3575]
Sidebar not working, causing white screen when clicked on link.

**Comment by rmroot** [comment]
Fixed sidebar usage in report
Fixed printing errors of rollup report
Re-organized code to separate concerns into own components/services
Pre-Assessments not printing (causing errors, creating new issue)

**Comment by koay9f** [comment]
roll up print has no pie
