### ISSUE TITLE
PSAT Sankey 2.0

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3582]
Change psat sankey to plotly.js usage

**Comment by nbintertech** [comment]
Current chart below. Estimating 3 points left for additional styling tweaks, testing and development time to merge in with changes since it was last current with develop branch.
![psat.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/92fc9b65-3832-4674-8e19-2ec63f19d49c)

**Comment by koay9f** [comment]
Two problems:

In Novice View - Sankey is not updating as I change things, I have to switch between BL and mod to refresh the page

If I switch to direct drive, then I get the "greater than 100%" message.  I'm guessing this is b/c drive efficiency is now at 100%...?  100% is fine, greater than 100% is bad.
