### ISSUE TITLE
FSAT - Sankey 2.0

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3586]
Refactor fan sankey to use plotly.js

**Comment by nbintertech** [comment]
Current visual on this chart is below. Estimating 2/3 points left for testing and development time to merge in with changes since it was last worked on.
![fsat.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/e3b97348-2fa4-4e8d-81a7-6ed4fca0d72f)

**Comment by koay9f** [comment]
Some weird things:
Sankey in Explore Opportunities is displaying, Sankey under "Sankey" is not

getting some weird results in mod with no drive losses (drive == "direct drive")
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/91e23297-4ef9-4204-b873-0d5a2798cf1e)
maybe, at least to help trouble shoot, in addition to the % in the hover label, we also have the kW? (the values for both internal nodes should be 413)
Use `Fan Example` make a new mod and have it set up like the above pic

**Comment by koay9f** [comment]
One problem still

* like pumps, I have to navigate away for the sankey to update, but now I have to navigate to "Modify All" (switching between BL and mod doesn't update)

* Drive type == direct does work (unlike pumps), so that's good
* Buttons for BL/Mod look good
