### ISSUE TITLE
Fan Assessment Density

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3590]
Change "Use Custom Density" to "Use Known Density"

If `Gas Type` = "Other Gas" then the ONLY `Method to establish Gas Density` is "Known" so hide everything including the drop down for Method.  Have it pass "Custom" to suite w/o showing it to the user.

In Specific Gravity help text (if Fan UI issue in this will be "relative density") - remove sentence about flue gas.

For Gas Density help text add - `To convert from relative density to actual density, multiply relative density by the density of air at STP (1.2 kg/m^3 or 0.075 lb/ft^3)`

**Comment by AlexBotts** [comment]
**See Attached Table**
[https://app.zenhub.com/files/80439269/5ba432b8-4b2f-409b-9372-8308390529d2/download](https://app.zenhub.com/files/80439269/5ba432b8-4b2f-409b-9372-8308390529d2/download)

1) Need to remove some combinations of options for calculating psychrometric parameters
If the user selects “other gas” then the gas is NOT air.  The psychrometric relationships between wet bulb dry bulb, dew point, density, etc. are valid only for air, not for other gasses.  So the Relative humidity, dew point and wet bulb methods need to be removed (grayed out and not selectable) from the “method” pulldown if the user has selected “other gas”. 

2. Include relative density method for “Other Gas”
If the user selects “other gas” I suggest they should have two choices available in the “method” pulldown: 
•	“Use Known Density” and 
•	“use relative density” (what you previously called specific gravity)

**Comment by koay9f** [comment]
@AlexBotts - check with Sachin if Flue gases can use air psychometric calcs and if they count as "air"

**Comment by AlexBotts** [comment]
@koay9f flue gas is not treated like air... once burned there should be less oxygen  therefore the density and other parameters will not be "like" air.

**Comment by koay9f** [comment]
FYI the issue main body should be up-to-date with the `to-do's` for the issue.  The second comment has a table that may be handy

**Comment by koay9f** [comment]
`Gas Specific Gravity (G)` is still present in all three forms.

for all the fields with "Gas ... " (except Gas Type and Gas Density)  change to "Air ..."

Not sure: Can "Gas Density" be "Air Density" if "Gas Type" == "Air" and "Gas Density" if other?
