### ISSUE TITLE
Fan UI Improvements

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#3592]
-Use only one decimal place for fan efficiency

- Specific heat of air is constant - remove field from user input - since it is in the suite - just pass 0.24 all the time.

-In fan type change "Axel" to "Axial"

-In fan type dropdown reorder to be in alphabetical order
- In Fan list: all instances of "DIDW" should be "DWDI" and "SISW" should be "SWSI"

-Change the word "Pump" to "Fan" on "end tutorial page" and twice on "explore opportunities page"

-Change wording throughout from "gas specific gravity" to "gas relative density"

-On the "install more efficient motor input" option - if one is `Specified` - only show the "Specified Motor Efficiency" for *that* option (if BL is specified, only show BL efficiency) -@mroot - is this possible? 

- Remove old terminology from fan dropdown
o	Air handling, 
o	Material handling and 
o	Long Shavings

**Comment by AlexBotts** [comment]
- Use only one decimal place for fan efficiency

- In fan type change "Axel" to "Axial" 

- In fan type dropdown reorder to be in alphabetical order

- Change the word "Pump" to "Fan" on "end tutorial page" and twice on "explore opportunities page" 

- Change wording throughout from "gas specific gravity" to "gas relative density"

- On the "install more efficient motor input screen" It would be slightly better if the “baseline Motor Efficiency” and “Modification Motor Efficiency” choices did not appear at all when the “Modification Efficiency Class” is specified

**Comment by koay9f** [comment]
Specific Heat Gas - @AlexBotts  - we need to check w/ Tom, Sachin, and Daryl - did we include that b/c of flue gases? Can Flue Gases use the Wet Bulb Temp method to estimate density?

**Comment by AlexBotts** [comment]
@koay9f 

Old Terminology - after reviewing the AMCA standard and speaking with Tom old terminology should be removed from MEASUR (excel data should be kept). Each of them fall into a previously mentioned category (material handling =type of radial)

**Comment by koay9f** [comment]
FYI - the text in the main body of the issue should be up-to-date with all the `to do's` for the issue

**Comment by nbintertech** [comment]
@koay9f Note for future issue - The user still sees the Specific Heat Ratio form input in fan tutorial pages 
![fantut-spec-heat2.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/9a2efaf6-d36a-47d2-8464-1cb8130b646c)

![fantut-spec-heat.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/25cfd9b8-da42-4147-83fd-bfabec994069)

**Comment by koay9f** [comment]
Missed some pumps
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/99fcc310-8b75-4eb5-b4dc-2122b26c7ccf)

Otherwise awesome
