### ISSUE TITLE
SSMT Rollup - Print

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3597]
Add printing for ssmt rollup

**Comment by koay9f** [comment]
holding back b/c of other roll up problem.

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9ee228ed-4091-4001-b91c-17d9d823a5c2)
Change "SSMT" to "Steam"
Get rid of "Assessment" for Pumps & Fans Summary
