### ISSUE TITLE
Report Rollup Printing

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3602]
Pie charts are breaking report rollup printing. 

I believe it is an issue with getPieWidth() and getBarWidth() calls from templates

Consider replacing pie charts with plotly?

**Comment by koay9f** [comment]
Mod pie is missing
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/e275761f-b65a-4017-8b94-64e1445228e9)

Missing in report also
