### ISSUE TITLE
Restructure output reports for Fan module 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#3623]
•	Generates a lot of pages.  The diagrams and graphs could be a little smaller. - koa - don't spend too much time on this one
•	Need to report which “Assessment” modifications are checked, and echo the input parameters for each modification, i.e. “Install VFD”, “more efficient fan”, etc.  - koa - @rmroot can we do this? what about assessments made in expert view? if we do it here we should do with with other assessments also
•	The input values should also be reported for all “System Setup” screens.  - koa what is missing?
* Match the name of the headers for "Input Data" match "System Setup" tabs

**Comment by rmroot** [comment]
Skip the first bullet point, taken care of in #3619 

Probably want to create second issue for the second bullet point for all assessments

**Comment by koay9f** [comment]
okay.  I'll make an issue for bullet 2

**Comment by AlexBotts** [comment]
@koay9f I think Ron's confusion on bullet 3 ("input values should...") is that the system setup pages have different names than what are shown on the report. All the input data is shown in the report. Can we change names to be consistent? 

1. Fluid = Base Gas Density
2. Fan = Fan setup
3. Motor = Fan Motor
