### ISSUE TITLE
Fan results update

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3646]
Update to fan density results taking suite issue #482 into account

BaseGasDensity is returning a lot more than just density now.

In Assessment & fan traverse calculator - Make results tab for Density page.

Hopefully in the order of the return object
Density of the gas in pounds per sqft, lb/scf
Absolute Pressure: in Hg
Saturated Humidity Ratio: unitless
Degree of Saturation: unitless
Humidity Ratio: unitless
Specific Volume: ft^3/lb
Enthalpy: btu/lb
Dew Point: F
Relative Humidity: unitless
Saturation Pressure: in Hg

return order:
return po, pIn, satW, satDeg, humW, specVol, enthalpy, dewPoint, rh, satPress

**Comment by causeyc** [comment]
Instead of the BaseGasDensity bindings returning just density (po), they are now returning a BaseGasDensity object with all ten of the above calculated quantities being accessible as object attributes.

**Comment by rmroot** [comment]
Suite updated in PR https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/489

**Comment by koay9f** [comment]
Sorry - Relative Humidity should be in (%).  Also, "Relative Humidity" is misspelled (Humdiity)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/03aa5b99-63c3-40ab-b0a4-f84aa0cf0153)
