### ISSUE TITLE
Explore-Opps PHAST - Disabled/Selected baseline value

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#3652]
Child issue of #3625

PHasT > Assessment > Explore-Opportunities
The user would like to see the baseline and modificaton values side by side

**Comment by koay9f** [comment]
Broken.
Lots of typescript errors
`hasOpportunity` undefined
`nativeElement` undefined
 ^ repeated a lot

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2cb46cb2-5290-4b56-8807-95e92515181f)

**Comment by koay9f** [comment]
Clicking "optimize Furnace Atmosphere Makeup System" doesn't give any fields to change

need a file w/ "Atmosphere" loss
[https://app.zenhub.com/files/80439269/ae8d79f1-6746-4bfe-b123-e677fb2dcd7a/download](https://app.zenhub.com/files/80439269/ae8d79f1-6746-4bfe-b123-e677fb2dcd7a/download)



Second loss off center
This was in an Electrotech>EAF>Cooling loss
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/169447f0-5421-4190-a30e-6bcb12e107a5)
