### ISSUE TITLE
Figure out if "cfm" should be "acfm" or "scfm" through out

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3729]
* Fans
* Compressed air
* random other places

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/80439269/410e0483-8a70-43c7-afcc-9c3b40f5f5e8/download](https://app.zenhub.com/files/80439269/410e0483-8a70-43c7-afcc-9c3b40f5f5e8/download)

**Comment by koay9f** [comment]
want to check that the calculations are still good.

**Comment by nbintertech** [comment]
Calculations looking good vs. results in the attached sheet.[https://app.zenhub.com/files/80439269/a203a05f-cac0-4fdc-85d9-85d325e7eb4d/download](https://app.zenhub.com/files/80439269/a203a05f-cac0-4fdc-85d9-85d325e7eb4d/download)

**Comment by koay9f** [comment]
one last thing, need to replicate in metric

if imperial ---> then metric
         psig ---> kPag
        psia ---> kPaa
        scfm---> Nm3/min
        acfm ---> m3/min

**Comment by koay9f** [comment]
One left

Receiver Tank > Metered Storage > Air Flow Req & Metered Flow control
