### ISSUE TITLE
Add Dew point (wet bulb*?) to Weather Calculator

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3741]
for issue #3698

Dew point needs to be calculated from the suite method calculateFanAttributes and added as a parameter option

**Comment by koay9f** [comment]
Per discussion with Tom - this should probably be wet-bulb.

I attached the original paper, a web calculator using this formula, and a spreadsheet calculator for you. 
https://www.omnicalculator.com/physics/wet-bulb#how-to-calculate-the-wet-bulb-temperature
 
Please note that this equation uses Celsius and RH% (1-100).  “This equation is valid for relative humidities between 5% and 99% and for air temperatures between -20C and 50C, except for situations having both low humidity and cold temperature. Over the valid range, errors in wet-bulb temperature range from 218 to 10.658C, with mean absolute error of less than 0.38C.”
 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/28fe1355-12a3-4697-8dec-ccd0f76782fc)
