### ISSUE TITLE
Cooling Tower Calculator UI

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3742]
[https://app.zenhub.com/files/80439269/63ef86b1-e29f-4a54-b56f-3725dc5a21c2/download](https://app.zenhub.com/files/80439269/63ef86b1-e29f-4a54-b56f-3725dc5a21c2/download)

Have an excel file with sample UI that will be in dropbox if needed

**Comment by nbintertech** [comment]
Can we post a link to the dropbox folder containing the excel file?  My free dropbox account doesn't allow me to view a folder unless it's a child directory less than 2GB (ORNL parent folder is 3).

**Comment by koay9f** [comment]
Also - forgot to put it in there
https://www.dropbox.com/home/AMO%20Tools/Chilled%20Water/Calculators/Cooling%20Tower

**Comment by koay9f** [comment]
Since we are in a bit of a hurry... these are placed in order of "to-do".  Any you think you can't get done, move to the new issue I'm making for Cooling Tower Updates

High priority
4.	For Evaporation Loss Correction Factor, can add “%” as the unit, just like drift loss factor?
5.	When toggling “Yes” between “No” for Drift Eliminator, the default values are not set correctly. When Yes, it should be 0.01% and when No, it should be 0.2%.

Low priority
Can we limit cooling load's result to just two decimal places? For example 13.00 MMBtu/h
Can we add one decimal place to the water consumption and water savings results for Baseline, Modification and Results Pane on the right? For example 230.1 kGal or 10.1 kGal

Very low priority
Order of Input fields
1.	Group 1: can we do this order: Water Flow Rate, Cooling Load, then Annual Operating hours? Typically, water flow rate is the easiest to get and operators and cooling load and operating hours are a little harder.
2.	Group 2: can we have Cycles of Concentration and Drift Eliminator.
3.	Group 3: can we have Evaporation Loss Correction Factor and Drift Loss Factor. Users do not have to change the values in this group. Maybe we can give it a different color? 
{Kristina note: I personally don't think Drift Loss Factor should be that far away from Drift Eliminator.  If you think you agree, maybe don't have 3 groups, and have it be "Cycles", "Drift Y/N", "Drift Factor", "Evap Factor".  I don't like the idea of "different color" either. }

**Comment by nbintertech** [comment]
Low priority fixes above, moved to 3790 for after-release to do.
