### ISSUE TITLE
Fan Traverse Tweaks 2

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3754]
May need to split this into multiple issues, but putting it here for now
More help text is needed - Ron will help (EDIT - about what?)

The results table should be in order of flow (left to right on the diagram)
EDIT: so the table should be 3a, 3b, 3c, 4, a, 2, 5 (5 might be before two if conditions are right)

~The planes don't have the right numbers on them (Ron will help and get back to us)~
EDIT: The planes numbers in ISO and AMCA are not the same. Add help text (see below)

EDIT: Ignore below this, moving TO DOs to a new comment

S-tube pitot tube types require a static pressure correction
* let users enter corrected static pressure (no change, but add some help texts)
* somewhere on the page, have a table the same size as the velocity pressure table where they can enter all the static pressures.  Final static pressure = average of all the entries)

redesign plane 3 pages.  the order is wonky (EDIT - how?)

"Velocity in the cross section would be helpful" - I think add a left hand side result with the velocity, if we can calc w/o calc-ing everything
In plane 3 - add help text for AMCA recommendations for number of traverse readings (EDIT - see below for functions in the suite)

**Comment by koay9f** [comment]
putting table order in a separate issue.

**Comment by koay9f** [comment]
Help Text Changes:

Plane 1 - is fine

Plane 2 -  ```Plane 2 is the fan outlet flange. If the evase was included in the Rated Fan Performance, Plane 2 can be located either upstream or downstream of Plane 5, however downstream is uncommon.```

Plane 3 - ```Plane 3 is the plane used for the Pitot-static traverse for purpose of determining flow rate. This plane is "Plane 5" in the ISO 5802 standard. [Picture]```

Plane 4 - ````Plane 4 is a plane upstream of fan used to establish fan inlet Plane Static Pressure. This plane is "Plane 3" in the ISO 5802 standard.````

Plane 5 - ```Plane 5 is a plane near the outlet used to establish fan outlet Plane 2 Static Pressure. If the evase was included in the Rated Fan Performance, this might be upstream or downstream of Plane 2.  This plane is "Plane 4" in the ISO 5802 standard. ```

**Comment by koay9f** [comment]
Motor Input Power (input and result) should be in kW

Change name of tab "Fan Shaft Power" to "Motor Power" (maybe)

**Comment by koay9f** [comment]
Total Issue To Do 
- [ ] Reorder fields
- [ ] Add "Calculate Static Pressure" functionality
- [ ] Add Plane 3 velocity result with other results (see first comment for math)
- [ ] Add help text to each plane
- [ ] Motor Input Power (input and result change to kW (fix any unit conversions, etc.)
- [ ] Change name of "Fan Shaft Power" tab to just "Power"
- [ ] Add "Fan Shaft Power" Result on page (bold left side result fine)
- [ ] Small edit to Power tab overview help text
- [ ] Results page, "power" should be "fan shaft power"




![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1da0c6da-8fc9-49a9-8c89-5de128ef5047)

**Comment by nbintertech** [comment]
Adding to checklist - doing some behind the scenes work to improve how we display units.
