### ISSUE TITLE
Fan Curve Problems

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3756]
The Example is wrong.  Use the values in the Fan Example Fan Curve Calc

If have static head/pressure, OpPt2's placement is off (is bad in both pumps and fans)
No static pressure = good
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2edcd4ef-ca8f-435a-8196-158a59d4eac1)

some static pressure = bad
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/10384589-025a-4bf1-b5e0-cded080888ed)

Would putting it in plotly help?

**Comment by koay9f** [comment]
This is not a "bug" but an engineering failure.  To best fix this, will need to redo how MEASUR determines the modification curve, the BL/mod section of the form, etc.

{text in brackets outline changes to algorithm}

1 – user enter pump/fan curve data (equation or data points) and system curve data {no changes}
2 – MEASUR calculates the operating point from the intersection of the two lines {no changes}
3 – User provides baseline Speed/Diameter {no change} **_and modification flow/head_** (since user’s won’t actually know what speed/diameter will get them to their new desired operating point)
4 - MEASUR calculates …
     A - new head/flow from the system curve { modificationHead = staticHead + Constant * power(modifcationFlow, systemLossExponent) or modificationFlow = power((modificationHead - staticHead)/Constant, - systemLossExponent) }
     B – new speed/diameter from affinity law {modificationSpeed = baselineSpeed * (modificationFlow/baselineFlow}
     C – new pump/fan curve from other affinity law {no change}
5 – MEASUR displays 
            A – mod speed/diameter
            B – new curve, with new operating point

**Comment by nbintertech** [comment]
Adding to the above - Modified condition form will go below the system-curve form (and is only visible when system-curve open)
