### ISSUE TITLE
Convert Calc graphs to plotly

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3757]
Would let us do a lot more.

**Comment by rmroot** [comment]
Break up into individual issue as you go

**Comment by nbintertech** [comment]
Graph updates status:

- [x] Pump > Specific Speed
- [x] Pump > Achievable Efficiency
- [x ] PH > O2 Enrichment
- [ ] PH > Efficiency Improvement (holding)
- [ ] Pump/Fan > System Curve (in-progress - moved to epic #3850 )
- [ ] SSMT > Steam Properties (in-progress)
- [ ] SSMT > Sat. Properties
- [ ] NEMA > Motor Performance
