### ISSUE TITLE
Performance Opportunities: Visualize tab

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3777]
Cannabilizing this issue to represent performance opps..

**High priority: Visualize tab**
- Lag introduced when hovering over chart. Sometimes up to 30 seconds. Issues exist with Plotly hovermode and scattergl on certain types of datasets. 
- Thread blocking and UI lag due to non-passive event listeners (some originate from Plotly, others MEASUR code)

Current ideas - changing hover settings depending on context, use plotly resampling library, downsampling, display a chunked date range selected by the user

**Comment by nbintertech** [comment]
Changing this to represent work needed for updatingthe cleaning/date mapping UI for multiple files.

**Comment by nbintertech** [comment]
If a user marks a column as date or time, it's use should be marked true and disabled.

**Comment by nbintertech** [comment]
Met with Alex to show UI changes that work around performance issues. 

- small datasets get no UI change
large datasets (multi-hundred thousands):
- adds user messaging to make workflow clear
- annotations on/off workflow
- time series ranges (reduces plotly rendering time)

First prototype
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/0ccb3eab-97fb-4dcb-bd0d-1c5f13252c0d)
