### ISSUE TITLE
Pump Inventory: Setup

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3798]
Create main setup tab with sub pages:
- Plant setup
- Departments
- Pump Properties
- Catalog

**Comment by koay9f** [comment]
Overall things look good.  There are some issues with units that I'm wanting to check up on but will need some minor tweaks

**Comment by nbintertech** [comment]
@koa I moved above comment to 6299. Feel free to close
