### ISSUE TITLE
Plotly Update for Pump Achievable Efficiency

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#3808]
Child of 3757

Update Pumps > Pump Curve to Plotly

**Comment by koay9f** [comment]
Flow rate can be higher than 5000 gpm, the flow rate values used in the graph should probably be based on the min/max's used in the validation.

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/357b84a5-9b91-42a1-9161-88d735be0a4a)
