### ISSUE TITLE
Generic and User Motor DB

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3816]
1 - change name of MotorData (not commented out) to GenericMotorData
2 - uncomment MotorData
3 - change the name of some of the GenericMotorData fields to match MotorData
4 - not sure the best way to do this, but maybe add one more field in MotorData that is "ID of the generic motor that you chose" this is never displayed, but maybe used to compare the user fields back to that generic DB.  Kind of like how PH has the charge materials DB and if you change a value it highlights green.  Do not need to compare motorEfficiency (as that will LIKELY) change, but if you change any of the others we should get some kind of warning that the motorEfficiency and other fields are likely no longer valid.

**Comment by rmroot** [comment]
Ignore the comment above. User Motor DB is going to be saved in MEASUR and "generic" is coming from the suite.

Use this issue for adding additional motor inventory fields to the user motor db.
