### ISSUE TITLE
O2 enrichment tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3831]
Change headers to "Baseline" and "Modification"
Maybe reformat to be like other BL vs Mod calcs (almost any calc from the TH) {this might be better as a separate issue}

Once the user hits "Plot" the BL is "locked" (unlocks when user hits "Reset data")
then the user can change various fields in the mod and "plot" more lines

New graphs:
y always =  Savings
Different X axis:
Combustion preheat temp, flue gas temp, O2 in flue gas
Maybe switch between them like steam properties (a dropdown near the X axis?) or different tabs?

**Comment by nbintertech** [comment]
Moved Baseline/Mod reformat to #3852
