### ISSUE TITLE
Flue Gas Standalone

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3837]

**Comment by nbintertech** [comment]
Please check that the loss result does NOT need conversion.

Both heatInput (heat delivered) and the result should be in users energyResultUnit
```let flueGasLosses = (1 - availableHeat) * flueGasData.flueGasByMass.heatInput;```

**Comment by koay9f** [comment]
Add field: "Fuel cost"

Need a results panel.
Results - like a TH:
BL Fuel use and Cost
Mod Fuel use and cost
 Fuel savings and Cost savings

**Comment by koay9f** [comment]
Order:
Op Hours
Fuel cost
Type of Fuel
Fuel

Other than that, it is good.  DO NOT need multiples like others I'm throwing back
