### ISSUE TITLE
Motor Inventory: Batch Analysis

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3847]
Add batch analysis logic to motor inventory

**Comment by rmroot** [comment]
the "operating hours" that is sent to the replace/rewind batch analsyis should actually be operatingHours*utilizationFactor
and Utilization Factor should probably default to 100% -kristina

**Comment by koay9f** [comment]
Batch graphs - 
"replace/rewind summary"
Fourth option is "NA".  I think this should be "Incomplete"

For the "Motor Energy Costs"
1 - make "Rewind" category = "Rewind when fail" (if this effects the other graphs & table that is fine)
2 - for each category have "Current", "Rewind", "Replace"
3 - Change name to "Motor Annual Energy Costs"
