### ISSUE TITLE
O2 enrichment Baseline/Mod updates

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#3852]
From #3831:

Change headers to "Baseline" and "Modification"
Maybe reformat to be like other BL vs Mod calcs (almost any calc from the TH) {this might be better as a separate issue}

Once the user hits "Plot" the BL is "locked" (unlocks when user hits "Reset data")
then the user can change various fields in the mod and "plot" more lines

**Comment by koay9f** [comment]
Looks great -

one unit conversion problem.  "Combustion Air Preheat Temp" is not converting when "generate example"
