### ISSUE TITLE
MotorInventory: Data field help

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3871]
help text for each data field in motor inventory...

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/31905969-7637-4169-90ea-bddc4d869795/download](https://app.zenhub.com/files/80439269/31905969-7637-4169-90ea-bddc4d869795/download)

**Comment by AlexBotts** [comment]
Reference Sheet is "UI Names and Groups"

[https://app.zenhub.com/files/80439269/168af0d3-57a7-491e-af44-434256eaef6e/download](https://app.zenhub.com/files/80439269/168af0d3-57a7-491e-af44-434256eaef6e/download)

![Help Text - Stator Slot Graphic.vsdx.jpg](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/5e22acb8-95d0-4618-9c5f-75366c9e2f68)
