### ISSUE TITLE
MotorInventory: Field Calculators

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3872]
1. Determine which fields can be calculated
2. Add modals for needed calcluators
3. Hook up to fields

**Comment by rmroot** [comment]
Lets get 1. done for this sprint 7/24/2020-8/7/2020

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/369dc40e-f337-4e46-a8ee-de17eeae9278/download](https://app.zenhub.com/files/80439269/369dc40e-f337-4e46-a8ee-de17eeae9278/download)

I'm pretty sure that these are all independent enough that we can use them as it.
