### ISSUE TITLE
Compressed Air Leak Survey in metric

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3873]
... is very broken.
has something to do with compressor specific power.  
1 - need to convert the number from 0.16 kW/scfm to ?? kW/(m3/min)
2 - I think that kW/m3/min is breaking things

**Comment by rmroot** [comment]
Additional: Need to convert the value set for specific power when a different compressor type is selected

**Comment by rmroot** [comment]
Updated:
- Conversions for calculations
- Conversions for defaults
- Conversions for specific power set by dropdown
- Utility cost set when changing utility type based off of settings

**Comment by koay9f** [comment]
The specific power conversion is not working.  Maybe it would be easier, instead of converting to have two separate tables.  I also noticed this was a problem in the TH compressor reduction calc
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0c9907c2-5df2-4622-820f-43af34a0b131)

All the conversions for the defaults are good
In "Estimate Method" the LABEL for the input in metric needs to be m3/min (not cfm)

All the conversions for the calculations are good (flow rates and such, since specific power isn't working.)

How ridiculous would it be to have 1 decimal place for flow rate / consumption if in metric?
