### ISSUE TITLE
Motor Master Detail Review

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#3890]
Fixes from Kristina and Alex motor master setup review

[https://app.zenhub.com/files/80439269/343c0ad1-fc49-4255-8d3b-373130fdf3a8/download](https://app.zenhub.com/files/80439269/343c0ad1-fc49-4255-8d3b-373130fdf3a8/download)

**Comment by rmroot** [comment]
Think I covered most everything. Can't hook up the settings until I am saving to a folder. Not sure what the problem with the "use existing" link is, working for me. May not have installed the motor db correctly or something

**Comment by koay9f** [comment]
metric - all powers (anything with hp) should be kW

sorry this has set so long.

**Comment by koay9f** [comment]
Missed Replacement Information > Modified Power (should be kW in metric)
