### ISSUE TITLE
CA - Connect Data Explorer to CA

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#3912]
Have some kind of "copy to assessment" button for the Day types tables in Data Explorer

Ask what type of assessment (right now only answer is CA)
Ask which assessment? (can it be sent to a new one or should it already be started?)

**Comment by koay9f** [comment]
It overall seems to be setup, but in System Profile, when have "use data explorer" selected, the UI is all there but it is not pulling profile data from system explorer
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3965b5f0-a900-4ba7-afb3-d50ab0035577)

**Comment by nbintertech** [comment]
Testing done by Alex looked good. No further work done
