### ISSUE TITLE
Pump/Fan Curve intersection accuracy

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#3998]
Intersections are still being approximated. This is because there is not always a coordinate pair created for the _actual_ intersection that is calculated. Maybe there is a way to take the regression curve equation and mathematically produce the intersection from that?

- Baseline intersection finds the two coordinates bookending where the intersection would be, and sums them, taking the average to get the intersection.  
Lines 398-443 in the below file. calculateBaselineIntersectionPoint()
https://github.com/ORNL-AMO/AMO-Tools-Desktop/blob/develop/src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts

- Modification intersection - Iterate over all coordinate pairs, calculating distance for each, taking the shortest distance, finding those points, and summing/averaging the coordinate pairs for greater accuracy.
lines 74-107 calculateModificationIntersectionPoint() https://github.com/ORNL-AMO/AMO-Tools-Desktop/blob/develop/src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts

**Comment by nbintertech** [comment]
Maybe also helpful:

Regression curves being built at https://github.com/ORNL-AMO/AMO-Tools-Desktop/blob/develop/src/app/calculator/system-and-equipment-curve/regression-equations.service.ts

**Comment by koay9f** [comment]
New library(ies)
https://nerdamer.com/quickstart.html

Baseline intersection:

shiny new function: nerdamer.solveEquations(systemEquation=baselineRegressionEquation,'flow');
then use the regression equation and that flow to find head (or pressure)

Mod intersection:

If: ![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8ad94bd5-e18a-4a67-a5ff-6b83b96c9d8f)

Find Head (or Pressure) using the regression curve and the user input

Would be interesting to see if nerdamer.solveEquations(systemEquation=modRegressionEquation,'flow');
get the same values


Else
nerdamer.solveEquations(userModHeadInput=baselineRegressionEquation,'flow');

Would be interesting to see if nerdamer.solveEquations(systemEquation=modRegressionEquation,'flow');
get the same values


nerdamer.solveEquations seems to put results in a string.
need to take out of string and put into an array? and then find the value that is both real and positive.  There *should* be only one.
Maybe find the one that is closest to

**Comment by nbintertech** [comment]
@koay9f Confirm can close, done as part of #6651
