### ISSUE TITLE
Think about help text only on focus

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4002]

**Comment by nbintertech** [comment]
PH - current field help text should stay on focusout. For general help text use accordion panel to show/hide. Stacked accordions when multiple general or long sections.
Steam - current field help text stays on focusout.
![mock.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/dad463de-1e82-4f6e-9ea3-52aa552a4752)
