### ISSUE TITLE
pump curve calculations

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4032]
The calculation for efficiency seems to be off

just from the info in this 

efficiency = (2503*137/3961.38) / 105.5 = 82.1% (close, but not quite right)
efficiency = (1980 * 88/3961.38) /53.8= 81.76% (not at all close)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6941c1a7-9303-435c-9b2a-d07f4ae52d8b)

This is probably also a problem with fans

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ccef3a02-37d3-4756-a062-cd3f075da4fe)

Problem with fans too
(106777*12*.98/6362) / 375.7 = 52.5%

**Comment by koay9f** [comment]
I think we might be using other pre-established calcs to do this.  It might be better to just calc efficiency from scratch...

**Comment by rmroot** [comment]
I believe I fixed it

Fan Example:
Baseline
((122204.5 * 15.52022792817098) / 6362) / 551.6810142185637 * 100 = 54.038537956488334
Mod
((106776.96710267215 * 11.974548884334125)/6362) / 375.71753965000676 * 100 = 53.49110971190879

Pump Example:
Baseline
((601 * 300.7223545630536) / 3961.38) / 47.380548804390436 * 100 = 96.29275086699634
Mod
((495.92013311148094 * 208.72399063190778) / 3961.38) / 27.28265830330387 * 100 = 95.77472662476609

**Comment by rmroot** [comment]
Should double check it works in both sets of units.. Not seeing any unit conversions

**Comment by koay9f** [comment]
pumps: (flow x head x specificGravity / 3961.38) / power
fans: (flow x pressure x compressibilityFactor /6362) / power

Unit conversions, pumps:
flow: WHATEVER --> gpm (gal/min)
head: WHATEVER --> ft
specificGravity - none needed
power: WHATEVER --> hp

Unit conversions, fans:
Flow: WHATEVER --> ft3/min
Pressure: WHATEVER --> inH2O
compressibilityFactor - none needed
power: WHATEVER --> hp

Metric example pumps power data set are not good numbers.  Change to these
35.6, 34.6, 34.6, 35.1, 35.9, 36 (going from 0 flow/top to bottom)

Metric "Generate Example" Efficiency results, Pumps:
137 m3/hr --> 603.2 ft
92 m --> 301.8 ft
1 = 1
35.3 kW (if implement the above change) --> 47.4
Efficiency = (603.2 x 301.8 x 1 / 3961.38)/47.4 = 96.3
** if you implement the above change to the example, then the efficiencies will be the same

Metric "Generate Example" Efficiency results, Fans:
57 m3/s --> 120776 ft3/min
3821 Pa -->15.4 inH2O
.98 = .98
400.2 kW --> 590.3
fans: (120776 x 15.4 x .98 /6362) / 590.3 = 48.5%
This will be a little different from imperial, I don't know why...

**Comment by rmroot** [comment]
Fan Example
400.2 kW  = 536 hp
Efficiency = 53.5%


Was actually a bug for pump power example in metric. Was using the same conversion as head, ft -> m.. fixed no using hp -> kW or whatever is selected.
