### ISSUE TITLE
PSAT Crashing

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4043]
From user:

I was using the PSAT portion of MEASUR and tried printing a copy of the output report so I could get a copy of the graphs for use elsewhere. However**, when printing a second time, the program crashes to the desktop**. Both times I am printing to PDF. Also, I've attached the PDF report generated. **I selected to print the Sankey diagram but it didn't show up in the PDF**.

To make things easier, I took videos:
https://youtu.be/8uolbNMrZgI
https://youtu.be/-WFAzNa45GE
https://youtu.be/HH-ucUemP-w

I used the "Xbox Game Bar" on my laptop to record, so the end of the video is the crash and the music is my Spotify. It didn't capture the print dialog but I did print to PDF twice. If you do need to hold onto the dataset**, I request you scrub the facility name.**

[https://app.zenhub.com/files/80439269/5f45faf5-318f-4397-828a-5df8a50c2f3f/download](https://app.zenhub.com/files/80439269/5f45faf5-318f-4397-828a-5df8a50c2f3f/download)

[https://app.zenhub.com/files/80439269/bd5208b4-2009-482e-abca-334f45d0812e/download](https://app.zenhub.com/files/80439269/bd5208b4-2009-482e-abca-334f45d0812e/download)

**Comment by koay9f** [comment]
Key points
* Printing twice causes crash
* Sankey doesn't print
* I removed facility name from data file

**Comment by nbintertech** [comment]
This bug happens when printing any assessment (or anything) twice if the app hasn't been restarted in-between. This is an Electron issue, reported to be fixed when we upgrade to 10.1.3. There are also black line artifacts being left on the generated pdf. No workaround for fixing these yet. 
I started cleaning up a few other printing related things (branch `issue-4043`).

**Comment by koay9f** [comment]
It does not look like this was fixed. 

Should we add this to known issues?

This was in the console
```npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! amo-tools-desktop@0.8.1-beta electron: `electron .`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the amo-tools-desktop@0.8.1-beta electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ak1\AppData\Roaming\npm-cache\_logs\2020-11-08T20_42_08_339Z-debug.log
/c/Program Files/nodejs/npm: line 34: 678876 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"
```

**Comment by nbintertech** [comment]
- Couldn't reproduce again, testing with all 4 example assessments. 
- No open Electron issues for printing bugs, though could be remnants of the previous fix?
- Possible node.js issue? My machine is running node 12.8, while bug appears using 10.13
