### ISSUE TITLE
WasteWater: Explore Opportunities

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4044]
Need list of potential opportunities we want to add to explore opportunities

**Comment by koay9f** [comment]
from manual

```Typical alternate scenarios that may be evaluated include, but are not limited to, process design conditions, use of alternative aeration equipment, use of alternative operating dissolved oxygen (DO) concentrations in the reactor, impact of changes in influent loadings as a result of a new industry, impact of turning aerators off to achieve denitrification, and so on.  ```




`Modify Aerator Performance`
DO Concentration

`Modify Aerator Power`
Aerator Operating Power

`Modify Aerator Speed`
Aerator Speed
