### ISSUE TITLE
ESC 31 Use of Economizer

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4060]
[https://app.zenhub.com/files/80439269/3cd3a270-1287-4de0-b412-4372f3d1bf75/download](https://app.zenhub.com/files/80439269/3cd3a270-1287-4de0-b412-4372f3d1bf75/download)

[https://app.zenhub.com/files/80439269/1ac76f11-11df-433d-96a6-1a8bce2cf8dc/download](https://app.zenhub.com/files/80439269/1ac76f11-11df-433d-96a6-1a8bce2cf8dc/download)

**Comment by nbintertech** [comment]
Waiting on confirmation of suite side functionality

**Comment by koay9f** [comment]
results not updating with user input
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5df5c4a1-22c2-4614-b763-fbb0c2da1a8e)
