### ISSUE TITLE
Waste Water first review

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4071]
In no particular order:

* Default values need to be in imperial and not switch when I close the assessment (also put this in the unit conversion issue)

Default values
* most should be blank
* The following should have the default values you currently have: the last 5 of activated sludge (cell debris, viomass yield, half-saturation, endogenous, max specific substrate)
* Electricity Cost - from folder

Validation
* Type of Aerator should set validation for Aerator speed
1- Mechanical Aerators (50% to 100% speed)
2- Positive Displacement Blowers (≥ 50% speed)
3- Centrifugal Blowers (typically can only run at  90% speed or greater)
Should be yellow validation - does not stop calculations if triggered

Activated Sludge subheaders
Make subheader for activated sludge
Field Data: Temp to flow rate
Concentrations: Inert VSS to MLSS
System Constants: last 5

Explore Opps - Either turn off page or put "Explore Opps works" there. it crashed when I clicked

Quick Results
RAS flow rate displays as 00.4 (WAS flow rate 00)
Add "Field OTR" as one of the "quick results"
Add units (from bio-tiger excel)

Full Results
Add units

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/87a75f30-90a4-4eb6-8745-0631f619f653)

Add "symbols" to these field names (ignore the time step and retention time on the list)

**Comment by koay9f** [comment]
The "Annual Cost" and "Annual Energy use" numbers are actually monthly, not annual.

Question for Tom:
Should we divide that by (30 x 24) hours/ month and have annual operating hours?
Or just x 12?

**Comment by rmroot** [comment]
moved defaults to own issue #4078

**Comment by rmroot** [comment]
Add SRT Days to results panel

**Comment by koay9f** [comment]
Results:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f26a58f0-4149-420f-b9b9-3da4b7061d14)
