### ISSUE TITLE
WasteWater: Default

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4078]
Check that values are in imperial

All are blank except the last 5 of activated sludge (cell debris, viomass yield, half-saturation, endogenous, max specific substrate)

**Comment by nbintertech** [comment]
Changed below defaults for issue #4184

> Hide "Time Step for SRT modeling", set to 0.5 days
> Set default "Max SRT" (above) to 100

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1a1431bd-0b2f-4bbf-95a5-7f629df6d530)

**Comment by koay9f** [comment]
New Assessment thinks that it can't move on
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/746cdac6-bc7d-4803-a43f-10a3e29c7285)
Does the hidden field (time step or something like that) have its default on? it should be 0.5

Other Defaults
Plant Control Point default = MLSS
O2 Transfer Coefficient Ratio (α) = 0.84
Saturation DO Concentration Ratio (β) = 0.92
Aerator Operating Time = 24
Aerator Speed = 100
Electricity Cost = Inherit from folder/Settings
