### ISSUE TITLE
WasteWater: Report Graphs

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4087]
add graphs to report graphs section of waste water report

**Comment by rmroot** [comment]
verify printing looks good

**Comment by koay9f** [comment]
report is broken (clicked on report via the analysis page)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f9187d87-1790-4430-b320-382c0f3941ba)
