### ISSUE TITLE
WasteWater: Diagram

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4092]
![image (6).png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/5f962f5b-c346-4c74-b962-504238ee723a)

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/076400b8-1c60-4c90-a1e8-ebdf5e62e7b8)

**Comment by koay9f** [comment]
going to be getting a new diagram soon.  When we do, pls remove both existing diagrams in favor of the new one.

**Comment by koay9f** [comment]
new diagram

![diagram.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/39045301-f3f1-4f2f-b899-60fac3c739d6)
