### ISSUE TITLE
Motor FLA change

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4115]
The warning we applied to FLA when "inputs to this calculated value have changed" are triggered too easily.

I sometime get it as soon as I calculate it. 

I assume this is done by the warning calculating what the value "should" be and seeing if they are equal? Maybe it is triggering b/c of rounding errors. 

Since users may enter their own values which are not exactly the same as the calculated maybe we do something like this

% difference = abs(user input - calculated value)/calculated value. if % difference is > 5%, display this yellow warning:

`Value is greater than X% different from estimated FLA (### A). Consider using the "Estimate Full-Load Amps" button.`

**Comment by koay9f** [comment]
Maybe too much accuracy in result.  maybe cut decimal places for all Amps

**Comment by nbintertech** [comment]
Also removing some unnecessary help min/max table in both fans/pumps

**Comment by koay9f** [comment]
Works great except -
Create a new assessment 
click the button for Estimate FLA
Change rated motor power (150 should work)
Field goes orange/yellow, but no message

Moving on to next page, returning and THEN fiddling, it works

**Comment by koay9f** [comment]
Still have to navigate away to make the message appear (highlights but no message)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/eb06c680-a759-4345-8bb3-6e2a579c918d)
