### ISSUE TITLE
Icons for PH calcs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4117]
Let me know if they still have the white background and I'll send them in slack

Flue Gas
![flueGas.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/664880b7-b61b-4a07-b33b-2925abb112de)

Wall
![wall.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8a3c0d54-ce89-4a0e-8de3-ce22ddd78feb)

Charge Materials
![chargeMaterials.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/80cd0268-ed79-4992-85bd-515dc3e1ab8b)

Hot Air Leak
![hotAirLeak.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b3fcf34d-fc93-4a43-b8bd-211e78678f88)

Fixture
![fixture.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d80e41f0-8091-41bb-bedf-6364d64df24c)

Opening
![opening.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1c792b2b-0b6f-48ed-ba8a-fd9ca9ddf2fa)

Cooling
![cooling.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/eed7e717-671a-455a-be8e-c64d65960f61)

Atmosphere
![atmosphere.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/14c69ea0-e357-440e-911b-09e689743c82)

**Comment by nbintertech** [comment]
Images downloaded - closing issue.
