### ISSUE TITLE
PH integration into TH

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4119]
Each calc (except flue gas) will have the following potential utilities:
* Natural Gas
* Electricity
* Other Fuel
* Steam

If Natural Gas or Other fuel - field called "Available Heat" with link to "Flue Gas Calc Modal"
If Electricity - field called "Thermal Efficiency"
If Steam - no field

Help Text for new field field
TO DO - Kristina
Steam - needs reminder that this is just for if steam is coming into your system as a utility
NG/Other fuel - note if steam is the thermal transfer medium, Available heat = boiler efficiency
Electricity - if hybrid furnace, should use "Other fuel" and estimate the total usage and unit costs based on weighted average of energy use

**Comment by nbintertech** [comment]
- [ ] Wall
- [ ] Flue Gas
