### ISSUE TITLE
Fan Curve Pressure Precsion

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4122]
In imperial (need to look at metric)
the pressure needs one decimal point (currently has none)

if we could sneak this in asap I would really really appreciate it

**Comment by nbintertech** [comment]
Also verified that we are not rounding off pressure values while building lines/coordinate arrays

**Comment by koay9f** [comment]
I'm really sorry, could we bump this to 2 decimal places?
