### ISSUE TITLE
Fan Traverse Barometric Pressure

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4124]
Each plane has a user input for barometric pressure.  I think it is "defaulted" to = what is input in the gas density page form.

Could we make it so that barometric pressure on these pages is a "result" (same number just "locked") unless they click a link that is "Change Plane Barometric Pressure", then it becomes a user input with the same default.

**Comment by rmroot** [comment]
"Variation in planar barometric pressure" : default "no"

**Comment by koay9f** [comment]
Looks good, but it is not saving when you move on to the next plane, so it is effectively stuck on "no"
