### ISSUE TITLE
Additional Units for Converter

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#413]

**Comment by rmroot** [comment]
**Frequency**
_Hertz (Hz)_ 
1 Hertz = 103 kilohertz (kHz) = 106 megahertz (MHz) = 109 gigahertz (GHz) = 1012 terahertz (THz)

**Force**
_Newton (N)_
1 Newton = 0.22481 Pound-force (lbf) 

**Pressure**
_Pascal (Pa)_
1 Pa = 10-5 Bar (bar) = 0.0075006 Torr (Torr) = 0.000145038 Pound-force per square inch (psi) = 9.8692 X 10-6 Standard atmosphere (atm)

**Mass**
_Kilogram (kg)_
1 kilogram = 1000 grams (g) = 0.001 metric ton (t) = 6.022 X 1026 atomic mass unit (u) = 0.06852 slug (sl) = 2.2046 pound (lb)

**Comment by koay9f** [comment]
FYI  a lot of these values are missing something to signify an exponent (1 Hertz = 10^3 kilohertz (kHz), etc.)
