### ISSUE TITLE
Validation updates to Charge Materials

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4132]
Changing some warnings to validation in new standalone calculator and assessment.

**Comment by koay9f** [comment]
Where did this one come from?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/105d19ba-0537-46e6-9f5b-99a811ad1ca7)

Are there any others that got added that I should double check my dumb-ness?
