### ISSUE TITLE
Missing TH Report Graphs

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4151]
From the user - "I just finished another virtual Treasure Hunt.  MEASUR is working well, one thing we found was that if on the report section we do a print and print to PDF, not all items show up on the PDF.  I attached the json file and the PDF I printed.  The graphs don’t show.  Might be a setting or something?  "

**Comment by rmroot** [comment]
Was not able to re-create. Wonder if they didn't click on the report graphs option..? Not sure, did clean up some of the printing styling.

**Comment by koay9f** [comment]
Yeah, just tested the user's data and it actually doesn't work.  I can't figure out what is special about their assessment.  Sorry for not including it originally. 

I made a folder on the dropbox (JSON files), the file has the issue number in it.
[https://app.zenhub.com/files/80439269/591bcc68-70dd-4286-a0d8-e1ace869ef09/download](https://app.zenhub.com/files/80439269/591bcc68-70dd-4286-a0d8-e1ace869ef09/download)

The "Red Star Cedar Rapids" assessment

I am getting this error.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/07b0cbcb-4bcd-45ee-8326-7dc73dc83603)
