### ISSUE TITLE
Mixed Opps getting added twice - chest only

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4156]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a2c0ed87-db88-4b38-9fb2-58146cf37c5d)

It is good on report
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9c93d4af-b78c-4301-a62f-09b06311e903)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b584c884-af3f-42cb-ae01-e2ab2f145f72)

**Comment by rmroot** [comment]
This came from the changes for 4098, need to figure out how we go about splitting the Implementation Costs for mixed opportunities

**Comment by koay9f** [comment]
Almost!!!

Additional savings from mixed opps / custom opps are not getting added to total annual savings
if you "turn off" a saving, the additional savings is still getting added to total savings

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/8b5dd11b-b494-42ad-93a2-4191a4bd2f64/download](https://app.zenhub.com/files/80439269/8b5dd11b-b494-42ad-93a2-4191a4bd2f64/download)

Still happening.
Each Opp has $1000 additional savings. If you turn off one of them, then the additional savings still says $3000.  Other savings behave properly.
