### ISSUE TITLE
WW Quick Report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4160]
~Maybe just these variables + the energy variables?~
EDIT: See comments, ignore this

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/69c0e003-0145-41ce-9a74-3c98ab7383ec)

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/59c6502e-9742-451e-9f1c-ed9960fe27d6)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/cf5b0af3-19e9-4bfa-b854-b9f679b45e79)

**Comment by koay9f** [comment]
All of the above looks great, I just have something to add:
If "Plant Control Point" == "SRT Days" then, show MLSS (calculated, not input) pls.

**Comment by nbintertech** [comment]
Need to setup observable for results or calculate differently -> Moving last comment to #4317
