### ISSUE TITLE
Audit Fan/Pump help text

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4166]
Remove any min/max tables that don't provide useful information (i.e. below). Expected min/max don't appear to be working. Double check anything else suspect.

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/8aa5cf40-179c-403f-83ca-88f6b097fe70)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/23fe0a0d-6142-4ac0-b0bd-925163710520)

**Comment by nbintertech** [comment]
The two above are examples, but I believe these min/max tables occur all over in the app. Since it's a larger issue feel free to work on this in pieces if needed.

**Comment by koay9f** [comment]
It's not really a table, but it still should be removed:
Pumps.  Full Load Amps (It is likely also in Fans, and anywhere else FLA is a field)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/621378d9-ca83-4fae-b6b9-ba191d685bc2)

This one can be removed also
Pumps Electricity Cost (may be in other places also)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6dbc800f-f515-41ab-97ce-a7200d372546)
