### ISSUE TITLE
Fan Traverse UI changes

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4168]
Parent issue #3754 

- Change/add Plane help text
- Power help text
- Fan shaft power naming
- Remove decimals from current/amps inputs and results

**Comment by koay9f** [comment]
Okay 99% of things got done. 

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2d40fa25-9b8c-42df-90a4-785cd0172602)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/804c9979-a1d1-4f3f-bc06-ea6df73bf2a0)
