### ISSUE TITLE
SVI calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4183]

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/820116bd-df35-458d-9c4e-c5447a8d7285/download](https://app.zenhub.com/files/80439269/820116bd-df35-458d-9c4e-c5447a8d7285/download)

**Comment by nbintertech** [comment]
Calculator finished for the moment... waiting on feedback from original calculator creator/expert.
