### ISSUE TITLE
WW SRT Graphs enhancement

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4186]
make it so you can change the X axis to be:
SRT days (current)
MLSS
something else?

**Comment by koay9f** [comment]
maybe make this another page
so there are two graphs pages, one with the SRT graphs, the other more like the graph page of data explorer?  
Have the full list of column names that can be either X or Y. multiple y's? is there a line?
Only scatter plots
annotations? full data explorer might be over kill...

**Comment by nbintertech** [comment]
Taking in a slightly different direction. Mark has this set up so we can use the same page and easily implement an X axis dropdown (in orange) next to the original Y dropdown (select graph)
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/05c088fd-1b7c-48c9-b802-e30a23502e03)

**Comment by koay9f** [comment]
Change the name of the header tab to just "Graphs"
Can we set the order of the dropdown menu for choosing the X-axis?
1 - SRT Days
2 - MLSS
then default order is fine for now
