### ISSUE TITLE
PH - Opening View Factor

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4198]
In both Assessment & Standalone

the Field "View Factor" is supposed to have a default value in it calculated from the dimensions (thickness, length/height/radius) and it is not showing up any more.

Maybe add a "Calculate View Factor" button if that would be better

**Comment by nbintertech** [comment]
No longer auto calculating from dimensions - adding the calculateViewFactor() button.
