### ISSUE TITLE
Process Heating - small issues

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4243]
Aux - why is duty cycle first. it should be last

EAF - Slag loss - Heat Capacity - in imperial the unit label is incorrect.  It says btu/scf-F and should be btu/lb-F

**Comment by nbintertech** [comment]
[https://app.zenhub.com/files/80439269/80f03584-4e23-465b-baf7-cebc1a850d69/download](https://app.zenhub.com/files/80439269/80f03584-4e23-465b-baf7-cebc1a850d69/download)

Attached example has EAF for testing. Import like below...
 ![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/347659bc-acb5-46ff-8d2e-57f7124503cc)

**Comment by JustinCIS** [comment]
Will need to clarify a few details before starting this one.  Will check in with @koay9f

**Comment by koay9f** [comment]
Slag loss screenshot:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/31dc637e-4e73-4118-9815-69bd41fe53b1)
