### ISSUE TITLE
Bleed Test Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4248]
As standalone as well as in assessment calculators tab

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/80439269/460060b1-6d78-41ed-b997-72f4bda9cf4c/download](https://app.zenhub.com/files/80439269/460060b1-6d78-41ed-b997-72f4bda9cf4c/download)

**Comment by nbintertech** [comment]
![image (14).png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/e1226063-da34-4f5a-9586-596d8d3d954d)

**Comment by koay9f** [comment]
something is off:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/af5daf5d-77cd-4695-9e3e-aa5a19597594)

should be 1148.4. It's off by a factor of 10, which is weird.  The math looks fine, so I'm not sure where the problem is.


Also tried this:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2616b489-ff95-40d2-95f0-9ca3e54cc389)

and answer should be 765

**Comment by koay9f** [comment]
Also
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/fad19dc7-92bf-4962-ae8e-c6dec2a10763)

**Comment by AlexBotts** [comment]
The math is missing a set of parenthesis atmospheric pressure should be in the denominator
 ![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/4c7e52dc-2b08-4eb8-959a-21e34d876287)

**Comment by AlexBotts** [comment]
Test values here:
[https://app.zenhub.com/files/80439269/fdd7bfa0-bc8f-4771-8db6-cac7b7899973/download](https://app.zenhub.com/files/80439269/fdd7bfa0-bc8f-4771-8db6-cac7b7899973/download)

**Comment by koay9f** [comment]
Math now matches old math and help text fixes are good.
BUT
Alex changed the math.  So math needs to be fixed again :(
