### ISSUE TITLE
Compressed Air Control Adjustment Factor

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4259]
Had to make it so that can only evaluate one compressor at a time and had to lock the compressor control type to the baseline.
Fix this

**Comment by nbintertech** [comment]
There is another possible bug or change to this - holding off until updated.

**Comment by koay9f** [comment]
Okay... 
For Compressed Air reduction Calculator AND Air leak Survey

baselineEnergy = # units x flowRate|BL x specificPower {This is good}
modEstEnergy =  # units x flowRate|mod x specificPower {This is good, but note the name change}
Savings = (baselineEnergy - modEstEnergy) x compressorControlAdjustment {This is good}
modificationEnergy = baselineEnergy - Savings {This is new!}

So yes, this means for the survey, if you have all the leaks checked, you will still have some mod energy. It sucks, but that's how the world works.

For Compressed Air reduction calculator:
For the mod, lock the compressor control AND compressor Type from BL to mod. If possible, don't even show it

For multiple compressors, each one should have that calculation done, but they are locked in pairs (BL & mod)

Would it be better if the suite were to handle the BL, mod and savings calcs or do it in the desktop?

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0c5f4bc4-cc7a-472d-9e49-a577d7bd64e8)
Baseline Results looks good and UI looks good but the mod and savings calculations are incorrect.

for compressor 1
baselineEnergy = # units x flowRate|BL x specificPower x OpHrs = 1 x 100 x 100/100 x 1000 = 100,000
modEstEnergy = # units x flowRate|mod x specificPower x OpHrs = 1 x 50 x 100/100 x 1000 = 50,000
Savings = (baselineEnergy - modEstEnergy) x compressorControlAdjustment = (100,000 - 5,000) x 50% = 25,000
modificationEnergy = baselineEnergy - Savings = 100,000 - 25,000 = 75,000

for compressor 2
baselineEnergy = # units x flowRate|BL x specificPower x OpHrs = 1 x 50 x 10/100 x 1000 = 5,000
modEstEnergy = # units x flowRate|mod x specificPower x OpHrs = 1 x 25 x 10/100 x 1000 = 2,500
Savings = (baselineEnergy - modEstEnergy) x compressorControlAdjustment = (100,000 - 5,000) x 100% = 2,500
modificationEnergy = baselineEnergy - Savings = 5,000 - 2,500 = 2,500

Baseline displayed: 100,000 + 5,000 = 105,000 (correct!)
Modification displayed: 75,000 + 2,500 = 77,500
Savings = 25,000 + 2,500 = 27,500

**Comment by koay9f** [comment]
This calc change also applies to the Leak survey:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a26061cf-9219-4c8e-984b-932480e73f1e)

baselineEnergy = # units x flowRate|BL x specificPower x OpHours = 1 x 10 x 100/100 x 1000 = 10,000
modEstEnergy = # units x flowRate|mod x specificPower x OpHours = 1 x 0 x 100/100 x 1000 = 0
Savings = (baselineEnergy - modEstEnergy) x compressorControlAdjustment = (10,000 - 0) x 50% = 5,000
modificationEnergy = baselineEnergy - Savings = 10,000 - 5,000 = 5,000
