### ISSUE TITLE
WW Mod Automation - DO

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4261]
For the DO field in Explore Opps or Expert View have an auto calculate button.

DOtemp = DO {user input}
calculate things
O2percDifference = (Total O2 Required - Total O2 Supplied)/ Total O2 Supplied
if O2percDifference > 0.01 then {if this has too many iterations then we can adjust}
DOtemp = DOtemp - 0.1 {if this takes too much computation time then we can adjust}

else, return DOtemp & results

I'm a bit worried that this will run the entire table generation each time.  Is there a way we can break up the calculations so that is not the case?
Or can we edit the calculations so that the iteration is handled on the desktop side and the suite just calculates it via an input of SRT?
If a revamp of the suite is necessary, then this can get pushed back.

**Comment by nbintertech** [comment]
requires #4185

**Comment by koay9f** [comment]
I think ideally, we would also have similar auto calculations for
Aerator Operating Time
Aerator Speed

Same idea, if O2percDifference > 0.01 then change time or speed (depending on which you click)


Min values for each auto calculation
DO - min value = zero
Time - min value = 16
Speed - min value = already has a warning for this (depends on Type of Aerator)

Also, if as you reduce any of these, the % difference goes up, stop the calcs and return the first value

**Comment by koay9f** [comment]
Warning for if Operating Hours < 16 does not show up on Explore Opps.

Sometimes Calculate DO button doesn't always work.  Not sure what causes it.   


Using Example

Calculated this fine
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2f21ffee-f627-4395-840d-aa55e180dd40)
Calculated this fine
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3182ddec-f338-4ee5-affc-b0bd008fa8ff)
Did not like this
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6dda0f60-ec13-46d7-abea-fb51e2ad98d8)

Looks like it is b/c it would make DO <0, but without slowly decreasing speed and clicking calculate, I don't know that. May need to brainstorm ways to generate errors

**Comment by koay9f** [comment]
This can go down to ~ 80% (that would generate an error on speed, but it should be possible and I'm getting the "cannot improve" error
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/dfccca47-5452-41ad-b904-18e627cc4a6a)
From WW example

You should be able to either reduce Oph hours to 17 or speed to ~80%
Did manually, but it is saying that it cannot optimize
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9f40b611-a09b-4a36-b0de-1f9f1c6f8433)

**Comment by rmroot** [comment]
I am disabling links when a modification is invalid because optimization cannot be done

Changed verbage to "Optimize ... "

Should have calculations fixed
