### ISSUE TITLE
Waste Water Input Summary Report

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4306]
<s>Inputs have changed, need to update waste water input summary in the report.

No longer have MAX SRT
Added Plant Control Point
SRT
Do you have an anoxic zone with returned mixed liquor from the aerobic zone?

SRT/MLSSpar are displayed based on Control Point selection
make sure there isn't anything else,</s>

**Comment by nbintertech** [comment]
I've already done the above work on branch  `issue-4306`. Go ahead and pull that branch to work from. 

We need to update the labels on Waste Water report --> input summary result page to match the form field labels on the Activated Sludge and Aerator Performance tabs found in the Waste Water assessment --> Modify Conditions tab.

**Comment by koay9f** [comment]
No data for "Do you have an anoxic zone..."
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bffe2473-ce88-487e-b7f5-e857f7e93b1e)

**Comment by rmroot** [comment]
Missing Aerator and Type Aerators
