### ISSUE TITLE
New Energy Source

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#431]
![energy source](https://user-images.githubusercontent.com/25389736/27752967-95255f16-5db1-11e7-9302-f2ca5233d142.png)

Screen shot for Energy Source Tab

**Comment by pshires** [comment]
@koay9f do you know if this is complete?

**Comment by koay9f** [comment]
I think the functionality is there... mostly?
This was mostly to have the screen shot.  Is there somewhere else to put it?
