### ISSUE TITLE
Fan Fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4328]
@nbintertech - feel free to break this up and assign part of it to others.  Mark may need to help with some of it.

#4332
<s>Fan Assessment: 
- Add Red Warning (stop calcs) if outlet pressure is higher than the inlet pressure 
- Switch to Yellow Warning: when the outlet pressure is negative 
- Switch to Yellow Warning: when the inlet pressure is positive
- Fluid: if Type == "Other Gas", don't show relative specific gravity - hide for now, may rework this later
- Calculators: don't show traverse in assessment calculators</s>

#4331
<s>Report:
- Input Summary - Motor Power (and probably Motor Current) has a "input" for the mods, should just be "- - - " for mods.  Probably also true for pumps.
- Input Summary - if use "known efficiency" do "- - - " for fan type
- Input Summary - always says fan type says "radial tip"
</s>

#4364
Traverse:
<s>
- Remove defaults for new assessment. everything should be blank unless it is based on a number from within the assessment (density, barometric pressure, and some others)
- Calculate Static Pressure: default's in table should = 0
- Calculate Static Pressure: can we remember the user's input in case they want to switch back? Other ideas?
- Calculate State Pressure: order of this page is weird, move static pressure & its table to before "INPUT PITOT TUBE VELOCITY PRESSURE READINGS"
- change name of "INPUT PITOT TUBE VELOCITY PRESSURE READINGS" to just "PITOT TUBE VELOCITY PRESSURE READINGS" and make the font size the same as other headers 
- Barometic pressure displayed =/= input on page i (all plane pages)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d8a7e7a3-40cb-4b9d-892e-c5971186dbe4)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8a8f4e6c-60ce-4dde-84c8-ccd60b1bfe4d)

- **BIG: user fields for static pressure in planes 4 & 5 need to return**
- After using the "Estimate Flow and Pressures" button, the outlet pressure field is mistakenly populated by the value for the Inlet pressure variable {EDIT: not sure this is the case - I think it may have something to do with the last issue, check once static pressure 4 & 5 are back}
- Plane 3 velocity - where is number coming from and why does it not match table? (table is closer to correct)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/cb221f6d-004b-4681-884c-449933ac6e22)
- ~Planar density: suite says for the planar density calculation, if nothing is entered into base gas density (such as in the modal where it does not exist) it uses data from plane 3a.  So why is there a correction from what is entered in tab i?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/18936b0b-f33f-467b-b475-061f17fcf919)
(can see in above pics that in tab i density = 0.044, in table it is 0.0397588)~

- Plane 3 static pressure table always has 10 columns
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4d1baa45-0f09-4e2d-a0cf-2711646210f4)
- Plane 3 static pressure: can you calculate average with NAs removed? and not have error on blank (maybe just a warning)

- Gas Density Psychrometric table results - show dry bulb in table </s>

**Comment by nbintertech** [comment]
Don't need for reference anymore - closing to cleanup board
