### ISSUE TITLE
Fan sub-reports

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4329]
would be nice if the psychrometric table and traverse calculator results could make it into report

**Comment by nbintertech** [comment]
In the fan assessment (fsat) we have a psychrometric results table:
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/635afb8a-68e4-413d-8320-1482d12584c7)

and under the Field Data tab > calculate flow and pressures modal there is a traverse plane result table:
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/992d6fc9-7828-4024-8516-73b4223e39d0)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/4e3a0522-2127-4500-8e17-471d2eb21fd2)

We want to add the psychrometric results table and the traverse calculator results to the report section under a new tab (called something like 'Other results'). This will show up in the rollup report as well.
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/9c5499ce-4bdd-4f85-85ed-e52b6530fd2c)

Start by looking at fsat-report.component, gas-density-results.component, calculate-flow-pressure.compont, app-help-and-results-panel (in fans)
