### ISSUE TITLE
Fan Report changes

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4331]
parent #4328

Input Summary - Motor Power (and probably Motor Current) has a "input" for the mods, should just be "- - - " for mods. Probably also true for pumps.
Input Summary - if use "known efficiency" do "- - - " for fan type
~Input Summary - always says fan type says "radial tip"~

**Comment by koay9f** [comment]
If use "Known Fan Efficiency" Not sure if that is enough of a trigger, it might have to be "did not click optimize"
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7d514366-e3f5-42a8-8212-7bff104a5c31)

This is what "I Know the Fan Eff" or "not optimizing" looks like
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d39a259c-40da-403a-88eb-868864aaf045)
This is what "optimizing" looks like
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/379f4731-f26f-4d98-8e40-b98305483d2d)

**Comment by koay9f** [comment]
For all modifications, "Load Estimation Method" and "Motor Power" (or "Motor Current") should be " - - " 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/e97c438b-eed6-4098-8af7-ef945eb689cb)

**Comment by koay9f** [comment]
Ignore the third point
