### ISSUE TITLE
Fan Assessment Changes

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4332]
parent #4328
Fan Assessment:

Validations
Add Red Warning (stop calcs) if outlet pressure is higher than the inlet pressure
Switch to Yellow Warning: when the outlet pressure is negative
Switch to Yellow Warning: when the inlet pressure is positive
Old: ![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bf9cffd9-78ec-488f-8c4b-e93ff50c737f)
New: ![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/65c68cb2-6b3d-4465-8f3e-b6fece24a01d)

Flow Rate: must be greater than zero (exclusive). Needs message - look at other non-zero messages for text
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6eabda1d-48bd-4b1f-bd28-0a50f70d0095)

Fluid: if Type == "Other Gas", don't show relative specific gravity - hide for now, may rework this later
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/20c89b0e-36eb-47a3-b92c-252ae62aa319)

Calculators: don't show traverse in assessment calculators {this might be in another issue}
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/35b24c2a-59cd-4fb6-8902-2e759190458a)

**Comment by koay9f** [comment]
The switch to yellow warning for Inlet didn't seem to work correctly
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f2cef85a-0097-43b3-bf6a-7e350b6ab39d)

The red for P out < P in is good
The yellow for P out < 0 is good
Everything else for this issue is good.
