### ISSUE TITLE
Min/max validation Pump RPM for Belt Drive

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#434]
Need Values

**Comment by koay9f** [comment]
Min = 1
Max = n/a (there is no upper limit)

**Comment by koay9f** [comment]
The above values are for checkPumpRpm
if Belt Drive
min = 1; max = no max
if Direct Drive
min = 540; max = 3960

The help text should probably also be changed to reflect this.
