### ISSUE TITLE
Fan & Pump Defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4347]
Fans
Fluid Page
Change the fan `Fluid` page's defaults to this
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/377024b5-28da-48da-b186-8597814b4936)

Also
Validation for Relative Humidity should be >= zero (inclusive not exclusive)

Fan Page
Fan Speed default = blank

Fan Field Data, 
Input & Output Pressure modals
All fields blank {if this messes something up on the main page let me know}

Fans & Pumps
Motor Page
Rated Motor Power = blank
Motor RPM = blank

**Comment by koay9f** [comment]
Defaults for Traverse "Calculate Flow and Pressures"
[1] Fan Basics
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0ec633ac-ae18-4059-a665-11efe0872360)
Corrected Fan Speed = Fan Speed from Asessement
Corrected Density = Density from Assessment
Corrected Baro Pressure = Baro Pressure from assessment
Rated... includes Evase = `No`
Outlet Static ... = `Downstream`
Number ... = 2


[2] Traverse Data
[i]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c9aeb694-bf48-461b-bb48-517376e480b5)
[1] & [4]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/53640a31-b532-46a7-a7e7-db25559d30ce)
Height, Width, # inlet boxes, Dry Bulb temp = All `blank` 

[2] & [5]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6d9db937-37ce-41a7-b0e4-acb0a0030aac)
Height, Width, Dry Bulb temp all = All `blank`

[3a], [3b], [3c]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4520c403-6fae-47a1-b7ff-361d4035ab84)
Height, Width, Dry Bulb temp all = All `blank`
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/363ace9d-414f-4420-b275-3033106058be)
Pilot Tube Type = `Standard`, 
... Coefficient = Default there is good
Num. Traverse holes = 1
Num. Insertion Points = 1
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2b505f28-1085-4c7d-a23b-5c0a74dc8743)
Velocity Pressure Readings = All `Blank`
Static Pressure = `Blank`
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0898cac8-8cb0-4aab-a012-50fea0b3c025)
Static Pressure Readings = All `Blank`
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6c2a5fb3-dcff-48cc-afba-17e24df9b9c0)

**Comment by nbintertech** [comment]
Need to look at this again. Removing defaults in fan traverse modal revealed some buggy behavior. Look at static pressure validation. Some other validation may be off.

**Comment by koay9f** [comment]
Sorry, the fan fluid page, Relative Humidity should == 0 but buggy bug #4404 is making it crash

Calc Flow & Pressures Modal 
Fan Basics page > Number of Traverse Planes = 1

My notes were not great, but [4] and [5] are also supposed to be blank like [1] and [2]
And for both [1] and [4], Number of Inlet Boxes = 1

[3] - Pitot Tube Coefficient = 1 (sorry I assumed it would pick up the value for the choice of "standard" I was dumb)

**Comment by koay9f** [comment]
Everything above this is good
I missed some in pumps (if this doesn't get done by release - not end of world)
Field Data > Head
Field Data > Calculate Head
When first open should be in the "blank" state (same as reset data)

Change defaults/"reset data" so that
Fluid Specific Gravity = 1
Flow Rate = Flow rate in Field Data

Now that the suite is fixed, can change the Fan > Fluid > Relative humidity to = 0
