### ISSUE TITLE
Placement of Cost & opHours

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4349]
some assessments have the cost and opHours in an "Operations" page.  This is good. make others like this

**Comment by koay9f** [comment]
Also Implementation costs


For wastewater - the two "modeling conditions" - if that won't screw things up. (SRT might, so it can stay if it needs to)

Start with Pumps.  Then do fans.  If those both work, we'll talk about wastewater

**Comment by nbintertech** [comment]
Decent sized issue, moved waste water work to 4807
