### ISSUE TITLE
Fan CFM

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4352]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b98484f4-fe17-4fe2-b227-8b67d8094199)

Where else does it need to be ACFM :D

**Comment by AlexBotts** [comment]
Please see attached doc for locations of issue. All "ft3/min" should be replaced with "acfm"
[https://app.zenhub.com/files/80439269/d56147f1-3348-414c-a877-da63cf0fe8d2/download](https://app.zenhub.com/files/80439269/d56147f1-3348-414c-a877-da63cf0fe8d2/download)
