### ISSUE TITLE
WW on home page

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4365]
Need icon

**Comment by koay9f** [comment]
![wastewater-icon.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/79aac57e-bec1-4edf-97ae-cf6023f9f1b6)![ww small icon.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/77d42c4e-64d8-4c81-8845-d184fde73194)

**Comment by nbintertech** [comment]
@koay9f Are we replacing the existing water drop or should these go elsewhere?

**Comment by koay9f** [comment]
Me being dumb again
Italic sub header text needed
"Based on the Bio-Tiger Model for Wastewater Treatment Plants"
