### ISSUE TITLE
Updates to ESC 7 and Air Heating

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4376]
- Move results to results-panel table
- Add fuel cost input, with energy savings output

Note: Do this for all future ESC's

**Comment by koay9f** [comment]
No results.  Has error.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c7932efc-8f8c-49d5-bebd-92c69fb2da11)

**Comment by nbintertech** [comment]
This should work with updated suite. Moving to NV
