### ISSUE TITLE
New PH calcs small tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4402]
Air heating using flue 
Exhaust gas temp leaving HX result has a $ in it

Heat Cascading
Heat transfered - recovered ... result has a $ in it

Fuel Heating Value should have a default based on the fuel type. It is available from the fuel composition (drop down or "add new fuel"
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/acdc3abb-4ba6-438e-8ba1-b8ca5b388311)

**Comment by nbintertech** [comment]
Changed to populate FHV with the default typical natural gas (1032.44). Needs #4406 to complete/allow user to change selection.
