### ISSUE TITLE
MEASUR Process Cooling Calc Overview

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4422]
Ideally, we would like these to run two ways
1 - single instant (fill out all the forms and get a single answer)
2 - annual aggregate: use bin analysis ("weather calculator" - lump together all the hours in the year that is is between two temps/ humiditys/etc and use the "bin range" to fill out the form (40 - 50 F --> T = 45 & the hours that are in that range = ophrs) then sum those all up to get annual savings

Right now the example calculators and I think the algo (and I fairly certain the C++) all work in the spirit of # 1.  
IDK if we want to do the aggregating in the suite (as another "calculator" that gets called) or in the desktop. Depends on computation time and ease of developing.

Also, the Weather binning calculator needs to be working

Anyway, something to think about and discuss

**Comment by nbintertech** [comment]
Remote branches updated to current develop. Waiting on help text, icons, etc before PR.

**Comment by nbintertech** [comment]
Ready for verification, branch `cooling-and-weather`

**Comment by koay9f** [comment]
can you make an installer in Mac so peoples can test?

**Comment by nbintertech** [comment]
@rmroot is handling for #5229
