### ISSUE TITLE
Remove ngx-electron

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4425]
Create API for calling electron in ipcMAIN

use preinstall script to load addons

This is a security enhancement (done in VERIFI already)

**Comment by nbintertech** [comment]
These changes are required to update to latest

**Comment by nbintertech** [comment]
I will verify and close when Dev/web are finished. Was able to get ngx-electron removed and service added - could not update node version or electron/electron-builder. #6174 has more info

**Comment by nbintertech** [comment]
Need to get develop building on this. Alternate and possibly better solution - look at steps needed to finally go 'full web'

**Comment by nbintertech** [comment]
This should be ready to implement - develop branch can now be installed/built under node v16

**Comment by nbintertech** [comment]
This can get closed when wasm branch is merged in

**Comment by nbintertech** [comment]
Closing - done in 6259 (wasm-transition-updates)
