### ISSUE TITLE
Rollup report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4435]
Bottom chart with BL & mods - need a total row

**Comment by koay9f** [comment]
How to get to the issue:
Dashboard: Click on one of the folders on the left, click "select all assessments", click generate report
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/739fc666-9de6-47a6-8ddc-63fcc165eedf)

Roll up report:
Click on one of the top cards
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/173a2f20-e7d3-4266-a2fc-9a82feb3ca67)

Scroll down to the bottom report - look for the table under the bar chart

Pumps & Fans & Steam & Wastewater are similar:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d6a4fdb2-84d1-4ce5-b2d6-56ac37ef7bec)

Treasure hunt is different and won't need this.

Process Heating will be a bit weird.  No total for "Energy Intensity" or "Available Heat"
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b302955b-387f-4d97-b970-95a9361c7a66)

**Comment by rmroot** [comment]
In rollup-summary-table.component

create variables for  Total Baseline Energy Use, Total Modification Energy Use, Total Baseline Cost, Total Modification Cost, Total Cost Savings, Total Implementation Cost and Total Payback Period.

Iterate through tableData object onInit and sum the respective values.

Total Payback = Total Implementation Cost / Total Cost Savings


Will also need to do similar addition to phast-rollup-furnace-summary-table skipping Energy Intensity and Available Heat
