### ISSUE TITLE
Compare two existing pump/fan

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4460]
In expert view
A question/radial button:
Compare two existing pumps/fans or what-if scenario?
O Two existing pumps/fans (have field data for both)
O What-if scenario

If What-if scenario - algorithm as is
If Two existing - use the baseline algorithm twice

**Comment by koay9f** [comment]
When create first scenario, no way to specify that it is a "compare two pumps" scenario:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b609e37d-2732-4408-957f-d77e4d6c3e08)

Showing energy/cost savings even if no changes have been made
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4dd63475-7807-48ae-92d2-8805c19c52e7)
Might just be better in this case to not show any savings between the two pumps... I'll get back to you.

**Comment by koay9f** [comment]
Visually, looking good.
Baseline results seems to be copying Scenario 1 instead of using the baseline though
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/104f91d1-9207-45de-9526-fa9d92440349)

I checked, it is not doing this in whatif

Also something weird going on with the saving...
looks like it might just be motor power, Load Estimation Method and Motor Current
(I'm guessing it is b/c before, those fields weren't in the assessment, so it just isn't saving them yet)
![issue4460.gif](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/174fefec-76e1-4426-b1fb-ca8ed521096b)


Weirdly, fan's looks like it is doing okay

**Comment by nbintertech** [comment]
@rhernandez-intertech pull from branch `issue-4460-c` to look at this. I took care of the basellne copying scenario 1 issue. Please investigate the saving/badge issue.
