### ISSUE TITLE
weird blank space in dashboard

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4463]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/09be48ed-93a6-4446-912c-0ffe3db3b196)

[https://app.zenhub.com/files/80439269/d9400d5f-946b-451e-bdef-20cf49bb7a58/download](https://app.zenhub.com/files/80439269/d9400d5f-946b-451e-bdef-20cf49bb7a58/download)

**Comment by nbintertech** [comment]
Assessment export/import attached above
> after going into the assessments, they moved back to the right spots, so I'm guessing it has something to do with the sorting by "last updated"
