### ISSUE TITLE
TH Integration - Waste Heat for Absorption

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4480]

**Comment by nbintertech** [comment]
Please check labels and energy units on fuel/energy cost, available heat, and results. This calculator started a bit different than the others.

**Comment by koay9f** [comment]
This one needs to get rolled back to what it was before I think
It is another one with a self contained Baseline/mod/savings. (no side by side or anything like that)

It is an electricity calculator (not fuel, other fuel or steam)

for results, have a table at the top of the results page that has everything but the last two lines.

Then have the normal BL table, Mod table and savings table based on these:
Baseline Electricity = Annual Energy Savings
Mod Electricity = 0
Savings = Annual Energy Savings

**Comment by nbintertech** [comment]
Removing calculator from Treasure hunt for now...

**Comment by koay9f** [comment]
Electricity Cost should be filled via Facility Basics

same as others
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/aa47f759-9727-4dff-9353-b96d81d7c5a2)
