### ISSUE TITLE
TH Integration - Air-heating

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4485]
Air Heating:
No BL vs. Mod inputs
Results:
Baseline = Ave. Firing Rate x Operating Hours
Mod = Ave. Firing Rate x Operating Hours - savings
savings = savings

**Comment by koay9f** [comment]
Really close

Flue Gas side
Field order should be
Annual Operating Hours
Utility type
Type of fuel
Fuel
... everything else is good
defaults are good

Math connecting to cost savings is screwy
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f70de3bd-cd18-4fd7-80d5-c8e088830232)
The PERCENT savings is correct but the annual savings is not
Looks like stuff in report is correct.  just the treasure hunt quick report is screwy

I used generate example for the NG one and generate example but changed to "Other Fuel" and "Coke Oven Gas"
