### ISSUE TITLE
TH Integration - Heat Cascading

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4486]
Heat cascade:
May setup Primary and Secondary process side-by-side, but nothing good for inputs for "Baseline" vs. "Modification"

For results:
Maybe current results can be on the right side somewhere, or just skip most of them.
Suite issue in to fix something and add an "hourlySavings"

Annual BL energy = firingRate2 x hours2
mod energy = firingRate2 x hours2 - energySavings
savings = energySavings

**Comment by koay9f** [comment]
I'm dumb.
This needs to be fixed in standalone & TH

Annual BL energy = firingRate1 x hours1 + firingRate2 x hours2
mod energy = firingRate1 x hours1 + firingRate2 x hours2 - energySavings
savings = energySavings
