### ISSUE TITLE
CompressedAir: Profile Compressor Ordering

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4499]
get compressor ordering setup with user population and automatic ordering

**Comment by koay9f** [comment]
Top row is blank 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/44fab076-4ec0-4aa7-a56b-8e400988f9c9)
(There is a sequencer - just happened when initialized page)
Everything else is good.  Alex says "Good Job Mark. Good Job"
