### ISSUE TITLE
CompressedAir: Performance Points

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4502]
Calculate performance points, apply defaults logic

**Comment by koay9f** [comment]
lube injected load/unload is off.  Alex is looking

**Comment by AlexBotts** [comment]
- Lube injected > Load/unload > Performance points > Max full flow power is not correct 

Example: Comp ID 629 Max full flow power should be 90.1 kW

**Comment by AlexBotts** [comment]
- New Installer (0.3.2) graph is not correct for lube injected load/unload comps

**Comment by AlexBotts** [comment]
All Load/unload (non cent) are off for max full flow power
