### ISSUE TITLE
TH new calc Icons

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4525]
Need to do something for the TH icons. Right now all the new ones are on "white" backgrounds.

**Comment by nbintertech** [comment]
@koay9f  What did we do originally? For existing TH icons the circle is part of the image. It will be FAR easier to continue down that road. We could achieve a circle using html/css, but it will probably never match the lighting embellishment/shadowing from whichever image editor was used on the originals.

**Comment by rhernandez-intertech** [comment]
For this issue I made the backgrounds of calc icon's in TH circles that did not have backgrounds
