### ISSUE TITLE
Pumps - create new assessment didn't work

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4536]
I don't know what happened...

**Comment by nbintertech** [comment]
Couldn't reproduce this crash so far. 

Steps to reproduce -> create a new pump assessment, fill out system setup until Field Data tab, open Calculate Head modal and input some data. Maybe have to play more with that last step.

**Comment by shivasaurus** [comment]
Couldn't reproduce this bug either.
