### ISSUE TITLE
Modal dialog and composition in the help section of the flue gas analysis screen

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#457]
Flue gas composition information should appear in the help section. In addition, the user should be able to modify the composition for the single assessment.

**Comment by koay9f** [comment]
Here's the field help text.  Still need to write help text for the whole modal, but want to have some conversations first.
[Flue Gas Help Text.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1146190/Flue.Gas.Help.Text.docx)
