### ISSUE TITLE
Heat Cascade Heating Value

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4582]
for both stand alone and TH

1- change name to "Higher Heating Value"
2 - it should change as you change the Fuel. 
3 - AH & HHV only matter for the SECONDARY process.  maybe move Fuel &  HHV over there are remove AH from the primary side?

would it be better if we somehow combined HHV and AH?
make the calculate button return both
As is, a user could accidently choose Fuel 1 on the main page and Fuel 2 in the AH modal...

How would this effect TH?

**Comment by nbintertech** [comment]
Moving from 4406 "Heat Cascading should take the default HHV value from the selected fuel (typical nat gas, etc) in modal. Will involve changing results returned from flue gas modal"
