### ISSUE TITLE
Process Cooling Cooling Tower Fan Energy

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4592]
Need to use process cooling calc branch

From user
    For Annual Energy Savings from Results on the right, when the savings is less than 100 kWh, can we add one decimal? 

Use 3 sig figs

**Comment by nbintertech** [comment]
Branch to work from is issue-4419. You'll need to merge develop into it before running. On finish just push the remote branch as we don't want to merge it into develop yet.

**Comment by nbintertech** [comment]
Merged into Issue-4422 locally
