### ISSUE TITLE
Psychrometric graph

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4603]
Tidy Version
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/673a02c5-886e-4410-998f-7e5fcd53fa8a)

color coded version
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b8c64811-c870-408d-8fd3-3839c9279cae)

bottom X-axis = "Dry Bulb Temperature" (unit = user choice)
Y-axis = "Humidity Ratio" (no unit)
ideally: 
"Top x-axis" = "Wet Bulb Temperature"
and labels for Relative Humidity

### _**Curved lines (blue)**_
Make lines that are at constant relative humidities 
Constants: User set: Barometric Pressure, Specific Heat Ratio, Gas Type, static pressure
Constant: Hard coded: Method == Rel Humidity
List 2: Dry Bulb = sequence(35 , 130, by 5) ? May want to increase the increments for better resolution
List 1: Relative Humidity = sequence(0, 100, by 5) (may want to change to by 10 if too crowded)
y1 = Humidity Ratio (one line for each Relative Humidity)
This will create a list of values to make lines: x = Dry Bulb, y = Humidity Ratio, one line for each Relative Humidity
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1a275af5-b04b-4342-92a4-d8d7b1f5efaf)

### _**Straight lines (red)**_
Constants: User set: Barometric Pressure, Specific Heat Ratio, Gas Type, static pressure
Constant: Hard coded: Method == Wet Bulb
List 2: Dry Bulb = sequence(35 , 130, by 5) ? {same as above} May want to increase the increments for better resolution
List 1: Wet Bulb = sequence(35 , 130, by 5) (may want to change to by 10 if too crowded)
y2 = Humidity Ratio (one line for each Dry Bulb)
This will create a list of values to make lines: x = Dry Bulb, y = Humidity Ratio, one line for each Wet bulb temp
NOTE: if result "Relative Humidity" > 1 then do not display. This may be solved by filtering Wet Bulb list so that Wet Bulb <= Dry Bulb
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f549e2b2-408c-4e70-9668-e735b484b75c)

**Comment by nbintertech** [comment]
I've created branch `issue-4603` with Charlotte's work on this. We'll need to update plotly syntax and use the plotly service before the chart will compile.

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f8fc9cb9-fe52-449f-a0a5-89eec417623e)

**Comment by koay9f** [comment]
NOTE: might need two seperate sets of the hardcoded data. One for metric and one for imperial
