### ISSUE TITLE
CompressedAir: End Uses

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4644]

**Comment by AlexBotts** [comment]
![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/559bd236-a218-4923-84a5-6cbaa01e7426)

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/80439269/d2b06899-796d-47ee-96f1-8fe2ec127529/download](https://app.zenhub.com/files/80439269/d2b06899-796d-47ee-96f1-8fe2ec127529/download)
