### ISSUE TITLE
CompressedAir: EEMs

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4647]

**Comment by AlexBotts** [comment]
![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/a2f33dcf-ed4a-4756-ac86-2b907e9e4da8)

**Comment by AlexBotts** [comment]
Here is the file for the cascade EEM. At the bottom of the cascade sheet you will see a key on what PP will change [https://app.zenhub.com/files/80439269/efa22b00-c8e3-4df7-b86f-29fa5771b642/download](https://app.zenhub.com/files/80439269/efa22b00-c8e3-4df7-b86f-29fa5771b642/download)

**Comment by AlexBotts** [comment]
- Cascade EEM is not showing reordering in the profile summary

**Comment by AlexBotts** [comment]
Waiting for greater CA team testing
