### ISSUE TITLE
CompressedAir: Report

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4648]

**Comment by koay9f** [comment]
The demand side energy Projects & supply side energy projects are not going in the right bins.  Alex will add list

**Comment by AlexBotts** [comment]
![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/ed185249-9b48-4459-85f4-7e65a53b7979)

I drew the line in the wrong spot the first time

**Comment by rmroot** [comment]
@AlexBotts says this has been done. Moving to NV

**Comment by koay9f** [comment]
Auxiliary Power should be combined with Improve end use Efficiency. If the payback period is negative maybe "**" instead of whatever is calculated?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d937713e-dbe0-49e6-a788-3a1271e3df24)
