### ISSUE TITLE
CompressedAir: Profile Data Options

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4649]
V, PF, Amps
% Power
% Blowoff (centrifugal)

**Comment by AlexBotts** [comment]
Need to allow 2 decimals for power factor 
validation -> no negative numbers

**Comment by AlexBotts** [comment]
Validations for amp,V, PF option -> no negative numbers

**Comment by AlexBotts** [comment]
can we change the message to say "profile data cannot be negative" or "values cannot be less than 0"
