### ISSUE TITLE
CompressedAir: Example

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4650]
Need example for compressed air

**Comment by AlexBotts** [comment]
The CA example is not under the "example" folder.

**Comment by AlexBotts** [comment]
I needed to restore example settings first

**Comment by AlexBotts** [comment]
![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/44942bda-4eaf-4487-9871-d85a0d1ef06b)
Every time I reset the examples, it makes a new CA example assessment. Even If I reset back to back without changing one

**Comment by AlexBotts** [comment]
New example needs uploaded since Aux equipment fix in issue 4993
