### ISSUE TITLE
CompressedAir: Next Button navigation and tab disabling

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4693]
Add next button navigation to setup and disabling for tabs in system setup.

Anything past inventory should be disabled if there are no valid compressors

Talk to alex about how we want to validate day type days. Up to you if you want to make a new issue for that or just use this one

**Comment by rmroot** [comment]
Next when in system profile doesn't do anything.

Should go "Setup Profile" -> "Profile Summary" -> "Graphs" -> "Assessment"

**Comment by nbintertech** [comment]
Holding off on this for end uses tab

**Comment by rmroot** [comment]
Change next button to "Go To Assessment" when on system profile
