### ISSUE TITLE
Compressed air: metric

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4699]
Compressed air is not saving when you say you want to be in metric

**Comment by koay9f** [comment]
Pressure: bar (g or a as appropriate)
Air flow: m3/min
Vol: m3
length/distance: m

That place with hp that doesn't do anything - should be kW
for air flow: if there is an S (SCFM) --> Nm3/min

**Comment by rmroot** [comment]
Add units to input fields across assessment

Need to add convert units service to convert the data to the units we currently have in place
