### ISSUE TITLE
Altitude Correction Calculator

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4702]
Math exists somewhere in MEASUR. Should be added to CA assessment calculators

**Comment by koay9f** [comment]
It is in the psychrometric data.
It is literarily just a field that is altitude and the result is just barometric pressure.
May want to find SOMETHING else to do for this but not sure now.


![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c635d917-cf29-4c72-a7dc-9c6e35c213ce)

**Comment by koay9f** [comment]
looks great.  Here's an icon. If it isn't all properly transparent and such let me know and I'll send it in slack
![altCorrectionicon.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8aebd0c1-e0d3-4077-b40a-2fd24227080b)
