### ISSUE TITLE
Import Error Messaging

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4708]
If a user is trying to import treasure hunt opportunities in the dashboard they get a message about "Invalid File", we can enhance this message with something like "This is a treasure hunt opportunites file and must be imported within a treasure hunt"

treasure hunt opportunities have an origin of "AMO-TOOLS-DESKTOP-OPPORTUNITIES" and assessments just have an origin of "AMO-TOOLS-DESKTOP"

**Comment by koay9f** [comment]
I didn't even notice this one!!! Thanks Charlotte & Mark this is great!
