### ISSUE TITLE
Enhance Compressor related validation

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4709]
- Add validation warning block at top of inventory
- Add validation coloring to inventory row in the explorer
- Add validation badge/coloring for collapsed fields
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/c02cd1c8-6c0c-41ae-ac87-99f70896bbe1)

**Comment by koay9f** [comment]
This does not seem to be fully implemented. 
If error in performance points...
I am seeing an error at the header "Performance Points" I'm not seeing anything at the top or in the inventory

Errors elsewhere in the form seem to have desired effect.

**Comment by nbintertech** [comment]
Perf point validation relating to the compressor got turned off. Assuming this is so testing could still be done while perf point validation was being fixed. I'll turn them back on for now
