### ISSUE TITLE
Adjust Width of Results Panel

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4744]
Allow user to adjust width of results panel similar to how we can adjust left side navigation. This is for chiller staging (base branch `cooling-and-weather`. We may implement this app-wide eventually.

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/7fca840d-6039-40b0-827c-f326959067a9)

**Comment by koay9f** [comment]
I like this. please implement app wide.
