### ISSUE TITLE
CompressedAir: Profile Graphs

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4788]
Work out what data we want to show on hover and if we want hovering baseline/mod linked like in waste water.

May remove the % graphs if we add percentages to the hover templates

Tom will have input

**Comment by nbintertech** [comment]
Just letting this one simmer for a bit while we decide on third chart vs other option

**Comment by rmroot** [comment]
Baseline and modification y-axis range should be the same.

**Comment by koay9f** [comment]
Sent excel in slack
4 graphs:
*System* Capacity (acfm) with horizontal line for max system capacity (this is compressor capacity @ hour / system max capacity)
*Compressor* Percent Capacity (this is compressor capacity @ hour / compressor max capacity)
*System* Power (with horiz line? - ask Alex)
*Compressor* Percent Power
