### ISSUE TITLE
PHAST Design Energy Use View

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#48]

**Comment by koay9f** [comment]
![picture1](https://user-images.githubusercontent.com/25389736/27609106-ce988c7a-5b57-11e7-92b8-1735709d2b50.png)

Hopefully a screenshot of what this is supposed to be...

**Comment by koay9f** [comment]
More screen shots

![ex measured values for equip](https://user-images.githubusercontent.com/25389736/27752921-57f02c8e-5db1-11e7-8a4e-97208bf496a5.png)
![ex process heating equipment info](https://user-images.githubusercontent.com/25389736/27752923-57f18070-5db1-11e7-99e8-d4566cc92c24.png)
![heat zone 1](https://user-images.githubusercontent.com/25389736/27752925-57f3cd62-5db1-11e7-9be4-fd86f5618e42.png)
![heat zone 2](https://user-images.githubusercontent.com/25389736/27752922-57f13d9a-5db1-11e7-93d2-ad261f61e476.png)
![ex energy system details](https://user-images.githubusercontent.com/25389736/27752924-57f21774-5db1-11e7-8377-b0c0420a919b.png)

**Comment by koay9f** [comment]
Rough mockup of result pages for design energy use comparison.

Depending on what type of furnace the user chooses there will be different Design pages.  If there are words in yellow, those are my notes (shouldn't be in the final product)

Design Comparison Page for Fuel Fired Furnaces

![image](https://user-images.githubusercontent.com/25389736/28476822-73fbcf86-6e1f-11e7-93eb-d97878979528.png)


Design Comparison Page for Steam Furnaces

![image](https://user-images.githubusercontent.com/25389736/28476902-cac56ba6-6e1f-11e7-9389-1acb609a0d34.png)

Design Comparison Page for Electro technology Furnaces

![image](https://user-images.githubusercontent.com/25389736/28476944-fb80004e-6e1f-11e7-8f1b-4d297e691630.png)

If electrotech uses kW for the losses, even when using U.S. units, then all Btu should be replaced with kW.
