### ISSUE TITLE
Add Bin table/matrix to Weather Binning Calculator

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#4800]
Pull latest from cooling-and-weather. Add table where each bin is row and columns are upperbound, lower bound, hours

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/82a748a3-bef7-47fa-8aa3-2f2eaf3be201)

**Comment by koay9f** [comment]
can't see.  Looks like the table is under the graph
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b996e41c-138e-4c7d-b449-c60344ac5d50)
