### ISSUE TITLE
Performance points -9999

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4801]
For Lubricant Free screw compressors and reciprocating compressors the no load discharge pressure is showing -9999, this value needs to be 0 when the compressor is selected from the database 

Can we make it so that if the DB returns "-9999" it instead shows 0?
(Future addition - don't implement yet, but think about: And lock the field? - just if DB says -9999)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c549b00a-b7c2-4eae-baa9-387ff2c1a9e3)

**Comment by AlexBotts** [comment]
Lets go ahead and make this a two part 
1) for start/stop controls lock the no load pressure to 0.  
2) for other fields that show -9999 show the user a blank field and force them to enter data

**Comment by nbintertech** [comment]
[Uploading... image.png]
