### ISSUE TITLE
System Capacity in gal

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4809]
When in imperial units. the final results for Total Pipe Volume, Total Receiver volume, Total Capacity of Compressed Air System - should be in gal
Need to add Unit conversion to results for standalone, and in CA module (calcs & modal).

In the popup modal in CA System Information the unit conversion when you hit save and the number goes into  the field would then go away (b/c it would not be needed anymore.

This will make Alex very happy :)

**Comment by nbintertech** [comment]
Changes will be merged to compressed-air branch

**Comment by koay9f** [comment]
looks good but rounding errors are making it a little dumb.
No decimal places on anything with gal
