### ISSUE TITLE
EEM - Improve End Use Efficiency

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4840]
Need to add a field that is "New Equipment Power" (@AlexBotts - check verbiage pls).

Help Text: (@AlexBotts - check verbiage pls)
Power rating of new equipment. If airflow is reduced by replacing an end use device (for example a pneumatic valve with an electric actuated valve), that will decrease your compressor energy use, but increase your direct energy use. 

Math: @AlexBotts pick one (the last is more work, but I think it might be best...)
for every hour that the flow is reduced, add this power to the power demand
OR
for every hour add this power demand?
OR
add a check box option for "New Equipment is on" and add this power to every hour that check box is checked?
(would the motors for these new equipment be potentially always on? should we have another field that is unloaded power? and I getting too complicated?)

**Comment by AlexBotts** [comment]
option 1: every spot where the flow is reduced the power (kW) from the replacement equipment will need to be added. 

An option also should be added to add multiple end use improvements rather trying to clump it together as one
