### ISSUE TITLE
EEM Differentiate Supply & demand side

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4842]
Figure out how to do this?
Icon? Colors?

**Comment by rmroot** [comment]
@AlexBotts says this has been done. Moving to NV

**Comment by koay9f** [comment]
Okay, I'm a bit slow on this one, but what was done?  I can't tell the difference between them still.
I thought our plan was something like colors (seems like it would be gaudy) 
What about just putting `(Supply)` or `(Demand)` after each EEM name?

**Comment by AlexBotts** [comment]
My misunderstanding. I thought this was referring to the report differentiation. This issue is referring to a visual que on the EEM page

**Comment by koay9f** [comment]
let's go with teh (Supply) and (Demand) for now

**Comment by koay9f** [comment]
ehhh...
now I'm going to be picky. 
Can Supply/Demand go on the other side of the title and maybe be a bit smaller font or something?
