### ISSUE TITLE
Lines vs Markers

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4846]
can accidently have lines for non-time series data still

If make a time series chart & use lines.
Then switch to non-time series...
The data will still be lines, but the drop down will only have the markers option and it will not change back.

**Comment by nbintertech** [comment]
Files for testing

**Comment by nbintertech** [comment]
More work needs to be done in data explorer before this can be worked on further. Will revert to original state and moving this to backlog until we can find a proper solution.

**Comment by koay9f** [comment]
Throwing this back to Inbox b/c I don't want it to be lost but I have confirmed it is rolled back. 
The really probably should be in the compressed air roll out if at all possible.
