### ISSUE TITLE
Compressor Profile avg operating point

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4889]
Find avg operating point for each compressor for each bl/mod
put point on compressor profile

**Comment by AlexBotts** [comment]
Notes for me later: This is going to be the average during the "on" hours for each day type (this will be needed to find the operational specific energy or the operation intensity). The second part of the issue: I think we wanted to point out where on the performance profile the compressor is operating

**Comment by koay9f** [comment]
Add dots to profile graph in system setup
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c7b7c7e8-3068-4f4c-93a7-ed28f8fbf07b)
Maybe add check box like "graph all compresssors" for "Graph Average Operating Points" 
Would need to be disabled until complete "System Profile"

do not include the op points on the graph in Assessment.

**Comment by koay9f** [comment]
Looks good. Needs the different shapes for each daytype. (Tom suggested in weekly). Also, mabye up the size a bit
