### ISSUE TITLE
PHAST Aux Equipment View

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#49]
Assessment & analysis for PHAST

**Comment by koay9f** [comment]
![picture1](https://user-images.githubusercontent.com/25389736/27597794-711e858e-5b31-11e7-9ac8-eb53f2f99d6c.png)

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/28476657-c393f6e6-6e1e-11e7-89a2-cd8257909a0a.png)

Please forgive rough mock-up. 
The field for Equipment Name/Designation might get changed to a drop down (with the different equipment shown in the previous pic)

Can choose two different ways to calculate total energy use: using voltage and current or rated power.  The circles are supposed to be radial buttons.

I'll put the math in another issue and link them when I have them up.

**Comment by rmroot** [comment]
for calculated:
Total Power (kW) = ((phase ^0.5)*Voltage*Current* power factor * (Duty/100) ) /1000

for rated:
Total Power (unit) = power (unit) * (Capacity / 100) * (Duty/100) )
