### ISSUE TITLE
Handle Refresh and URL Changes

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#4931]
Application should be able to refresh. Right now it goes to 404. I think this might be because the core component and dashboard components have empty strings in routing tree

May need to break into larger issues to handle but if user changes assessment ID in url we need to be able to handle that

Example:

measur.ornl.gov/ssmt/4

4 is the ID of the assessment, if that get's changed to an ID that isn't ssmt assessment or a different ssmt assessment we are not really setup to handle that properly. Same goes for other assessment types

**Comment by nbintertech** [comment]
- Handling refresh and direct routing should be a server config. Gina and I are looking at this.
- Also handling re-nav to home screen in terms of Db lifecycle and other init logic.

**Comment by nbintertech** [comment]
Using proper routing now, not hashLocationStrategy

**Comment by nbintertech** [comment]
This error is appearing from time to time even after routing and apache server config have been fixed. Hard to reproduce but seems to have something to do with having multiple tabs open and/or directly navigating to child route by url ![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/5a2b513f-2d7c-438b-a5ed-90dec8e4a6ff)

**Comment by nbintertech** [comment]
"I think instead of concerning ourselves so much about the routing/navigation that's more out of our control we think about how that wasm module is initialized
Currently it's using the .js script spit out by emscripten but I think there may possibly be ways to load it synchronously" 

https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running

**Comment by nbintertech** [comment]
No longer an issue
