### ISSUE TITLE
Diagram for PSAT

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#494]
Diagram for PSAT - To be put in another tab with the results/help (So results/diagram/help ?).  Also on that tab should be a way to choose if you want to see this figure or the Sankey Diagram.

Tom has seen a sketch of this, but has not seen/approved the final version, so hopefully there will be no changes.

![image](https://user-images.githubusercontent.com/25389736/28468145-1c79f5e0-6e00-11e7-87e1-94cc940f89cd.png)

Ideally, when hover over the area around the text in the drawing, corresponding inputs and results will appear in a text box.

Motor:
Efficiency:
Power:
Current:

Rated Motor:
Power:
Full Load Amps:
Voltage:

Fluid:
Specific Gravity:
Flow Rate:
Head:

Pump:
Type:
RPM:
Efficiency:

These numbers will come from a mix of results and inputs
Results:
Motor Efficiency
Motor Current
Motor Power
Pump Efficiency

Inputs
Rated Motor Power
Full Load Amps
Rated Motor Voltage
Specific Gravity
Flow Rate
Head
Pump Type
Pump RPM

Let me know if I wasn't clear with something

**Comment by jonhadden** [comment]
Makes perfect sense. I'm thinking of using a simplified, but more detailed line drawing for components (See attached).
![motor-spacer-blocks](https://user-images.githubusercontent.com/1999028/29031281-55d4a83e-7b53-11e7-9ab3-5cda542c73b5.jpg)

This is a bit more detail than I think we need, but I'll be working on drawing today for PSAT.

**Comment by koay9f** [comment]
Sorry I didn't see this notification.  I originally suggested something like this to Tom and he's the one that requested the blocky one (though that could have been more in reference to my drawing skills and not to the style of drawing).  If it's not too late, I'd send him an email asking about it.
