### ISSUE TITLE
Condensing Economizer

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#4972]
new calc will have details soon

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8bb344f7-3ada-42b0-85cd-9c927c7391f5)
Annual numbers should all be in the annual section.  
Where you have those numbers, can we show hourly heat? so we have both mmbtu/hr and mmbtu/yr

**Comment by nbintertech** [comment]
Also adding ability for user to choose/add fuel (locked to Gas type)

**Comment by koay9f** [comment]
Need a row in "Results" that is `Total Heat Recovery` = sensible + latent
for example: 6.7 + 11.51 = 18.21
