### ISSUE TITLE
Modal Size - results overflow

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5008]
I've only found this here, but the results is overflowing the modal.
Process Heating>Fuel-fired>Flue Gas> Solid/Liquid Fuel > Calculate Moisture in combustion air modal

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/67f50c5c-3f64-4964-8ec2-7d2727d830a9)

**Comment by rmroot** [comment]
Fixed modal layout. When verifying make sure to check the units for the inputs and results are correct, was previously based on fan settings

**Comment by koay9f** [comment]
units look good. could probably generally clean it up (more like inputs for stand alone psychrometic than fan density,) but it gets the job done. would want to talk to Sachin first so will close this issue for now.
