### ISSUE TITLE
Co2 Savings Calculator Help Text

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5021]
We need to add field by field help to standalone calculator. We only have general text at the moment

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/cb161994-9c11-4757-bf6f-eca8187b6ba3)

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/790acdc3-ed0f-4831-9f5d-0e674eb9bdd7/download](https://app.zenhub.com/files/80439269/790acdc3-ed0f-4831-9f5d-0e674eb9bdd7/download)

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7cc67fe8-b357-4d7e-9e6e-90f1cd26dbf0)

If fuel use & electricity use are actually the same field with just some label changes, then the text should be 
"Energy use"
Amount of energy ...

if they are separate, then "electricity" should be "fuel"
