### ISSUE TITLE
Roll up report additional graphs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5038]
Something to make it actually "roll up" everything
* Total annual Electricity, Natural gas (be careful including the TH and steam in this)
* Graph with % energy use accounted for (aggregate pumps, fans, compressors, etc.- so like 50% of your energy is for process heating, 5% fans, 45% compressors)

**Comment by koay9f** [comment]
for ref:
Pumps, Fans, compressed air, wastewater == "electricity"
Process Heating depends on what type for each assessment (fuel or steam = "fuel", electrotech = electricity)
Steam = fuel

**Comment by rhernandez-intertech** [comment]
The graphs are now in uniformed units, the common report unit. and the graphs update when the common report unit is changed
