### ISSUE TITLE
CompressedAir- add profile validation 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5049]
Need to add profile validation for each type of data entered. Right now we only have no negative numbers allowed. Engineers need to work on this first

**Comment by AlexBotts** [comment]
- power->  cannot go over SF (115% or calculated power ) ==Red warning
- Flow -> Less than 150% of rated == yellow warning
- For V, PF, or Amp
 -> PF >=1 (Red) 
-> V max 6600 (red)
-> Amp use Upper limit == SF x Amps from Nameplate data in inventory  (red Warning)

**Comment by ysintertech** [comment]
Need to also 
- add border styling to each cell that is invalid or throws a warning
- add error/warning messages

**Comment by ysintertech** [comment]
Validation needs to also disable other tabs within the assessment
