### ISSUE TITLE
PH - solid fuels - %O2 / XA

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5061]
revisions to backend and desktop interaction mean that the calcuation for excess air or %O2 is no longer shown.
can put it back so it looks like gas fuels (at the bottom) but won't be coming as part of the suite results.

Does not need to be in compressed air release.

**Comment by nbintertech** [comment]
We're just adding the two results to Solid flue gas everywhere that they appear for Gas flue gas. I.e. standalone calculator flue gas, modals, assessment. The results should already be part of the flue gas results interface. They will be empty/undefined
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/570a2463-1500-4f92-992a-171ca3599b69)

**Comment by koay9f** [comment]
why are they empty/undefined??? I'm just going to say, the changes to the gas fuels calculator is why there are so many problems now in PH.

For all fuels I think we used to calculate these separately from the big math that calc'd available heat. 
Gas fuels then got that big update and XA/%O2 was calc'd inside the AH calcs.
BUT it is still not for solid/liquid.
So... could we do something so we can still get the XA/%O2 from the suite and display it here (idk if we can just to some if gas then use AH else use this thing or go back further and if gas then show these results, else show these, that just so happen to look very similar, idk...).  the suite method/calculation is `SolidLiquidFlueGasMaterial::calculateExcessAirFromFlueGasO2`
