### ISSUE TITLE
New stm calc's unit conversions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5066]
connect New steam calcs (condensing HX, feedwater economizer, vent steam) to Steam's unit settings instead of just imperial / metric.
Let me know if there are any units that don't have a customization option.

**Comment by nbintertech** [comment]
These were the units I thought may have settings, but didn't find anything for.
- fuel unit
- heat input / energy rate input
- higher heating value

Also added units in validation msg where possible.
