### ISSUE TITLE
Pumps bug

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5080]
Open a pump assessment (Example works)
switch to assessment
switch to expert view
no tab is selected
problem seems to be just in pumps
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/38ca967f-fa52-400b-a1a7-7cd0ec41ee05)

**Comment by nbintertech** [comment]
Closing. No one can reproduce.
