### ISSUE TITLE
Compressed Air Tutorial 

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5083]
need tutorial

**Comment by rmroot** [comment]
[https://app.zenhub.com/files/80439269/04d1277e-ff53-4df3-99e5-f836709dc780/download](https://app.zenhub.com/files/80439269/04d1277e-ff53-4df3-99e5-f836709dc780/download)

compressed air user manual found in `tutorial-pdf` branch

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/80439269/709c9c6d-76d9-4e36-9f0b-eb45684baadf/download](https://app.zenhub.com/files/80439269/709c9c6d-76d9-4e36-9f0b-eb45684baadf/download)
