### ISSUE TITLE
Old tutorial step bug in PHAST

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5102]
Reproduce by: Settings > Reset all data > Open PHAST example. 

Might take a few tries. This bug has come and gone over time
![old-tutorial-phast-error.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/4a75bc85-114b-46c9-a4b4-eeb5b3cc4492)

**Comment by koay9f** [comment]
reset 3 times and never got error, so closing for now.
