### ISSUE TITLE
New FSAT Tab error flicker

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5130]
When opening a new FSAT the operations tab is marked with an error (red) - once I click the tab it goes away. That component is probably not being passed an update fsat or it's a timing issue. Did we just look at this in pumps? Please check pumps also.

![newfsatbug.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/ce7a38aa-9f75-4d61-8f85-256221eed6ec)

**Comment by rhernandez-intertech** [comment]
Pumps does not have this bug, it is only in Fans
