### ISSUE TITLE
Motor Inventory Delete bug

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5132]
Modal is not coming to foreground - bad z-index

The parent of whichever component is the parent of modal probably needs a class to set the z-index. Search 'inModal' and see others for examples
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/ac3a787f-5724-468d-b804-8db1b46bd583)

**Comment by rhernandez-intertech** [comment]
I cannot recreate this bug, I believe the fix for this bug was done in issue 5118
