### ISSUE TITLE
Roll up units

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5138]
we added modules since we made this.
We need to update for steam at least. maybe check others

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bc84b14c-4380-4954-b503-0f88bb304e4f)

Need common unit for all other assessment types (Fans, Steam, Wastewater, compressed air).
However...


Maybe instead of "common energy units" for each assessment, instead do each energy type.
Energy Unit
Fuel / Steam (can probably get away with combining) {This would be used for PH assessments and Steam Assessments}
Electricity {This would be used for PH Assessments and Pumps, Fans, Wastewater, Compressed air assessments}

This would make your pie charts easier to work with I think. If you know everything is in proper units.

We have this that can be used to make defaults?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9779946d-002f-46ab-80ed-e7e0b2181d6d)

**Comment by rhernandez-intertech** [comment]
Added a Common Report Energy Result Unit and a common result unit for each assessment type. The units are saved to rollupReportSettings, and they can be changed from the units menu in the Summary Report.
The Common Report Energy Result Unit will default to the Energy Result Unit value. 
Processes Heating will only have one rollup unit now, Kristina is cool with the tables in PHAST rollup being in the same unit. 
![image.png](https://images.zenhubusercontent.com/60b7bed2e39f152beecc60b4/d2ace0ab-8fc7-477f-9a66-ba3a38bb63fb)

The Report Summary card for each assessment will be the common unit for its assessment type. 
![image.png](https://images.zenhubusercontent.com/60b7bed2e39f152beecc60b4/a74a2e79-afd6-4128-8de3-d1e57db7b283)

**Comment by rhernandez-intertech** [comment]
Pre-assessments will be in the same unit as the assessments in the rollups. 
and the units of the rollups will be correct when printed

**Comment by koay9f** [comment]
all electrical modules (pump, fan, WW, CA) should be MWh by default.
That's the only thing I noticed needing anything.  everything else looks good
