### ISSUE TITLE
Add simple payback period calculations to PSAT

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#514]
Requires three additions to the code:

- Add "capital cost" to Field Data

-Calculate Simple Payback Period with the formula: SPP = (Initial Cost/ Annual Savings) X 12 months

-Display Simple payback period within Assessment Report

**Comment by gaccawi** [comment]
Rather than capital cost, call it implementation cost.

**Comment by koay9f** [comment]
This would also be needed on PHAST

**Comment by koay9f** [comment]
"Implementation Cost" NOT "Capital Cost"

**Comment by rmroot** [comment]
PHAST implemented, PSAT needs to be added still
