### ISSUE TITLE
Multiple CA bugs

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5164]
2-3 things that need fixing here. This may take a few different tries to reproduce.

- Create a copy of the CA example for testing.
- Go to system information, change is sequencer used to yes --> **if profile data 0 or greater it should be valid** (screen below) 
- Leave assessment and come back in --> **System Profile should have values either 0 or greater** (not always happening)
- **Go to Assessment button should be disabled if setup is invalid**
![image (13).png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/af5891e6-b54f-4774-95bb-394cbae04397)

**Comment by nbintertech** [comment]
Couldn't reproduce system profile validation/ target sequencer problem

**Comment by koay9f** [comment]
Could not reproduce the initial problem, but did "manually" blank out the profile data and it isn't giving an error or stopping "Go To Assessment"
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a5eef8c2-32f3-465b-822b-dd7740c4f24f)
