### ISSUE TITLE
Investigate Unit conversions in PH Flue gas

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5182]
All the conversions for the inputs are working correctly (including the displayed heating values in the fuel modals)
but the Available heat changes when you do a unit conversion. I wonder if there is a conversion that is getting missed before sending to the suite? Maybe check Ambient Air temp first (recently added field).
If can't find anything, maybe make a note and move to the backlog/icebox.

original
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b2eb7691-2d92-4e12-81c5-fc5b4fd8b023)

converted to metric
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5e76ded1-dfa6-43a3-9a5c-50186e0e1736)

**Comment by nbintertech** [comment]
Alt test set 
![image (2).png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/4727af83-e227-44cc-a299-1e5b9f54f52e)

**Comment by koay9f** [comment]
notes: it is just a problem with gas fuel gases.  solid/liquid seems to be behaving

**Comment by nbintertech** [comment]
@rhernandez-intertech Please take a look at this issue using the alt test numbers above, before you do 5127
