### ISSUE TITLE
Rollup Report Printing Errors 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#5193]
There are errors that pop up in the console when printing the Rollup Report.

**Comment by rhernandez-intertech** [comment]
![image.png](https://images.zenhubusercontent.com/60b7bed2e39f152beecc60b4/3f45b82d-8849-449d-9638-b912a2b43f97)

**Comment by koay9f** [comment]
looks like more were made...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/abbf6a83-60ed-423d-bc76-47eba2e8cb3f)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6bdc1107-3b49-4722-937a-de6bb4bdbd00)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/56e73b6e-80ce-41aa-84a8-7d50dcc98246)
