### ISSUE TITLE
Compressed Air: Date Interval options 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5194]
Currently on the profile data (System basics>System Profile>Setup profile) we offer 1 hr and 1 day intervals. Add 15 min and 30min intervals 
This may effect the data explorer integration.

**Comment by rmroot** [comment]
Known areas that will need to be updated outside of calculations:

- [ ] Profile Setup
- [ ] Profile Summary
- [ ] Graphs
- [ ] Mod: Improve End Use Efficiency
- [ ] Mod: Reduce Run Time
- [ ] Mod: Use Automatic Sequencer

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/dd3b0261-543c-4aec-8822-071ae78dc988)

**Comment by rmroot** [comment]
Dropdown change was done right before you tested.

Issue #5810 handles validation (I don't think there is a max validation for % capacity)
