### ISSUE TITLE
Compressed Air: Isentropic efficiency 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5195]
Add a line item in the report for each compressor for the isentropic efficiency. The specific power  at full load (in issue #5196) will need to be calculated first.

Isentropic Efficiency = (16.52 *((((Discharge pressure + 14.5)/14.5)^0.2857)-1))/Specific Power at Full load 

![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/fa5a88e8-59eb-453e-bdf9-6a01ee64dac9)

**Comment by AlexBotts** [comment]
Later for help text: from CAGI
www.youtube.com/watch?v=VLjexIHLPqM

**Comment by koay9f** [comment]
Specific powers are good, location etc is good. but Isentropic Eff is off.  Maybe paraenthese in the wrong spot?
(power((115+14.5)/14.5, 0.2857) - 1) * 16.57/19.58
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/206117a3-1a0b-46df-8836-e247590f1c1f)
