### ISSUE TITLE
Compressed Air: VFD controls 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5198]
AM work around: Start with mod unloading and "play" with discharge pressure until it looks right 
Current Idea is to design rule as for 3-5gal/cfm and leave the edge cases looking weird 
Eric has been contacted for guidance

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/80439269/3fe6534a-d4be-4891-97cc-80ceac027a05/download](https://app.zenhub.com/files/80439269/3fe6534a-d4be-4891-97cc-80ceac027a05/download)

**Comment by AlexBotts** [comment]
The calculations for the performance points are here

[https://app.zenhub.com/files/80439269/355bc049-f6f0-4f9f-9340-b6744dd14fd9/download](https://app.zenhub.com/files/80439269/355bc049-f6f0-4f9f-9340-b6744dd14fd9/download)

**Comment by AlexBotts** [comment]
The math is looking better.  The other VFD options need added to the general DB, there should be an option for each size and type (outlined in the doc commented on April 20)

Default values need corrected.
Unload point capacity default = 20% (it currently says 50% but I don't think this field is connected) 
Full Unloaded Power % of Full load default = 5% (it currently says 50% - this one is connected)
 ![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/3ecd537b-55cd-477e-9d8a-5c25d61cce6f)

**Comment by AlexBotts** [comment]
the unload point capacity field isn't connected to anything. When I change it the PP should also update.
![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/8bb2946b-eeb4-4175-b582-582a442c3c72)

**Comment by nbintertech** [comment]
Look into non breaking suite error for missing properties
