### ISSUE TITLE
Compressed Air: Network Controls 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5199]
Current Brainstorming: 

3.	Networking controls
        a. Use demand from baseline and turn on most efficient comp for that demand
            i.	Optimize either isentropic eff or specific at fL
                1.	Ask user to pick method (isen or specific)
        b. Maybe allow for user to select base and trim comps
           i.	Optimize either isentropic eff or specific at fL, show and let them choose base/trip for each comp
       c. Load Sharing for Centrifugal to avoid blowoff 
           i. Would need to load one compressor to just at blowoff and then load the next cent. This only works if the first would be over 100% loaded

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/80439269/fdd696b3-98ae-4c70-9f10-3c1f0ad94e1d/download](https://app.zenhub.com/files/80439269/fdd696b3-98ae-4c70-9f10-3c1f0ad94e1d/download)

**Comment by AlexBotts** [comment]
Algo 1 of 3: Control via efficiency
 [https://app.zenhub.com/files/80439269/443e9b03-25b2-4b39-a063-d2ec30505dea/download](https://app.zenhub.com/files/80439269/443e9b03-25b2-4b39-a063-d2ec30505dea/download)
[https://app.zenhub.com/files/80439269/f83a43f5-bd81-40d8-9632-6cff574c5f23/download](https://app.zenhub.com/files/80439269/f83a43f5-bd81-40d8-9632-6cff574c5f23/download)

**Comment by AlexBotts** [comment]
Algo 2 of 3: Centrifugal Load Sharing
[https://app.zenhub.com/files/80439269/70d9a30e-60cf-4100-9ccb-d35665ae2268/download](https://app.zenhub.com/files/80439269/70d9a30e-60cf-4100-9ccb-d35665ae2268/download)

**Comment by rmroot** [comment]
Created issues for other control types. Will create PR's into issue-5199 branch for those issues
