### ISSUE TITLE
Stm results column headers

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5204]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5dc8c66f-3b8f-471c-bbaa-8743dbc2236d)

**Comment by nbintertech** [comment]
Also ![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/bef4e1cc-dbfd-46f4-ada1-816d999f7124)
