### ISSUE TITLE
Optimize Pump & Motor Calculation Error

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#521]
Motor rated power some how is being multiplied by 100, which is then effecting other calculations, which I assume are still correct, but I can't really tell.

**Comment by gaccawi** [comment]
Can you provide the specific inputs and a screenshot depicting the error?

**Comment by koay9f** [comment]
[PSAT Inputs.pdf](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1183784/PSAT.Inputs.pdf)

**Comment by koay9f** [comment]
Size margin was not being /100 before being used in calcuations
