### ISSUE TITLE
Treasure Hunt kg/MWh to kg/kWh conversions 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#5219]
The conversions for electricity CO2 output rate is currently converting MWh to kWh and it needs to be kg/MWh to kg/kWh

**Comment by koay9f** [comment]
Need to do it in PH also. 

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9047cc9f-f49e-40ae-9a50-d686d6e6f801)
401 kg/MWh * {1MWh / 1000 kWh} = 401/1000 kg/kWh
there are 401 kg from a very large amount of energy. there are only 0.4 kg in the smaller amount of energy.
