### ISSUE TITLE
PSAT Motor Performance

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#522]
Would it be possible that "motor power" in the "motor performance" calculator that is within PSAT use the rated motor power from baseline?  And save when you change screens?

**Comment by gaccawi** [comment]
Per discussion with Mark Root:
So when you hit "Save" in a calculator is it going to mean "Save as Modification" or "Change Baseline"

**Comment by koay9f** [comment]
I was assuming the NEMA Energy Efficiency calculator was done that way, but it just defaults to the motor rating I happened to pick.  

Could they both just default to the rated motor power that the baseline is at (and not save any changes)?  If not, could Motor Performance default to 200 so there is something there to start?

**Comment by rmroot** [comment]
The Pump calculators inside a PSAT context will default to baseline values when applicable. I believe this is existing functionality.
