### ISSUE TITLE
Reported issue with conversion between C and F - Psychrometric

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#5224]
Per reporter:

I am a certified DoE QSPAT auditor and have historically used PSAT on a regular basis.

I am also a lecturer for the UK Royal Institute of Mechanical Engineers.

I have been training some industrial companies with regard to energy management and have been going through psychrometric charts.

As you can appreciate, using manual psychrometric charts is tricky, and therefore, I was hoping to demonstrate the potential of Measur for various elements of energy management.

However, as you can see on this chart, there appears to be a problem in the conversion between temperature of oC and oF with regard to the wet bulb temperature.

The data has been entered on the left as 25oC dry, 21oC wet, however the result page on the right still shows dry as 25oC, but wet, which was a primary entry as 69.8oC, which is not correct, since the result is a oF reading.

**Comment by gaccawi** [comment]
See attached.
<img width="640" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/8973004/149233524-7ee310b1-e52f-4a37-b7ac-15dcc9388022.png">

**Comment by koay9f** [comment]
Not 100% sure, but I think the result where Relative Humidity == 70.2% is correct
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0a117267-9c6d-4c20-b4e2-96ffe9402df0)

**Comment by koay9f** [comment]
Real issue - something is wrong with pyschrometric calcs in metric (both standalone and in fans, if start the assessment in metric. it is fine if you start in imperial , even if you switch to metric)

**Comment by rmroot** [comment]
BaseGasDensity values that were not being displayed were not being converted on creation of defaults

**Comment by koay9f** [comment]
standalone is fixed but the problem still persists if you start a fan assessment in metric

**Comment by rmroot** [comment]
specificHeatGas hardcoded to .24 for wetBulb calculation
