### ISSUE TITLE
Save Stand alone Graphs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#523]
Is there a way to save graphs plus the data from the calculators?  This is to save the data.

**Comment by koay9f** [comment]
Also for things like the Pre-Assessment Calculator

**Comment by gaccawi** [comment]
For Pre-assessment tie to the folder. Others to the asssessments

**Comment by koay9f** [comment]
Tried clicking Add PH Pre-Assessment/Screening

Pop up came up asking if I wanted to save to folder (could this be a bit smaller, it stretched all the way across the page)
Click the button, nothing happened...

**Comment by koay9f** [comment]
The pre-assessment calculator does not work for a folder that existed before the update. it works on new folders (and continues to work if the app is shut down and reopened)
