### ISSUE TITLE
State point analysis tool

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5234]
Instead of entering clarifier area - let people put in clarifier diameter.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/dc844f64-c1dc-4e70-91fd-cdb695d2d823)

**Comment by nbintertech** [comment]
Include blue link below form label that allows user to input diameter and have area calculated. 
`area = (diameter / 2)^2 * pi`
