### ISSUE TITLE
Add CO2 Savings to Compressed Air

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5249]

**Comment by koay9f** [comment]
Unit labels
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/422a1970-f956-4dcf-9e65-72a96a8f637e)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0ca4165f-05d8-4570-91c6-71f07956177d)

**Comment by koay9f** [comment]
I'm sorry I didn't notice this before... you don't need the "(   )" in the units...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/56897264-09c1-44b5-9358-5098ffcbfaf9)
