### ISSUE TITLE
Calculator Text

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5257]
I will probably add things to this and just use it as a place to put little things. No need to start on it until closer to release

Replace FSAT with "Fan". make sure the calculator doesn't say FSAT in it also
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7a0975d3-ddee-4681-8daa-191fb5d9797c)

Calculator Names:
Make sure left and right and the title within the calc and calc's help text match.  these do not. Also "Flue Gas Loss", "Fixture Loss". Wall Loss & Charge Material are good. all but "Gas Leakage Loss" I think are good on the calc's page but pls check 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6095b34b-11f2-4dc6-9370-c491f95c5d79)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/342cd339-4cda-4718-9b7d-a8c9c0051576)

Make sure we don't say "This calculator ...".  Just the text on the calculator navigation pages.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0688e249-57cc-44ad-9096-6e7213a8211f)
Estimate the heat loss via the walls of the equipment
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f9901397-e70c-4ec4-b98e-fc9ae22f2615)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/63d2d90b-2a02-4ec8-9f59-d6d5f6964868)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/dfff6525-25d5-45fc-b1a7-8ceccc49cc35)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/79b26cde-978b-4250-91df-a88d0d6f0ec3)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/97ec7306-7c93-4dc4-a789-275dc1d40634)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3892ad9c-1044-4ced-bb2d-bf52d2754d24)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6bca19b5-dabf-4605-86ea-9f977430168d)

Bit more...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a503accf-1b12-416b-a6d8-50317180eece)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9accf21b-b959-415d-ba65-7538e7e3efd5)

**Comment by nbintertech** [comment]
Please also fix the alignment on this text and icons. It's probably just a matter of consistently using maring OR padding and the same values
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/bfa2303f-bc36-4065-80b8-b5c8ee3c0be3)

**Comment by koay9f** [comment]
Oops. we got too zealous
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/11851a9e-0add-42bb-b5ec-f2cccf9b18cc)
