### ISSUE TITLE
Cash Flow Diagram Calculator

### ISSUE THREAD

**Issue by vanced** [ORNL-AMO/AMO-Tools-Desktop#526]

**Comment by vanced** [comment]
[Cash Flow Diagram Calculator.pdf](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1183866/Cash.Flow.Diagram.Calculator.pdf)

**Comment by vanced** [comment]
A cash flow diagram is a pictorial display of the costs and revenues associated with a project. Costs are represented by arrows pointing down, while revenues are represented by arrows pointing up. The time periods for the costs dictate the horizontal scale for the diagram. Although some costs occur at different points in time, most of the time, an end-of-the-year approach is sufficient.

**Comment by koay9f** [comment]
Change "Junk" to "Disposal"

Benefit/cost Ratio = {(Annual Energy Savings * lifetime) + salvage} / { (Installation cost + disposal) + ((O&M cost + fuel cost) * lifetime)}

Simple Payback = (Install cost * 12) / (Annual energy Savings)
