### ISSUE TITLE
Final CO2 issues

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5262]
Treasure Hunts default Electricity "Total Emissions output rate" should be 0.40107 (not 401.07)

Steam
Mixed Fuels - not calculating average. no errors displayed, nothing put in user input field
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9a629304-8a45-44e7-9144-550bd8a3039e)

**Comment by nbintertech** [comment]
Also using this issue to do final dev testing on CO2

**Comment by nbintertech** [comment]
#5307 #5239

**Comment by nbintertech** [comment]
Note for me: Look at root scoping eGrid service (get rid of promise delay)

**Comment by nbintertech** [comment]
co2SavingsData should not get set in update-data service

**Comment by nbintertech** [comment]
SSMT new assessment 
- natural gas rate not populated if electricity emissions are retrieved from settings
- not setting fuel type correctly 

PHAST new assessment
- EAF not saving other fuel type correctly
