### ISSUE TITLE
WASM Final Testing

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5263]
- [x] Merge develop into wasm and test before merge back into develop
- [   ] Test issues found in suite

**Comment by nbintertech** [comment]
Need to remove unused calculator files (showinng unused on build)

**Comment by rmroot** [comment]
Memory leak issues found in testing. Will use this issue to remove those files and investigate breaking problems to make a plan going forward

**Comment by rmroot** [comment]
completed in #5615

once verified we will merge into develop
