### ISSUE TITLE
PH Electrotech Fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5267]
Fuel's data isn't being applied right
Things to fix:
For all electrotech
* Fuel & steam costs should be per MMBTU or GJ, no kW
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/e56ea676-a787-496e-8f6b-1147becef9a2)

For Non-EAF Electric furnaces.
* Energy Summary
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6cc1dfc3-7e71-4581-8152-7e2975fe94ac)

* Executive Summary
Math is below
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c2384649-ec1c-403f-af88-a22319fd5c8c)
Cost math
Heat Input for Burners: 0.42659 MMBTU/hr = 125 kW
AH = 80% --> 100kW is used by furnace
charge materials required 300kW --> 200kW of electricity
Unit costs: $5/mmbtu, $0.1/kW

So cost = fuel cost + electrical cost ...
Fuel = 0.42659 mmbtu/h * 1000 h/y * $5/mmbtu = 2132.95
Electrical = 200 kWh/h * 1000 h/y * $.1/kW = 20000
total = $22132.95

EAF
* Energy Summary
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d6d5acb1-6f44-4e49-8d69-fe750d9190fe)
Like non-EAF need to seperate out electricity & NG and have 3412 Btu/kWh as HHV
For this one, I think, if it can be done quickly, rename Fuel to Natural gas and add rows for
Electrodes (energy used = 1 kW)
Carbon Coal (energy used = 1 kW)
Other Fuel (energy used = 3kW)
Then for Fuel used in the compare table, add NG + Carbon Coal + Electrodes + Other Fuel and make sure electricity is in there right 
* Exe Summary
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/cdfb415e-da11-4ea0-bbdf-0e831194ec5c)
So, here cost = fuel cost + electricity cost + coal cost + electrode cost + other fuel cost
We only ask for fuel & electricity right now.
So like above fuel cost = NG heat input * fuel cost, electricity = "Electrical Heat Delivered" * electricity cost.
Awesome additions would be adding 
"Carbon Coal Cost" , "Electrode Cost" in $/lb and "Other Fuel Fost" in $/MMBTU (or GJ), and adding those costs also..
This last bit can also be made another issue for later.

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/9f877f88-9ca2-4b4e-9e59-87ba4612b8d7/download](https://app.zenhub.com/files/80439269/9f877f88-9ca2-4b4e-9e59-87ba4612b8d7/download)

**Comment by koay9f** [comment]
Need individual cost fields for carbon coal ($/lb), electrode ($/lb) and other fuel ($/mmbtu)
($/kg & $/GJ in metric)
For the costs in the Exe summary, keep them $/mmbtu but you'll need to calculate it
[$/lb] / {mmbtu/lb}   <-- will need to convert btu/lb to mmbtu/lb (or kJ/kg to GJ/kg, should just be able to do 1/1000000 for both if don't want to do real conversion)

**Comment by koay9f** [comment]
small label issue in Exe Summary
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ccaba061-196b-43e8-bbb0-3b1c7e6d2452)
math is looking good. will check again when I can set different values for unit costs.

**Comment by koay9f** [comment]
non-EAF looks good.

**Comment by nbintertech** [comment]
- Added correct results to report > energy used and executive summary for eletrotech and EAF systems
- Added new fuel costs for EAF systems

**Comment by koay9f** [comment]
Non-EAF cost looks good.
Non-EAF carbon is off:
Inputs
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0cd2013a-51ee-4051-96bf-915b3827df68)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/af6b4cac-6a01-4bf5-8965-f644cdc51430)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2610e7b6-0731-4637-857f-0d4aa5317dae)

1001 kW electricity * 100 kg/MWh * 1MWh/1000kWh = 100.1 kg/hr
0.375336 MMBtu/hr  * 10 kg/MMBTU = 3.75 kg/hr {0.375336 is from user input or exhaust gas loss + fuel heat delivered if you need to use results}

total hourly co2 = 103.85 kg/hr
total annual co2 = 103850 kg/yr

EAF

breakdowns look good. will look at carbon more in it's issue

**Comment by nbintertech** [comment]
Changes made:
fixed incorrect electricity use bug
fixed incorrect Nat gas cost bug
fixed coal carbon and electrode costs:
- no longer multiplying heating value * use of each and converting from kJ->GJ/Btu->MMBtu
- not using cost conversion

**Comment by koay9f** [comment]
Honestly, I think this is done, but I'm getting confused.  I think I'm going to close this and once the next round of PH stuff is in, just make new issues for anything I find.
