### ISSUE TITLE
Steam Calc's crashing app

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5273]
Steam calcs (maybe just turbine) are crashing app when changing property type.
only noticed with turbine, isentropic efficiency. 
No error messages. 
Maybe failing the steam properties assiging a region in the suite. 
How did we keep that from happening elsewhere?  Was there a bit of a delay before calculating? 

![steamBug.gif](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4d9a7f7b-9514-4df3-9b1b-26a87d16f667)

**Comment by rmroot** [comment]
Two problems:
1) the validation was not being properly updated on form changes
2) The suite had the outlet steam properties calculation hard coded to use temperature, so when passing in an entropy value it crashed the calculation.
![image.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/6decdadd-8fe6-4220-a8fa-d18ae707193e)
