### ISSUE TITLE
Pumps Tutorial

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5299]
[https://app.zenhub.com/files/80439269/85425037-2257-4da5-ab71-e36a2d6ff66a/download](https://app.zenhub.com/files/80439269/85425037-2257-4da5-ab71-e36a2d6ff66a/download)

**Comment by rmroot** [comment]
work done in `tutorial-pdf` branch

PDF added, here is the word document version:

[https://app.zenhub.com/files/80439269/462153a2-471a-41ea-9d69-42b42721e026/download](https://app.zenhub.com/files/80439269/462153a2-471a-41ea-9d69-42b42721e026/download)

**Comment by koay9f** [comment]
A few grammar / layout tweaks and a few places where I beefed up some of the material. 
[https://app.zenhub.com/files/80439269/e3a753f3-314b-46b1-883c-862308e0bb24/download](https://app.zenhub.com/files/80439269/e3a753f3-314b-46b1-883c-862308e0bb24/download)
