### ISSUE TITLE
Process Heating Tutorial

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5300]
[https://app.zenhub.com/files/80439269/3ac32ec0-8b31-4636-8106-90f1e11c5e88/download](https://app.zenhub.com/files/80439269/3ac32ec0-8b31-4636-8106-90f1e11c5e88/download)

**Comment by rmroot** [comment]
[https://app.zenhub.com/files/80439269/7dadbf37-4e78-4bdb-af98-4dfb11305250/download](https://app.zenhub.com/files/80439269/7dadbf37-4e78-4bdb-af98-4dfb11305250/download)


first pass at user manual for process heating

in `tutorial-pdf` branch
