### ISSUE TITLE
Fan Tutorial

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5301]
[https://app.zenhub.com/files/80439269/2df23a6b-4016-4e17-a2d9-8578366ea502/download](https://app.zenhub.com/files/80439269/2df23a6b-4016-4e17-a2d9-8578366ea502/download)

**Comment by rmroot** [comment]
[https://app.zenhub.com/files/80439269/39652a81-f223-461c-a186-a23d1f7505ff/download](https://app.zenhub.com/files/80439269/39652a81-f223-461c-a186-a23d1f7505ff/download)

in `tutorials-pdf` branch

**Comment by koay9f** [comment]
[Uploading... Fan Tutorial doc.docx]

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/8c49b9b4-7e41-4ce2-bfa1-acb77bab33be/download](https://app.zenhub.com/files/80439269/8c49b9b4-7e41-4ce2-bfa1-acb77bab33be/download)
