### ISSUE TITLE
Wastewater tutorial

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5304]
[https://app.zenhub.com/files/80439269/dc3b7904-4f56-49ef-8dde-af1e23cc13d1/download](https://app.zenhub.com/files/80439269/dc3b7904-4f56-49ef-8dde-af1e23cc13d1/download)

**Comment by rmroot** [comment]
[https://app.zenhub.com/files/80439269/348dfb80-29e0-4256-8552-32259b5782bc/download](https://app.zenhub.com/files/80439269/348dfb80-29e0-4256-8552-32259b5782bc/download)

in `tutorial-pdf` branch
