### ISSUE TITLE
CO2 error message

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5307]
Not sure what this is about or if it is important.

When you open the operations page in 
pump, fans, steam, TH, PH:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/66cc8df8-072a-4217-add4-61fc7dfe3fc2)

not in motors...

**Comment by nbintertech** [comment]
A fix for this is in PR. Will verify in #5262
