### ISSUE TITLE
CO2 Emissions EAF Updates

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5325]
Needed mods and changes to CO2 emissions due to #5267

Added Forms for electrotech with EAF:
- Natural gas emissions rate
- Coal Fuel options (list from coal and coal from other fuels) and Coal carbon emissions rate
- 'Other' Fuel options (list with  everything that isn't NG & steam/hot water) and Other fuel emissions rate
	- Added mixed fuel emissions calculation

Added report result data tables:
- hourly electrical/chemical used (converted to kWh)
- annual emissions
- annual costs
- Hide three tables and corresponding rows depending on whether in report or results panel and electrotech vs EAF

Moved existing result rows
Fixed existing result display for heat delivered rows

**Comment by koay9f** [comment]
Carbon CO2 label & associated math should be kg / mmbtu
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a41edb96-e677-404f-b16b-0c919cacf6e3)
kg to tonne conversion needed
coal math should use calculated energy use in mmbtu not lb
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/744c44fd-17a7-4bbf-905f-91058f002089)

**Comment by koay9f** [comment]
SO CLOSE!!!!!!
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/31dc68e4-ff1c-48f1-9d53-cfc4b58a5e44)
Coal: 1 lb/hr * 15000 btu/lb * 1000 h/yr * 100 kg/MMBTU *  1MMBTU/1000000btu * 1tonne/1000kg = 1.5![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f6e7ce28-eadb-45fa-9767-8c65bdf711a2)
Electrode: 1 lb/hr  * 1kg / 2.20462lb * 1000 h/yr * 44/12 kg/kg *  1tonne/1000kg = 1.5
Electrode = `Electrode Use` {converted to kg} * ophours * 44/12 {convert to tonne}
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a4ec927c-b60e-44b8-8696-e510057139c5)
Coal: 1 lb/hr * 1000hr/yr * $0.1/lb = $100
Electrode: 1lb/hr * 1000h/yr * $3/lb = $3000

Also FY a lot of errors when start new assessment
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/28102ab0-773e-414c-82a2-d411057052c9)

I think sometime I'd like to add pie charts that were the breakdown of energy use, emissions and costs for the 5 categories, but that can wait :D

 [https://app.zenhub.com/files/80439269/fd125055-69d1-4548-8430-a0933dc817fa/download](https://app.zenhub.com/files/80439269/fd125055-69d1-4548-8430-a0933dc817fa/download)

**Comment by koay9f** [comment]
SO SO CLOSE!!!
I forgot to delete the first pic above.  Electrode needs a math tweak. it doesn't have the electrode use's ** convert to kg** (in imperial it is in lb)

Electrode: 1 lb/hr * 1kg / 2.20462lb * 1000 h/yr * 44/12 kg/kg * 1tonne/1000kg = 1.5
Electrode = Electrode Use {converted to kg} * ophours * 44/12 {convert to tonne}
