### ISSUE TITLE
Sankey Print

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5339]
has weird lines
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/90c0513e-1094-408f-8b93-8d99d11687ee)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6d584cbb-ee10-4cf7-b350-d5e00000e841)

**Comment by nbintertech** [comment]
Dropping this for the moment to work on other priority. 

Bug here.. https://github.com/plotly/plotly.js/issues/4547
Only hunch is that there are some Plotly initialization animations which are smearing. Possibly a 'smearing' from the text style or shadow?
**Looks like sankey prints clean in both VERIFI and MEASUR web app but not desktop app wrapped w/ electron. Look into changing electron print**

**Tried:**
x - chart seems to be fully rendered and document ready status complete before printing is done
x - turn off animations at CSS level. Works for rendered plot but not printed sankey
x - try delaying print timer 
x - force a window focus on page
x - try checking document on ready from window service
x- hide labels if print view and put the labels into a table

- change text style/shadow
- Render sankey with a method that does not include init animation
- Look into different electron/print methods

https://gist.github.com/fcingolani/3300351
https://stackoverflow.com/questions/49650784/printing-a-pdf-file-with-electron-js
https://www.electronjs.org/docs/latest/api/web-contents

**Comment by nbintertech** [comment]
Dropping this for the moment to work on other priority. 

Only hunch is that there are some Plotly initialization animations which are smearing. Possibly a 'smearing' from the text style or shadow?
**Looks like sankey prints clean in both VERIFI and MEASUR web app but not desktop app wrapped w/ electron. Look into changing electron print for sankey or general**

**Tried:**
x - chart seems to be fully rendered and document ready status complete before printing is done
x - turn off animations at CSS level. Works for rendered plot but not printed sankey
x - try delaying print timer 
x - force a window focus on page
x - try checking document on ready from window service
x- hide labels if print view and put the labels into a table

Look at...
- change text style/shadow
- Render sankey with a method that does not include init animation
- Look into different electron/print methods

https://gist.github.com/fcingolani/3300351
https://stackoverflow.com/questions/49650784/printing-a-pdf-file-with-electron-js
https://www.electronjs.org/docs/latest/api/web-contents

**Comment by nbintertech** [comment]
branch 'upgrade-plotly' can be used for testing this
