### ISSUE TITLE
Printing Rollup BUG

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5360]
Tried to print rollup

Got these errors
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f40fe8e3-0d21-4a79-a04a-c240d7b2dcf0)

MEASUR SLOWED DOWN.  Thought it froze, but eventually started responding (wouldn't update as I changed window size or click things).
I *think* it was b/c it was still working on printing the (very long) rollup report. Should we maybe keep it in the "printing screen" longer?
The first time I tried to print, the pdf never got beyond the first page and Since I thought it had frozen I closed out and the "print" just never finished. Second time I did get a pdf.

I'm guessing there are a couple different issues here, so split this up as needed...

**Comment by nbintertech** [comment]
We'll probably just need a conditional unsubscribe in system-profile-graphs. The other issues may have been a snowballing effect

**Comment by rhernandez-intertech** [comment]
can not recreate bug
