### ISSUE TITLE
Highlight differences from BL - PHAST

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5364]
There are instances (especially with newer fields) where MEASUR doesn't register a difference between the baseline and mod in assessments - both individual field highlighting and badge changes

Below is a list of known fields, but there may be more

Basically any CO2 emission factor field (or the associated dropdowns)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4d1c725a-ce61-407a-9c50-538782e579e0)

New cost fields in Process Heating - Electrotechnology - Electric Arc Furnace
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/301780b4-8e5f-4b80-916e-1899ef1b4950)
I checked the rest of process heating  - CO2 related fields and 2 new fields need the blue
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2fb2bf11-d4e4-43c1-8b43-dfa95506148c)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b0934867-eea6-485b-9b6f-557c8e3165c3)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/61c0cd49-28b0-4832-a075-53c69659433f)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bf6503be-5c92-46fa-9a7b-9b9feab53c28)

steam
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b6fd77ba-c793-4470-acc0-9856c84e9978)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/abf47cf7-69dd-451c-a80b-7e40669b1abf)
This one may have been an artifact of being an older assessment...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f7b55623-7477-4741-a7f2-39b55659bca9)

I haven't looked at Pumps, Fans or wastewater. They will need to be checked quickly
Compressed Air doesn't have an Expert mode, so only the View/Add Scenario button needs to be tested

**Comment by nbintertech** [comment]
I would break this into new issues by assessment type and assess effort points as you go. Start with PHAST (use this issue for it and drop the effort points). 

The task may get larger when getting into the CO2 fields. Break out as appropriate.

**Comment by koay9f** [comment]
buggy bug bug bug

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/df27373d-e8ba-475d-8a27-7c4be5e46186)

**Comment by koay9f** [comment]
process heating - electrotech - electric arc furnace
Operations
the new costs still don't make the badge change or show up in the veiw/add scenairos list
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d952ae5a-3207-4431-9269-297eeec7c61c)

process heating - fuel fired
Flue gas
Moisture (gas form) - no change in badge or V/A scenarios
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/29d45094-3582-42a1-a481-5dbad1effdf4)

**Comment by koay9f** [comment]
Looking good.
One field in Fuel PH:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d4ebe428-ee03-4e96-830e-76e4ba8766ba)
