### ISSUE TITLE
Compressed Air: Air Leak Survey Orifice Method

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5377]
There is a bug somewhere in the calculation. The original excel sheet is giving the proper answer but doesn't match MEASUR. Alex is combing through to find the issue.

**Comment by AlexBotts** [comment]
StandarDensity and sonicDensity are being calculated incorrectly. I also don't see caDensity being calculated at all. 

caPressurePSIA = supplyPressure + atmpressure
caDensity = (caPressurePSIA * 144 / 53.34 * airTemp)
standardDensity = atmpressure * 144 / (53.34 * airTemp))
sonicDensity = (caDensity * (2 / (1.4 + 1)) ^ (1 / (1.4 - 1)))

**Comment by AlexBotts** [comment]
Assuming calculations above work out, the label on the UI for SupplyPressure will need updated to "psig"

**Comment by rmroot** [comment]
this is a suite issue BTW

**Comment by AlexBotts** [comment]
Moving to the suite side
