### ISSUE TITLE
Correct fuel emissions factor conversions

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5382]
- Steam and TH emissions data should get converted when existing assessment goes imperial to metric
- Steam and TH fuel factor should convert properly when used in metric.

Use inverted energy conversion convert units service

**Comment by koay9f** [comment]
- [ ] Steam: convert assessment from imperial to metric - good
- [ ] Steam: setting value when in metric - incorrect
- [ ] TH: convert assessment from imperial to metric - good
- [ ] TH: setting value when in metric - good
