### ISSUE TITLE
Remember losses tab when different modification is selected

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5392]
**SEE LAST COMMENT**
When I select a different modification, the app should keep me on the same tab. I.e. if I am currently on operations and select a modification it will move me to wall or another loss.
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/b4bbc81a-2060-40d1-b4c3-9d819d68b84a)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/8d05500e-325d-44da-af1e-a03334e25b50)

**Comment by koay9f** [comment]
Kristina needs to review to see if this is feature or bug

**Comment by nbintertech** [comment]
Somewhat of a feature, tossing back to inbox for future

**Comment by nbintertech** [comment]
Permission to close?
