### ISSUE TITLE
Flue Gas Calc Help improvement

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5401]
This is true for anywhere the flue gas form is used (standalone, modal, PH assessment)

_Help text improvements_
* in help text show defaults or suggested ranges
* add default for ambient air, fuel temp, combustion air temp (65F)
*  Show higher heating value (energy / mass, not energy / volume) right under the fuel dropdown
* default values when reset form
* default fuel = Gas; Natural Gas (make sure it is there when you reset form)

**Comment by rhernandez-intertech** [comment]
Dividing this issue in two. This issue, 5401, will be for the new default values and the addition of Higher Heating Value. And the other issue will be for the adding suggested ranges to the Help Text.
