### ISSUE TITLE
Type of Areator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5435]
Make the name for "Type of Areator" change depending on the bubble type
if option is only blowers: "Type of Blower" and "Blower Speed"
if option is only aerator: "Type of Aerator" (no change)
otherwise: Type of Aerator/Blower, Aerator/Blower Speed or if can't do the dynamic

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/471de233-0c1e-46ee-b706-feee6ab5ca40)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/04579ec0-6108-4d9d-9700-a840950bea28)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c9fe86c5-25c1-43a2-b585-81e4ae0671cd)

**Comment by rmroot** [comment]
Should the first dropdown label be changed from 
"Aerator" to  "Aerator/Blower" ?
How about "Aeration Operating Power" ?
