### ISSUE TITLE
Reset System Settings bug

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5446]
Toggle checks are tied together when they should be toggling separately. Check each label/check input is using different id's

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/27efc1cd-1c10-445f-b0a2-d4428e3253e7)

**Comment by rmroot** [comment]
Okay so this is actually intended behavior. If "Delete User Assessments" is selected then "Reset Example Assessments" will also be selected but that could be confusing so we are going to reset the examples if "Delete User Assessments" is selected but just not have it checked.
