### ISSUE TITLE
Inlet Pressure validation style

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5454]
Create a new FSAT > Field Data --> Inlet pressure validation style has possible mispelling or is looking for the wrong property
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/1adc9529-032c-4134-98c8-4b496e3055e1)

**Comment by koay9f** [comment]
main issue looks good, but why is there an error for inlet velocity pressure?
It is also not effecting calc or top badge, just red highlight.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/179db772-594e-4bd6-9c58-b25caef0242b)
