### ISSUE TITLE
Profile Summary Graphs Styling

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5509]
1. Fix headers
2. Fix missing scrollbar

I believe these were resized and aligned correctly at some point before CA printing style changes were made. Either way we should clean these up. Shortcut -  try looking at commit history in vscode to see when/where it was changed and revert back to that style without changing print rendering (if it's accurate).
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/5614294c-40f0-4f23-aeae-e815f2e9d684)

**Comment by koay9f** [comment]
Scroll bar still missing

**Comment by koay9f** [comment]
Scroll bar is there - 
but now need a bit of padding at the bottom (sorry to keep adding)
