### ISSUE TITLE
WW BL vs Mod diffs

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5527]
BL vs Mod diff highlighting should not be shown when in system-basics. Also present on activated sludge --> volume field. This can probably be fixed with a simple call to canCompare() or a check if (!insetup) in the forms.
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/b8f6afd4-e475-4a52-ba14-9b8fd37831b9)

**Comment by ysintertech** [comment]
not able to reproduce, closing issue for now.
