### ISSUE TITLE
Audit folder/directory functions in the explorer

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5535]
Generally look at select boolean logic. May take a few tries to reproduce..
- directories not selectable immediately after creation
- copy/move multiple items stay selected after action

**Comment by nbintertech** [comment]
@kaichen127 Try to reproduce these and see if they still need addressed

**Comment by kaichen127** [comment]
weird case: after copying an assessment, directories are not immediately selectable (_.find() shows undefined for selected subdirectories for some reason)

**Comment by kaichen127** [comment]
Fixed issues:

Issue 1 : exporting anything under a directory (including when the 'select all' button is clicked) doesn't work properly - after re-importing the exported file, the directory is imported as completely empty
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/e172be9d-3cb5-46e5-a6c4-73572001d6c5)![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/39ef2352-f899-4da9-83a7-caed02bf91f4)
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/2d5a6cda-aa20-4c1c-8c7f-5741e5f86065)

Issue 2 : recently imported directories aren't selectable - the buttons on the top (e.g. 'Delete') don't react to the directory being selected

Issue 3 : after clicking 'Select all folder content' and then unselecting any item (directory, assessment, inventory), the Select all button remains checked

Issues that need to be fixed:

After copying an assessment/inventory, directories aren't selectable (buttons on top don't react to click)

**Comment by nbintertech** [comment]
This is in release, need to merge release-1.3.0 or cherry pick changes to update
