### ISSUE TITLE
Release Notes v1.0.1

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5569]
Release notes and version number change

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/b7c1eee8-3937-4df8-afed-7f85f3a3eeb4/download](https://app.zenhub.com/files/80439269/b7c1eee8-3937-4df8-afed-7f85f3a3eeb4/download)
Here's the release notes.  The only things outstanding are 1 more tweak to the CA printing and the CA example. Both of which are already in the notes.
