### ISSUE TITLE
Data Explorer seconds getting lost

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5595]
Figure out something to help when seconds get lost b/c of bad data formatting (problem for csv, maybe xlsx)

Maybe something that lets the user say, well it is 5 second data and we just concencate things together?

**Comment by rhernandez-intertech** [comment]
The seconds are getting "lost" when the data is being read from an .xlsx or .cvs file.
This is messing up how the data gets graphed.
