### ISSUE TITLE
Psychrometric Chart Enhancements

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5597]
Add multiple points to chart.

Motor Performance - added by clicking
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d273c6f5-dff5-4a20-b43f-f32a92d3ba0d)

Not sure if we want to go the clicking route.  Maybe combine the "Add Row"  and just graph all the points in the table
Do we need the lines for all of them?
Do we want lines connecting them?

**Comment by rhernandez-intertech** [comment]
can only make points on existing lines and those line do not say Rel Humidity or Wet Bulb, only get x, y data
