### ISSUE TITLE
Compressed Air Export

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5602]
So we can't export CA assessments with all the DE data attached b/c way too big.
BUT
it would be really handy if the useful stuff was exported so that other users can change things around later and make sure everything is properly applied. 

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b351b814-7ad6-4124-adc2-7e3816768427)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9e6a2156-2756-4e53-b06f-fd80e2b8988c)

**Comment by nbintertech** [comment]
Looking at other options.
The bytes/string limit in place is the limit for browsers in memory export. Original issue https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/1615
