### ISSUE TITLE
Fan Inlet & Outlet pressure modal not updating in Assessment

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5612]
In explore opps the inlet outlet pressure modals don't have a "Save and Exit" and "Apply Data" doesn't work (doesn't update calcs from BL and doesn't save or apply). Seems to work in expert view
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/738c9064-9361-45ca-ae99-3b7e8b326a20)

**Comment by rhernandez-intertech** [comment]
once the Inlet and Outlet pressure modals updated things properly, compressibility factor needs to be updated from Explore Ops or else a "Change after Check" error occurs when switching to Expert View. So that was addressed in this issue as well
