### ISSUE TITLE
Handle CA CO2 input display when no emission rate

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5616]
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/0bd3f602-ad99-48c4-acd5-0488661e9eed)

**Comment by JL102** [comment]
reproduction notes
Step 1) Create a new Compresses Air assessment. 2) Fill out the assessment: you can enter 500 for total air storage in system information and set data from an existing compressor in inventory. 3) Go to the Report tab. 4) click print -> select all ->  print. Then the errors will pop up in DevTools console
