### ISSUE TITLE
Process Cooling Help Text

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5628]

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/c98e9546-1d13-4b1d-bc03-ae84022c9b78/download](https://app.zenhub.com/files/80439269/c98e9546-1d13-4b1d-bc03-ae84022c9b78/download)

**Comment by koay9f** [comment]
There's a large amount of padding on the left side of the help text for Olling Tower Basin Heater
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/441f94ef-b59e-4bbb-8c43-1f73181acb99)

**Comment by koay9f** [comment]
Basin Heater edits:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/82f1bc35-a1bb-418c-99cc-00445f2fbd21)

Chiller energy perf edits
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d594f815-ed4f-4c89-80c0-978749375b88)

**Comment by koay9f** [comment]
One more:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4708600d-baaf-40e6-bda5-4ca3df7ef2c9)
