### ISSUE TITLE
Phone/Tablet UI Inspection

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5638]
Now that web is working we should do a run through of the application on phone/tablet sized screens and create some issues (probably an epic) to better handle those views.

Some areas may not realistically be usable but other areas can be enhanced.

Some examples:
- Dashboard cards
- Standalone calcs
- Reports
- Sidebar/navigation
- Modals

**Comment by nbintertech** [comment]
Assess what needs to be done here, broken down by section. Then meet with me and we'll develop an epic

**Comment by nbintertech** [comment]
Closing - broken down to #5786
