### ISSUE TITLE
Total Downloads CSV/XLSX

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5648]
We need to be able to run a standalone script (probably python/nodeJs) that can call the github API for download data of MEASUR/VERIFI and then compile a spreadsheet showing total downloads

```doing "total downloads" include everytime a .yml file gets pulled which is everytime the app checks for an update or everytime the app is opened```

**Comment by JL102** [comment]
[downloads.csv](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/8922579/downloads.csv)
Current output titles: Name, Date, Windows, Mac .DMG, Mac .ZIP, Linux AppImage, Linux Tar.GZ, latest.yml, latest-mac.yml, latest-linux.yml
Any requests/changes before it's finalized?

**Comment by koay9f** [comment]
looks good!
