### ISSUE TITLE
Chiller Staging Calc improvements

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5652]
* Defaults for "Design/Max Capacity Ratio" 
     - if chiller type = "Centrifugal" --> default = 0.92
     - if chiller type = "Screw" --> default = 1
* Disable "Design/Max Capacity Ratio" field if selected chiller type = "Screw" (and make sure value =1)
* Reset Data --> Chiller type = "Screw", Ratio = 0.92

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9e16d0de-acd3-4557-b390-c6dcb801f248)

**Comment by JL102** [comment]
Note: Waiting for word from Wei before doing the third bullet point.

**Comment by JL102** [comment]
Testing note: Prior to fixes, switching to type = Screw and then clicking Generate Example or Reset Data would keep Motor Drive Type & Compressor Config Type disabled.
