### ISSUE TITLE
Cooling Tower Basin / Heat Validation

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5661]
Add validation to fields in PC calcs
[https://app.zenhub.com/files/80439269/101142f2-9b6f-4081-9b8e-ca5a255caf33/download](https://app.zenhub.com/files/80439269/101142f2-9b6f-4081-9b8e-ca5a255caf33/download)

Red = stop calculations (don't show any results/don't send to suite)
Yellow = just show message
Assume the number shown for min/max is valid unless cell is outlined

Red example:
FIELD NAME must be greater than 0 [units]

Yellow example:
Basin temperature set points are usually less than 50 F

make sure the message and checks have unit conversions (see basically any other calculator for example)

**Comment by nbintertech** [comment]
Basin / Perf moved to #5703

**Comment by koay9f** [comment]
I feel silly for throwing this back, but  there is a comma at the end of the message
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d34d63d9-6c7e-4f9f-9cb3-6f5c7bde17b7)

Fan energy
message cut off
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4c023618-6ef6-4b22-8bae-71227ef381d6)
