### ISSUE TITLE
Arrow key - Pump & Fan Assessments

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5668]
Change amount field changes with single arrow key strike

**Comment by koay9f** [comment]
Pump `Pump & Fluid`
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/661117cb-6229-47bb-886e-3720d51d8978)
Pump `Motor`
[STILL NEED THIS ONE]
Pump `Field Details`
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b6c88c88-a516-492f-b944-b48e048dc8b0)
Head Modal - is a standalone calc - leave for now

**Comment by JL102** [comment]
Note: Same multipliers in the modification screens in the Assessment tab

**Comment by koay9f** [comment]
looks good.  Do a quick check with some things like motor rpm and motor power that they have the same step in other assessments (motor inventory & compressed air).
There are some pages on fans that are a bit different that you need to glance at.
Fan & Fluid: 
air Density: x0.1
Specific Heat ratio: x.1
Field Data: leave alone I think. the values are too different in metric, it will really throw things off
