### ISSUE TITLE
Arrow key - Compressed Air assessments

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5669]
Assessment Basics
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/3b4c3022-d4ef-4fb6-92a3-ccaba7042ee7)

System Information
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/4fca776a-e5f2-44ce-944e-da59e78e5915)

Inventory
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/847b37c6-b616-4ca0-bf70-caa3a14722ff)
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/ba3f22ed-04b4-408c-bd5f-e69984032f8c)

Day Types
[ALL x1]

System Profile -> Profile Data
[ALL x1]

**Comment by koay9f** [comment]
System Information > System Elevation x10
System Information > Total Air Storage x10
Inventory > Motor Power x10
Inventory > Design Inlet Pressure x1
Inventory > Motor Service Factor x0.1
Inventory > Proportional Modulations... x1
Inventory > Max Full Flow Pressure x1
Inventory > Performance Points {All} x1
