### ISSUE TITLE
Code cleanup: CSS classes for calculator icons

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5678]
The classes `ico-size`, `ico-size2`, `ico-size3`, `ico-size4`, and `ico-size5` are a bit of a mess. They all refer to the same size (55px), and the only difference between them is the background color. The steam and waste-water icons have the right idea: they extend `ico-size4` and change the color based on the additional class `steam` and `waste-water`.

Proposed changes:
1. Rename `ico-size`, `ico-size2`, `ico-size3`, `ico-size4`, and `ico-size5` to `ico` to determine their size and shape
2. Use the classes `ico-general`, `ico-compressed-air`, `ico-fans`, `ico-lighting`,  `ico-motors`, `ico-process-cooling, `ico-process-heating`, `ico-pumps`, `ico-steam`, and `ico-waste-water` to determine their color.

**Comment by nbintertech** [comment]
Reminder to run through a Treasure Hunt to verify styles look correct where the calculators are integrated there.

**Comment by JL102** [comment]
Awaiting feedback from Tom on whether we want to remove the background gradient on "reduction" calculators with a circular icon and their own background.

![electron_2022-06-17_14-51-02.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/dba3c3d0-25a6-4dbd-8842-08aa10bb1dc4)

![electron_2022-06-17_14-50-38.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/a143289f-1f77-4446-bd28-5b6a384b6a06)

**Comment by koay9f** [comment]
Per Tom - Leave the reduction calcs as it (with the gradient).
