### ISSUE TITLE
Arrow key - Motor Inventory

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5683]
Plant setup
![electron_2022-06-15_13-49-34.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/280ff5f4-3248-4f26-9952-f1317d6cd50f)
Departments
![electron_2022-06-15_13-51-17.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/4487e953-fca2-4d1c-9f07-6df7e2d1744e)

Catalog -> all
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/ab516eea-8be3-43b3-b99e-c258d5ee52bd)
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/27d18f99-f104-4c16-aae5-bc9240a0a0f4)
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/8cb674fc-3cf9-4f7f-88ce-44b36b85614e)

**Comment by koay9f** [comment]
Everything is pretty good
Rated Motor Power x10
