### ISSUE TITLE
Arrow key - Treasure hunt

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5684]
Energy usage and cost
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/8aee0f3d-a653-4b6c-b419-b9e8c569d4d0)
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/c42c05ef-bc2b-4d27-9d47-2de78d3fa379)

Calculators in other issues

**Comment by koay9f** [comment]
Good call on not doing the calculators.  Those use the same forms as the stand alone calcs, so things should just follow along.
I think none should have more than a x100, and most carbons should be at x1 (electricity being the exception)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7537f11a-90e3-424a-9166-f119935d3925)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d972bcec-eb2a-4c79-8060-652234fc0026
)


There is one calc that isn't a standalone:
It's the last one in the list
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/44659edc-04be-4dc8-8332-9bafb8c7e559)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f9ee292c-806c-4aa5-b2b3-637ddb611217)
