### ISSUE TITLE
Pre-assessment standalone colors

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5699]
Things should be green
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b3efd248-0e69-4706-8ee0-201c88702ccd)

**Comment by nbintertech** [comment]
Wondering if this is outdated. We currently change the color for each energy type. pump below
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDBaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e8d214babb56e7e731fa5a09facca8bc552b21b/image.png)

**Comment by nbintertech** [comment]
Closing -fixed so color changes with energy type in 6380
