### ISSUE TITLE
something that pings zenhub for # issues in each pipe

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5727]
talked about this last week...

**Comment by JL102** [comment]
As discussed offline: This script will not be put into any of the ORNL-AMO repositories, as it is for task-keeping, unrelated to the tools themselves. 
For the time being, it has been put into a new public repository under my own account: https://github.com/JL102/ORNL-AMO-ZenHub-Stats
