### ISSUE TITLE
MEASUR release does not load on Firefox

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5741]
From commit f681ac7f4e:
`ERROR TypeError: window.indexedDB.databases is not a function`

It appears that `indexedDB.databases()` is non standard and only exists on Chromium browsers. Is this function call necessary to load the app? https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

core.component.ts:
```js
    // const start = performance.now(); 
    window.indexedDB.databases().then(db => {
      // const duration = performance.now() - start;
      // console.log(db, duration);
      this.initData();
    });
```

**Comment by nbintertech** [comment]
Verified working in prod
