### ISSUE TITLE
Dropdown chevrons (v and ^) point in the wrong direction on Custom Materials and Settings

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5743]
Collapsed dropdown menus should appear with a downward chevron ("v"). Sometimes expanded dropdown menus keep the downward chevron, but sometimes they get a bit of visual flourish by inverting the chevron ("^"). The "About" page does this correctly, but Custom Materials and Settings do it incorrectly.

Custom Materials start out expanded, so their chevrons should start out like "^":
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/5a6715fe-4562-4f5f-9458-a1a5ff8d0c95)

Settings start out collapsed, so their chevrons should start out like "v":
![image.png](https://images.zenhubusercontent.com/629f63e243d33b2a6a3a59f2/d5edab78-5de7-46a2-a6e9-5380db20e591)

**Comment by rmroot** [comment]
If expanded then chevron should be down

If collapsed then chevron should be up

Looks like just the About page should be changed.
