### ISSUE TITLE
Chiller Performance TH Integration

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5758]

**Comment by koay9f** [comment]
Savings on card doesn't match gauges
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d527813e-dbcc-4ee1-8583-73ed9e4fdf9e)

**Comment by koay9f** [comment]
After clicking in the Edit Calculations then hitting "X" gauges disappear
and if you do it too many times the app seems to freeze (clicking doesn't work).
no errors
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d04b8657-b08a-45cc-babc-ffde26727e37)

**Comment by koay9f** [comment]
Just going to put this in here.  not sure which calc is the problem, but PPT export isn't working
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2924b7a8-0150-4fe1-bb1b-62aee5edc2e5)
