### ISSUE TITLE
Cooling Tower Fan TH Integration

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5759]

**Comment by koay9f** [comment]
Getting an error from this one.

Also , the annual savings in the card do not match what is in the gauges
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f69e596d-3827-44ec-a3c5-3c479e4af285)

**Comment by koay9f** [comment]
Same secondary bug as energy perf & temp reset (lost gauges, haven't frozen yet...)
