### ISSUE TITLE
Cooling Tower Basin TH Integration

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5760]

**Comment by rhernandez-intertech** [comment]
This calc uses Weather Data to generate a second set of results aside from the results generated from the calc itself, so we need to decided which set of results we want to use for Treasure Hunt, and if needed, restructure the calc to require the use of weather data

**Comment by koay9f** [comment]
Can we hide the option to see the "See Calculated results"?
It is just kind of confusing
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c92d9096-429e-4f13-ae8d-ae525ce4967b)
