### ISSUE TITLE
CompressedAir: Debug -  0 power = 0 flow 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5764]
When 0kW is entered into the profile the airflow should also be 0. I think this is a bug. I have the .json and csv data, not able to upload here

![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/06d9ccf1-9c64-45b3-9bb0-92ace95c78bf)![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/da3a0bd9-82a4-4b97-bf4d-0ffdaee46ee2)

**Comment by rmroot** [comment]
fixes in issue for VFD calculations 

https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/657
