### ISSUE TITLE
Data Explorer: If less than one min error & other tweaks to functionality

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5772]
Had (exactly) 1 minute data intervals and it is yelling at me

I think we need to look at the trigger for the warning and make sure it only triggers if < 1min and not <= 1 min.  AND make this a yellow warning (so you can move on even without a working time stamp, it is just at your own risk)
Additionally - maybe make it so the drop down feels more optional or has a "not applicable" option so we can move on even with bugged data.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4aaeaacf-2263-4ea1-af9c-f91268241498)

**Comment by rmroot** [comment]
Not preventing advancing with warning. Created new issue to handle UI changes #5839
