### ISSUE TITLE
CompressedAir: Check EEM pressure calculations

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5777]
There may be a bug that needs to be confirmed in the EEM calculations. Reduce pressure and cascading set point, I think we dealt with this but documentation doesn't reflect. Need to check that a reference pressure is being used (either 14.5 or 14.7) for "P_atm" and the atmospheric pressure from the user is being used for "P_alt" in the equation below 

![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/cc595d8f-07d5-4a94-aaf4-618a015445fd)

**Comment by rhernandez-intertech** [comment]
![image.png](https://images.zenhubusercontent.com/60b7bed2e39f152beecc60b4/6c7e5083-2515-4b69-b725-d582959f7dfc)
@AlexBotts approved this issue.
