### ISSUE TITLE
Pop up error in new install

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#578]
![image](https://user-images.githubusercontent.com/25389736/29635422-037f5082-881b-11e7-8909-587106d81ac8.png)

When I try to click to change what page I'm on.  If click ignore enough it goes away and I can use the tool, but the head calculator is not working at all
![image](https://user-images.githubusercontent.com/25389736/29635469-26a33164-881b-11e7-9812-0dd893086a17.png)

**Comment by gaccawi** [comment]
Issue resolved.
