### ISSUE TITLE
Display delayed

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5790]
Was really confused for a bit until I realized the many part was just delayed or something. 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7ef0f9f0-af0a-4205-a51e-a40512915dd6)

I tried navigating away and coming back but I think I had deleted the account that was dispalying on the right and the left is actually what was delayed.

**Comment by nbintertech** [comment]
Closing, moved to VERIFI
