### ISSUE TITLE
Navagation back to data explorer once applied data to CA

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5801]
Users have commented that it is difficult to return to the data explorer to review their data after it has been applied.
Brainstorm ways to make this a bit more smooth.

**Comment by nbintertech** [comment]
I brainstormed a few other ideas on this, but for now just implemented the minimum  - what we had talked about.

- Add direct link from profile table to de
- Add a few more hints/messages about apply to assessment functionality

**Comment by koay9f** [comment]
Looks pretty good, but the button should be visible even when you are using "Set data from data explore"
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/680ca72d-7021-427e-b505-7ee5f010a71c)
not here :(
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8b7d1c4d-c067-4b31-a6c7-ceaade31622c)

Also side note - what is that warning?  Maybe have that dropdown default to blank instead of already having something selected? that way the warning can show until you have something set for all daytypes.  We may also want to rethink this workflow a bit :(

**Comment by nbintertech** [comment]
I see #6287 was opened, maybe a continuation of this
