### ISSUE TITLE
CompressedAir: EEM Shutdown Timer 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5811]
In the assessment, when a shutdown timer is used, and the flow is == 0 turn compressors off and use dashes to represent. The shutdown timer can be set in the baseline or from the reduce runtime EEM 

![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/2d094a9e-93fc-4e5b-8239-b065951f2148)

**Comment by rmroot** [comment]
all is working correct as-is. Closing
