### ISSUE TITLE
FSAT WASM bindings error

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5814]
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/cdcde1eb-811d-42d7-a35f-f380653a3c34)

**Comment by rmroot** [comment]
Problem was undefined compressibility factor. 

It was supposed to be calculated but inlet and outlet pressure = 0 so was being set `NaN`

added null check before calling suite.

may need to look into calculation when inlet and outlet = 0
