### ISSUE TITLE
Release Notes and Version Change

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5819]
Update version to v1.2.0

add release notes

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/a613df11-8c12-4e77-888a-b6c780332e68/download](https://app.zenhub.com/files/80439269/a613df11-8c12-4e77-888a-b6c780332e68/download)

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/21b9cc46-33ec-49dc-875f-9e35231c84b7/download](https://app.zenhub.com/files/80439269/21b9cc46-33ec-49dc-875f-9e35231c84b7/download)
