### ISSUE TITLE
CompressedAir: Power when Flow is over 100%

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#5823]
When the flow is over 100%, the power should default to full load power. Currently it is producing 0kW

![image.png](https://images.zenhubusercontent.com/5e4ffc1aa541aecb7b4865d7/800e74bf-a764-4ed8-b5bc-88cc255f286a)

**Comment by nbintertech** [comment]
@AlexBotts  - created suite issue 662
