### ISSUE TITLE
Data Explorer Export to .json bug

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5834]
Frank unable to export data to .json file from data explorer

**Comment by rmroot** [comment]
The problem is that the data is very large (140 MB).

We are most likely going to address this when we do a Data Explorer V2 epic

**Comment by nbintertech** [comment]
Closing - we made changes to DE --> Compressed Air integration a few months back (can't find issue) and this is no longer a problem in DE.
