### ISSUE TITLE
Feedback Screenshot

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#584]
Tried to take a screenshot for feedback and this is what I get

![exportdata](https://user-images.githubusercontent.com/25389736/29688222-00662100-88ed-11e7-976b-5a4a13cf8473.png)

The same thing happens if I take a screenshot of the application in powerpoint or using the sniping tool.  I have to use "Screen Clipping"

**Comment by rmroot** [comment]
Appears windows has trouble with screenshots. Going to remove the screenshot link if the OS is windows
