### ISSUE TITLE
Low Priority Calculators for Training Release

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5885]
Last batch of calculators to apply responsive styles to

In order of priority:
1. Charge Mat
2. Cooling Loss
3. Opening Loss
4. Fixture
5. Atmosphere
6. Leakage
7. PH New calcs (waste heat, heat cascading etc);

**Comment by koay9f** [comment]
This is looking a little weird
Charge Mat, Cooling, Wall, Opening, Fixture, Atmo, Leak

Low priority though.  It can go into the release like this if needed, but if can fix it before, awesome

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/07a27d19-ea6d-40b6-8495-937b48e37a20)
