### ISSUE TITLE
Seperation between side bar and main body

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5899]
... seems to have disappeared. It looks fine in calcs with BL/mod, but in others, kind of weird looking

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4a79ccfb-bb84-4f4f-81ca-cb931c8d07c8)

**Comment by nbintertech** [comment]
Reverted to MEASUR scrollbars used previous to 5717
