### ISSUE TITLE
Moisture in Combustion Air Fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5919]
* Remove from Stack Loss Calculator UI (set to 0.73%)
* Update help text (reference that it is a percent)
* Work out actual min/max (there is a max amount of water that can be in air...)
* Maybe remove the `/100` and % symbol and just make a fraction

**Comment by nbintertech** [comment]
BY VOLUME
Desktop unit in help text as %
Sent to suite as  fraction
```
SUITE METHOD
flueGasLossesByVolume --> 
getProcessHeatProperties --> expects fraction
```

BY MASS
Desktop unit in help text as %
Sent to suite as  fraction
```
SUITE METHOD
SolidLiquidFlueGassMaterial -->
getHeatLoss -- > expects %
```


Other methods used in calculator
BY MASS
calcExcessAir --> 
```
SUITE METHOD
flueGasByMassCalculateExcessAir --> expects %
```

```
SUITE METHOD
calculateFlueGasO2 --> expects %
```
