### ISSUE TITLE
PSAT - some fields can be removed from baseline

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#592]
Since we have removed the mandatory use of "optimization" some fields are not necessary from the baseline. 

However, they should still be available for modifications, in both "Explore Opportunities" and "Modify conditions"

Fields:
Pump & Fluid --> Kinematic Viscosity - 1
Pump & Fluid --> Fixed specific speed? - no
Motor --> Size Margin - 0

These are not used in the calculations for baseline but are used in the calculations for optimization.  

Let me know if I need to clarify this more

**Comment by koay9f** [comment]
Explore Opportunities Page
If click yes for Optimize... automatically then the fields are available

![image](https://user-images.githubusercontent.com/25389736/29731735-a04ed5b0-89b3-11e7-8420-6cd6703b399e.png)

Modify conditions Page
If click yes for Optimize... automatically then the fields are available
![image](https://user-images.githubusercontent.com/25389736/29731777-c7464efa-89b3-11e7-992e-56abc11b5cad.png)

All help text should be moved with them.  I will try to update them a bit more later to be sure they reflect why they will be popping up when you click the box.

**Comment by gaccawi** [comment]
Make sure no unintended consequences in the tools suite.

**Comment by pshires** [comment]
`https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/112`  - addressed in this PR, those input fields are now no longer needed in the baseline only calculation.
