### ISSUE TITLE
Bug in TH from Cooling Tower Makeup Water 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#5921]
there is something buggy going on with the unit conversions for Cooling Tower Makeup Water calculator in TH.
to recreate this bug, make a Cooling Tower Make Up Water opportunity, then change the units of measure in TH from Imperial to Metric, then change the units of measure back to Imperial and the bug shall appear.
![image.png](https://images.zenhubusercontent.com/60b7bed2e39f152beecc60b4/60c85812-be3f-4709-a0ee-432702c38601)

**Comment by nbintertech** [comment]
Closing... original issue still open
