### ISSUE TITLE
Web - Pipe Insulation Calc

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5928]
Something screwy with web pipe insulsation calc

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/56d6e161-4ad4-4a4b-bac8-231202dc4bcf)

Last week it seemed to work, but was giving different results from the desktop version, so also pls check that

**Comment by nbintertech** [comment]
Verify results against desktop version
