### ISSUE TITLE
Tank Insulation Calc - New Field

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5941]
Add new field "Surface Temperature" if Insulation is != "None"

Validation: bad if >= tank temperature or <=ambient

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/792372b0-e9bc-4686-be3c-a0ce58d2929c)

**Comment by nbintertech** [comment]
- Show surface temp if has insulation
- Must be less than tank temp, Must be greater than ambient temp
