### ISSUE TITLE
Steam Explore Opps Fuel Type

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5945]
Steam Explore Opps Uses the wrong fuel Type dropdowns

Explore Opps > Adjust Boiler Operations > Change Fuel Type
Still has the old dropdowns
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/761038df-d85b-407e-858b-1dc6d966f7ad)

Should have this (the carbon stuff): 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ef2691fb-de7c-44c7-92f1-ec4d7f4359a5)

**Comment by rhernandez-intertech** [comment]
Explore Opps > Adjust Boiler Operations > Change Fuel Type for BL and Mod should display the carbon emissions from fuel fields

**Comment by koay9f** [comment]
Change is good.
BUT
When I made a new Scenario, it kept the changes to "Change Fuel Type" and even kept the changes when I unchecked the box:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f3a6f9c8-549a-4c45-9403-f0e20cd8adce)

**Comment by nbintertech** [comment]
I fixed the issue with changes persisting on box uncheck. I couldn't reproduce the data being copied to a new scenario but I suspect this fix might be the same thing that caused that.

Tested:
ssmt example
creatae new ssmt
create new scenario (from all three locations)
switching scenarios

**Comment by koay9f** [comment]
Unclicking Fuel makes it clear out, so that is the main thing fixed.

But the persistance is still there.  I did however notice that navigatnig away and coming back does also make it go away, so I can't really send you a json with the issue.

1 - Made a new assessment (500 steam temp, 2's for other things in boiler; headers: 500, 300, 100)
2 - Explore ops - change fuel type
3 - Scenario 2 - change fuel type is still selected, but if nav away it goes away

Since you can clear it out it is not top top priority, but let  me know if you want to have a call about it
