### ISSUE TITLE
Surface Temp in tank insulation

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5955]
desktop issue for tank insulation fix

**Comment by rmroot** [comment]
duplicate issue to #5941

use this issue for web version updates

**Comment by rmroot** [comment]
Need to update the call for tank insulation to match new signature with new variable from:

https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/673

**Comment by koay9f** [comment]
We seem to be off by a factor of 100 somewhere
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/2b8ead06-0800-4bce-b86c-d7058381c62e)

**Comment by koay9f** [comment]
For some reason, the WEB version only is using the wrong value to calculate the mod's energy cost.
I think it is using 3.99 no matter what (or the previously entered value? not sure)
Either way, for the example, the mod cost should be something more like $12 (is correct in desktop)

**Comment by nbintertech** [comment]
Which version of the desktop are you using for reference?
- utility cost/energy costs in the web and current desktop version function the same
- in web/desktop the modification, utility cost is always 3.99
- in web/desktop modification appears disabled (but sends 3.99)

I'll remove the disabled modification utility cost and make sure the example is set to 12 in web/desktop. Anything else needed?
