### ISSUE TITLE
Compressed Air MaxFullFlow Validation bug

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#5972]
In VFD control type, Max Full Flow is not displayed, yet still makes design details form invalid.

**Comment by koay9f** [comment]
the above is good, but we are missing a message for this validation (No Load, Power)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5ed1e7e4-0c30-4a3d-933f-5b90e354912b)
