### ISSUE TITLE
Test electron-builder 23.0.4

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#5989]
need to test so gina can build on new computer

**Comment by nbintertech** [comment]
Will test installing forwards/backwards versioning again
From Alex:![image (57).png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/9f55bfa0-46d9-4c4f-9f89-490d6d765a5d)

**Comment by nbintertech** [comment]
Closing again, moving custom installer problem to an icebox issue
