### ISSUE TITLE
Remove max validation from electricity costs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#5994]
Remove the "cannot be greater than $1/kWh" from electricity field validation.
This validation is hindering international users

Maybe comment it out for now and eventually we have it dependent on the currency chosen?

**Comment by nbintertech** [comment]
Needed before next release

**Comment by nbintertech** [comment]
Fixed pumps and fans. Checked all calculators - everything else doesn't need it or has been done
