### ISSUE TITLE
Badge for Energy Input in EAF

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6026]
... doesn't revert to green/blue after fixing error regarding electricity input (importing old assessments).[https://app.zenhub.com/files/80439269/b7cb001b-575a-4ee4-938d-f8a2d384d200/download](https://app.zenhub.com/files/80439269/b7cb001b-575a-4ee4-938d-f8a2d384d200/download)

will also need to fix several costs.  
Carbon = 0.06
electrode = 3
other fuel = 4

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b86d80d6-5ff8-4e7a-a445-004a0b1c72e5)

**Comment by koay9f** [comment]
Does not need to be in for release, but I'm still getting a red badge for Energy Input :(

**Comment by nbintertech** [comment]
Validation for mod was being based off baseline values.
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/0dbea12a-ae15-4c79-9741-22024b63c98a)

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/9fdec195-85db-4aaa-98ff-7d4204aad6ae)
