### ISSUE TITLE
MEASUR v1.2.4 Release Notes and Version update

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6049]
- Add release notes to github release, app version modal
- Change version in app package.json

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/80439269/c0695e98-3415-41de-adff-14759ea391bf/download](https://app.zenhub.com/files/80439269/c0695e98-3415-41de-adff-14759ea391bf/download)

**Comment by koay9f** [comment]
also sending in slack
v1.2.4 notes:[https://app.zenhub.com/files/80439269/aa04acd2-04b0-4c32-9a83-312ebace6983/download](https://app.zenhub.com/files/80439269/aa04acd2-04b0-4c32-9a83-312ebace6983/download)
