### ISSUE TITLE
Last minute tweaks to TH graphs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6053]
The donut charts all have "Current undefined" instead of "Current Cost" or whatever they used to be.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6e41f48c-cd88-48df-a7b4-9c4c19ed78a8)

Before:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/17d5337e-b46c-4343-b092-fbbbc82e861a)

Also some trailing decimal places to remove
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/fd302536-bbc1-4f55-ac6a-1a86ebe0fa0f)

**Comment by koay9f** [comment]
Total CO2 donut still has a lot of decimals behind it.  
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/e393c370-63cb-4eb0-80b5-851b33747150)

**Comment by nbintertech** [comment]
Tieing this up since Rachel is out today
