### ISSUE TITLE
Day Type Analysis Graph

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6072]
Graph should show summation of avg power for all compressors at every interval (currently hour). 

Original log tool
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/f7d9a257-3d49-48d6-b5df-50bd94af158e)

Options...
This should be the default behavior for the tab?
Be able to select which totals are shown by day type?
Basically filter the graph totals by selecting/grouping different day types

**Comment by nbintertech** [comment]
I think we'll have to shop the 'all equipment/compressor/unit/reading/data' language in the next thursday meeting . Alex wasn't sure what would sound the best either, below is what I;ve gone with for the time being

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/5f658909-4e98-48e4-a07f-4d41772ffe7f)

**Comment by koay9f** [comment]
Overall I think it is really good. I think the language works for now. 

ISSUE 1:
You should still be able to switch between the Data's.  I can only look at the Total aggregated, not the individuals. EDIT: this happened when I first created the analysis. I added it to a CA assessment, then returned back and I could access the individual. no errors or idea why I couldn't at first.

ISSUE 2:
Everything should be included by default I think. It takes long enough to run the analysis that it would be kind of annoying to have to redo it EVERY time. Maybe the select columns section be on the initial page as well with the "Day Type Average Interval" dropdown? (if that will take too long, maybe make separate issue and handle after release)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9b45b9af-a194-4819-80cf-071dc4855735)

**Comment by koay9f** [comment]
Really should go in 1.2.4

**Comment by nbintertech** [comment]
Issue 1: Doesn't repro - will test more
Issue 2: Sounds like we're good here - still more testing
Issue 3: done

**Comment by nbintertech** [comment]
- Fix next/finish button confusion (when multiple datasets are present only show finish on last page)
- Use alias in DTA graph instead of fieldname
- Lose box shadows to match visualize tab
