### ISSUE TITLE
Solid Fuel Composition

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6074]
Why is ambient air temp in here.  it doesn't seem to do anything
ambient air temp is now part of the main form, could we just use that for whatever this one is for?

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d2dcc67b-b63a-4781-814b-28e056fd5713)

**Comment by nbintertech** [comment]
Removed - I think this was added by mistake in 5674
