### ISSUE TITLE
Testing on Annotations and user dataset issue

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6075]
- Annotations did not show during Demo with Frank. Use all Fuji Data sets (Add 3 data series) for testing. Possibly due to lag
- Test dataset with month/day/year data causing issue in loading

**Comment by koay9f** [comment]
Annotations worked with me for the Fuji data set at first
They seemed to survive adding a data series.

Are we saving annotations? When I went to another data visualization, they were gone when I came back.

**Comment by koay9f** [comment]
Getting what we have NOW into 1.2.4 would be good
Getting the annotations saving is less important than EEMs, so if we need to make a new issue and close this that is fine.

**Comment by nbintertech** [comment]
Please run some tests to make sure annotations that are created still appear (though they are not saved if you export/leave the app
