### ISSUE TITLE
Better Handling for date formats

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6078]
- Add format parsing for different date formats if the catchall formatting of moment constructor fails
- Add messaging to user, restore changed datasets and return to map-date-time

**Comment by koay9f** [comment]
So I changed Fuji 3 to d/m/yyyy h:mm:ss (I think, ask and I'll send) and it didn't work.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5b417eef-af3a-4d73-a197-5b7becd220d8)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/137434aa-2e0b-458d-a19e-3b7813b91cb7)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7961f1b8-e37c-4aa1-88ed-e56e3127646c)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c221fd38-02d1-49ab-a6b5-b4f0e9041477)

**Comment by koay9f** [comment]
Will not be end of the world if cannot get in 1.2.4.  Should probably add some language saying dates should be in MM/DD/YYYY

**Comment by nbintertech** [comment]
- Add drawer for better display of all time stamp help
- Add accepted formats
- fix scroll height bug hiding sub nav bar
- fix tooltip

**Comment by koay9f** [comment]
Timestamp is one word
This is in there several times
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d7e947e1-b04a-4e02-bddd-e3648ba3988b)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/e9591652-90bd-4397-b0b7-7b104f58c630)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8b7c96fd-5789-4dcf-9ddd-9d5b9344b848)
