### ISSUE TITLE
Full load amps

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6098]
This applies anywhere the Full Load amps calc is used (pumps, fans, compresed air, stand alone calcs, etc.), or anywhere the fields motor RPM  or motor efficiency class is used.

- [x] Rated Voltage - validation: min value should be 200V, not 208V
- [x] Motor RPM - add help text: (at end of existing). 
```These calculators are based on curve fits to actual purchasable motors and motors in the original MotorMaster Database. At the time of data collection, premium motors were only available in 2-, 4-, or 6- poles: rpms lower than 900/1080 rpm extend past the bounds of the models and results may be inaccurate. ```

- [x] Full Load Amp calculator high level help text. Replace ```Enter measured data to calcuate your system's annual savings potential ``` with 
``` Enter meaured data to estimate your motor's full load amps. This is calcuated based on curve fits from historic MotorMaster data and actual purchasable motors.```
 - [x] Full Load Amp field replace "Note" in help text: 
``` Note: The correct Rated Voltage, Rated Motor Power, and Motor RPM should be entered before the button is pressed. FLA are calcuated based on curve fits from historic MotorMaster data and actual purchasable motors. If any of these values change (either in the baseline or when creating a scenario), this button should be used again. ```

**Comment by kaichen127** [comment]
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/19033bbc-1f7b-4297-94cf-18d574b25e19)

**Comment by kaichen127** [comment]
should I try to format it differently or just leave it as a word chunk ?
