### ISSUE TITLE
Sidebar usability improvements

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6107]
We need to improve the usability for adding a second Y-axis. 'Add axis' can be a bit hard to see, and the left side menu is already quite full. Should take any future changes such as those in 3775 and 3781 into account
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/db81fada-6743-482a-8cfa-3b3b0dfaf1bf)

Repro example: 
Use example data and set power on one axis and pressure on the other with time series as an x axis.

**Comment by nbintertech** [comment]
Scope of this is pretty small but I'm taking some liberties on a redesign since this area could be much more clean with all we're trying to fit in.
Original below and proposed tabbed layou![DE og sidebar 1.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/a754752d-67fb-4673-8f6b-18f47f5e6802)![DE og sidebar 2.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/1363541e-61ab-4661-9264-67b307b56357)![DE tabbed layout.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/b1ba5be9-8cc1-4995-a2b8-e13c73670a69)t

**Comment by nbintertech** [comment]
Waiting for Alex's thoughts on this one

**Comment by nbintertech** [comment]
Some post meeting notes. Need new mockup to show...

Tabs:
"Data Selection" - Plot type, marker type, whatever is needed for basic rendering of each plot type. X axis data, Y axis data
"Customization" - customize axis colors, series names here etc.. here
"Annotations" - annotations on/off

**Comment by koay9f** [comment]
100% love, but has some issues.  Added new issue with review #6507 b/c I thought this issue might be long enough
