### ISSUE TITLE
Handle duplicate named columns/readings

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6108]
Handle duplicate named columns if user hasn't specified a unique alias. Where and when should alias be used vs the field name from file

**Comment by nbintertech** [comment]
I think the concern here was actually to fix time series segments of duplicate named columns when 'time series' is not selected x axis![6108 - issues.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/a8d11bef-3587-4545-a332-22abd654aa89)

**Comment by nbintertech** [comment]
Fixed the issue in above comment. There aren't currently bugs presenting because of duplicate names, but I could add something preventative messaging if duplicate names are detected in the field/alias setup.

**Comment by koay9f** [comment]
Looks like if they are identical col names in the same file it works (assigned the second one a "_1" but if you have two files with the same col names (or upload "file 1" and "file 1 - copy", then it doesn't do anything for the aliases of the second file (and no error messaging)

**Comment by nbintertech** [comment]
Closing - Existing handling is good. not worried about dealingn with duplicates in multifiles at this time
