### ISSUE TITLE
CA Network Controls: Isentropic Efficiency

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#6113]
Use issue to track the isentropic efficiency method for ordering compressors

**Comment by koay9f** [comment]
Senthil says it looks good. Waiting until quick test in develop before closing

**Comment by koay9f** [comment]
Looks good.
Why does some have 3 decimals?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/db4d0359-353f-4dc6-b341-ded761588213)

Consistency in decimals places is good, but does not have to be in before release.
