### ISSUE TITLE
CA Networking Controls Load Sharing

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#6114]
use this issue to track CA load sharing method

**Comment by koay9f** [comment]
Alex is not happy with this.  Is it possible to not include JUST THIS control type in 1.2.4?

**Comment by koay9f** [comment]
Mark's work is good, but engineers need more time to look at it.

**Comment by nbintertech** [comment]
Note for me.. need to remove load sharing option before release

**Comment by koay9f** [comment]
Confirmed that load sharing is removed for 1.2.4 release.  Moving to "Completed" until we have an update from the CA team.

**Comment by rmroot** [comment]
We have added the option back in for testing. After further testing we will decide if we want to keep the option for the next release. Make sure this issue has been updated/verified prior to the next release.

**Comment by rmroot** [comment]
This is hidden until the CA team commits to testing the feature. Moving back to inbox to collect dust

**Comment by rmroot** [comment]
From Alex:
Looks good  - couple minor adjustments 
- Need a name change to "Equal capacity ratio load sharing" 
- Need to add the auto shutdown feature to centrifugal

**Comment by rmroot** [comment]
EDIT Needed: "Centrifugal Equal Capacity Ratio Load Sharing"
