### ISSUE TITLE
Banner and Welcome Screen styling

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6202]
1. Check assessments/inventory and make banner divider widths consistent - OR just check with Kristina and see if we can remove these (looks better IMO) ![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/c77acc35-6899-4903-8737-4eeaab162816)

2. welcome-screen (tutorial overlays) styling falls out of alignment below roughly 1200px. Make sure the book overlay is consistently over the banner book at most sensible screen widths. Otherwise restyle to make welcome-screen.components responsive

![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/2208d548-a409-495c-a765-e8f176c7eceb)

**Comment by nbintertech** [comment]
Are the borders on the banner icons really necessary?

**Comment by koay9f** [comment]
#1 is good
#2 - the overlay seems to have a max width and will run short on larger screens.  Can we make it so that "overlay" is right justified and the excess space is covered in the black?

**Comment by kaichen127** [comment]
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/8706f645-37ea-4c0b-94cc-178c4ab50a0d)

"Get started" popup is off-centered

**Comment by koay9f** [comment]
Ummm... I can't get the pop-ups to trigger...

**Comment by nbintertech** [comment]
All good
