### ISSUE TITLE
Calculate values in Facility Basics

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6215]
From Paul's March 2023 Lear TH
10.	Under facility basics, it asks for energy price, quantity, and cost.  Ideally, if you input the quantity and either of the others, it should be able to calculate the average price or total cost. 
koa - I would have swore I already had this as an issue… but I cannot find it

**Comment by nbintertech** [comment]
@kaichen127 give this a shot once your other sprint issues are done. Let's do a 10 min call first to outline.
