### ISSUE TITLE
Air Leak Survey - Ongoing bugs

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6257]
Continuing to have issues in this calculator. 

We should get an example outline from Kristina/other expert for a set of real world leaks and do some testing on this (or recreate the example from scratch). Log any bugs or exceptions that are found and consult with me before starting.

- Test standalone calculator and TH calculator
- Get user TH exports if possible

**Comment by kaichen127** [comment]
tried using the calculator via All Calculators->compressed air->leak survey and treasure hunt->treasure chest->import, couldn't find any errors in the console (which i guess is a good thing ?)

**Comment by nbintertech** [comment]
Will give this a quick look myself and then close

**Comment by nbintertech** [comment]
TH showing created date of 9/11 (from Chris 'Assessment_ABB_BuildingB') showing nulls for some air leak items, breaking treasurehunt

**Comment by rmroot** [comment]
Contact me for assessment for testing

**Comment by nbintertech** [comment]
Re: upgrading this calculator UI or logic - one of the more heavily used in TH, and seems to be demo'd frequently by Chris.
Ideas:
- improve the interfacing between parent calculator component and child forms/service. Leak counts seem unreliable and there is a race condition as mentioned above
- Revamp all event logic for forms and results?
- Totall remake calculator - rumored ideas to copy this calculator into steam

**Comment by nbintertech** [comment]
This is in wasm-1.3.1-hotfix-airleak and needs to be cherry picked into develop
