### ISSUE TITLE
Complete Web/WASM merge

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6259]
Pull the lever on going full web.

TODO:
- Look through Suite-db for recent changes that need migrating to the web api services in wasm branch
- Follow up on containerizing app once transition has been made (this is on ORNL internal dev ops roadmap, low priority)
- Revisit README issues - notes for any legacy nan/suite users

**Comment by rmroot** [comment]
Should just take a look at the size difference of the installer/app when switching over. Not sure the impact of wasm vs nan

**Comment by nbintertech** [comment]
branch in both desktop and suite: `wasm-transition-updates`

**Comment by nbintertech** [comment]
It's in develop. closing
