### ISSUE TITLE
Apply Mobile UI to Pump Inventory

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#6264]

**Comment by koay9f** [comment]
I clicked on the [home] icon and it wouldn't navigate and gave error.  
Only noticed this for pump inventory in mobile (other things worked in mobile, pump inventory worked in normal screen)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d52725799a3cf82089195e06f7c49a242ce53cc/image.png)
