### ISSUE TITLE
Side bar too big

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6281]
I can't change the width of the sidebar and it is taking up too much of the screen
**![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/68581d1f-b21d-4bc3-b443-abd99ac1b74a)**
**![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/73489d3e-6894-43c7-b1d6-c621a64e30aa)**

I know I can hide it, but I kind of like being able to see both the sidebar and the main page. 
I think we got rid of the adjustability for a reason but either it needs to come back (when not mobile / when the screen is a certain minimum size) or we need different parameters governing how wide it is.

**Comment by nbintertech** [comment]
@kaichen127 let's talk before you start
