### ISSUE TITLE
Mobile UI - Add New Assessment Modal

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6282]
Doesn't quite fit in vertical screens. Need to tweak or add some messaging
Actually it's all mobile UI screens - horizontal the modal tries to get really big and you can't really see it at all...

**Comment by nbintertech** [comment]
Note for whoever picks this up - I've changed the new assessment modal to be a shared component `create-assessment-modal` as part of 6250 --> make sure you have those changes

**Comment by nbintertech** [comment]
@kaichen127 if there are other HIGH PRIORITY modals used in the app that are borked on mobile, you could make note   and share with us to create issues for those also

**Comment by kaichen127** [comment]
note : modal looks fine in mobile view when on the home page or the dashboard but if creating a new assessment while inside another assessment, dimensions turn out weird
 ![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/f8f4786c-9aff-4750-85b6-3da952ec2ed2)
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/c171d56e-9265-4daf-a270-948046d81f2c)
