### ISSUE TITLE
Visualizer: optimize performance and render workflow

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6284]
Went over workflow again to optimize performance. Found DB call that was causing blocking behavior in zone.js (angular dependency) and removed. Call was previously being used to save 'last used' data explorer data.

Breakdown:
- Let user decide when to render DE Visualize chart --> Add a 'Create graph'  button.
Visualize tab shouldn't render chart until axis, series selections, etc are made and submitted. Worth seeing if folks like that workflow better (it may save load time for a chart thats not used). Basic user input and text changes still render automatically
- Remove unused calls to DB (1 sec -5/6 seconds lag in zone.js) on large files
- Remove object copies (100ms)
- Remove and simplify code added to workaround existing lag -->userGraphOptionsObj, timeSeriesSegments

**Comment by nbintertech** [comment]
NOTE; Leaving time series range selectors hidden for now. These take quite a bit of processing power to create and are no longer needed as a work around to LAG

**Comment by koay9f** [comment]
Closing this for now. See #6507
So much faster and better now.
