### ISSUE TITLE
Compressed Air - System Profile workflow

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6287]
Should these two be the same for all day types?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c8e40939-6203-481a-99c8-c123ee4b3e3c)
If so, can we redo the flow so they don't have to set it for all daytypes (see error message by data entry section)

If not and in general, we need to make it more obvious that you are using this screen for all of the day types.  Maybe "next" changes the daytype? A warning if you have entered any data for a day type?

**Comment by rhernandez-intertech** [comment]
here is a mock up of how CA system profile will look with a link to a list a Day Types and a warning message that will go away when all the Day Types have data entered.
The list of Day Types will appear in a popup modal, the list of Day Types will indicate which Day Types still need data to be entered.
![image.png](https://images.zenhubusercontent.com/60b7bed2e39f152beecc60b4/e8008ba6-36e8-4b9f-b961-4c16c28c9ee9)
