### ISSUE TITLE
Inventory Unit/Field changes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6299]
Unit changes
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/768dbe55-5acc-46e4-b9ef-8d9de89b2c24)

Use the table for final say on units to use, but here's where they are
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5ed60340-754f-4482-98e8-cfdc5089ff6e)
Note the missing %
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9f612245-e240-483e-8b7b-5803ca496559)

FIELD NAME CHANGE
Minimum flow size should probably be minimum flow rate.  

Help text for it:
Moved to #6320

NEW FIELD
Notes.  
Just a big area for notes.

POTENTAL FIELD REMOVAL/HIDING
Displacement.  Daryl isn't sure what this is supposed to reference.

**Comment by nbintertech** [comment]
Moved from 3798... @koa - Overall things look good.  There are some issues with units that I'm wanting to check up on but will need some minor tweaks

Here's one:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a97f02de-ff06-412e-9c97-f240e18bca8b)

**Comment by koay9f** [comment]
Impeller Diameter: lower case I for in  AND mm for metric
Inlet/Outlet Diameter: mm in metric (sorry I know it says cm above)
