### ISSUE TITLE
PHAST - Electrotech Other - Energy Input Exhaust Gas Losses - Field by field help content

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#633]

**Comment by koay9f** [comment]
Help text for (hopefully
[Help text - ET.docx](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1369683/Help.text.-.ET.docx)
) all remaining PHAST calculators (electrotechnologies and steam)
