### ISSUE TITLE
Mobile UI Explore Opps

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6335]
In Expert view you haave the BL/Mod/Details Menu, but in Explore Opps you have to scroll to get to the results.
Would like to explore what a top menu for explore opps looks like

**Comment by rhernandez-intertech** [comment]
also make the Help page a tab in the System Setup/Basics so users won't have to scroll down to the help text

**Comment by koay9f** [comment]
Gauge in savings results is acting weird in pumps & fans & WW & CA. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlFVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4b63fa76ad74fb41b1576ef3241c1740aba2abd/image.png)

Either shrink or just don't display.  Maybe ask in Thursday call? I vote don't display 
Process heating doesn't display it
Steam shrinks it
