### ISSUE TITLE
PHAST - Provide help text for auxiliary equipment 

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#634]
Provide help content for rated capacity, duty cycle, etc.
![image](https://user-images.githubusercontent.com/8973004/30115445-bd9cdd90-92e8-11e7-8d54-ae99777f55a3.png)

**Comment by koay9f** [comment]
Rated Capacity: The percent of the rated capacity that is used 
min: 0 max: 100


looks like everything else has text

**Comment by gaccawi** [comment]
Need better descriptions for duty cycle
