### ISSUE TITLE
Unable to export directories properly in the dashboard

### ISSUE THREAD

**Issue by kaichen127** [ORNL-AMO/AMO-Tools-Desktop#6369]
![image.png](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/f8706d91-2134-4a89-9c44-925a6a8cc6e3)

Exporting a directory and importing it will just give an empty directory

**Comment by kaichen127** [comment]
Addressed in #5535

**Comment by kaichen127** [comment]
There is a weird edge case where if you export both a directory and an assessment (that's not in a directory), only the directory gets successfully exported - only happens when select all is not clicked

**Comment by nbintertech** [comment]
duplicate
