### ISSUE TITLE
Dual Bins for Weather calc

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6375]
Using this issue to track any logical changes need to tie all other issues together.

**Sum of changes:**
Allow user to put in parameter data range starting value
Allow user to add multiple binning params
Code change - update NG template forms to use reactive forms
Update result table to reflect changes
Add Heatmap/density plot for multiple binned scenarios

**Nice to have**
Case delete button should be right side, larger
Allow manual param option for each case. Appears as "filtering param"? or something else

---------
**Background**
The weather calc is setup to do dual binning, but right now you have to set the second bin manually for each bin, which might only really be useful for filtering, not creating dual bins.

We may want to rethink how we make the bins, especially for auto-dual binning. 
Maybe set bin size and ... IDK something that lets users choose if they want the first bin to start at the first number or each bin be a rounded value (starting a bin at 14F or 10F) instead of setting the range for each bin
If we dual bin we end up with a HUGE number of bins and I'm not sure what the graphs would look like.  
Maybe this?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/a5e6f4ab-0f4b-4edf-b799-96c2c6505ca3)

**Comment by nbintertech** [comment]
Will need a call to clarify what we're trying to do and resolve confusion on manual vs auto binning, what needs to change and stay the same. 

We also have #5769 which seems similar. 
Also factor in #4737 managing different cases

**Comment by nbintertech** [comment]
Pretty close to finishing this, but we'll need to meet and answer some q's on when and how each bin param should set bins, override custom bins, second param bins, etc.

I may be able to improve speed of charts if we know how likely it is we'll need to support additional params in the future.

<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2o4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17b746faeac708cfb2e7a089c8e06246e5f9a316/image.png" alt="image.png" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd244QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcb0189f6e78681d4107175d782d82350bf019bd/image.png" alt="image.png" />


2 Params
<img width="1184" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3I4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5297a4123b42ebf94e4c4943c8c96980df58e19c/image.png" alt="image.png" />

<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3o4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--575bfd9690a25866b384fc15845ed03140b93d1b/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Loving it!
Small things
Data validation for Staring Value - not sure what it is based on, but I think we can probably just nix it. 
End value should be the end of the last bin, not the starting value of the last bin (example, you put in 100, with a bin size of 10, you will get a bin that is 100 - 110). 
last bin should probably be something like "if binStart > end Value then stop"
if that is more complicated, then "end value" should be changed to "Start of last bin"

was able to make this custom heat map <3
<img width="923" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd24afd31f0729f3286d929fe2f1cb6a8f96dbc1/image.png" alt="image.png" />



unless this will be the quickest thing ever - maybe make an issue to either choose bin size or bin count.

**Comment by nbintertech** [comment]
Starting value checks the minimum value from the available weather data. Still remove?
need more info on last request.. bin size or bin count?

**Comment by koay9f** [comment]
End bin should not be bigger than bin size
on parameter change - update end value value and validation

**Comment by koay9f** [comment]
FYI - just checked even though this is still in NR - it looks like it partially works - I don't get an error message, but now it is just not letting me generate bins even though there are no visible error messages..

<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEF4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f923536dd04854a182cf81fee7593d16e5848080/image.png" alt="image.png" />

**Comment by koay9f** [comment]
so close
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGcwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e99360cf28b3cf1bca3d63ee0bac590435c9bbaf/image.png" alt="image.png" />
