### ISSUE TITLE
Data Explorer Plotly Rangeslider

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6387]
Implement Plotly rangeslider
https://plotly.com/javascript/time-series/

**Comment by nbintertech** [comment]
Need to demo this for Kristina. The Plotly's range selector is a bit odd - need to figure out how this could be useful IF at all ![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/226608d3-1f91-467a-a967-bcd199f1fb1d)

**Comment by nbintertech** [comment]
Did this never get merged? Need to check

**Comment by koay9f** [comment]
see #6507 
Works beautifully for time series.  Love. 100% would recommend, 2 thumbs up.
Makes scatter plot & histogram not work at all.

**Comment by nbintertech** [comment]
Closing - done for #6507 #6362
