### ISSUE TITLE
Arrow key - Steam

### ISSUE THREAD

**Issue by kaichen127** [ORNL-AMO/AMO-Tools-Desktop#6400]
![steam1.PNG](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/c1d4a78d-1672-403d-baca-0778145e2c81)
![steam2.PNG](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/1d73577d-b391-4cf2-9899-30a1562cf451)
![steam3.PNG](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/0bd87939-6d59-4ab4-8c4d-4c12422c389d)
![steam4.PNG](https://images.zenhubusercontent.com/6477700057b381ed6656b41c/fc7cbb67-0dbf-4db2-b5ad-a1a058d05125)

**Comment by koay9f** [comment]
Operations - Emission output x1
Boiler - deaerator vent rate x0.1
Header - low pressure header - pressure x10

everything else looks okay
