### ISSUE TITLE
Add Assessment opportunity to Treasure Chest

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6453]
Add assessment opportunity (behave like existing custom opportunity):
- pumps, fans, CA, process heating 
- plug bl/mod energy use into util consumption
- allow user to select modification for opportunity 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e57981e4ece389c168dd179fda1b53a87dd368a1/image%20%2835%29.png)

**Comment by koay9f** [comment]
If needed - can "turn off" process heating for the release. If you do shoot for getting PH included, then there are a few things than can be fixed later

Bugs found:
* Added Pump example to TH Example with the "VFD" scenario.  Turned off all opportunities except the Pump
     *  Cost was good. Utility Savings was good. CO2 savings was off. Was 229, should be 115. 
     *  Actually, if you turn off everything it is 115, so the opportunity might be okay, but something else is wrong (this was seen with other assessments also)
     *  Payback looks correct (it's not in other places, so was just checking here)
*  Added PH example to TH Example.  Tried to select "All Opportunities" scenario. Got error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c08bdbf8fa2599a56b2d6e6600734c99b86d0f95/image.png)

     *   Added 2 zeros to NG use and cost so gauges were not mad
 *   Reset application, opened TH example, turned off everything, no savings
 *   Added pump example , selected vfd opp - CO2 savings still 229. Turned off the opp (nothing on) savings = 115t
 *   Reset again
 *   Increased the TH NG use & cost (x100), added PH assessment. no bug - seems to be related to not having enough NG in system setup.
      *   Does not have weird residual savings like pump
      *   Cost savings is correct (~$2M)
      *   CO2 savings is not (reading 3 t instead of 21,274.49)
      *   Payback is wrong (put total implementation cost of $7k).  (should be $7000 / $2004788/yr = 0.00349yr (probably should have made that higher costed :D )
 *  would be nice if implementation cost was put in electricity for pump/fan and put in right spot for PH
 *  need to be able to select Gas or Other Fuel for fuel fired PH and steam, Gas, or Other Fuel for Steam (this can be lower priority and happen after release)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a99116bc4d33485dd613f807652bd980e9e1116/image.png)
 *  Added Steam to TH
      *  did not yell when I didn't have steam to calculate with.
      *  Should be able to set as gas or other fuel (see above) (this can be lower priority and happen after release)
      *  Did not apply CO2 savings
 *  Added not-EAF electro tech to TH (after rest example)
      *  does do weird nothing selected, still have CO2 savings thing
      *  CO2 breakdown by Utility in Exe Summary looks okay, ish - NG is slightly high... by the same amount that CO2 Savings gauge is off. If turn things off - then the "correct" numbers (what should be there with the opp on) remain in the table
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c303d8a4a972160af33b415cb813a4601593d389/image.png)

      *  Cost not correct - needs fuel costs also
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--788bd74c45ae9a92f9682b8958d01c7c09a5801f/image.png)
* cleared examples, loaded EAF
     *  Non-electricity utilitys are still in kWh/yr in the source data table.  need to convert to TH fuel units
  [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGpHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e82383647653f220d5f6771a777d7d2232f1166a/image.png)

     * Gauge cost savings is low. Other Fuel only has the "other fuel" also needs to have the electrode & coal energy savings (like CO2). Same in Report
     * Gauge & report CO2 numbers are perfect
 * Updating after changing assessment works (tested for EAF specificially)
* Added Fan example - same problems as pumps

**Comment by koay9f** [comment]
PH assessments
[testing TH assessments - PH - Copy.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fce7be0f764491bddc57141ffbb3bbf6de5d98b7/testing%20TH%20assessments%20-%20PH%20-%20Copy.txt)

**Comment by nbintertech** [comment]
***********
**IMPORTANT** before texting next round of changes you must reset examples, and any assessments used to test. 




********

**Comment by koay9f** [comment]
Remaining things I see -

- For now - Process Heating steam assessments should default to "Gas", since the value you are pulling in is the MMBTU and not klb (numbers are good - just change the utility type default)

-

**Comment by nbintertech** [comment]
- Change steam energy type to interpret/show as "Gas", use total co2 savings output
- Change preview table display label units and values to be yearly
- Fix gas costs not included for non-eaf electrotech

**Comment by koay9f** [comment]
Carbon Coal & Electrode still not included in "other fuels" 's cost.  Carbon emissions & utility savings are good
