### ISSUE TITLE
Copy Items btn bug 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#6473]
In the Directory Dashboard, the copy btn is not responding properly to the select all toggle.
At first the copy btn will not enable when the select all toggle is on, then if an assessment is individually selected then the copy btn will not disable when nothing is selected.
This is probably related to adding the export btn to assessments. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnluIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81234a8ec317a232910de6da4f1150f86152a7df/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjJuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6d19082bb07ca23eb0c1b64ae69c04c7c80c1f3/image.png)

**Comment by rhernandez-intertech** [comment]
Bug was actually caused by issue 6369 and 5535

**Comment by koay9f** [comment]
I think this is still in there. 
I had it "on" when nothing was selected. 
after I got it off, when I clicked "select all" it did not come on
It *did* come on when I selected individual items.

**Comment by nbintertech** [comment]
I'll take this over once the other directory issue, #6380 has been looked at. Didn't realize this was made and we have a lot of overlap with directory issues being made between Kai/Myself/Rachel.

**Comment by nbintertech** [comment]
Functionality intentional - closing see #6555
