### ISSUE TITLE
Steam - Header - decimal point bug

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6480]
In the header page, in any field - if you type "." it moves you to the front of the field.
Can be up to 3 headers.

**Comment by nbintertech** [comment]
forms were stripping the '.' on every change and returning it back to existing form - effectively erasing it.

Needed to change how validation is done on inputs. We should run headers through a couple different validation scenarios

**Comment by nbintertech** [comment]
We looked at this and fixed the decimal point bug. Opened #6595 for future work based off of findings here.

Verification - test header forms with multiple scenarios, ensure validation (specifically validation based off other fields) works correctly. Just tested validation and it looks good to me
