### ISSUE TITLE
Treasure Hunt PPT modifications 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#6486]
Will update this issue with changes that will be made to the TH PPT as I go through the notes from Chris.

**Comment by rhernandez-intertech** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFBVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65411d06ead2c98f3674833d41dbc58ff3623409/image.png)

**Comment by koay9f** [comment]
Mostly looks really good.

One kind of big problem - if an opportunity doesn't have a "Team" it now doesn't really appear in the slide deck.  Maybe we can have an artificial "Team Blank" for the team pie chart and making the presentation? 
`if is.na(TeamName), TeamName = "Team Blank"`   type of thing? 
Simpler solution - make a default Team Name of "Team"? so there is always something?

Picking nits...
Slide 1: can the title text be left justfied and the logo line up with it?
Slide 11: can any thing be done when there is only 1 "other utility" to go on this slide (make it bigger?)  - this can be shunted off to another issue if necessary

**Comment by koay9f** [comment]
No team looks good.
Side note - Assessment ops look good

The only thing I can see that was asked for and isn't in is the decimal places. I think all $ values in tables should have NO decimal places.
If this isn't a quick fix - then spin it off into a new issue and close this please.
