### ISSUE TITLE
Explorer - Prevent errors, enforce setup, add messaging (NV fixes)

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6507]
OMG this is great

Few (hopefully) quick fixes

Time Series:

NICK: moved 1/2 to new issue #6512
3.
Setup with just the 3rd fuji.  desided to make more interesting and added 1 & 2.  When I got to the select date/time column page, it had the option to choose that a column was a "date" greyed out.  Went back to begining, removed all data files, reuploaded, selected the header row & refined data. when got to "map date and time" it is just stuck on loading with this error:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVVVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3ae103a290c1e009fb576ad3e106fcf3e12ad6f/image.png)

4.
Cannot reproduce reliability but I think sometimes the Finish Setup / Next button doesn't follow through correctly (try navigating by top menu rather than next). if can't find, we'll just try to keep an eye out.

5.
If you delete a series WITHOUT applying graph changes, then in teh graph select the series in the legend to hide it, you get a "not error" and I think it forces the update. This is mostly just an FYI, the only action item I can think of is maybe make the "Apply Graph Changes" button flash or something. Maybe each change, maybe ever 15 seconds if you don't click it? If my screen is big and I'm focusing on the graph I forget to hit it and **I'm** the one who asked for it :D

5b
Similar idea for manage annotations.  If user does not toggle that off after a while, maybe it flash?

-----------------
Scatter Plot
6
Ummm.... something weird here.  I have x-axis as Power 2, but it is showing me dates and the graph does not look like I would expect (like a shot gun pattern)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf2f63bdc1f62d0f55206f3bc7b44bc012bad867/image.png)

Same with histogram.  I'm going to blame the slider
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e7d200db24276e53f90c45fe20fa0a8184a5f3/image.png)

**Comment by nbintertech** [comment]
Summary:
1. At some point an old piece of angular library code stopped firing (activatedRoute.url sub in data-setup.ts). This caused the problems in #6512, and new problems in #6362.

2. Setup tab header selection no longer defaults. User must select an option or going forward is disabled.
3. Added some data checking and invalid messaging to display in cases of poor setup or incorrect graph option choices,  below:
A. No time series column selected in setup - links to map date and time tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGt1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c65ddc5e4f913e92aef493c54a51e3fdde3ee8f/image%20%2844%29.png)

B. invalid x or y selected for scatter - links to setup
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHd1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59a541915f41d6b2f75d54459e82241d709ae691/image%20%2845%29.png)

C. catch all message - setup done incorrectly, a weird choice has been made, or something went wrong
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODR1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--769b5ea6ed26d0edc3848a02df53b09ac67d2af7/image%20%2846%29.png)

4. Fixed rangeslider bug changing layout.xaxis when in bar/scattter
5.  Deleted series automatically apply graph changes
