### ISSUE TITLE
Pump Errors

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6508]
[Issue 6508.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee6ce8002edb4002ad000526951a5ea67e11b8bf/Issue%206508.txt)
When going into pump assessment (System Setup) get this error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9ae658a1460dd6af0b3f64abaf738cf2d080932/image.png)

Also, Motor is triggering an error (yellow) but no messaging

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--911b1de7c9736ebbdd9690e402800b6c9aa8e321/image.png)

**Comment by nbintertech** [comment]
#6348 first part
