### ISSUE TITLE
Process Heating Heat of reaction validation

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6510]
When did this get added? This can be 0.  It should not be <0...
Only a problem when solid charge material
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72433927bfe2fd14eab4ecb0377bb393a4cc11bc/image.png)

**Comment by nbintertech** [comment]
Looks like this was added by mistake when Kai did form stepx10 issue. Not showing anywhere else
