### ISSUE TITLE
Print is not creating PDF in desktop or web (Windows and Mac)

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#6523]
User reported problem as below: 

![image002](https://github.com/ORNL-AMO/AMO-Tools-Desktop/assets/8973004/d9ce084d-4883-4b2d-97a1-0ac18f84acb0)

Dear all,
I have problem to have a printable file of MEASUR reports.
After selecting the assessment, generate report, print button … the report is generated but not printed in PDF file or other. Or I don’t find the localization of the printed file in my pc.
Could you help me to solve this issue.
 
You will find below a screenshot of the window of printing report.
My operating system : Windows 10 Professional
Used version of MEASUE : Online v1.3.1

I have confirmed that the print pdf is not displayed. User returned to the summary screen. I tested Fan and Steam. Online Windows using Firefox, Mac using Chrome, Mac using Safari. I tested also MEASUR Mac v1.3.0. So, it isn't only in the v1.3.1. No error in the console (at least that seemed relevant, only reporting a 502 for the weather.ornl.gov query

**Comment by nbintertech** [comment]
Fixed multiple points of failure with general printing and CA printing. 

Successfully tested/printing:
- example assessment reports individually selected options
- example assessment reports select all
- rollup individually selected
- rollup select all
