### ISSUE TITLE
Something wrong with PH Sankey

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6526]
[Bootcamp Furnace.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHROQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1168dd2a6f4b54407373c40cf21d0da0ba532825/Bootcamp%20Furnace.txt)

Some of it is a very narrow "window" in which you can play with it
But there is something wrong with teh data it is graphing...

**Comment by nbintertech** [comment]
@koay9f Will new electrical heater losses need to be added as a sankey result node?

**Comment by nbintertech** [comment]
was just a style compressing the width
