### ISSUE TITLE
PH - non-EAF electrotech

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6537]
I think this workflow/math got messed up when working with the EAF. 
We did some tweaks with #5340, #5267 and I think something got missed.

The Fuel Available heat seems to be stuck at 94% instead of referencing the user input.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a21f62fe21d45790cec3655debf4b4feda70fdaa/image.png)

For testing:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66a90e4b6798c96272d96653ba6fa2ce499a4f5e/image.png)

**Comment by nbintertech** [comment]
Fixed - caused by an automatic merge which overwrote measur-side results with calls to suite
