### ISSUE TITLE
PH - electrotech improvement

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6538]
Add a field for Electrical Efficiency.  Calculate Electrical Losses from calculated electricity delivered. Calculate total energy input.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a2ba83a8aa662a9d4c49c09d2be4d1b69c0d17b/image.png)

**Comment by koay9f** [comment]
ignore pic above and use this
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXQzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fff2536e891efd5e302a0cfdd10eb6f3c9ef0610/image.png)

**Comment by koay9f** [comment]
ADDITIONAL:
Name Change
"Total Heat Input for Burners" --> "Total Additional Fuel Heat"
Help text replacement:
Additional heat supplied per hour by fuel burners. This value is zero for most electrotechnologies. This can be calculated from the fuels higher heating value and volumetric flow rate.

Fuel Heater Efficiency --> "Available Heat of Fuel"
Help text for Fuel Heater Efficiency/Available Heat of Fuel: 
Fraction of heating value of the fuel available for use. This can be calculated from estimating the flue gas losses with the "Calculate" button. 

Help text for electrical efficiency:
Efficiency of the conversion of electrical energy into heat, this is often close to 100%.




Help text for Electrical Efficiency:

**Comment by nbintertech** [comment]
for me: getEnergyUseReportData() --> double check that old logic re: flue gas losses doesn't allow them in steam / electrotech

**Comment by nbintertech** [comment]
Changes summary:
- Add electrical efficiency input, electrical heater losses result
-  remove/cleanup redundant form call to results
-  remove mx-auto causing sankey width problem
- Change field names and help text
- Stopped adding exhaust gas losses to "gross heat input"
- Stop setting named result "input total" to "gross heat input" as a default value
- Add results totalProvidedElectricalHeat, totalAdditionalFuelHeat

**Comment by koay9f** [comment]
99% perfect

if Available Heat of Fuel = 100% --> Exhaust Gas Losses are 0 (shown as --- , which is good)
but then it doesn't calculate Electrical heat delivered or electrical heater losses. Just setting Energy Input Total equal to the fuel heat delivered. 
This probably isn't a big issue b/c that won't be 100% 
In fact could probably put in validation saying it must be <100% (and not equal to). But I think there is an if statement in there that is doing it, and those cause problems :D

**Comment by nbintertech** [comment]
We're good. No changes made
