### ISSUE TITLE
PH - electrotech - energy input Badges not reflecting 

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6539]
Should have a yellow badge
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5a3662732401c317de5b1b8e2bbe45e6a02c343/image.png)

**Comment by nbintertech** [comment]
Please confirm  - It looks like we also are checking min constraints on exhaust gas temp (not showing in form). This value is never set, never used, just seems like old logic so I'm going to remove

**Comment by nbintertech** [comment]
Please confirm  - It looks like we also are checking min constraints on exhaust gas temp (not showing in form). This value is never set, never used, just seems like old logic so I'm going to remove

**Comment by koay9f** [comment]
I think I agree with exhaust gas temp no longer being used so the validation is unnecessary

**Comment by nbintertech** [comment]
fixed - energy input  exhaust gas tab not checking energyInputheatDelivered warning
fixed - energy input tab - was not checking energy input heat delivered
fixed - energy input tab - not checking warnings on modification
remove "heat warning" exhaust gas temp warning (field no longer used)
remove energy input exhaust gas method call to suite


Curent warnings/validation for energy-input form (EAF):
- min electricity validator
- warning 'Exhaust Gas Losses must be less than Chemical Energy Delivered. Please check Electricity Input value.'
- warning 'More heat than necessary is being delivered via burners. Check fuel inputs or estimate other losses.'

Current warnings/validation for energy-input-exhaust-gas form (nonEAF):
- available heat greater than 0, max 100
- warning 'More heat than necessary is being delivered via burners. Check fuel inputs or estimate other losses.';

**Comment by koay9f** [comment]
using PH electro example I sent for TH
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22107779c8a459798ac52c9baec3532a68342660/image.png)
