### ISSUE TITLE
DE on small monitors (but not mobile small)

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6553]
In Histogram type chart, cannot see bottom of sidebar
problem (scrolled down as much as possible)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b68b933e8752ae9ee76ce797a5193df77be50ba/image.png)

setup:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d799957955c1f9ef7ee337135dccd3a4648bac7e/image.png)

**Comment by nbintertech** [comment]
Removed sidebar inner scroll - and fixed outer sidebar scroll. Added padding to bottom of visualizer window so data summary/help sidebars can be seen if needed

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c481aaf15693c5a5f0a65c9744ef8952004b71d/image.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddac6e3a114183ebc336a80dbca3528f595b6c4b/image.png)

Having 3 scrollbars isn't great but 800x500 res is about as small as I could imagine a person wanting to use this

**Comment by nbintertech** [comment]
Data summary and help tabs don't handle the scroll height the same - this can also be fixed, but they are still usable IMO
