### ISSUE TITLE
Too many options in dropdown

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6564]
This dropdown isn't supposed to include these...
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--593e1eca7faf7bc3633408e8b07463039b1a45d2/image.png)

**Comment by nbintertech** [comment]
educated guess for us: when pump inventory was implemented, the constant for pump types probably got shared. See commit and revert block

**Comment by nbintertech** [comment]
Removed drive types form the list. No idea why this was done during pump inventory. inventory drive and pump options look correct but should probably be peeked at.
