### ISSUE TITLE
Pump Inventory integration: Modify conditions

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6572]
Changed this a bit, so:
 
- If connected show status in explore opps
- if connected show status in modify conditions (Don't allow changes in modify conditions)
- Set form heights equal in modify conditions (baseed on connected form)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGUyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da005161ab91fcc2acea5aba8234ae2c6db943d8/image%20%2851%29.png)

**Comment by nbintertech** [comment]
Tested scenarios: 
connected pump, 
connected pump and motor, 
motor connected pump inventory, 
create new assessment from inventory,
new asssessment add pump connection (and motor)
making invalid changes after connection exists, 
deleting item when connection present.

**Comment by koay9f** [comment]
Things look good. my testing was not yet exhaustive.  Added issue about modifications on connected assessments (didn't see this one in here)
