### ISSUE TITLE
Enhanced Analytics Events

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#6583]
Add more analytics events to MEASUR:
- Create Assessment
- Access Assessment (each type)
- Access calculators

**Comment by rmroot** [comment]
Added analytics events:
- Create assessments/inventory
- View assessments/inventory
- Access to each individual calculator
- Run day type analysis
- Use data exploration

Let me know if there is more I should be adding.

**Comment by nbintertech** [comment]
Need to investigate, looks like this may not be working

**Comment by nbintertech** [comment]
We're going to add measur_version alongside measur_platform
It's most likely that unaccounted for users are those who have not updated to a version that contains the measur_platform event/dimension
<img width="1591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTE3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac1b0c37c783df59917477aa7b24809532275a6f/image%20%2846%29.png" alt="image (46).png" />
