### ISSUE TITLE
CO2 emissions not calculating right away

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6604]
Saw this for pump & fan, didn't notice for PH, didn't test others.

When you first run the assessment (values don't really matter, just don't cause errors), the Annual CO2 Emissions result is zero until you click inside the emission factor on the operations page (if you set a zip code it works fine).

**Comment by rhernandez-intertech** [comment]
Bug is in Waste Water as well, operations (CO2) data is not being calculated into the result data when the Operations page is not clicked on during setup or the creation of a modification
