### ISSUE TITLE
Electrotech Result data enhance

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6606]
Add "Annual energy consumption" to bottom with emissions & costs
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b2e58a0fee7c0b282bee1fd5ff68fef02c25e1e/image.png)

**Comment by nbintertech** [comment]
We're adding to exec summary instead, because it already contains annual
