### ISSUE TITLE
Export Opportunities for Assessment Opps

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6618]
No "slot" for stating you will export an assessment opp.  makes it go weird if you only have assessment opps
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJ4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8dd87e2efb2e609e461f00da73544c7e68730c0c/image.png)

**Comment by nbintertech** [comment]
branch 6613
