### ISSUE TITLE
PHAST result data printing

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6641]
Fixes report result data tab, input summary tab, are not printing when selected. All graphs print when sankey selected.

Tested in rollup also

**Comment by koay9f** [comment]
Sankeys extend out of page.  
Can we shrink or rotate page / figure?

[MEASUR test ph print.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEp2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffe61c2bfb9b7574e17a6420283a402c1f08fd34/MEASUR%20test%20ph%20print.pdf)

**Comment by nbintertech** [comment]
This is just a factor of available screen. I think the best thing to be done here is wrap this into an issue RE all sankeys with some of the mods we talked about a few months ago. I'll start with adding some basic checks to reduce spacing levels based on flow size.  Will use #6581
