### ISSUE TITLE
Fix Pump/Fan Curve

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6651]
Talk with Kristina

[pump curve rev 20231207.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29868ed77c9a6da50358066976c6a199a35c5cb4/pump%20curve%20rev%2020231207.pptx)
[pump curve.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ROQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83f52dddaf6543cdd394d625dd0427a07708582b/pump%20curve.xlsx)

**Comment by nbintertech** [comment]
Reimplement equipment and power curves "By Data" logic for getting modification regression and equation calculations. Fix data pair generation for curves and make changes to "By Equation" as well.
