### ISSUE TITLE
Create export to csv/excel for heatmap

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6659]
Export in format of heatmap (can use plotly 'data'?) otherwise hidden copytable

**Comment by koay9f** [comment]
Can this easily be changed to tab deliminited?  
If so, please do and change button to just "Copy Data"
If not, just close.

**Comment by nbintertech** [comment]
My mistake - my brain kept hearing 'tab delimited' as synonymous with CSV. Fixed to output the below format: <img width="1022" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a291075ac48f3f8530764a604e6305d6a738424f/image.png" alt="image.png" />
