### ISSUE TITLE
System Curve with metric units

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6664]
Existing bug pre-6651. Generally looking wrong. Need to step through this once the imperial examples are verified from 6651. I began adding some conversions to the default inputs but that didn't take care of everything.

**Comment by nbintertech** [comment]
Synopsis: Less a conversions problem and more of a not sure what the intended behavior is supposed to be.

If you load fan example (which is by data) and then click by equation in imperial you're getting pretty close to the same output/chart. If you do the same in metric its quite different. this may be less a conversions problem and more an intended behavior problem - Is there also supposed to be an example for by equation, and if so should it be the same? or should clicking by equation reset the calc? Same questions for pump calculator. If you follow the same steps, you see pretty similar but different outputs for by data/by equation.

<img width="1796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWQ3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49de1b70bb7dc82a64477fc1627a8dc5fd1f8a22/Fan%20by%20equation%20imperial.png" alt="Fan by equation imperial.png" />

<img width="1633" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXA3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e03ca26b482ded1423ea66a8487a6f0997a2868/fan%20by%20equation%20metric.png" alt="fan by equation metric.png" />

**Comment by koay9f** [comment]
Yes, there should be an example.  The example for "by equation" should just use the equation that is generated in by data. Just guessing, conversion doesn't work right on the coefficients, if there is anything at all, so we just need to put in a new example based on the by data equation

**Comment by nbintertech** [comment]
Ok recap... pump and fan curves both had different examples showing in imperial/metric.
- changed pump imperial example defaults to be what actually shows
- fixed conversions getting the wrong unit
- copied generated equation coefficients from by data over to by equation

**Comment by koay9f** [comment]
For metric,  Fan, by equation, you should be using this:
<img width="919" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21a8daef582e6dc0576ff935fafa1fb1628f4273/image.png" alt="image.png" />

For imp, pump, by equation
<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5adfc3d4e1badcf6c7cb382d61897e1363e5b373/image.png" alt="image.png" />

Given what we have for the metric pump example, 99% sure it looks the same as above for metric also (for the equations, not the max flow)

**Comment by nbintertech** [comment]
Neither of these example form inputs seemed successful:
Fans yielded the below chart. 
<img width="1226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGY5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebf8ac3a0730911bd1cb3d969f018647fdd41995/image.png" alt="image.png" />

Pumps numbers ended in a circular process that froze the app (probably because of max flow rules).
it'll probably be more productive for us to look at numbers I already have in place from the last "fix" and pin down exactly what's wrong about the chart or which specific inputs are wrong. It's seems like this calculator doesn't respond predictibly to hard coding in numbers to use for example like the rest of our calcs. I want to get some leads on that before I spent time unpacking again.

**Comment by nbintertech** [comment]
We looked back at this. Everything from original issue-6664 pr was verified as correct. Previous 2 comments can be ignored
