### ISSUE TITLE
Higher Heating Value calculation

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6685]
There may or may not be a difference between desktop & online
This should be 10,593.08 btu/lb
Can we look at what's coming out of the suite, what units it should be in, and what the unit converters are doing?

<img width="548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fa277b7319d7de9ee20e3f13755672447e24d50/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Notes for me: could be related to recent issues where wasm/develop merges unwrote changes https://github.com/ORNL-AMO/AMO-Tools-Desktop/pull/6464/files

**Comment by nbintertech** [comment]
Fixed and tested working in PHAST and flue gas calcs. Have been multiplying by 100 since start of WASM bindings - must've been a misread by me when coding.
