### ISSUE TITLE
Steam Reduction Calc Fixes

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6686]
A lot of this is a suite issue.  Putting it here for now...

* "System Efficiency" field needs a /100 before given to suite
* "System Efficiency" renamed to "Boiler Efficiency"
* Help for "Boiler Efficiency": 
`The energy efficiency of the boiler system (stack loss, shell loss, blowdown loss, etc.).
Natural gas-fueled boilers are typically 85% efficient, steam heat exchangers are typically 90% efficient. A process heat exchanger would have a system efficiency of 0.85 x 0.90 = 76.5%.
Losses will further reduce system efficiency and must also be taken into consideration. Do not include losses due to distribution system.
`
* New field: "Distribution Losses" (will need a /100 before given to suite) units = % 
* Help for new field: 
`Estimate losses (from steam leaks, traps, etc.) associated with the transmission and distribution to the point where the steam reduction is taking place. If the steam leak is near the source, this is likely close to 0; if the steam reduction takes place down stream, estimate the steam lost due to leaks at that point.`

ALSO - need to add 2 more new fields - see Steam Properties Calcs, need to collect 1 more data point on steam and know what type of data it is (temperature, enthalpy, entropy, quality)
ALSO - enter unit conversion needs work.  the suite will now be in metric/steam units.  please see attached.

[steam reduction calc final.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08e635fdf2727fe5fb7b65bad4aa28bdaa6809a2/steam%20reduction%20calc%20final.docx)

**Comment by koay9f** [comment]
ISSUE HISTORY - ignore
Need to ask someone a bit more knowledgeable about steam or TH than me.

Question 1: when you use "offsheet" for a *Steam* utility are you entering the MMBTU of fuel to produce the steam or the MMBTU of the steam?
Answer - to get the correct klb steam, you need to enter the MMBTU of the generated steam.
Question 2: when you use "offsheet" for a NG or Other utility, are you ....
Answer - to get the correct MMBTU fuel, you need to enter the MMBTU of the fuel burned.

Problem - you are using the same field for two different values & for Scenario 2, you currently get the wrong klb steam. This is not a big deal, but looks bad.

Solution 1 - assume the above and change the math for off sheet, non-steam utility calculation of steam generated
Solution 2 - ask user if consumption = fuel energy or steam energy (drop down)

steamReduction.cpp
line 82:            tmpSteamUse = otherMethodData.getConsumption() * (1000000.0 / specificEnthalpy);

need to replace with an if statement based on utility type
if steam:             tmpSteamUse = otherMethodData.getConsumption() * (1000000.0 / specificEnthalpy);
else:             tmpSteamUse = (otherMethodData.getConsumption() * steamReductionInput.getSystemEfficiency() )* (1000000.0 / specificEnthalpy);

EDIT: need to edit above - solution 3 - remove off sheet option if utility == steam.  fix steamReduction.cpp so it uses the efficiency. 
think about changing the names of things in the dropdown

**Comment by koay9f** [comment]
Still need to "convert" to code language and deal with enthalpy

[steam reduction calc help.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1B5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e774f88b6c6ef3b963f8e4aa1a5a57d8b63d3441/steam%20reduction%20calc%20help.pdf)
