### ISSUE TITLE
Fix: Users must hard refresh for new app release

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6699]
Users ideally shouldn't have to hard reset their browser upon new releases.

'Best' solution - use cache busting. In short, we'd add a release hash or some other identifier to the url so measur url would be treated as new. Need to study up on this . Any issues with current routing style? Additional server config needed from Hayden?

Minimal solution - Send user toast pop up on new release, asking them to refresh if they experience trouble

This will likely improve/fix some of the caching issues with #6706

**Comment by nbintertech** [comment]
- Angular dist file and assets are setup to do cache-busting correctly (output-hashing)
- I've set up some event handlers to allow the app to tell when a new version has arrived. The suggested UX for this is popping up a toast notification with a button allowing the user to hard reload/refresh cache - rather than forcing reload.
- Won't be able to finish and test in a meaninful way until we have access to the dev server and I can download the PWA and test caching at a real URL

**Comment by nbintertech** [comment]
Will close after 1.5.0 is deployed

**Comment by koay9f** [comment]
I can actually see this in dev each time dev updates, but agree, will close after 1.5.0

**Comment by nbintertech** [comment]
Working - tested going from 1.5.0 to 1.5.1
