### ISSUE TITLE
Nat Gas Reduction Bug

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6709]
Air Flow Msmt = Mass flow of air

<img width="1666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ead9521d827291dde2171f87b4b571f0f28274c/image.png" alt="image.png" />

Energy Subtotal SHOULD == (0.953 /.8) * 1095 = 1304 MMBTU/yr not 13 MMBTU/yr.  What is going on?????

ALSO - 
What is a ft3/yr/yr?  why so many yrs?

**Comment by nbintertech** [comment]
Can I assume the calculation difference is taken care of by #6732?
