### ISSUE TITLE
Auto-update features

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#673]
When the dialog box appears to notify the user of an update, it would be nice to display information about what is in that update.
Is this possible to automate?

Also, is there a way to display an actual progress bar? Or someway to indicate how far along the download is?

**Comment by pshires** [comment]
https://electronjs.org/docs/api/auto-updater

The API doesn't seem to  a way to get release notes before you download, only after you download the update.

**Comment by koay9f** [comment]
Look more into this and then break it down further
