### ISSUE TITLE
X Reduction Percent Efficiency

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6732]
Found in Steam Reduction & Natural Gas Reduction
Electricity Reduction looks okay

The percents for efficiency should be "converted" to fractions before being sent to the suite (i.e., /100)
We were doing this as part of the unit conversions before WASM but I think it had to get moved.  I tried to find an example of where we are doing it properly but I can't navigate the desktop :D

**Comment by nbintertech** [comment]
@rhernandez-intertech before you do a ton of hunting - check the git timeline diffs for these files from when we switched over. Might have your work cut out for you - this worked for me on another PHAST binding input.

**Comment by koay9f** [comment]
we can catch them as we find them, but "Efficiency" is a really common field that all needs the same treatment.  Maybe for now, just treat as is, but I'll make an intern issue to find them all and confirm.  Would this relate to Doxygen documentation? (just message me)
