### ISSUE TITLE
Add labels to DE visualize Axis title fields

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6769]
@AlexBotts 

<img width="773" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFE3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--650041bf4c615a1a9722b844173eb6e332366aca/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
This may now be irrelevant

**Comment by nbintertech** [comment]
Also need to fix dissappearing 2nd Y axis

**Comment by koay9f** [comment]
<img width="1854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemc3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00708544a5abf09fe91b6cb6280daac459c775a9/image.png" alt="image.png" />


Not sure what the first part is supposed to be addressing. Axis title fields seem to have labels. 
Green - Where is second y - axix?
red - changed series name, graph not updatings and cannot click "apply graph changes"

**Comment by nbintertech** [comment]
Update the description with original screen from Alex. The combo of broken graph state and lack of axis labels probably made it hard to identify that field was the axis title, where if it was working, a user could connect the dots - anyway, added labels

axis 2 is not showing above because it hasn't been chosen as the axis to use for that series - "Use Y axis"

**Comment by koay9f** [comment]
I just noticed the second thing - suggestion:
have the label for teh user input for teh second y axis be "Y Axis - right Label"
if select "add y -axis" then the additional data series default to using the right axis

**Comment by nbintertech** [comment]
Changed so that any additional data series (not primary) will use right y axis when user decides to add it (automaticaly uses left if user removes right y axis).

Fixed broken update events for series name

**Comment by nbintertech** [comment]
Changed so that any additional data series (not primary) will use right y axis when user decides to add it (automaticaly uses left if user removes right y axis).

Fixed broken update events for series name
