### ISSUE TITLE
Compressed air calculation - similar calcs different results

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6817]
Same calculation happens in 3 places, but I'm not sure where the calc is, which makes me think it is in the desktop

Where is leak rate calculated for these three calcs:
* Assessment - `Calculate Air Storage Capacity` / System Capacity Calc
     * Where is math for leaks 
* Bleed Test Calc
     * Where is math for leaks 
* Useable Air Capacity Calc 
     * CompressedAir.h > calculateUsableCapacity
     *  (tankSize / 7.48) * (airPressureIn - airPressureOut) / 14.7
     *  tankSize --> gal returns receiver size in gal or scf, comments say both but gal might be kind of commented out?
     *  do not know where leak rate comes from

**Comment by koay9f** [comment]
<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cea25cc66b5bb901f7985a9207ee7c514f4ae33a/image.png" alt="image.png" />
<img width="659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzRsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f9de17a6a8b38597eaa34dbf2729bcfcfad85ff/image.png" alt="image.png" />

<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f857b5142e24e7ddf56d37baf1ff0e6691f7b412/image.png" alt="image.png" />

**Comment by rhernandez-intertech** [comment]
Here is the math for the leak rate for the Calculate air storage capacity
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c0ea49844edabf099a13bcd5b053051889d5f00/image.png" alt="image.png" />

and here is the math for the Bleed Test calc
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9sQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4620d53afa734f3862d3ba8c7c8c6e6062afb4ad/image.png" alt="image.png" />

and this is that math for Usable Air Capacity calc
<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d8810a250cfd6216c56e869e08d44a0417cc130/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Fixes:
Bleed test.  
I lied.  2 things:
Add this pic in for help text for "Test Pressure" and "Time"
<img width="912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG9xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc12cdec1e0740867b0f451f47d29d033de1bd55/bleedTest.png" alt="bleedTest.png" />

bleed-test.service.ts
Line 71: the 14.7 should be replaced with a new field for atmospheric pressure
`  let leakageDenominator: number = copyInputs.time * copyInputs.atmosphericPressure;`

UI: add field for atmospheric pressure (see system capacity for help text etc.)


System Capacity / CA Assessment "Calculate Air Storage Capacity"
standalone.service.ts
Line 175 & 176: no divide by 60, add the `* 1.25`
 `let denominator = (inputCpy.leakRateInput.dischargeTime ) * inputCpy.leakRateInput.atmosphericPressure;
    outputs.leakRate = numerator * 1.25 / denominator;`

Where ever UI is for System capacity (remembering it is also in the CA Assessment)
Units for "Discharge Time" should be minutes (min)
<img width="627" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54c547d9b6f8a1e24f97df05cf919855fea5e6a2/image.png" alt="image.png" />

More UI
Replace all fields for "Leak Rate" with corresponding ones from `Bleed Test`.  Help text, field names, etc.





Useable Air Capacity
Honestly, just hide the references to leak rate calculator within that.
Should keep the field for "Atmospheric Pressure" (can be moved as necessary), but the result for leak rate, the input for "Discharge Time", and the header "Leak Rate Calculator" should all go away.

**Comment by nbintertech** [comment]
Made all of above changes. Metric System Capacity results should be double checked. There were conversions that were stripping leak rate input, hence no result shown. Looks correct to me now. 186 acfm vs 5 Am3/min
