### ISSUE TITLE
Co2 Emissions Mixed Fuels

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6830]
1. Mixed Fuels - totalFuelEmissionsOutputs values are being overwritten on tab/view change in SSMT because the fuelType value for Mixed Fuels is an empty string.  I believe 'Mixed' is used elsewhere and should be used here unless it will conflict with something else (i.e. in TH). This is defined in a constant used in both PHAST and TH so should be tested thoroughly. 

location -> setCo2SavingsData() -> setEnergySource
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVUyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcea95e41f10347cb14e7cb7160f0f911af2d297/image.png" alt="image.png" />

2. We also observed Nat Gas emissions value being populated in when user backspaces the input down to null/undefined or changes energy/fuel types. Its possible fixing #1 will take care of this

Original bug observed by Kristina below:
This field is relooking up the value or something each time you navigate away so that any changes do not save
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN014QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bb1d2387eda9cf9d63edb892f4ebeb86b65ba31/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Need the assessment. There may be a specific case or some outlier causing this. Couldn't reproduce.

Tested - BL and MOD values reflected in form and EXOPPS when navigating tabs and in/out of assessment, measur, as well as changing modifications

**Comment by nbintertech** [comment]
Fixed both issues.
Tested new SSMT, SSMT example by choosing Nat Gas, Petro, Mixed, navigating between tabs, selected scenarios, assessment open/close. backspacing input digit by digit as well as clearing all input.
Also tested PHAST and TH implementations that were related to Mixed Fuel constants used - no issue or change there.
