### ISSUE TITLE
1.5.0 Release Notes

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6832]
Need updates notes from Kristina

**Comment by koay9f** [comment]
[Release Notes v1.5.0.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1EwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a941f5001e942164f951b6ca091fd9b1ca01358/Release%20Notes%20v1.5.0.txt)
