### ISSUE TITLE
MEASUR: 1.5.2 Release

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6843]
bug fixes

Email david.steiner@hexion.com (emailed MEASUR help on 2024/07/10) to let know that #6912 is fixed

**Comment by koay9f** [comment]
[Release Notes v1.5.2.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39d45977511f0b6893a093415ff9bab28f2d0211/Release%20Notes%20v1.5.2.txt)

Release notes if 1.5.2 (no auto save)
