### ISSUE TITLE
MEASUR 1.5.0 Mac installer Stapling issues

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6857]
ORNL machines cannot satisfy apple/signing stapling requirements. Hayden has IT request in to resolve this.

**Comment by nbintertech** [comment]
Hayden on install of 1.4.0
<img width="266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acdc2596f664ac14d3a827cc16bf147b5fcfafc9/Screenshot%202024-06-06%20at%201.39.37%E2%80%AFPM.png" alt="Screenshot 2024-06-06 at 1.39.37 PM.png" />

Potentially missing 'stapling' step of signing

**Comment by esserhr** [comment]
We've a solution to stapling our builds via GitHub-provided runners in the future when builds are automated, so closing this issue for now.
