### ISSUE TITLE
PH Energy Results units cause problems with CO2 emissions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6861]
When we do CO2 emissions I think we assume that the energy units are in either metric or imperial and not custom.  
Need to be sure to convert energy before doing CO2 calculations
<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2xCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3e9ce0e37849d1d0e7ffd82eed2dd6bc9cedd1e/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Fixed so we're converting phast energies (electricity use, fuel use) from custom energy result unit to emissions units (GJ/MMBtu).

it seems that coal/carbon and 'other' fuel used are only ever in imperial/metric, GJ/MMBtu. If that doesn't seem right I can dig deeper.
