### ISSUE TITLE
Cooling Tower makeup water - water cost not saving

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6863]
Looks like
1 - water cost isn't being pulled in from the setup
2 - water cost isn't being saved if entered manually
3 - water cost math isn't being done (could relate to previous)

Just need water. cost = 0.004, values don't matter, just more than 12000 kgal
<img width="1688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2REQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b82cdf2fe6ea73d57d5461b3e02f59ed7d5a42fe/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Likely 2 things going on here:
1. Fixed water cost populated from TH settings
2. Suite inputs are spitting out INFINITY and NAN. Inputs look normal. Probably need a call to get expert eyes on this
