### ISSUE TITLE
If I delete the examples and then upgrade the tool do the examples come back?

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#688]
When we roll it out, it might be nice if they don't, but right now, it might be good if they did...

**Comment by koay9f** [comment]
How do you reset your data?

**Comment by rmroot** [comment]
![reset-data](https://user-images.githubusercontent.com/10789740/30752368-b441e7cc-9f81-11e7-984e-bf8bff8a14a7.PNG)
