### ISSUE TITLE
Pipe/Tank Insulation in metric

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6912]
For both Pipe & Tank Insultation
When calculators are in metric  
Utility Cost is still in $/MMBTU on label.
Results are in MMBtu. 

1 - labels are wrong, Should be $/GJ and GJ to match TH
2 - I *think* unit conversion is in MJ for "Heated" and **_should be_** GJ to match TH 
(I think I found the unit conversion and it looks like it is doing MMBTU for imperial, heated, MJ for metric, heated, and kWh for both, chilled, but it is confusing).  

3 -  the results doesn't quite match what I'm getting in MJ. this could be few things, but need to review unit conversions.
Just do a quick double check that things match what the suite is expecting/providing
Data in imperial (correct results)
<img width="1610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cf5cb63dc9dab555e67c5db0fe9c4b7155f3832/image.png" alt="image.png" />

Data in metric (except $/MMBTU, that value is in $/MMBTU)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5ZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f964e18fd8008b375c39a287de1ac8e7c06670ee/image.png" alt="image.png" />

Correct value in metric:
1168 MMBTU is 1,232,310 MJ = 1,232.31 GJ.  This is close (returning 1,278,232 "something probably MJ"), but not quite.  It could be me converting from the user's metric to imperial + the dropdown for wall thickness not being perfect, but please check unit conversions to be sure.

from: MEASUR-help ticket. David Steiner, Hexion, 2024/07/10

**Comment by nbintertech** [comment]
@koay9f this is the type of issue that would be great to have Michael take a look at once he is familiar with the project. It's important to resolve - not necessarily complex but involves a lot of cross-checking and knowing where to look.

**Comment by nbintertech** [comment]
Hard to compare examples between imperial/metric since they are different examples, but...

Obvious issues fixed:
- removed utility cost mistakenly being divided by 1000 (?) - calculation was: ` energyCost = results.annualHeatLoss * input.utilityCost / 1000`
- Fixed labels not detecting metric units
- Fixed (changed to GJ) results converting from watt/hour to MJ
- Removed call to modification energy source type no longer used

If issues still remain, let's discuss over a call
