### ISSUE TITLE
Pull Added Energy (Motor equipment) into Intake and Discharge

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6916]
In Intake and Discharge we want to see a sub form showing any added energy to that source/outlet from a plant-wide motor. May have more than one motor. 

- We'll still keep the added motor energy section in Water System form?
- Do we need to see a field or result that's the sum of all motor energy?

<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcf4587879fbd39ad061423a646c69bd615ed1ff/Group%204%20%281%29.png" alt="Group 4 (1).png" />

<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64dd8d49c6814bf6c941474539f49babf460fa32/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Yes we will still keep the process-level energy estimations
Re- sum of energy: we'll have to think on how to approach this. my guess is that if you have a intake wide flow that had energy added to it before splitting up (i.e., on the intake form), then "process one" would get a portion of that energy = {flow process 1 from input 1}/{flow input 1} and it would just be "inherited" from input 1, if that makes sense. So, even if you don't add any more energy to process 1, it does still have that from when it was part of input 1
