### ISSUE TITLE
Add info about data storage to About page

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6924]
Add section about where data is stored

Also, maybe add things about our open source license, etc?

Mark is doing the same thing for VERIFI, see what he's doing

https://dev.measur.ornl.gov/about
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fde3e95790230d075b5889e904ee44e276b6dd9c/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Added info about data storage to 'data storage and backup' sidebar link. Added open source software declaration to about page
