### ISSUE TITLE
Automated Backup

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6925]
Push for upcoming release:
- Add sidebar link 'Data storage and backup'
- Add laymans Info about measur data storage and how it works #6924 , advise user to backup
- Allow restore from file
   - Desktop - Add automated backup file ion/off setting - file will be continously overwritten
   - Web - Adjust sidebar link and modal so user can download backup file of all data (without needing to select for export)
- Pop up warning if user navigates away without selecting automated backup location
- Pop up warning when user restores backup notifying them it will overwrite ALL data

Future:
- versioning?
- Refine UI during dashboard overhaul, possibly integrate to that area
- More direct control of the setting from sidebar

**Comment by koay9f** [comment]
looks like a good start to me
