### ISSUE TITLE
Compressed Air - Add "fill right" function to assessment 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#6933]
Compressed Air - Add "fill right" function to assessment 

via Frank Request 

Add the fill right functionality that is currently in system basics>system profile> setup profile>Compressor ordering table  to the assessment tables that are similar. At least reduce system runtime and improve end use efficiency 

<img width="493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVU5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4d46b8a859072fc3ef57d2d009a4237040ffb94/image.png" alt="image.png" />

**Comment by AlexBotts** [comment]
ideally by October 14, 2024

**Comment by nbintertech** [comment]
example <img width="955" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU5PQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46a40c90879f4a54a196e1a81a2c9c5d57125834/image.png" alt="image.png" />
