### ISSUE TITLE
Compressed Air - Add compressor ordering number to the base/trim system control type

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#6934]
Add compressor ordering number to the base/trim system control types in the setup profile compressor ordering table (instead of just on/off). Logic already exists in the profile summary portion, just need the ;able - trim compressor will always be last one on. 

<img width="1426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWM5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0c35e7adfd769ffa827cb3a1ed4ffd15e22e71f/image.png" alt="image.png" />

**Comment by AlexBotts** [comment]
from Frank

**Comment by nbintertech** [comment]
Added logic to allow mutli compressor numbered ordering on base/trim types. Fixed 'Turn all on' automatic ordering by full load pressure

**Comment by koay9f** [comment]
Setup profile is not updating when change things in inventory
Trim is not always forced to last compressor - that is bad

<img width="960" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2FEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cdd97642c1a5da56f05393a7cca8828c15c9d98/image.png" alt="image.png" />

**Comment by AlexBotts** [comment]
More info: The 'trim' compressor should always be in last place (of the on compressors), regardless of full load pressure ordering. Currently looking like the ordering is still based solely on FLP. In the screenshot above, from top to bottom, the order should have been 2,1,3

**Comment by nbintertech** [comment]
Change FLP to test ordering

**Comment by nbintertech** [comment]
Moved the last few comments to #6969 - multiple changes and doesn't seem to be a side effect of this issue
