### ISSUE TITLE
Data Explorer - Vertical and horizontal trace lines 

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Desktop#6935]
via Frank 

Add vertical and horizontal trace lines to DE. 

<img width="1002" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkU5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de65f77ee2302a34fdf8eec8844ab77349effe96/image.png" alt="image.png" />

Pump curve has vertical, not horizontal. 
If this slows DE down too much, the answer is no

**Comment by nbintertech** [comment]
Also added a toggle on/off for existing range slider
