### ISSUE TITLE
PHAST - Openings - View Factor

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#694]
In PHAST - Openings.  to find the view factor the tool tells the user to look it up in a table.  We do not provide this table.  
PHASTEx provided this graph
![image](https://user-images.githubusercontent.com/25389736/30759753-5f8b2f12-9fa5-11e7-8a00-d8e61133ffa8.png)

Could we digitize and make a modal?

**Comment by koay9f** [comment]
This is the code from PHAST 3.0 to calculate View Factor.
It has 2 parts: the function to calculate View Factor & the if statements that tell you which functions to use

[Calculate View Factor.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46cb959620978fa89becff75ad58e7d40f4724672616e1673295f127b54778154d555ca9480c0a16adfbdd22a1e76a22d85c0be8d63b5e71956f17bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8f463d1906198aff5932a58b06.txt)

**Comment by pshires** [comment]
completed on the backend https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/146
