### ISSUE TITLE
CA - Control Type VFD - Pressure Range

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6967]
Lower number should be full load (cut-in).  Alex thinks the higher number should be the "Turndown" but is displaying as zero

<img width="937" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fc9f245c6ba646e3d780503718e5583f0eab349/image.png" alt="image.png" />

Ask Alex for file to test

**Comment by nbintertech** [comment]
Lower number is currently Full Load discharge pressure, higher number changed to Turndown discharge pressure.

<img width="1224" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d990b9351612bb5058101493b8e8c24901d4aa96/image.png" alt="image.png" />
