### ISSUE TITLE
Steam CO2 emissions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#6991]
It looks like at some point the reported value for CO2 emissions in steam got off by a factor of 1000

I looked at issues and didn't see any to do a /1000 anywhere, and the issues I did see (for labels CO2 Emissions & Steam) looked closer to right in the screenshots.  

<img width="1822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82497ff92015914c5343ed00f6e490a74a746a0a/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
This was caused by 6981. I added tonnes conversion to the shared co2 savings method by mistake
