### ISSUE TITLE
Add New Fuel (solid) display problem

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#7000]
Everywhere you get the Add New Fuel model except the custom materials page -
Enter data such that it sums to 100 & save
Reopen and select fuel from dropdown
every number is (still?) a fraction instead of a percent

from - riyaz

**Comment by nbintertech** [comment]
The suite db that stores these materials already converts to a fraction, so I removed the function doing this on the MEASUR side. Looking at git history it looks like this may have gotten confused 4/5 years ago also. Anyway, conversion problem should be fixed but there is another issue with custom materials that is making it harder to test
