### ISSUE TITLE
Add DOI and OSTI page to About page

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#7009]
Information about citing MEASUR can be found at our OSTI page: https://www.osti.gov/doecode/biblio/69000
MEASUR's DOI is https://doi.org/10.11578/dc.20220107.3

<img width="1341" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--586d4622b35410f6ccf0abf83a5ce2aa17b5967d/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Just want to confirm - both these URLs go to the same place. is the DOI supposed to be plain text?

**Comment by nbintertech** [comment]
Just want to confirm - both these URLs go to the same place. is the DOI supposed to be plain text?

**Comment by koay9f** [comment]
everything looks good.  thanks for adding link to download also
