### ISSUE TITLE
Quick help text update - Pumps & Fans

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#7017]
**Efficiency Class **
Motor Help
Enter measured data to calculate your system's annual savings potential.
Efficiency Class
Efficiency Class is the classification of efficiency given to motor. This can be found either on the nameplate or based on how the motor compares with the NEMA MG 1-2003.
Efficiency Class options include Standard Efficiency, Energy Efficient, Premium Efficient, or Specified.

The Premium (IE3) and Energy Efficient (IE2) classes are based on motors that match those NEMA classes. Standard motors should be used if the efficiency is below Energy Efficient (IE2). 
If the user knows the full load efficiency, it can be directly entered using the "Specified" option. The motor efficiency at load will be calculated based on the same curves used for the other efficiency classes.

**Efficiency **  For the pump & fan assessments and any calculators that use the same form (Full Load Amps?). Field only visible if the efficiency class == specified

Motor Help
Enter measured data to calculate your system's annual savings potential.
Efficiency
If the users knows the full load efficiency of the motor, it can be entered here instead of estimated via the efficiency class.

Motor efficiency is the ratio between the amount of mechanical work the motor performs and the electrical power it consumes to do the work, represented by a percentage. A higher percentage represents a more efficient motor. Electric motor efficiency is dependent on (but not limited to) design, materials, construction, rating, load, power quality, and operating conditions. Enter this value as a percentage.

**Comment by nbintertech** [comment]
Updated:
psat - motors, modify -> motors, explore opps -> motors
fsat- motors, modify -> motors, explore opps -> motors
pump inventory - catalog motor
motor perf calculator
nema calculator
fla calculator

Didn't update motor-inventory - there is no specified option
