### ISSUE TITLE
Pump Motor Power Factor Too Large

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#7032]
Power factor calculation is way too large under specified efficiency scenario. Motor inputs look good. Need to check suite

**Comment by koay9f** [comment]
making a suite issue to change the suite to expect a fraction. so we will need to switch this back after that is done

**Comment by nbintertech** [comment]
Reversing this now. We also changed EstimatedFLA in suite so will need to check that on desktop side
