### ISSUE TITLE
PHAST - Electrotechnology Auxiliary power calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#705]
The C++ returns the loss for this calculator in kW.  Should be converted to Btu/hr so the unit conversions work correctly.

**Comment by koay9f** [comment]
AuxiliaryPower.cpp
lines 12 & 13 should be...

double AuxiliaryPower::getPowerUsed() const {
	return pow(motorPhase, 0.5) * supplyVoltage * avgCurrent * powerFactor * operatingTime * 3.412136247820839;


AuxiliaryPower.h
line 46 should be ...
* @return double, auxiliary power used in btu/hr

**Comment by pshires** [comment]
Fixed in https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/124
