### ISSUE TITLE
CA Sankey Bug

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#7073]
From Alex:

The compressed air sankey tab was not showing any content for the inplant data she had. See me for the data file. 

I narrowed it down to the power-sankey.service.ts `getAirPropertiesLookupData` function. The lowRangeProperty is coming back as undefined for one of the values. I've pushed up a branch with my temporary fix (issue-7073).

I also was unable to go to the "Airflow Sankey" tab. Didn't get any errors and didn't investigate.

**Comment by nbintertech** [comment]
Airflow sankey is disabled (it does not exist)

It seems to me that low pressure bound needs to be greater than 0. Will check with Alex about whether low pressure bound being negative is a valid case, and what should be done either way

**Comment by nbintertech** [comment]
PSIA TO PSIG AND PSIG TO PSIA conversions in the sankey algo were incorrect (used shared convertUnitService, instead of +/- atmosP), creating negative pressure values and killing the sankey.

**Comment by nbintertech** [comment]
Verified by @AlexBotts - closing
