### ISSUE TITLE
add recommended citation to about

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#7075]
Just some text around the link

Information about citing MEASUR can be found at our OSTI page: https://www.osti.gov/doecode/biblio/69000
Suggested APA Style Citation:

Accawi, Gina, Root, Robert Mark, Blondheim, Nick, Howard, Dmitry, Hernandez, Rachel, Armstrong, Kristina, Cranfill, Kita Dawn, Shires, Preston, Kaminski, Michal, Hadden, Jon, DePauw, Josh, Sakovets, Yevi, Causey, Colin, Beanblossom, Kyle, Whitmer, Michael, Ledbetter, Allie, Rappoport, Ben, Saravanan, Shiva, Merchant, Charlotte, Kokul, Shubham, Fontenot, Zach, Vance, David, Worley, Andrew, Aziz, Omer, Ferree, Autumn, Rosser, Noah, Jensen, Jeff, Adams, Mark, Rios, Raul, Wenning, Thomas, Armstrong, Kristina, Nimbalkar, Sachin, Accawi, Gina, Abbas, Ahmad, Chaudhari, Subodh, Sundaramoorthy, Senthil Kumar, Botts, Alex, Cox, Daryl, Casada, Don, Thekdi, Arvind, Martin, Vern, Martin, Donovan, Falk, Mats, Wroblewski, Ron, Harrell, Greg, Cunningham, Glenn, Papar, Riyaz, Brockway, Walt, Guo, Wei, & USDOE Office of Energy Efficiency and Renewable Energy. (2022, March 22). MEASUR - Manufacturing Energy Assessment Software for Utility Reduction [Computer software]. https://www.osti.gov//servlets/purl/1856108. https://doi.org/10.11578/dc.20220107.3

**Comment by nbintertech** [comment]
@rhernandez-intertech - we want to present your name as Rachel Stone here right? Does that need to be changed anywhere else?
