### ISSUE TITLE
PF Triangle calc bug

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/AMO-Tools-Desktop#7117]
- something funky going on with the results where they equal the inputs
- set the chart to have a set x & y axis so the triangle change can be seen 
- show results below the chart

**Comment by koay9f** [comment]
Using a static axis limit isn't really working well.
Can we do it so axis are something like 1.05 * max(realPower, reactivePower)
(sorry not sure of variable names)

Also, we need a quick pass at some validation
for now:
* power factor <=1
* power factor >0
* phase angle < 90
