### ISSUE TITLE
CO2 emissions results followup 

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#7134]
Assessment level settings - be able to change result in assessment.  Should operate like the process heating results (don't need to ask if they need to update fields, since it will just change results

Labeling fixes: 
Fans & pumps & process heating & compressed air
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1c1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--760ec8020f0340388c63bdc19a3b1eb957e1d0de/image.png" alt="image.png" />

<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2U1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3764544e5e266b4672e4c6cd7cdb4469e0926d1c/image.png" alt="image.png" />

<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMys1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1787be12cb33ec27fbdcbc5b48eac5a9888ed4ef/image.png" alt="image.png" />

Process Heating
has "tonne" hard coded it looks like
<img width="703" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE81Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80c2173a0b589fa241879e34ec2e96e19d2e4a91/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Fixes:
- Add emissions result unit as assessment/inventory specific result
- Upgrade user settings when new version is installed

Tested with new assessments, old assessment imports, old assessments during install of new measur
