### ISSUE TITLE
Motor Performance Calc Improvements

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#7199]
<img width="757" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNkQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--629ff0284bb65c69dbd7d19f734833cdef0cd089/image.png" alt="image.png" />

1 - X-axis - percent format, by 10% if looks okay (40% instead of 0.4)
2 - dark grey hover - percent format, 1 decimal places, add label text (instead of `0.58100000003` --> `58%  Shaft Load`
3 - why are all data points XX.1%?  is this a suite issue? should be XX.0%

**Comment by nbintertech** [comment]
<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklnQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f691c495c3bb18a89bba0cb2a3aab6af47a885e3/Screenshot%202024-12-12%20064750.png" alt="Screenshot 2024-12-12 064750.png" />


Plotly can’t do exactly as asked on this one, but there is one good option (A) , one less reasonable option.. and C:

A: Keep the original X hover tag with the value only (44%) and don’t worry about the ‘Shaft Load’ text. This tag comes for free with a hovermode setting that allows you to see hover data for all traces over X.

B: Use the hover tag with value and text (part of a custom hover trace), but will need to find a way to ‘hack’ the original tag out. Also note the Shaft Load (hover trace) showing in legend, which I’m thinking we’d want removed

C: rebuild the chart with custom logic to programmatically show hovers over all three

**Comment by koay9f** [comment]
A is fine.
B would be better if you could hide Shaft load from the legend, but that is probably more effort than it is worth.
