### ISSUE TITLE
Sometimes when I create a new assessment...

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#723]
Sometimes when I create a new assessment, it immediately makes a copy of it.  I have no idea what makes it happen.  I cannot consistently recreate it.  Just thought I'd let you know and if I can figure out what causes it I will add to this thread.

**Comment by rmroot** [comment]
Figured out what is happening. You are probably double clicking or double enter. It's creating an instance for each time you click/enter. I'll add a guard to prevent this from happening
