### ISSUE TITLE
PHAST - adding new fuels in flue gas

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#726]
Gas (by volume)
age]
![image](https://user-images.githubusercontent.com/25389736/31094433-43494bb4-a783-11e7-9024-9070e38eb42c.png)

Solid/Liquid (by mass)
![image](https://user-images.githubusercontent.com/25389736/31094438-4677e976-a783-11e7-9c27-2b35a7f9cd05.png)

**Comment by pshires** [comment]
addressed on the backend in https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/120
