### ISSUE TITLE
PHAST - Charge Materials c++

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#770]
edit: what was here is wrong.  see comment

**Comment by koay9f** [comment]
Also
SolidLoadChargeMaterial.cpp
Needs ( after ChargeFeedRate_ * 
Needs ) at end

Line 33
`hs = this->chargeFeedRate_ * ( (1.0 - this->waterContentCharged_) * this->specificHeatSolid_ * (this->meltingPoint_ - this->initialTemperature_) + this->latentHeat_ + this->specificHeatLiquid_ * (this->dischargeTemperature_ - this->meltingPoint_));`

**Comment by koay9f** [comment]
LiquidLoadChargeMaterial.cpp

Line 18
`        hliq = this->chargeFeedRate_ * ( this->specificHeatLiquid_ * (this->vaporizingTemperature_ - this->initialTemperature_) + percentVaporized_ * this->chargeFeedRate_ * (this->latentHeat_ + this->specificHeatVapor_ * (this->dischargeTemperature_ - this->vaporizingTemperature_)) + (1 - this->percentVaporized_) * this->specificHeatLiquid_ * (this->dischargeTemperature_ - this->vaporizingTemperature_));`

**Comment by pshires** [comment]
closed by https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/134
