### ISSUE TITLE
PHAST - Correction Factor

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#773]
Many tabs in PHAST have a "correction Factor" (Wall Loss, Atmospheric Losses, Fixtures, Cooling, Slag Losses), however these are not included in the calculators.

EDIT: only Wall needs it.  and it is already included in the bindings

This could be included in the C++ or the UI, which ever is easier.

The math is:
Actual Loss = Loss from C++ * Correction Factor

If in the C++:
would also need to add it to the h files and change all the unit tests..

**Comment by pshires** [comment]
closed by https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/134
