### ISSUE TITLE
PSAT - Auto fill some fields via fluid dropdown

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#840]
In the basic input information you could have a pull down for different common fluids for the user to select. You could also input a temperature so properties could be automatically modified.

Would need to:
- make list of commonly pumped fluids
- density
-kinetic viscosity
and how those change with temperature

* add drop down with the fluids
* default value for density & kinetic viscosity = value for fluid
* add something that would change the value based on a calculation with an additional input for temperature (modal?, something like "calculate full load amps"?)

**Comment by koay9f** [comment]
Gave math & data table to Preston to add either to the desktop or desktop and suite

**Comment by pshires** [comment]
do we want to deal with pressure affecting the boiling and melting points of different fluids? Should ask Tom about this.
