### ISSUE TITLE
PHAST Roll up units - connect #687

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#857]
Total Annual Energy Savings and Annual Energy (at the top, and for the small summary table we talked about)  should be in either MMBtu or GJ.
(If there is an electrotech in the roll up, convert the units to MMBtu or GJ).

Usually, since roll ups are by plants, all assessments should be in the same unit system (imperial or metric), what will we do if they are not?  Maybe use the global default setting?

**Comment by gaccawi** [comment]
connects #687
