### ISSUE TITLE
PHAST Default Help

### ISSUE THREAD

**Issue by RoundDev** [ORNL-AMO/AMO-Tools-Desktop#863]
Slag, Exhaust Gas, Energy Input, Other Losses, Operation Cost, Heat System Efficiency  are missing default Help field

**Comment by koay9f** [comment]
[PHAST page help.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46d8bcbb10b6c3b98eeeba03ac58fc846b0a65633b0ba92e7391a172fd1722050a0d1fae15515815aaabdb2ba6b33b268b5958bfd77f4366846c4ff8e7df46f554f832815d84beb68b49c1e83e27e18f874c3616010ac4.docx)
