### ISSUE TITLE
PHAST - Opening Losses Add Static Image to Help Text

### ISSUE THREAD

**Issue by pshires** [ORNL-AMO/AMO-Tools-Desktop#873]
Need to add this graph to the help text for view factor / opening losses as a whole (maybe?)

**Comment by pshires** [comment]
[PHAST_Lookup_ViewFactor.pdf](https://github.com/ORNL-AMO/AMO-Tools-Desktop/files/1459376/PHAST_Lookup_ViewFactor.pdf)

**Comment by koay9f** [comment]
Could make it smaller in help text and if user clicks on it, makes a pop up with bigger one

**Comment by AshaShibu** [comment]
Image broken on windows. Confirmed to work on Mac/linux

**Comment by AshaShibu** [comment]
Image still broken on windows.
![capture8](https://user-images.githubusercontent.com/31292133/33679922-0c9da810-da8e-11e7-80c7-7cf878de96a5.PNG)

**Comment by rmroot** [comment]
oops looks like the change in file extension did not save
