### ISSUE TITLE
Pre Assessment Help Content-Description

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#887]
Pre Assessment needs a description in the calculator menus

Calculator help content is needed, field by field help is being used from PHAST but I believe there should be some help on how to use the calculator itself

**Comment by koay9f** [comment]
tool description:
Enter design or metered energy use data for furnaces within a facility to determine the relative energy use and prioritize energy use evaluations and improvements

**Comment by koay9f** [comment]
help content to come...
