### ISSUE TITLE
Pre-Assessment Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#893]
Name should be:
"Pre-assessment / Screening Calculator"

Zones need to have editable names (don't need to do anything with them, just for easing user input)

Don't ask about auxiliary equipment

Anywhere where it says "collection" change to "data collection"

**Comment by rmroot** [comment]
going to add this to "Redesign" because I am going to have to rethink how this is designed based on the new system.
