### ISSUE TITLE
PHAST Pre-assessment calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#897]
The units are off.  I am not sure if MMBtu (Designed - Fuel)  is not being converted to Btu or if Btu (Metered- Fuel & both steams) are not being converted to MMBtu (I don't know what your base unit is for this), but it is resulting in weird numbers

![image](https://user-images.githubusercontent.com/25389736/32959539-e93a08a8-cb8f-11e7-9568-65e0c308c35a.png)

**Comment by AshaShibu** [comment]
![capture](https://user-images.githubusercontent.com/31292133/33620516-095b4e92-d9b6-11e7-94fb-3f98bb8daacf.PNG)
The units still seems off. 
![capture1](https://user-images.githubusercontent.com/31292133/33620514-07b805f8-d9b6-11e7-83e1-2521a3dbe308.PNG)

**Comment by AshaShibu** [comment]
![capture](https://user-images.githubusercontent.com/31292133/33620608-53dbb7c2-d9b6-11e7-9557-e67dca595739.PNG)


The units still seems off. Not sure if MMBtu is converted to Btu
