### ISSUE TITLE
Motor load Calculator

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#901]
Add a new stand alone calculator for calculating the motor load.

**Comment by gaccawi** [comment]
https://github.com/ORNL-AMO/AMO-Tools-Desktop/tree/add-percent-load-estimation

Mostly complete in this branch, needs finalizing the donut

**Comment by AshaShibu** [comment]
Update: Tom wants to add the case when line frequency= 50 Hz

**Comment by AshaShibu** [comment]
Needs further fixing: On opening the calculator, the synchronous speed is automatically set to the lowest possible value. The second and third user input rows should be switched and based on these values only the synchronous speed should be detemined
