### ISSUE TITLE
PHAST Min/Max

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#911]
Help text has mins & maxs for most fields, they should be enforced

Examples:
Charge Material: Average Specific heat...
Flue Gas: Excess Air

**Comment by koay9f** [comment]
CHARGE MATERIALS

![image](https://user-images.githubusercontent.com/25389736/33496056-c9196368-d696-11e7-8d39-628a3c00c0a0.png)


![image](https://user-images.githubusercontent.com/25389736/33496068-d21bb812-d696-11e7-9c1f-e7a0c402c11a.png)


![image](https://user-images.githubusercontent.com/25389736/33496093-e33924f4-d696-11e7-8b29-833974adac91.png)

**Comment by koay9f** [comment]
Fixtures: Specific Heat & Fixture Weight feed rate
Cooling: Average Specific Heat & Gas Flow
Flue: Moisture in air
Unburned carbon in ash

**Comment by koay9f** [comment]
These need *enforced* minimum = 0 and "Minimum = 0" added to help text:
Charge Materials : all three charge feed rates (yellow arrows in pics above)
__Wall__
wind velocity
total ... surface area

__Atmosphere__
Average Specific Heat
Flow rate

__Gas Leakage:__
Area
Specific Density

__Extended Surface: __
Area

_______

Wall Losses: Surface Emissivity needs min/max 0-1 Enforced & in help text

_______

These just need it in the help text
__Opening losses__
Diameter
% Open
Thickness
Height
Length

**Comment by koay9f** [comment]
Do not enforce ANY mins/maxes for temperatures.  All help text mins for temps should be removed in issue #912

**Comment by AshaShibu** [comment]
![capture9](https://user-images.githubusercontent.com/31292133/33684939-faaeb166-da9d-11e7-8814-e2d4667b6076.PNG)

Typo error
