### ISSUE TITLE
PHAST Temperature Help text Mins

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#912]
Remove minimum temperature, if one is listed (Flue Gas, Fixtures, Cooling, )

**Comment by koay9f** [comment]
Also in Non-EAF Energy Input
Combustion & Exhaust Gas Temp
These are also enforced and should not be

**Comment by pshires** [comment]
I can't seem to find evidence of these values being enforced.

**Comment by pshires** [comment]
These values were being keyboard enforced but not value enforced
