### ISSUE TITLE
PHAST Emissivity Max/Default

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#913]
Emissivity can be found on:
Wall  (Help text should be changed to read default = 0.9)
Opening
Extended Surface (Help text - delete "Units")

Max = 1
Default = 0.9

The line "Typical - 0.9" can be removed (it is in the help text)

Should be enforced. 
It is in the help text and enforced on some of the pages, but should be double checked

**Comment by pshires** [comment]
do we want to enforce a minimum of 0? I noticed that opening losses enforces a min of 0 and a max of 1

**Comment by pshires** [comment]
according to wikipedia, "The [Emissivity] ratio varies from 0 to 1." So therefore I am going to go ahead and enforce 0 as the minimum

**Comment by koay9f** [comment]
I think technically emissivity can exceed these bounds, but it is not likely in the use of this tool...
