### ISSUE TITLE
PHAST - Help text - Gas Leakage

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#915]
In the help text, the two temperature fields have (F) after the name in the help text.

Remove and add:
Units: F and C

like it is for other temperature fields  (all F's and C's should have the degree symbol, I just can't type one here...)

**Comment by pshires** [comment]
right now we have logic that will change the units to say either F or C depending on whether imperial or metric is selected, do we want to get rid of this for sure and just say F or C (with the degree symbols) ?

**Comment by koay9f** [comment]
I don't think we both with the logic on any other field.  

I think this is actually an issue for the whole page (gas leakage).  The Units should be a subsection under "input". 

look at another page in PHAST and try to match it.  Maybe comment out the code for now if we decide to implement that method though out the tool (since it might look better...)
