### ISSUE TITLE
PHAST - Name losses

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#921]
Would like to be able to edit/name the losses, especially for Wall losses

**Comment by gaccawi** [comment]
Rename folders, assessments also.

**Comment by koay9f** [comment]
Names of losses should be included on the "input report"

**Comment by koay9f** [comment]
Does not save name FOR TOTAL on Charge Material if Type = Liquid or Gas

Does not replace name FOR TOTAL on Cooling at all
