### ISSUE TITLE
PHAST - Report Graphs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#923]
Color choices aren't great.

For Pie: Sachin wants to think about it.

For Column: should be higher contrast between two bars.  Shades of Red & Blue? Orange & Blue? Orange & Purple?

Also, when smaller screen, the X-axis labels in the column graph start to tilt and mis-align themselves from the corresponding columns

**Comment by koay9f** [comment]
There are some good colors in the O2 Enrichment graph

**Comment by rmroot** [comment]
http://htmlcolorcodes.com/color-chart/ i use this for choosing colors

**Comment by rmroot** [comment]
per @DmitryHoward  https://coolors.co/011627-fdfffc-2ec4b6-e71d36-ff9f1c another resource for colors
