### ISSUE TITLE
PHAST - Flue gas - add ability to enter % O2 in flue gas instead of excess air

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#927]
Need: Dropdown or something to choose calculation path between "Flue Gas Temperature" (may be called "Gas Temperature", see #895 ) and "Excess Air"
     Choices: Percent oxygen in flue gas, Excess Air
     Name: Oxygen calculation input

if Excess air:  calc proceeds as normal.  Add line that shows result for % O2 in flue (non-editable)

%O2 = 2*XA / (8.52381 - (9.52381 * XA))

if %O2: calculate Excess air using equation, show as non-editable field, then calculate like normal

XA = (8.52381 * %O2) / (2 - ( 9.52381 * %O2))

Display Excess Air result

XA = Excess Air
%O2 = percent oxygen in flue

See page 2 of Algorithm document

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/33338541-6364b7c4-d444-11e7-8931-9aaf39f8d6f0.png)

![image](https://user-images.githubusercontent.com/25389736/33338544-65d72104-d444-11e7-932a-538e54d6fcdd.png)

**Comment by koay9f** [comment]
Looks to be working for Type of Fuel = Gas

Needs to be done with Solid/Liquid (by Mass)

**Comment by rmroot** [comment]
after merging PR https://github.com/ORNL-AMO/AMO-Tools-Desktop/pull/960 use logic from volume form and apply to mass form
