### ISSUE TITLE
ngOnChanges in flue gas component and flue gas form component

### ISSUE THREAD

**Issue by pshires** [ORNL-AMO/AMO-Tools-Desktop#933]
So I'm not sure if this was intentional, but I ran into this problem while working on issue #927. `ngOnChanges` runs only one time, essentially functioning as a second `ngOnInit`. This presented some complications when trying to add code that would run when a change is made to the form. Just want to confirm that this is the desired behavior.

Possible undesired theoretical performance issues due to me not understanding this can be found here: https://github.com/ORNL-AMO/AMO-Tools-Desktop/tree/issue-927
The `ngIf` statement in the flue gas form component executes significantly more code than the typical `ngIf` found elsewhere in various form components.

**Comment by koay9f** [comment]
Is probably tied to #955
