### ISSUE TITLE
Importing not working on v.0.2.3-Beta

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#947]
Just tried to import something and was told "invalid file type"

I thought I remembered something about this, has it been fixed?

**Comment by pshires** [comment]
attach the import data please

**Comment by koay9f** [comment]
okay.  It was b/c when the name was changed from "exportData.json", Sachin accidently deleted the .json as well.  

Is there any way that we can keep this from happening or otherwise give guidance to the user

**Comment by pshires** [comment]
I updated the error message (that pops up when the .json extension regex test fails) to also have " - Must be .json file extension"
