### ISSUE TITLE
Pre-Assessment Calculator

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Desktop#954]
Add description to "All calculators" page

**Comment by AshaShibu** [comment]
_Add description to Cash Flow Diagram_ 
Cash flow diagram displays the revenues (savings) and costs associated with an investment

**Comment by AshaShibu** [comment]
![capture7](https://user-images.githubusercontent.com/31292133/33670486-30486ef0-da73-11e7-80a4-a38039aac889.PNG)

Replace the highlighted text with the description above
