### ISSUE TITLE
PHAST - Setup Help

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Desktop#973]
System Basics, Operating Hours, and Operating Costs all share a single block of help text. Do we want more detailed help text for these screens?

**Comment by AshaShibu** [comment]
**Help Texts**

Operating Hours: Denotes the annual operating hours during which the facility utilizes furnace loads. Either the total hours of operation or the operating schedule (day/week, hours/day) should be entered.

Operating Costs:  Per unit cost of fuel, steam and electricity related to the operation of furnace.
