### ISSUE TITLE
PHAST Bug

### ISSUE THREAD

**Issue by AshaShibu** [ORNL-AMO/AMO-Tools-Desktop#982]
Add a charge material as baseline and add a modification. The tool crashes when I add more than one loss for the rest of the sections (fixtures and trays, wall, extended surface). With a single loss and modification, the tool works just fine.
[Talked to Daryl regarding this and he is of the opinion that multiple losses are possible.]

**Comment by koay9f** [comment]
FYI it does not crash on the version I received on Monday
